### ISSUE TITLE
How can I extract name while predicting label?

### ISSUE THREAD

**Issue by tarunw07** [facebookresearch/fastText#102]
For example when texts = [ Seja Vogel is an Australian musician who was a member of Brisbane bands Sekiden and Regurgitator.], I want output similar to [ (u'3', 'Seja Vogel') ].

**Comment by spate141** [comment]
It's not a fastText issue, you can implement it using any programming language

**Comment by tarunw07** [comment]
I think you didn't understand my problem.

This is how my test data looks.
__label__13 , orion ' s belt ( film ) , orion ' s belt ( norwegian orions
belte ) is a 1985 norwegian dual-language adventure and thriller film
directed by ola solum and tristan devere cole . it is based on jon michelet
' s 1977 novel by the same name . the film follows three svalbard-based
shabby seamen played by helge jordal sverre anker ousdal and hans ola
sørlie who discover a soviet bearing station .
__label__2 , slidell high school , slidell high school is a public school
for grades nine through twelve located in slidell louisiana . it is part of
the st . tammany parish public school district and serves portions of west
and central slidell .
__label__14 , full employment abandoned , full employment abandoned
shifting sands and policy failures is a book on macroeconomic issues
written by economists william mitchell & joan muysken and first published
in 2008 .
__label__10 , domed mauritius giant tortoise , the domed mauritius giant
tortoise ( cylindraspis triserrata ) was a species of tortoise . it was
endemic to mauritius .
__label__3 , pierre-francisque caroubel , pierre-francisque caroubel ( 1556
– summer 1611 or 1615 ) was a french violinist and composer . caroubel was
born in cremona . he lived in paris from 1576 and collaborated with michael
praetorius at the court of the duke of brunswick at wolfenbüttel . he is
known for his dance music bransles and galliards some of which were
published after his death in the anthology secret des muses ( amsterdam
1615 ) . some of the music arranged by praetorius in terpsichore musarum (
1612 ) was also by caroubel .
__label__8 , pârâul Ţapului , the pârâul Țapului is a tributary of the
chioara river in romania .
__label__4 , michael j . heming , michael john heming ( 24 january 1961 –
17 october 1984 ) was an english karateka and kickboxer . he was european
middleweight kickboxing champion and british semi-contact middleweight
champion in the 1970s who complied an impressive winning streak before
losing to jean-claude van damme in 1980 .
__label__8 , hebgen lake , hebgen lake is a lake located in southwest
montana and is created by hebgen dam . it is well known for the 1959 hebgen
lake earthquake ( magnitude 7 . 1 to 7 . 5 ) which occurred nearby on
august 17 1959 forming quake lake which is located immediately downstream .
__label__3 , shannon lee , shannon emery lee ( born april 19 1969 ) is an
american actress and businesswoman . she is the daughter of martial arts
film star bruce lee and linda lee cadwell the granddaughter of cantonese
opera singer lee hoi-chuen and the younger sister of brandon lee .
__label__3 , rena tanaka , this article is about rena tanaka the japanese
actress . for the morning musume/hello ! project singer of a similar name
see reina tanaka . rena tanaka ( 田中 麗奈 tanaka rena born 22 may 1980 ) is a
japanese actress and tv personality . in 1999 she won the japanese academy
award for ' best newcomer ' for her performance in give it all in 2001 she
received a ' best actress ' nomination for hatsukoi .

While classifying I along with label I want the name.
For this data I want result similar to this.
13  orion ' s belt ( film )
12 slidell high school
and so on.

**Comment by spate141** [comment]
fastText recognize labels with that `__label__` tag, (or you can define your own, as describe on readme file)

Model is trained with on only those labels, remaining part of line considered as a feature(normal text). So, you simply can't train a model on labels like, __label__3, __label__8 etc. and get something like 'Seja Vogel', 'pierre-francisque caroubel' along with prediction results.

**Comment by EdouardGrave** [comment]
Hi @tarunw07,
As noted by @spate141, fastText can be used to learn models for text classification (e.g. spam/not spam, positive/negative, etc...), while the problem you are describing is known as named entity recognition (https://en.wikipedia.org/wiki/Named-entity_recognition). fastText does not support named entity recognition.

**Comment by burgersmoke** [comment]
I find myself thinking more about the response above:
>  fastText does not support named entity recognition.

While fastText does perform document-level classification, my understanding is that the pretrained word vectors (https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md) can be used to infer a vector for any word even if it was not encountered at training time.  

Therefore, is there some reason why these vectors could not (or should not) be used as word-level features to algorithms like CRF?  It seems like it would be possible to do something similar to other work where inferred word-level vectors (a la word2vec or GloVe) are used as features in chunking or NER tasks.  Such is the case in (Collobert et al, 2011) (http://www.jmlr.org/papers/volume12/collobert11a/collobert11a.pdf)

Am I missing something fundamental about fastText?
