### ISSUE TITLE
Wrong link in docs

### ISSUE THREAD

**Issue by anakin87** [facebookresearch/fastText#1025]
At https://fasttext.cc/docs/en/crawl-vectors.html#adapt-the-dimension ,

the first link points to localhost: http://localhost:3000/docs/en/support.html#building-fasttext-python-module
It should be  https://fasttext.cc/docs/en/support.html#building-fasttext-python-module

**Comment by atmask** [comment]
I can take this one if it is open

**Comment by kwojcicki** [comment]
Fixed and merged by https://github.com/facebookresearch/fastText/pull/1032. Can be closed @anakin87
