### ISSUE TITLE
supervised training doesn't output .vec file 

### ISSUE THREAD

**Issue by PGryllos** [facebookresearch/fastText#104]
I am training on a sample corpus

```
__label__positive This is the first sentence that should be assigned to the label positive.
__label__negative This is the second sentence that should be labeled negative.
__label__neutral Each training case is then divided by a newline.
```

using the `./fasttext supervised -input sample_corpus.txt -output model` and although I can see the model.bin file I don't get a model.vec file.

**Comment by PGryllos** [comment]
Fix type in title

**Comment by spate141** [comment]
Refer to: #77

**Comment by EdouardGrave** [comment]
Hi @PGryllos,

We will change fastText to output the .vec file when using supervised training, probably next week.

**Comment by bittlingmayer** [comment]
As far as I can tell, in the current version it is again the case that `supervised` output is a `.bin` only, no `.vec`.

(Technically not your problem, but it breaks the currently released version of the gensim wrapper.)

See #250
