### ISSUE TITLE
Parameters used to train the language identification model

### ISSUE THREAD

**Issue by ArbinTimilsina** [facebookresearch/fastText#1044]
I am using the publicly distributed language identification model from here https://fasttext.cc/docs/en/language-identification.html.

I just noticed that  https://fasttext.cc/blog/2017/10/02/blog-post.html recommends using subword features. Is the publicly available model trained using this feature? Moreover, I was wondering if it would be possible to get the exact parameters that were used to train the model?

Regards,
Arbin

**Comment by radurevutchi** [comment]
Hey @ArbinTimilsina did you manage to get your answer? I'm looking for the same information.

**Comment by ArbinTimilsina** [comment]
@radurevutchi, I had convinced myself that the publicly available model was trained using the subword feature. However, I haven't gotten any answer regarding the exact parameters.

**Comment by Celebio** [comment]
Hi @ArbinTimilsina,
You can find the model parameters by using the command `dump`, like this:

```
./fasttext dump lid.176.bin args
```
Feel free to re-open the issue if you have further questions.

Best regards,
Onur
