### ISSUE TITLE
Movie recommendation system

### ISSUE THREAD

**Issue by HassanAbbas7357** [facebookresearch/fastText#1054]
Can i train FastText model on only one column? (Movies_titles) ?
To get the similar titles for the input title?
Keep in mind that i have 45k titles, and also tell me after training the model  approx how much: computation power consumption+ RAM consumption + time (will take the model to load into the RAM and predict ) because i want to use it in a webApp

**Comment by Celebio** [comment]
Hi @HassanAbbas7357 ,
If your titles are all in the same language, you can use a [pre-trained model](https://fasttext.cc/docs/en/crawl-vectors.html). Then you can query the vectors that represent your titles and compute their cosine similarity.

I hope this answers your question. I will close the issue now. Feel free to re-open it if you have further questions.

Best regards,
Onur
