### ISSUE TITLE
Error with multi-label loss

### ISSUE THREAD

**Issue by shashankg7** [facebookresearch/fastText#1063]
I am trying to train a multi-label classification model with loss 'ova'. I am getting the following error:

Read 18M words
Number of words:  138381
Number of labels: 3324
Progress:   0.2% words/sec/thread:    4139 lr:  0.898591 avg.loss: 114.726540 ETA:   2h33m27sterminate called after throwing an instance of 'fasttext::DenseMatrix::EncounteredNaNError'
  what():  Encountered NaN.
Aborted

**Comment by shashankg7** [comment]
Sorry, I missed this in the FAQ, it's due to the high learning rate. Reduced it, it's working fine now.

**Comment by hafiz031** [comment]
@shashankg7 how to spot a high learning rate? Is there any specified range for safe playing?
