### ISSUE TITLE
Useless warning message on load_model

### ISSUE THREAD

**Issue by osma** [facebookresearch/fastText#1067]
In the Python bindings of version 0.9.2, every time I call `load_model` - which in my understanding is the correct way to load saved models - fastText prints this message on stderr:

> Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.

It's defined on [this line](https://github.com/facebookresearch/fastText/blob/master/python/fasttext_module/fasttext/FastText.py#L440)

I understand that sometimes it's useful to explain API changes to users, especially when deprecated features are being accessed and better ways exist. But this seems a bit excessive, since there is no other way of loading the model so no easy way to avoid the message.

I silenced the warning by monkeypatching `eprint` like this:

    fasttext.FastText.eprint = lambda x: None

This is related to #909 which reported a problem (since fixed) that the warning message was printed as a blank line.

**Comment by Celebio** [comment]
Hi @osma ,
Thank you very much for your feedback.

This message was added to facilitate the transition between our old python module to the new one, as described [here](https://fasttext.cc/blog/2019/06/25/blog-post.html).

The message was removed by the commit https://github.com/facebookresearch/fastText/commit/9ef22d9fac33c84480fa2e4edf56df13cb0bcfbb.

I will close the issue now. Thank you again for feedback.

Onur

**Comment by saippuakauppias** [comment]
@Celebio can you publish new version on pypi? My package denend from fasttext, but I can't publish him:

```
Invalid value for requires_dist. Error: Can't have direct dependency: 'fasttext @ https://github.com/facebookresearch/fastText/archive/a20c0d27cd0ee88a25ea0433b7f03038cd728459.zip#egg=fasttext-0.9.2'
```

**Comment by noelslice** [comment]
@Celebio it would be much appreciated to have a new release with this warning removed

**Comment by saippuakauppias** [comment]
@noelslice please write the same in: https://github.com/facebookresearch/fastText/issues/1135
