### ISSUE TITLE
Google Drive returning 404 when attempting to pull using https://raw.githubusercontent.com/facebookresearch/fastText/master/classification-results.sh

### ISSUE THREAD

**Issue by jtaverni** [facebookresearch/fastText#107]
Example for one of the files:

Downloading dataset amazon_review_polarity
--2016-10-25 01:42:31--  https://googledrive.com/host/0Bz8a_Dbh9QhbaW12WVVZS2drcnM
Resolving googledrive.com... 172.217.3.193, 2607:f8b0:400a:809::2001
Connecting to googledrive.com|172.217.3.193|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-10-25 01:42:31 ERROR 404: Not Found.

Is there another place to download the data?

Thanks!

**Comment by spate141** [comment]
https://drive.google.com/drive/u/0/folders/0Bz8a_Dbh9Qhbfll6bVpmNUtUcFdjYmF2SEpmZUZUcVNiMUw1TWN6RDV3a0JHT3kxLVhVR2M

**Comment by cpuhrsch** [comment]
Resolved in recent revision.
