### ISSUE TITLE
Why is recall nan, f1score > 1 when calculated with model.test_label ?

### ISSUE THREAD

**Issue by davidefiocco** [facebookresearch/fastText#1072]
I am training a binary classification model with autotune with `fasttext==0.9.2`, and get a nan value for the per-class recall and nonsensical values for the F1 score when calling `model.test_label`.

To reproduce, I came up with a reproducible example:

```python
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import sklearn.datasets
import zipfile
import csv
import pprint
import wget
from fasttext import train_supervised
import fasttext.util

data = sklearn.datasets.fetch_20newsgroups(categories=['alt.atheism', 'sci.space'])
df = pd.DataFrame(data = np.c_[data['data'], data['target']]).rename({0:'text', 1:'class'}, axis = 'columns')

# assign labels
df["label"] = df["class"].apply(lambda row: '__label__Atheism' if row == "0" else "__label__Space")

# clean text features
df["text"] = df["text"].apply(lambda row: row.replace("\n", " ").replace("\r", " "))

# do train and validation splitting
train, test = train_test_split(df[["label", "text"]])

# dump train and validation
train.to_csv("train.csv", index = False, header=False, sep=" ", quoting=csv.QUOTE_NONE, escapechar=" ")
test.to_csv("dev.csv", index = False, header=False, sep=" ", quoting=csv.QUOTE_NONE, escapechar=" ")

print("downloading zipped word vectors...")
wget.download("https://dl.fbaipublicfiles.com/fasttext/vectors-english/wiki-news-300d-1M.vec.zip", 'wiki-news-300d-1M.vec.zip')

print("inflating word vectors...")
zip_ref = zipfile.ZipFile("wiki-news-300d-1M.vec.zip", 'r')
zip_ref.extractall(".")
zip_ref.close()

print("training model...")
model = train_supervised(
    input="train.csv",
    dim=300,
    verbose=2,
    pretrainedVectors="wiki-news-300d-1M.vec",
    autotuneValidationFile="dev.csv",
    autotuneDuration=300
)

# check model predictions
print(model.predict("What does God need with a starship?", k=1))

# do validation
validation_report = model.test_label("dev.csv")

print("validation summary:")
pprint.pprint(validation_report)
```

The code downloads a subset of a standard dataset (20news), reformats it into train and test sets, gets wiki-en word vectors and trains fasttext with autotune.

The output of the final bit of code, is
```
validation summary:
{'__label__Atheism': {'f1score': 1.8473282442748091,
                      'precision': 0.9236641221374046,
                      'recall': nan},
 '__label__Space': {'f1score': 1.8695652173913044,
                    'precision': 0.9347826086956522,
                    'recall': nan}}
```

Recall is somehow `nan` and the f1score exceeds 1 (it's twice the value of precision).

Seems to me (wild guess) that something funny is happening with my value of `gold` in 

https://github.com/facebookresearch/fastText/blob/b64e359d5485dda4b4b5074494155d18e25c8d13/src/meter.h#L39

and

https://github.com/facebookresearch/fastText/blob/b64e359d5485dda4b4b5074494155d18e25c8d13/src/meter.h#L45 which is zero while it shouldn't be.

I also found somebody else experiencing a similar problem on SO: https://stackoverflow.com/questions/61787119/fasttext-recall-is-nan-but-precision-is-a-number 

Am I doing something wrong (e.g. in the dataset preprocessing) or is this a bug?

What I am worried about is that problems in the computation of the F1 score may make autotune convergence troublesome.

`model.predict` on short chunks of text seems to be yielding sensible results.

**Comment by fv316** [comment]
I also have a similar problem. I always get a value for precision but no value for recall.

**Comment by davidefiocco** [comment]
My example runs fine (no `nan` values) if I install FastText with 

    pip install git+https://github.com/facebookresearch/fastText.git@b64e359d5485dda4b4b5074494155d18e25c8d13

It looks like https://github.com/facebookresearch/fastText/commit/b64e359d5485dda4b4b5074494155d18e25c8d13 solves this issue.

@Celebio maybe this is a serious enough bug to justify a bugfix release?

**Comment by Celebio** [comment]
Hi @davidefiocco , @fv316 
Indeed, we will do a post-release soon. Thank you very much for your feedback.

I am closing the issue. Feel free to re-open if you observe any issue again.
Thank you again for reporting.

Best regards,
Onur

**Comment by kmcmearty** [comment]
@Celebio - thank you for the fixes, I was able to call `test_labels()` and get correct looking results. 
My only question is if I should expect to see results with varying nans and 0.0 in the dictionary?

Here's an example from my output:

`'__label__plnr': {
                            'precision': 0.0, 
                            'recall': 0.0,  
                            'f1score': 0.0
      },
 '__label__gatrd': {
                              'precision': nan, 
                               'recall': nan, 
                               'f1score': nan
      },
 '__label__scape': {
                              'precision': nan, 
                               'recall': 0.0, 
                               'f1score': 0.0
      },`

you can see __label__plnr has all 0.0 values in the dict while __label__gatrd is all nan and __label__scape has nan in precision with 0.0 in the other k:v pairs. Is this normal or to be expected? A majority of my results resemble the output of __label__scape.

**Comment by carschno** [comment]
Are there plans to make a new release of the [Python interface](https://pypi.org/project/fasttext/)? The latest version on PyPi (v0.9.2, April 2020) does not incorporate this bugfix.

**Comment by davidefiocco** [comment]
> Hi @davidefiocco , @fv316 Indeed, we will do a post-release soon. Thank you very much for your feedback.
> 
> I am closing the issue. Feel free to re-open if you observe any issue again. Thank you again for reporting.

@Celebio I think I can't reopen this myself, but as things stand I think we should, as the newest version is still `0.9.2` as of today.

**Comment by unhammer** [comment]
Does this affect the results of autotune or training in general, or just the display from `test`? (Should we all stop using 0.9.2 and move to git immediately?)

**Comment by mrwunderbar666** [comment]
Issue still persists, even with the latest build.

Is this repository dead?
