### ISSUE TITLE
difference between fasttext and fasttext with subword information word vectors?

### ISSUE THREAD

**Issue by vr25** [facebookresearch/fastText#1076]
Hi,

I downloaded fasttext pretrained word embeddings but I am not sure about the difference between (fasttext) and (fasttext with subword information) [here](https://fasttext.cc/docs/en/english-vectors.html).

Any further explanation would be helpful!

Thanks!

**Comment by Celebio** [comment]
Hi @vr25,
Models with subword information allows you to handle out-of-vocabulary words and benefit from the morphology of the language's structure. 

For more information on this, you can refer to the original paper [here](https://arxiv.org/abs/1607.04606).

I will close the issue now. Feel free to re-open it if you have further questions.
Best regards,
Onur
