### ISSUE TITLE
ValueError: predict processes one line at a time (remove '\n')

### ISSUE THREAD

**Issue by onseau** [facebookresearch/fastText#1079]
Only getting this error for some csv files.  Not sure why though—I've tried to remove them or figure out what else it could be, but no luck.  Using BBedit.  Any advice/suggestions?

EDIT:  Also, awesome project by the way, thanks!

**Comment by Celebio** [comment]
Hi @onseau ,
Thank you for your 
I believe you have a problem with your parsing of csv files. You could use the `predict` function either with a single line string or an array of strings representing multiple lines. In either case each string should not contain "\n" character.

I will close the issue now. Feel free to re-open it if you have further questions.
Best regards,
Onur
