### ISSUE TITLE
Dimension of pretrained vectors does not match -dim option

### ISSUE THREAD

**Issue by PGryllos** [facebookresearch/fastText#108]
I am trying to use the `preatrainedVectors` option to run a suvervised labeling training. I have `.bin` file of trained vectors and I using it like that 

```
./fasttext supervised -input corpus_pn_1577277.txt -pretrainedVectors enwiki16_lr001_dim300_ws10_epoch2_neg6.bin -output small
```

where `corpus_pn_1577277.txt` is a set of labeled sentences and `enwiki16_lr001_dim300_ws10_epoch2_neg6.bin` is my pretrained model.

I get 
> Dimension of pretrained vectors does not match -dim option

Am I doing something wrong? thanks in advance!

**Comment by PGryllos** [comment]
The size of my pretrained vectors is 300 so I added the `-dim 300` option but I get the same error

**Comment by jowagner** [comment]
How did you resolve the issue in the end? Your last message says that -dim did not help but you closed the issue.

**Comment by geovedi** [comment]
had similar problem earlier, solved by switching from pretrained model format `.bin` to `.vec`.

**Comment by jowagner** [comment]
@geovedi: Have you signed or can you sign the Facebook CLA (see CONTRIBUTING.md)? If yes, please fork the repository, correct the README.md and make a pull request. You can do all this directly on github. No need to clone the repository to your local machine. Should take only a few minutes.
