### ISSUE TITLE
Still Memory leak with jupyter notebook

### ISSUE THREAD

**Issue by zmitchn** [facebookresearch/fastText#1080]

**Comment by zmitchn** [comment]
while True:
    model.predict("aaa bbb")

**Comment by Celebio** [comment]
Hi @zmitchn ,
The description is missing, but based on the title and code example I assume there is a memory when you use the library inside Jupyter notebook. As we don't control the internals of Jupyter, could you please provide a test-case outside of a Jupyter notebook where you can reproduce the memory leak?

I will close the issue now. Feel free to re-open it when you have the standalone testcase.

Best regards,
Onur
