### ISSUE TITLE
"Terminate called without an active exception" when setting both pretrainedVectors and autotuneValidationFile

### ISSUE THREAD

**Issue by beyondlei** [facebookresearch/fastText#1091]
When I was running the supervised training in **Python** by setting both **pretrainedVectors** and **autotuneValidationFile** parameters, the process was aborted with the message "terminate called without an active exception". There was no problem when setting only one of these two parameters individually, but when setting both at the same time, the problem appeared without a clear reason.

**Comment by emremrah** [comment]
Hello, have you find the reason?

**Comment by beyondlei** [comment]
I found the reason as follows: 
- When setting only the **pretrainedVectors** parameter, the default dim of the model will be same as the dimension of the provided pretrainedVectors and when setting only **autotuneValidationFile**, the training process will try to find the optimal dimension. Both work perfectly well.
- When setting **pretrainedVectors** and **autotuneValidationFile** at the same time, the training process will still try to find the optimal dimension of the model, which might be different from the dimension of the provided pretrainedVectors and therefore could result in the error.
- In order to solve the issue, it is needed to set the dim of the model same as the dimension of the provided pretrainedVectors such that auto-tuning will not change it.
