### ISSUE TITLE
Wrong vector size if word is float number

### ISSUE THREAD

**Issue by lampts** [facebookresearch/fastText#11]
After training word vector, I've check vector size on word: [-0.27998], I got the word vector is 99 instead of 100. So do we need to do preprocessing to filter out these numerical like words?

-0.27998 [ 0.70508   -0.43374    0.2001     0.077085  -0.056991  -0.27614    0.21743
 -0.25468    0.45824    0.20939    0.085696   1.0295    -0.32094    0.23692
 -0.14012    0.77944    0.38626   -0.14074    0.070259   0.0063866 -0.21889
 -1.0098     0.41252   -0.64827   -0.30834    0.62971    0.39256   -0.14508
  0.44633    0.094293   0.33191   -0.011547   0.22663   -0.15396   -0.078965
  0.23796    0.34684   -0.2233     0.31443    1.084     -0.17832   -0.11039
  0.24845    0.14074    0.038921   0.049496  -0.5893    -0.19393   -0.53372
 -0.010605  -0.15091   -0.35736    0.63122    0.096636  -0.14316   -0.46914
  1.1883     0.68973    0.45303    0.29499   -0.16392   -0.52919   -0.72379
  0.54775   -0.050434   0.44091    0.99511   -0.20806   -0.36489   -0.35815
  0.019567   0.39701   -0.55698   -1.4855     0.80146    0.51527   -0.69782
 -0.037633  -0.039004   0.16793   -0.3204    -0.35665    0.069757   0.43055
  0.63142    0.39043    0.72315   -0.55542   -0.44498    1.0321    -0.26342
  0.25087   -0.59114   -0.13786    0.12934   -1.226     -0.17471   -0.82121
  0.10297  ]

**Comment by piotr-bojanowski** [comment]
My guess is that there is a bug in the code that lets the empty string be part of the dictionary. What you are seeing is not a 99 dimensional embedding of "-0.27998" but a 100 dimensional embedding of "". What data have you trained on?

**Comment by piotr-bojanowski** [comment]
**bump**

**Comment by lampts** [comment]
Sorry for the late feedback. Yes, it seems if my data contains some string like blanks, space so I got the wrong vector size after the training. Please see the attached picture. I'm not sure it seems that some words looks like the output dimension.
<img width="606" alt="screen shot 2016-08-11 at 11 12 28 am" src="https://cloud.githubusercontent.com/assets/656949/17578568/b94c1520-5fb4-11e6-9949-b12f96db4606.png">

**Comment by EdouardGrave** [comment]
We fixed a bug which was happening when the training file contained bytes equal to 0.

Could you please pull the latest version, and see if it fixes the issue? Thanks.

**Comment by lampts** [comment]
Yes, it's fixed.
