### ISSUE TITLE
how to setup arguments for large labels?

### ISSUE THREAD

**Issue by luosmart** [facebookresearch/fastText#110]
hi all, I use fasttext for chinese classification.
#labels=150000
#doc=7000000
./fasttext supervised -input "${DATADIR}/label_user_session_shuf_train" -output "${RESULTDIR}/session" -dim 50 -lr 0.1 -epoch 2 -thread 6

But training is very slow, is anything wrong with my setup? thank you so much.
Read 40M words
Progress: 0.1%  words/sec/thread: 178  lr: 0.099905  loss: 17.670927  eta: 20h57m

**Comment by spate141** [comment]
Your label to doc ratio is quite low, what is the size of your one document ? Is this wikipedia corpus ?

**Comment by EdouardGrave** [comment]
Hi @luosmart,
When training models with a large number of labels, the hierarchical softmax should be used, using the command line option `-loss hs`:
```
./fasttext supervised -input "${DATADIR}/label_user_session_shuf_train" -output "${RESULTDIR}/session" -dim 50 -lr 0.1 -epoch 2 -thread 6 -loss hs
```
You can also try to add ngram features, using the command line option `-wordNgrams 2`.
