### ISSUE TITLE
Multiple files from folder as input

### ISSUE THREAD

**Issue by thak123** [facebookresearch/fastText#111]
Docs say that input can be given via -input arg.
$ ./fasttext skipgram -input data.txt -output model

I have a large folder with with files which are very large and I don't want to concatenate them together for training . 

Is there a way out . Or how do i retrain the model with different files ?

**Comment by spate141** [comment]
This functionality is not implemented yet. You have to concat all files in one.

**Comment by EdouardGrave** [comment]
Hi @thak123,

As of now, it is not possible to train a model from different files. Thus, you need to concatenate the files, as pointed out by @spate141. 

We might add this feature in the future, but we do not have a timeline yet.

**Comment by xwzhong** [comment]
hope multi-files input can be applied

**Comment by GeoffNN** [comment]
Has this changed?

**Comment by siyanew** [comment]
Any news?

**Comment by liyi193328** [comment]
any news

**Comment by aburkov** [comment]
Hi there. It's really a concern that the library cannot take a directory as input. In 2020, big data is real. I can't believe that at facebook, you train models using one huge file as input.
