### ISSUE TITLE
cannot load model python

### ISSUE THREAD

**Issue by spaceisonlynoise** [facebookresearch/fastText#1114]
hello,
I want to load a downloaded german fasttext model as such:
`ft = fasttext.load_model('cc.de.300.bin')`
i downloaded it from h[ttps://fasttext.cc/docs/en/crawl-vectors.html ](url) 

when i run the cell it gives me a warning and an error:
`Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.`

`ValueError: cc.de.300.bin cannot be opened for loading!`
Any help is greatly appreciated!

**Comment by miso-belica** [comment]
@spaceisonlynoise is there any specific reason to create a new issue when it already exists in https://github.com/facebookresearch/fastText/issues/1034? Is this issue somehow different from the one [you commented](https://github.com/facebookresearch/fastText/issues/1034#issuecomment-673340783) a few minutes ago? Can write the difference so it is clear here?

**Comment by spaceisonlynoise** [comment]
no i guess its not different enough, the differences are the language (german instead of nl) and the size which is only 1.23GB
