### ISSUE TITLE
English training set for sentiment analysis

### ISSUE THREAD

**Issue by inkrement** [facebookresearch/fastText#114]
Would be great if someone could provide a training set for sentiment analysis of english posts. I found some open sets, but they are quite small :/

**Comment by EdouardGrave** [comment]
Hi @inkrement,

Have you considered the Yelp Academic Dataset: https://github.com/Yelp/dataset-examples ? or the IMDb dataset from https://sites.google.com/site/nquocdai/resources ?

**Comment by inkrement** [comment]
@EdouardGrave Great, thanks!
