### ISSUE TITLE
Error when excute the command "make"

### ISSUE THREAD

**Issue by Sun-shan** [facebookresearch/fastText#115]
Hi, I configured the gcc、python、numpy、scipy, but when I use the following commands, I enconter errors, how can I solve them?

##################
The command :
git clone https://github.com/facebookresearch/fastText.git
cd fastText/
[root@instance-vmhl4w3u fastText]# make
c++ -pthread -std=c++0x -O3 -funroll-loops -c src/dictionary.cc
src/dictionary.cc: In member function ‘void fasttext::Dictionary::threshold(int64_t, int64_t)’:
src/dictionary.cc:202: error: expected primary-expression before ‘[’ token
src/dictionary.cc:202: error: expected primary-expression before ‘]’ token
src/dictionary.cc:202: error: expected primary-expression before ‘const’
src/dictionary.cc:202: error: expected primary-expression before ‘const’
src/dictionary.cc:206: error: expected primary-expression before ‘[’ token
src/dictionary.cc:206: error: expected primary-expression before ‘]’ token
src/dictionary.cc:206: error: expected primary-expression before ‘const’
src/dictionary.cc:210: error: ‘class std::vector<fasttext::entry, std::allocator<fasttext::entry> >’ has no member named ‘shrink_to_fit’
src/dictionary.cc: In member function ‘std::vector<long int, std::allocator<long int> > fasttext::Dictionary::getCounts(fasttext::entry_type) const’:
src/dictionary.cc:235: error: expected initializer before ‘:’ token
src/dictionary.cc:238: error: expected primary-expression before ‘return’
src/dictionary.cc:238: error: expected ‘;’ before ‘return’
src/dictionary.cc:238: error: expected primary-expression before ‘return’
src/dictionary.cc:238: error: expected ‘)’ before ‘return’
src/dictionary.cc: In member function ‘int32_t fasttext::Dictionary::getLine(std::istream&, std::vector<int, std::allocator<int> >&, std::vector<int, std::allocator<int> >&, std::minstd_rand&) const’:
src/dictionary.cc:256: error: ‘uniform_real_distribution’ is not a member of ‘std’
src/dictionary.cc:256: error: expected primary-expression before ‘>’ token
src/dictionary.cc:256: error: ‘uniform’ was not declared in this scope
make: *** [dictionary.o] Error 1

##################
My configure info is as follows ：

[root@instance-vmhl4w3u opt]# yum -y install gcc-c++ numpy python-devel scipy
Loaded plugins: security, versionlock
Setting up Install Process
Package gcc-c++-4.4.7-17.el6.x86_64 already installed and latest version
Package numpy-1.4.1-9.el6.x86_64 already installed and latest version
Package python-devel-2.6.6-66.el6_8.x86_64 already installed and latest version
Package scipy-0.7.2-8.el6.x86_64 already installed and latest version
Nothing to do

**Comment by spate141** [comment]
https://groups.google.com/forum/#!topic/fasttext-library/E7J8FdTploY

**Comment by EdouardGrave** [comment]
Hi @Sun-shan,

Your version of gcc does not support the new wording for lambda function. Please use a more recent version of gcc (4.6 or newer).
