### ISSUE TITLE
Hyperparams for aligning fastText vectors into existing aligned space

### ISSUE THREAD

**Issue by ethch18** [facebookresearch/fastText#1158]
Hello!  I'm trying to align the [Japanese Wikipedia word vector](https://fasttext.cc/docs/en/pretrained-vectors.html) with the existing set of [40 aligned vectors](https://fasttext.cc/docs/en/aligned-vectors.html) using the RCSLS method.  Specifically, I'm following the example script found [here](https://github.com/facebookresearch/fastText/blob/master/alignment/example.sh).  However, with the default hyperparameters in that script, the vectors are not aligning at all.

Here's the command I'm using to do the alignment, which is the one in the script with paths hardcoded, and the output:
```bash
$ python align.py --src_emb data/wiki.ja.vec --tgt_emb data/wiki.en.align.vec --dico_train data/ja-en.0-5000.txt --dico_test data/ja-en.5000-6500.txt --output data/wiki.ja.align.vec --lr 25 --niter 10
Loading vectors from data/wiki.en.align.vec
200000 word vectors loaded
Loading vectors from data/wiki.ja.vec
200000 word vectors loaded
Coverage of source vocab: 1.0000
Found pairs for training: 6819 - Total pairs in file: 6819 - Coverage of pairs: 1.0000
[init -- Procrustes] NN: 0.0000
[it=0] f = 0.1818
[it=1] f = 3.8797
[it=2] f = 2.6592
[it=3] f = 2.0588
[it=4] f = 1.8403
[it=5] f = 1.6021
[it=6] f = 1.4309
[it=7] f = 1.3756
[it=8] f = 1.3469
[it=9] f = 1.3332
[it=10] f = 1.3270
[it=10] NN = 0.0000 - Coverage = 1.0000
[final] NN = 0.0000 - Coverage = 1.0000
Saving all aligned vectors at data/wiki.ja.align.vec
```

And this is how I'm evaluating:
```bash
$ python eval.py --src_emb data/wiki.ja.align.vec --tgt_emb data/wiki.en.align.vec --dico_test data/ja-en.5000-6500.txt
Evaluation of alignment on data/ja-en.5000-6500.txt
Loading vectors from data/wiki.en.align.vec
200000 word vectors loaded
Loading vectors from data/wiki.ja.align.vec
200000 word vectors loaded
Coverage of source vocab: 1.0000
NN = 0.0000 - CSLS = 0.0000 - Coverage = 1.0000
```

I was just following the defaults, but are these hyperparameters reasonable and results expected?  If not, are there examples of better hyperparameters I could refer to?  Thanks!

**Comment by mateuszpieniak** [comment]
@ethch18 Could you explain how you solved the issue, please? Thanks!

**Comment by ethch18** [comment]
Hi @mateuszpieniak, unfortunately it's been a while and I didn't find any workarounds for this in my notes.
