### ISSUE TITLE
How to convert fastText word vectors to word2vec format, or vise versa?

### ISSUE THREAD

**Issue by chenmengdx** [facebookresearch/fastText#117]
Hi, it seems the binary format of word vectors in fastText and word2vec are not the same (fastText's are much larger in physical size). So how could I convert word vectors between this two tools, then I could re-use some word vectors trained before?

Thanks~

**Comment by spate141** [comment]
> Hi, it seems the binary format of word vectors in fastText and word2vec are not the same (fastText's are much larger in physical size)

yes, because it has more information

> So how could I convert word vectors between this two tools, then I could re-use some word vectors trained before?

You can use ".vec" file which generate with ".bin" file to re-use in other applications, or with -pretrainedVectors options. so many different use cases!

or check this, #52

**Comment by EdouardGrave** [comment]
Hi @chenmengdx,

As noted by @spate141, the .vec file format is identical to the .txt file format of word2vec, and should be used as the file format to exchange data between word2vec and fastText.

**Comment by loretoparisi** [comment]
@EdouardGrave hi, it is not clear to me how to convert back from the text format to the bin format: 
I have a Glove / word2vec text format where the first row has the number of words and the dimension like:

```
74177 200
the 0.333333 0.333333 -0.333333 0.333333 -0.333333 -0.333333 -0.333333 0.333333 0.333333 -0.333333 -0.333333 -0.333333 -0.333333 0.333333 -0.333333 -0.333333 0.333333 0.333333 -0.333333 0.333333 0.333333 -0.333333 -0.333333 0.333333 0.333333 0.333333 0.333333 0.333333 -0.333333 0.333333 -0.333333 -0.333333 -0.333333 0.333333 -0.333333 0.333333 0.333333 0.333333 0.333333 -0.333333 -0.333333 -0.333333 0.333333 -0.333333 -0.333333 -0.333333 -0.333333 -0.333333 0.333333 -0.333333 -0.333333 -0.333333 -0.333333 0.333333 0.333333 -0.333333 0.333333 0.333333 0.333333 0.333333 0.333333 -0.333333 -0.333333 0.333333 0.333333 0.333333 0.333333 -0.333333 -0.333333 -0.333333 0.333333 0.333333 -0.333333 -0.333333 -0.333333 -0.333333 -0.333333 0.333333 0.333333 -0.333333 -0.333333 -0.333333 0.333333 0.333333 -0.333333 0.333333 0.333333 -0.333333 0.333333 -0.333333 -0.333333 -0.333333 -0.333333 0.333333 0.333333 0.333333 -0.333333 0.333333 0.333333 -0.333333 0.333333 -0.333333 0.333333 -0.333333 -0.333333 -0.333333 0.333333 -0.333333 0.333333 -0.333333 0.333333 -0.333333 0.333333 0.333333 -0.333333 0.333333 -0.333333 -0.333333 0.333333 -0.333333 -0.333333 -0.333333 -0.333333 0.333333 0.333333 -0.333333 0.333333 0.333333 0.333333 -0.333333 0.333333 0.333333 -0.333333 -0.333333 -0.333333 0.333333 0.333333 -0.333333 -0.333333 -0.333333 -0.333333 -0.333333 -0.333333 -0.333333 -0.333333 0.333333 -0.333333 -0.333333 -0.333333 0.333333 -0.333333 0.333333 -0.333333 0.333333 0.333333 0.333333 -0.333333 0.333333 0.333333 0.333333 -0.333333 0.333333 0.333333 0.333333 0.333333 0.333333 0.333333 -0.333333 0.333333 0.333333 -0.333333 0.333333 -0.333333 0.333333 0.333333 -0.333333 -0.333333 0.333333 0.333333 -0.333333 -0.333333 -0.333333 -0.333333 -0.333333 0.333333 0.333333 0.333333 0.333333 0.333333 -0.333333 -0.333333 0.333333 -0.333333 -0.333333 0.333333 -0.333333 -0.333333 -0.333333 -0.333333 0.333333 
```

And I want to load this model in FastText for `predict-prob` or `nn`. How achieve that?

**Comment by stoufa** [comment]
@loretoparisi Hi, have you figured out how to convert `.vec` to `.bin` I need to do the same thing with Fasttext's pre-trained English word vectors [crawl-300d-2M.vec](https://fasttext.cc/docs/en/english-vectors.html), they only provide the `.vec` file and I don't know how to convert it to `.bin`

**Comment by obask** [comment]
@stoufa I think it's impossible to convert *.vec to *.bin, because binary representation contains learning parameters in addition to vectors.

**Comment by stoufa** [comment]
@obask thank you for replying.
For future reference, I found that Fasttext provide English word vectors in .bin format in the [Wiki word vectors](https://fasttext.cc/docs/en/pretrained-vectors.html) section. The embeddings provided in the [English word vectors](https://fasttext.cc/docs/en/english-vectors.html) section are in .vec format only.
