### ISSUE TITLE
WASM and Node.js Cannot use 'import.meta' outside a module

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/fastText#1173]
I have built [FastText][1] C++ module as wasm module using the provided make file, that is using the following flags:

    EMCXX = em++
    EMCXXFLAGS = --bind --std=c++11 -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['addOnPostRun', 'FS']" -s "DISABLE_EXCEPTION_CATCHING=0" -s "EXCEPTION_DEBUG=1" -s "FORCE_FILESYSTEM=1" -s "MODULARIZE=1" -s "EXPORT_ES6=1" -s 'EXPORT_NAME="FastTextModule"' -Isrc/
    EMOBJS = args.bc autotune.bc matrix.bc dictionary.bc loss.bc productquantizer.bc densematrix.bc quantmatrix.bc vector.bc model.bc utils.bc meter.bc fasttext.bc main.bc

The compiled wasm module is available [here][2]. When I run the module in the provided example [predict.js][3] I get a 

      var _scriptDir = import.meta.url;
                              ^^^^
    
    SyntaxError: Cannot use 'import.meta' outside a module
        at wrapSafe (internal/modules/cjs/loader.js:1072:16)
        at Module._compile (internal/modules/cjs/loader.js:1122:27)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
        at Module.load (internal/modules/cjs/loader.js:1002:32)
        at Function.Module._load (internal/modules/cjs/loader.js:901:14)
        at Module.require (internal/modules/cjs/loader.js:1044:19)
        at require (internal/modules/cjs/helpers.js:77:18)

caused by

    var FastTextModule = (function() {
      var _scriptDir = import.meta.url;
      
      return (
    function(FastTextModule) {
      FastTextModule = FastTextModule || {};
    
    ...

**NOTE.**
I had to adapt the compiled module from the original to Node.JS in order to support `require` instead of `import`, but this should not be related to that error.

  [1]: https://github.com/facebookresearch/fastText
  [2]: https://github.com/loretoparisi/fasttext.js/tree/master/wasm
  [3]: https://github.com/loretoparisi/fasttext.js/blob/master/wasm/predict.js

**Comment by loretoparisi** [comment]
**[UPDATE]**
I was able to solve this specific issue, adding `EXPORT_ES6=0` to the make file as described [here](https://stackoverflow.com/questions/65666725/wasm-and-node-js-cannot-use-import-meta-outside-a-module):

```
EMCXXFLAGS = --bind --std=c++11 -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['addOnPostRun', 'FS']" -s "DISABLE_EXCEPTION_CATCHING=0" -s "EXCEPTION_DEBUG=1" -s "FORCE_FILESYSTEM=1" -s "MODULARIZE=1" -s "EXPORT_ES6=1" -s 'EXPORT_NAME="FastTextModule"' -s "USE_ES6_IMPORT_META=0" -Isrc/
```

but now I get a different error when loading the modularized version:

```
TypeError: fastTextModule.addOnPostRun is not a function
```

due to call to `fastTextModule.addOnPostRun` in the `fasttext.js` file:

```javascript
fastTextModule.addOnPostRun(() => {
  if (postRunFunc) {
    postRunFunc();
  }
});
```

Inspecting the module I can find that the function `addOnPostRun` is defined as

```javascript
Module["addOnPostRun"] = addOnPostRun;
```

**Comment by loretoparisi** [comment]
**[UPDATE]**
I was able to build and run in NodeJS using modified Makefile above and PR https://github.com/facebookresearch/fastText/pull/1116 💯 
The NodeJS-ready wasm version is available [here](https://github.com/loretoparisi/fasttext.js/tree/master/wasm).

**Comment by Celebio** [comment]
Hi @loretoparisi ,
Yes https://github.com/facebookresearch/fastText/pull/1116 is correct and will be merged.
I am glad to see it unblocked you.

Feel free to close this issue if everything is OK from your side.

Best regards,
Onur

**Comment by loretoparisi** [comment]
@Celebio yes closing thank you!. Just a note, the `Makefile` needs to have `-s "USE_ES6_IMPORT_META=0"` to support `NodeJS` as well, I think it's worth to add it.
