### ISSUE TITLE
Wanna convert fastText into R version

### ISSUE THREAD

**Issue by harryprince** [facebookresearch/fastText#119]
fastText is so great to precess the multi-labeling problem, could I add an R wrapper for R user to integrate into the R workflow.

**Comment by cpuhrsch** [comment]
Hey @harryprince, there a few external libraries that wrap fasttext (for example for Python). We're planning on moving fasttext to a state in which it will be easier to use it as a library. We'd be happy to see R being supported for fasttext, but we won't add it to this repository, as it is a separate development. I'll close out this issue for now, as it is unrelated to fasttext itself.

**Comment by inkrement** [comment]
@harryprince I would really like to use fasttext in R. Did you find a library or did u start to write your own wrapper?

**Comment by pommedeterresautee** [comment]
@cpuhrsch I am building a wrapper for R.
Few things wich may help:
- not using exit when there is a failure, because it closes R (in the arg parser in particular). Exception are easier to handle.
- not using cerr to print message because it s very badly managed on R (the \r doesn t work on cerr but work on cout, for progress, at some point, the line is so big it crashes R). May be exporting an object with the state of the progress?

**Comment by inkrement** [comment]
There exists already a nice wrapper written by Florian Schwendinger (https://cran.r-project.org/web/packages/fastTextR/index.html).

**Comment by pommedeterresautee** [comment]
I have seen it. The author has rewritten parts of the original source code to make it work (cerr -> cout, add many Rcpp import everywhere for no obvious reason, etc.), now you need to redo the change each time you want to update Fasttext code.
Not a solution. 
Plus the binding is very partial (unsupervised part only).
I prefer to redo it.

**Comment by pommedeterresautee** [comment]
The wrapper is available there:
https://github.com/pommedeterresautee/FastRText

**Comment by inkrement** [comment]
@pommedeterresautee Correct me if I am wrong, but it looks like that you also included a "static" version of fasttext. Wouldn't it be better to include it using git submodules? This would allow easier/automatic updates.

**Comment by pommedeterresautee** [comment]
You are right it s a static binding, but the source code is intact, any modification is done through MACRO / -
include . So for an update you just need to drop new FastText source code. With submodule you also need to update the link. So, seems to me to be the same. Is there something I am missing?

**Comment by pommedeterresautee** [comment]
@inkrement I have separated both source codes in different folders but can't use submodule because it s not yet supported by `devtools::install_github`

**Comment by inkrement** [comment]
you are right, this is not possible yet. I just added it as submodule and update it using `git subtree pull --prefix <your_subfolder> https://github.com/<repo>`. Although, it is not not supported by devtools yet, it is a quite nice and clean method.

**Comment by pommedeterresautee** [comment]
Yep, it gives guarantee that the source code is original with no way to mess.... but I prefer to keep things simple, even more because the package is not yet on Cran.
