### ISSUE TITLE
Classification on AG news with learning rate 0.25 and trigram got 0.926 better than number claimed in paper

### ISSUE THREAD

**Issue by lampts** [facebookresearch/fastText#12]
LAAMPs-MacBook-Pro:fastText laam$ ./classification-ag.sh
Read 5M words
Progress: 100.0%  words/sec/thread: 2975763  lr: 0.000001  loss: 0.063118  eta: 0h0m
Train time: 6.000000 sec
P@1: 0.926
Number of examples: 7600

Is that something wrong with my testset on AGnews?

**Comment by Franck-Dernoncourt** [comment]
The [paper](https://arxiv.org/pdf/1607.01759v2.pdf) uses bigram to get `92.5`, and does mention:

> Note that we can increase the accuracy slightly by using more n-grams, for example with trigrams, the performance on Sogou goes up to 97.1%. 

Using trigram indeed yields 92.6 for AG.

**Comment by piotr-bojanowski** [comment]
Thanks for your comments. I consider that this is not an issue of this library and hence close this thread. 

Best

Piotr
