### ISSUE TITLE
Get ngram vectors (for a given input)

### ISSUE THREAD

**Issue by ptakopysk** [facebookresearch/fastText#121]
Hi,
This is related to #21 -- I understand you cannot printout the ngrams and their vectors based on the model (because hashing), but could you print out the ngram vectors based on an input consisting of words? Something like ./fasttext print-ngram-vectors model.bin < text.txt, printing all ngrams for each word together with their vectors (probably one ngram per line, with empty lines to delimit individual words).

Or should we just try to use https://github.com/pyk/fastText.py for that? (I haven't studied that one yet; anyway I think it would be nice to provide that functionality natively, since it seems trivial to do.)

(Based on the paper, the word vector is then just an unweighted sum of the ngram vectors, right? I am not very strong in C++ so I haven't found that place in the code yet.)

**Comment by EdouardGrave** [comment]
Hi @ptakopysk,

We will add this functionality very soon (probably next week). Stay tuned!

**Comment by arendu** [comment]
I am having trouble interpreting the output of `print-ngrams `function. I opened an issue #277. It looks like the subword vectors do not average to the word vector.
