### ISSUE TITLE
Fasttext prediction time

### ISSUE THREAD

**Issue by hrudya** [facebookresearch/fastText#122]
Fasttext is taking more time for prediction (1m29.672s for two tweets) . My model size is 865MB. Machine's details :8 GB RAM , 500GB hard disk, CPU: i7 vPro.

**Comment by iamtrask** [comment]
Best guess... you ran out of ram. Were other applications open?

**Comment by hrudya** [comment]
Yes, Other some applications were there. Let me try out. Other than that what you think about the worst and best prediction time?

**Comment by EdouardGrave** [comment]
Hi @hrudya,

Do you still have this issue? Have you tried with smaller models?

**Comment by hrudya** [comment]
On 5 GB RAM (free RAM), 
7.6 MB model, prediction time is 0.063 seconds
856 MB model, prediction time is 1.696 seconds
So, it is totally depends on model size. Actually, I need to use even more bigger model (for Big Data),
I am planning to use more memory. Thank you for the guidance.

**Comment by hrudya** [comment]
On 5 GB RAM (free RAM),
7.6 MB model, prediction time is 0.063 seconds
856 MB model, prediction time is 1.696 seconds
So, it is totally depends on model size. Actually, I need to use even more bigger model (for Big Data),
I am planning to use more memory. Thank you for the guidance.

**Comment by hrudya** [comment]
@EdouardGrave, It is a nice tool. I enjoyed the speed and accuracy. Thank you for replying to my query.

**Comment by EdouardGrave** [comment]
Hi @hrudya,

Thanks for your comment. A few tricks to reduce the model size is to reduce the dimension (using the option `-dim`, e.g. from 100 to 50), to increase the threshold for discarding words (using the option `-minCount`, e.g. from 1 to 5) or to reduce the number of buckets (using the option `-bucket`, e.g. from 2,000,000 to 500,000).
