### ISSUE TITLE
the shell script --"classification-results.sh" can't work appropriate

### ISSUE THREAD

**Issue by HeyEmmaHo** [facebookresearch/fastText#123]
when I run the shell script (classification-results.sh), i got this error below:

Downloading dataset ag_news
--2016-12-02 10:31:03--  https://googledrive.com/host/0Bz8a_Dbh9QhbUDNpeUdjb0wxRms
Resolving googledrive.com... 64.233.188.132, 2404:6800:4004:81a::2001
Connecting to googledrive.com|64.233.188.132|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-12-02 10:31:03 ERROR 404: Not Found.

It seems that this googledrive can't be work anymore. 

Any advise? or where can i got this corpus? 

Thanks!

**Comment by pennlio111** [comment]
+1 Same problem

**Comment by luosmart** [comment]
You can get it here![https://drive.google.com/drive/folders/0Bz8a_Dbh9Qhbfll6bVpmNUtUcFdjYmF2SEpmZUZUcVNiMUw1TWN6RDV3a0JHT3kxLVhVR2M](url)

**Comment by hhungry** [comment]
Thanks

**Comment by hhungry** [comment]
Thanks @luosmart

**Comment by cpuhrsch** [comment]
We fixed this in one of our previous commits.
