### ISSUE TITLE
Computing sentence vector from word vectors using model with character n-grams

### ISSUE THREAD

**Issue by alansalinas** [facebookresearch/fastText#1235]
Hello, I've been trying to understand how are sentence vectors generated from word vectors in a supervised model, this has already been addressed in #323 for the case when args **minn=0** and **maxn=0**, however after the issue was closed a question was brought up by @seanappler [here](https://github.com/facebookresearch/fastText/issues/323#issuecomment-383857871) and also @Umar-Ayub in #966 where apparently a mean of the word vectors + end_of_line vector is not equal to the sentence vector obtained directly from **model.get_sentence_vector()** , I've been going through the C code but haven't figured out an answer yet, I was wondering if anyone knows more about this or could point me in the right direction since in my own experiments I found the same behavior and haven't been able to replicate the process of computing the sentence vector (for a supervised model) using the word vectors + end_of_line vector, when minn and maxn are different from zero and wordNgrams = 1.

I understand if this is closed since it is not really a bug, but any help would be appreciated. Thanks.

**Comment by alansalinas** [comment]
Solved it, sentence vector in a supervised model is really the mean of all the features, when minn and maxn equal to zero then the features are the word vectors so the sentence vector is the mean of word vectors, but when there are subwords then these count as individual features for the sentence vector which equals to the mean of all words and subword vectors as indexed in the input matrix, which is not the same as the mean of word vectors obtained from model.get_word_vector since this method has already averaged the individual word features and the result is not equal as when averaging all the sentence features.

**Comment by Sandy4321** [comment]
how to get tokens used for specific word ?
