### ISSUE TITLE
Always get `0 examples` when run the classifier example

### ISSUE THREAD

**Issue by pennlio111** [facebookresearch/fastText#124]
I tried `dbpedia` and other database like `ag_news_csv` but always have 0 examples in the test file
```
/Users/me/anaconda/envs/fasttext/bin/python2.7 /Users/me/Documents/workspace/fasttext_niuread/test.py
/Users/me/Documents/workspace/fasttext_niuread
P@1: nan
R@1: nan
Number of examples: 0
[[]]

Process finished with exit code 0
```
Any ideas about the cause?
Thanks

**Comment by eloiup** [comment]
had the same issue. trying to figure it out

**Comment by EdouardGrave** [comment]
Hi @pennlio111 and @eloiup,

Do you also have this issue when running fastText from the command line?

**Comment by BGermonpre** [comment]
I'm having the same issue. I'm running a classifier via the Python wrapper.

The fasttext.supervised() function runs without errors, and I get a model.bin as output. But whatever I try to do with it (results on test set, or predict 1 new sentence), I always get nan or 0 results.

Any suggestions?
Thanks!

**Comment by josefinaperez** [comment]
I have this issue too. I can't figure it out.

**Comment by cpuhrsch** [comment]
Hello @josefinaperez, @BGermonpre, please follow up with the author of the Python wrapper, unless you can reproduce the error with the standalone fasttext binary. I'll close the issue for now, but please feel free to reopen if this is the case.

**Comment by jevenzh** [comment]
I have the same issue, could you help? @josefinaperez
