### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by xiaoguangzaia** [facebookresearch/fastText#127]
i change the config CC, and the error like this:

gcc -pthread -std=c++0x -O3 -funroll-loops -c src/args.cc
gcc -pthread -std=c++0x -O3 -funroll-loops -c src/dictionary.cc
gcc -pthread -std=c++0x -O3 -funroll-loops -c src/model.cc
gcc -pthread -std=c++0x -O3 -funroll-loops -c src/utils.cc
gcc -pthread -std=c++0x -O3 -funroll-loops -c src/fasttext.cc
gcc -pthread -std=c++0x -O3 -funroll-loops args.o dictionary.o matrix.o vector.o model.o utils.o fasttext.o src/main.cc -o fasttext
args.o: In function `fasttext::Args::Args()':
args.cc:(.text+0x1b): undefined reference to `std::string::_Rep::_S_empty_rep_storage'
args.cc:(.text+0x23): undefined reference to `std::string::_Rep::_S_empty_rep_storage'
args.cc:(.text+0x33): undefined reference to `std::string::_Rep::_S_empty_rep_storage'
args.cc:(.text+0x42): undefined reference to `std::string::_Rep::_S_empty_rep_storage'
args.cc:(.text+0x4a): undefined reference to `std::string::_Rep::_S_empty_rep_storage'
args.cc:(.text+0xbb): undefined reference to `std::string::assign(char const*, unsigned long)'
args.cc:(.text+0xd2): undefined reference to `std::string::assign(char const*, unsigned long)'
args.cc:(.text+0xee): undefined reference to `std::string::_Rep::_M_dispose(std::allocator<char> const&)'
args.cc:(.text+0x100): undefined reference to `std::string::_Rep::_M_dispose(std::allocator<char> const&)'
args.cc:(.text+0x112): undefined reference to `std::string::_Rep::_M_dispose(std::allocator<char> const&)'
args.cc:(.text+0x124): undefined reference to `std::string::_Rep::_M_dispose(std::allocator<char> const&)'
args.cc:(.text+0x135): undefined reference to `std::string::_Rep::_M_dispose(std::allocator<char> const&)'
args.o: In function `fasttext::Args::printHelp()':
args.cc:(.text+0x171): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
args.cc:(.text+0x1ca): undefined reference to `std::cout'
args.cc:(.text+0x207): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long)'
args.cc:(.text+0x216): undefined reference to `std::cout'

**Comment by luosmart** [comment]
setup this configure "CXX = c++  "  in Makefile.

**Comment by EdouardGrave** [comment]
Hi @xiaoguangzaia,

You should use `g++` instead of `gcc`.
