### ISSUE TITLE
Is there a way to see the raw prediction data?

### ISSUE THREAD

**Issue by jazoom** [facebookresearch/fastText#128]
I can only get it to output a number of predicted labels, without values.

For example, like in Vowpal Wabbit you can do `-r data/predictions-raw.txt` and you get an output containing the relative values for each label. This information could be useful to know how confident the model is that a particular label is the correct one. With fastText I really don't know if there was almost a tie and the model just picked the slightly-better label, or if one label was the obvious choice.

**Comment by sudowork** [comment]
You can get this behavior with the `predict-prob` command:

```
$ ./fasttext predict-prob model.bin test.txt k
```

**Comment by jazoom** [comment]
Excellent, thanks. Perhaps that should be documented in `Full documentation`?

**Comment by sudowork** [comment]
Looks like there's already a pull request to add it to the documentation: #106

**Comment by jazoom** [comment]
You're right. Thank you.
