### ISSUE TITLE
Suggested way to read/stream the word representations in python

### ISSUE THREAD

**Issue by kootenpv** [facebookresearch/fastText#129]
I'm wondering what is the suggested way to read/stream the word representations? It seems extremely show naively implemented.

It seems very weird to end up with a matrix like (ignore the values of the numbers):

```python
I 0.3 0.3 0.3
have 0.3 0.3 0.3
fun 0.3 0.3 0.3
I 0.3 0.3 0.3
am 0.3 0.3 0.3
happy 0.3 0.3 0.3
```

2 observations:
- I could not find a sentence boundary, so it is not easy to read back cases/lines.
- In case you really just use it as a word representation, then it does not make sense to have the words occur multiple times.

I'm curious to hear what the logic behind this format is, and hopefully, a nice way to read it fast in python :)

**Comment by luosmart** [comment]
1、in python just do  
`for line in open('model.txt'):
        fields = line.strip().split(" ") 
        word = fields[0]
        vec = [float(v) for v in fields[1:]]
       # todo
` 
2、A word only appears once in model.txt file.It will not happen " it does not make sense to have the words occur multiple times."

**Comment by kootenpv** [comment]
@luosmart I'm sorry I don't exactly understand :) I will show below that `2.` does happen.

I ran:

    cat ~/att_questions.txt | ./fasttext print-vectors model-1.bin > vecto.txt

Afterwards I ran:

    cat vecto.txt | grep "^again " | wc -l

With output:

    1893

In other words: in the vectors file I get 1893 times the word again with a vector following it...

I think in the end I just did a double loop to iterate over the original text (sentences) and over the words in those sentences, connected to the vectors file, where each line contains the word + vector.
But this is highly inefficient. I'm just wondering if it is intended like that.

**Comment by EdouardGrave** [comment]
Hi @kootenpv,

The vocabulary corresponding to a text file can easily be built using other tools as a preprocessing step to `fasttext print-vectors`, which is the reason why it uses streaming. For example, you can use the command line:
```bash
cat <text-file> | tr -s "[:space:]" "\n" | sort | uniq
```
or the (more efficient) python script:
```python
import sys

vocab = {}
for line in sys.stdin:
    for word in line.split():
        vocab[word] = True

for k in vocab:
    print k
```
Hope this answers your question. Best.
