### ISSUE TITLE
Supervised model with sub-word features

### ISSUE THREAD

**Issue by bkj** [facebookresearch/fastText#130]
Is there currently a way to train a supervised model using sub-word features?  Eg with nonzero `minn` and `maxn`?  I looked through the code and it looks like `getNgrams` never gets called in the `supervised` model -- only in the `cbow` and `skipgram` models.  Is there a particular reason for this?  Or some workaround?

If it's not possible, I may look into implementing myself

Thanks

EDIT: Obviously, you could preprocess the data into character n-grams, but I'd prefer not to have to do that if possible..

**Comment by EdouardGrave** [comment]
Hi @bkj,

You are correct that in the current implementation, sub-word features are not used for supervised models.

We will add this feature to supervised training soon (as well as other additional features).
