### ISSUE TITLE
Strange probabilities returned

### ISSUE THREAD

**Issue by jcalebgood** [facebookresearch/fastText#131]
I have noticed a strange issue in the way that fastText is handling probabilities and have seen this across all of the models that I have developed. There appears to be a cliff where sensible probabilities are returned and then after that the VAST majority have a 1.95313e-08 score. I see this with both negative sampling and hs. I haven't seen if this occurs with softmax.

Here is an example result:

 [0.371094, 0.0195313, 0.0136719, 0.0117188, 0.00976564, 0.00781252, 0.00781252, 0.00781252, 0.00585939, 0.00390627, 0.00390627, 0.00390627, 0.00390627, 0.00390627, 0.00390627, 0.00390627, 0.00195314, 0.00195314, 0.00195314, 0.00195314, 0.00195314, 0.00195314, 0.00195314, 0.00195314, 0.00195314, 0.00195314, 0.00195314, 0.00195314, 0.00195314, 0.00195314, 0.00195314, 1.95313e-08, 1.95313e-08, 1.95313e-08, ...]

The 1.95313e-08 score is there for about 20k classes.

I have seen this in every model that I have developed and the same value is returned even if the number of class labels are different (i.e. the sum across all of the scores does not = 1).

My questions are:

1. Why is it doing this?
2. Is there a way to get the actual confidence values across all of the class labels?

**Comment by Renesco** [comment]
I have the same problem.
Does anyone have any idea what's happening?

**Comment by jcalebgood** [comment]
Update: I trained a model using pure softmax. I am seeing the same behavior.

Note: I am using term features and not embeddings. I am not sure if this is a relevant detail.

**Comment by EdouardGrave** [comment]
Hi @jcalebgood and @Renesco,

this behavior is due to the tabulation of the log and sigmoid functions in [src/model.cc](https://github.com/facebookresearch/fastText/blob/master/src/model.cc#L301). It can be avoided by replacing these two functions by
```c++
real Model::log(real x) const {
  if (x > 1.0) {
    return 0.0;
  }                                                                                                                                                                
  return std::log(x + 1e-6);
}

real Model::sigmoid(real x) const {
  if (x < -MAX_SIGMOID) {
    return 0.0;
  } else if (x > MAX_SIGMOID) {
    return 1.0;
  } else {                                                                                                                                                         
    return 1.0 / (1.0 + std::exp(-x));
  }
}
```

**Comment by jcalebgood** [comment]
Thanks!
