### ISSUE TITLE
Interest in pre-initializing dictionary?

### ISSUE THREAD

**Issue by bkj** [facebookresearch/fastText#135]
Hi all -- I implemented functionality to pre-initialize the dictionary, so that it can be reused in subsequent runs over the same training dataset (useful for eg parameter tuning).  It's called by

```
fasttext init-dictionary -input myinput -output myoutput
```
and saves the dictionary to `myoutput.dict`.  

It's subsequently loaded by
```
fasttext supervised -input myinput -output myoutput -dictionary myoutput.dict
```

At the moment, it's tangled up with a bunch of other edits I've made, but if there's interest I could pull it out and open a PR.  Any thoughts?  I didn't want to spend the ~hour refactoring and testing if people don't think this is useful.

~ Ben

**Comment by EdouardGrave** [comment]
Hi @bkj,

Thank you for your proposal. This would indeed be a useful feature to add to fastText. However, we will refactor the dictionary class in the near future, and would prefer to get a PR for this once we have refactored the code. We will contact you once this is done, if you are still interested in adding this feature to fastText.

Best.

**Comment by bkj** [comment]
Sounds good. Looking forward to the refactor. Any other features that are
coming down the pipe that you can talk about?

**Comment by cpuhrsch** [comment]
Hello @bkj, I'm closing this issue due to age. For your information, we have this request on a short-list for upcoming features and are currently evaluating it in context of the redesign. Please feel free to reopen this issue at any point.
