### ISSUE TITLE
Classifying more than one label

### ISSUE THREAD

**Issue by bashartalafha** [facebookresearch/fastText#138]
How can i use fasttext to classify more than one label for each sentence, for example:
__label__1, __label__2, hello world from sentence 1
__label__2, __label__3, hello world from sentence 2
__label__1, __label__2, __label__3, hello world from sentence 3
.....

**Comment by spate141** [comment]
In order to obtain the k most likely labels for a piece of text, use:
`$ ./fasttext predict model.bin test.txt k`

**Comment by bashartalafha** [comment]
@spate141 Many thanks!! but actually i don't need all the 'k' labels, can i specify a threshold instead of 'k'?
for example:
__label__1, __label__2, hello world from sentence 1
__label__2, hello world from sentence 1
__label__1, __label__2, __label__2, hello world from sentence 1

**Comment by EdouardGrave** [comment]
Hi @bashartalafha,

As of now, it is not possible to specify a threshold instead of the number `k` of predictions. However, it is possible to use
```
> ./fasttext predict-prob <model> <test-data> <k>
```
to get the top-k predictions and their associated scores. You can then manually threshold based on the output of this command.
