### ISSUE TITLE
Distributed fastText - Parallel Training?

### ISSUE THREAD

**Issue by netankit** [facebookresearch/fastText#144]
Is there any distributed implementation of fastText (Ex. Spark), for handling really large input text corpuses for learning word vectors. Word2Vec has a Spark Implementation http://spark.apache.org/docs/latest/ml-features.html#word2vec. Since sub-word information in fastText (summation of vectors of character n-grams) is a defining difference, is it straightforward to work towards a Spark based implementation, using Word2Vec as base code?

**Comment by cpuhrsch** [comment]
I'll add this as a future feature we might consider implementing. For now it's not on our list of priorities, but it might very well soon.

**Comment by XiaolinZHONG** [comment]
i firmly believe this(with spark) will be very helpful for us to train a very large Chinese text

**Comment by qingyuanxingsi** [comment]
@cpuhrsch Any plan on this?

**Comment by medali994** [comment]
Hello, 
Is it always in your scope to implement fasttext with spark?

**Comment by ahmarz** [comment]
any updates on implementing fasttext with spark ?
