### ISSUE TITLE
"unrecognized command line option" on pip install

### ISSUE THREAD

**Issue by bittlingmayer** [facebookresearch/fastText#145]
When I pip install I see the following:

> Installing collected packages: fasttext
>   Running setup.py install for fasttext ... error
>     Complete output from command /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/x2/10f_q7xx4bb2cqz8qldp2pnc0000gn/T/pip-build-azh8jq8i/fasttext/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/x2/10f_q7xx4bb2cqz8qldp2pnc0000gn/T/pip-d9ym43nz-record/install-record.txt --single-version-externally-managed --compile:
>     running install
>     running build
>     running build_py
>     creating build
>     creating build/lib.macosx-10.6-intel-3.5
>     creating build/lib.macosx-10.6-intel-3.5/fasttext
>     copying fasttext/__init__.py -> build/lib.macosx-10.6-intel-3.5/fasttext
>     copying fasttext/model.py -> build/lib.macosx-10.6-intel-3.5/fasttext
>     running build_ext
>     building 'fasttext.fasttext' extension
>     creating build/temp.macosx-10.6-intel-3.5
>     creating build/temp.macosx-10.6-intel-3.5/fasttext
>     creating build/temp.macosx-10.6-intel-3.5/fasttext/cpp
>     creating build/temp.macosx-10.6-intel-3.5/fasttext/cpp/src
>     gcc-4.2 -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -g -arch x86_64 -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c fasttext/fasttext.cpp -o build/temp.macosx-10.6-intel-3.5/fasttext/fasttext.o -O3 -pthread -funroll-loops -std=c++0x -stdlib=libc++ -mmacosx-version-min=10.7
>     cc1plus: warning: command line option "-Wstrict-prototypes" is valid for C/ObjC but not for C++
>     cc1plus: error: unrecognized command line option "-std=c++0x"
>     cc1plus: error: unrecognized command line option "-stdlib=libc++"
>     error: command 'gcc-4.2' failed with exit status 1
>     
>     ----------------------------------------
> Command "/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/x2/10f_q7xx4bb2cqz8qldp2pnc0000gn/T/pip-build-azh8jq8i/fasttext/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/x2/10f_q7xx4bb2cqz8qldp2pnc0000gn/T/pip-d9ym43nz-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/x2/10f_q7xx4bb2cqz8qldp2pnc0000gn/T/pip-build-azh8jq8i/fasttext/

I'm on MacOS - Sierra (10.12.1), Python3.5 obviously.

Any hints?

**Comment by tomtung** [comment]
You might want to report this to https://github.com/salestock/fastText.py instead?

**Comment by bittlingmayer** [comment]
@tomtung Good point, will do.

**Comment by bittlingmayer** [comment]
See https://github.com/salestock/fastText.py/issues/106 and also https://github.com/salestock/fastText.py/issues/101
