### ISSUE TITLE
Resources required for classification-results.sh are not accessible

### ISSUE THREAD

**Issue by maxxkia** [facebookresearch/fastText#147]
Hi,

I tried to run classification-results.sh but it fails with errors. I started debugging it and then realized that the googledrive links in the script are not accessible. Can you update the links please?

**Comment by weisong82** [comment]
yes ,   https://googledrive.com/host/0Bz8a_Dbh9QhbQ2Vic1kxMmZZQ1k  will get 404.

**Comment by samkugji** [comment]
so do I :(

**Comment by csy530216** [comment]
so do I :(

**Comment by Lezeper** [comment]
so do I :(

**Comment by passerbythesun** [comment]
try this piece of code
```bash
  cookie="/tmp/cookie.txt"
  wget="wget --load-cookie $cookie --save-cookie $cookie"

  file_path=${DATADIR}/${DATASET[i]}_csv.tar.gz

  $wget -c "https://drive.google.com/uc?export=download&id=${ID[i]}" -O "${file_path}"
  file_size=`ls -l ${file_path}| awk '{print $5}'`
  if [ $file_size -lt 5000 ]; then
    echo "file size: $file_size, incorrect file, try again..."
    cfm=`cat ${file_path} | grep "tar.gz" | awk -F"confirm=" '{print $2}' | awk -F\& '{print $1}'`
    rm $file_path
    newurl="https://drive.google.com/uc?export=download&confirm=${cfm}&id=${ID[i]}"
    $wget -c ${newurl} -O "${file_path}"
  fi

```
reference: 
https://github.com/Nanolx/patchimage/blob/master/tools/gdown.pl
http://stackoverflow.com/questions/25010369/wget-curl-large-file-from-google-drive

**Comment by cpuhrsch** [comment]
We fixed this in one of our previous commits.
