### ISSUE TITLE
Discarding words at train/test time

### ISSUE THREAD

**Issue by MashaNaslidnyk** [facebookresearch/fastText#150]
In Dictionary::initTableDiscard(), values in Dictionary::pdiscard_[] (i -> probability of keeping words_[i]) are calculated as:
    real f = real(words_[i].count) / real(ntokens_);
    pdiscard_[i] = sqrt(args_->t / f) + args_->t / f;

I was wondering where the formula came from. Thanks!

**Comment by MashaNaslidnyk** [comment]
Explanation found in http://papers.nips.cc/paper/5021-distributed-representations-of-words-and-phrases-and-their-compositionality.pdf -> 2.3 Subsampling of Frequent Words . I'll close this.

**Comment by bkj** [comment]
FYI words are not discarded in the supervised model:

```
bool Dictionary::discard(int32_t id, real rand) const {
  assert(id >= 0);
  assert(id < nwords_);
  if (args_->model == model_name::sup) return false; # <-
  return rand > pdiscard_[id];
}
```
