### ISSUE TITLE
License for pretrained embeddings

### ISSUE THREAD

**Issue by sheerun** [facebookresearch/fastText#152]
Hey,

I see that the source of fastText is available under BSD, but what's the license of pretrained embeddings? CC-something? Public license? Something else?

**Comment by EdouardGrave** [comment]
Hi @sheerun,

The pre-trained word vectors are distributed under the Creative Commons Attribution-Share-Alike License 3.0 (https://creativecommons.org/licenses/by-sa/3.0/), like Wikipedia's text content. We will add this information to the readme.
