### ISSUE TITLE
ValueError when loading wiki.en.vec using gensim's word2vec

### ISSUE THREAD

**Issue by yg37** [facebookresearch/fastText#155]
ValueError: invalid vector on line 12898 (is this really the text format?)

Does anyone have any insight on what causes this? incorrect vector dimension, maybe?

**Comment by xrmx** [comment]
@yg37 looks related https://github.com/RaRe-Technologies/gensim/pull/1176

**Comment by tmylk** [comment]
Fixed in #1176. Please clone the latest code versoin in develop branch

**Comment by yg37** [comment]
Yes, that works. Thanks a lot!
