### ISSUE TITLE
How to recreate the English pretrained word vectors using enwik9

### ISSUE THREAD

**Issue by poppingtonic** [facebookresearch/fastText#161]
I want to expand the list of languages that have pretrained word vectors, and I'd like to know how the vectors in [this](https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md) list were generated. I have [enwik9](http://mattmahoney.net/dc/enwik9.zip), and the `wikifil.pl` perl script, to clean up the WikiPedia XML. If I run 
```fasttext skipgram -input wiki_dataset_cleaned.txt -output model```, 

is it sufficient to recreate the English word vectors model that you've published in the list? If I do the same thing with any other language in the WikiPedia languages list, how would I test the quality of the output model?

**Comment by ardeego** [comment]
@poppingtonic It may be sufficient for your purposes, but you can easily do much better. This question was asked here before, but I forget by whom. As far as I know there is no concrete answer from Facebook on how the preprocessing was done :(

What I can tell you though is that the pre-trained models in the repository were **NOT** created with the provided [``wikifil.pl``](https://github.com/facebookresearch/fastText/blob/master/wikifil.pl) script. The ``wikifil.pl`` is not very sophisticated, it will strip all special characters from your input and leave you only with lower case letters from ``a-z``. This will give you worse results when compared to the pre-trained binaries provided -- which are unicode and include special characters. For English ``wikifil.pl` might be OK for your purposes but other languages will suffer depending on the degree that they make use of special characters. 

In regards to using the ``enwik9`` archive please know that it is a bit small in size and will not even come close to the quality of the pre-trained vectors which have been generated from a recent and whole wikipedia dump (which is about 10-13GB compressed and 60GB uncompressed).

That said, if you are serious about making your own vectors based on wikipedia you simply need to get a recent wiki dump available here: [https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2](https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2) 

If you are using Linux or macOS you can pipe the output from ``bzip2`` directly into your preprocessor script of choice meaning that you won't have to unpack the archive at all. A good wiki preprocessor script which will do a much better job for most languages is available here: [https://github.com/attardi/wikiextractor](https://github.com/attardi/wikiextractor).

**Comment by cpuhrsch** [comment]
Hello @poppingtonic,

We now have a script called 'get-wikimedia.sh', that you can use to download and process a recent wikipedia dump of any language. This script applies the preprocessing we used to create the published word vectors.

The parameters we used to build the word vectors are the default skip-gram settings, except with a dimensionality of 300 [as indicated on the top of the list of word vectors](https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md) (we now understand that this could be more visible).

Thanks,
Christian

**Comment by bittlingmayer** [comment]
For this who need to call it on strings at runtime in python:

https://gist.github.com/bittlingmayer/7139a6a75ba0dbbc3a06325394ae3a13
```
# See https://github.com/facebookresearch/fastText/blob/master/get-wikimedia.sh
#
# From https://github.com/facebookresearch/fastText/issues/161:
#
# We now have a script called 'get-wikimedia.sh', that you can use to download and
# process a recent wikipedia dump of any language. This script applies the preprocessing
# we used to create the published word vectors.
#
# The parameters we used to build the word vectors are the default skip-gram settings,
# except with a dimensionality of 300 as indicated on the top of the list of word
# vectors (we now understand that this could be more visible).

'''
        sed -e "s/’/'/g" -e "s/′/'/g" -e "s/''/ /g" -e "s/'/ ' /g" -e "s/“/\"/g" -e "s/”/\"/g" \
            -e 's/"/ " /g' -e 's/\./ \. /g' -e 's/<br \/>/ /g' -e 's/, / , /g' -e 's/(/ ( /g' -e 's/)/ ) /g' -e 's/\!/ \! /g' \
            -e 's/\?/ \? /g' -e 's/\;/ /g' -e 's/\:/ /g' -e 's/-/ - /g' -e 's/=/ /g' -e 's/=/ /g' -e 's/*/ /g' -e 's/|/ /g' \
            -e 's/«/ /g' | tr 0-9 " "
'''
SUBEXES = ["s/’/'/g", "s/′/'/g", "s/''/ /g", "s/'/ ' /g", 's/“/"/g', 's/”/"/g', 's/"/ /g', "s/\\./ \\. /g", "s/<br \\/>/ /g", "s/, / , /g", "s/(/ ( /g", "s/)/ ) /g", "s/\\!/ \\! /g", "s/\\?/ \\? /g", "s/\\;/ /g", "s/\\:/ /g", "s/-/ - /g", "s/=/ /g", "s/=/ /g", "s/*/ /g", "s/|/ /g"], "s/«/ /g"]

import subprocess

def __normalize_text(s):
    for subex in SUBEXES:
        print("Applying", subex)
        s = subprocess.check_output(['sed', subex], input=s.encode()).decode("utf-8")
        print(s)
    return s

# Program to filter Wikipedia XML dumps to "clean" text consisting only of lowercase
# letters (a-z, converted from A-Z), and spaces (never consecutive)...
# All other characters are converted to spaces.  Only text which normally appears.
# in the web browser is displayed.  Tables are removed.  Image captions are.
# preserved.  Links are converted to normal text.  Digits are spelled out.
# *** Modified to not spell digits or throw away non-ASCII characters ***
# Written by Matt Mahoney, June 10, 2006.  This program is released to the public domain.

def __spaces(s):
    return ' '.join(s.split())

def preproc(s):
    s = s.lower()
    s = __normalize_text(s)
    s = __spaces(s)
    return s
```

**Comment by king-11** [comment]
@cpuhrsch in languages like Hindi english words are left behind after preprocessing won't that be an issue
