### ISSUE TITLE
Missing words in pre-trained word models

### ISSUE THREAD

**Issue by jkleiser** [facebookresearch/fastText#163]
In both the English wiki.en.vec and the Norwegian wiki.no.vec (both seem to have been generated 10-Feb-2017) I have found several lines where the word is missing (line starts with two spaces).
In the English wiki.en.vec it's these lines:
12900, 56584, 67892, 75704, 111160, 112319, 159600, 177644, 211774, 249817, 253947, 348995, 384886, 447410, 453309, 502685, 598754, 879842, 888044, 971594, 1065290, 1073392, 1111613, 1137048, 1142920, 1172153, 1438652, 1631875, 1649957, 1860095, 2020803, 2301656, 2386193, 2424017 has only 300 parts. Skipping.
In the Norwegian wiki.no.vec it's these lines:
3809, 51660, 57825, 121001, 155525, 182550, 204922, 207193, 221947, 229690, 388894, 391899, 406117

**Comment by EdouardGrave** [comment]
Hi @jkleiser,

Thanks for reporting this issue. These lines probably correspond to unicode characters which are displayed as white-space (or correspond to white-space).

For example, the first character of line 12900 of `wiki.en.vec` has a codepoint of 160, which corresponds to the unicode character 'NO-BREAK SPACE'.
