### ISSUE TITLE
Pre-trained word vectors and Translation Matrix

### ISSUE THREAD

**Issue by polineso** [facebookresearch/fastText#164]
Hi,
I would like to ask, Translation Matrices are already applied to pre-trained word vectors? 
Or all languages are in own 300D space and it should be done?
Thanks,
Andrii

**Comment by EdouardGrave** [comment]
Hi @polineso,

All models were trained independently (in their own 300D space) and no translation matrix were applied. So it is not possible to directly compare words from different languages, and if you want to do so, you will need to learn the translation matrix first.

Best
