### ISSUE TITLE
Failed to download pre-trained model

### ISSUE THREAD

**Issue by kevinlin311tw** [facebookresearch/fastText#166]
Hi all,

I am trying to download the pre-trained model from the provided URLs. But it seems like there might have connection problems. I tried to download the English pre-trained model a few times, but eventually I got the message as below.

$ wget https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki.en.zip
--2017-03-07 16:02:45--  https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki.en.zip
Resolving s3-us-west-1.amazonaws.com (s3-us-west-1.amazonaws.com)... 52.219.28.21
Connecting to s3-us-west-1.amazonaws.com (s3-us-west-1.amazonaws.com)|52.219.28.21|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10356881672 (9.6G) [application/zip]
Saving to: ‘wiki.en.zip.1’

 1% [                                                             ] 130,838,153 93.0KB/s   in 26m 14s

2017-03-07 16:34:00 (81.2 KB/s) - Read error at byte 130838153/10356881672 (Connection reset by peer).

**Comment by EdouardGrave** [comment]
Hi @kevinlin311tw,

The download seems to work fine. Please re-open if you still have issues.

Best
