### ISSUE TITLE
Are embeddings trained in supervised mode?

### ISSUE THREAD

**Issue by elbamos** [facebookresearch/fastText#169]
A coworker went through the source and thinks that in supervised mode, the "embeddings" fastText aren't trained to contain semantic information, as in word2vec, but only to predict the label. So, in his view, they're not really embeddings at all, but just a hidden layer.  

Accurate or inaccurate?

**Comment by EdouardGrave** [comment]
Hi @elbamos,

You are correct that in supervised mode, the word embeddings are only trained to predict the label (and not the neighbor words, such as in word2vec). They can thus be seen as a hidden layer.

Generally, a word embedding refer to any method where words are mapped to vectors. In that sense, the word vectors learned using the supervised mode of fastText are a kind of (supervised) word embedding. word2vec is another method to learn a word embedding, in that case without labeled data.

Best
