### ISSUE TITLE
fastText fails on bash on windows

### ISSUE THREAD

**Issue by pasaitow** [facebookresearch/fastText#17]
Ran ./word-vector-example.sh on bash for windows 10 and received the following:

```
Read 124M words
Progress: 100.0%  words/sec/thread: 100377  lr: 0.000001  loss: 1.667808  eta: 0h0m
Train time: 311.000000 sec
OMP: Error #100: Fatal system error detected.
OMP: System error #22: Invalid argument
Aborted (core dumped)

```

**Comment by piotr-bojanowski** [comment]
Hi,

We have not tested our code on Windows platforms and do not support it yet. We are looking into it and will provide support soon.
I updated the readme file with platform compatibility (commit ec493d160af94a0aeb6cc802bddd8ae1ca93c99a). 

Thanks for the tip!
