### ISSUE TITLE
Segmentation Fault error in Linux

### ISSUE THREAD

**Issue by jbhurwitz** [facebookresearch/fastText#173]
I am running fasttext on Linux 6.7, but I keep getting a "Segmentation fault (core dumped)" error.  I get the same error when I run the example shell scripts included with the fasttext installation package.  Am I doing something wrong?  I am using gcc 3.5.2, but since I do not have root permission, I have installed gcc locally.  To assure that fasttext was using the correct path for c++, I added the local c++ to my UNIX path and also updated the gcc configuration file with the correct path ("./configure --with-cxx-main=/home/<userid>/gcc-5.2.0/bin/c++).

**Comment by EdouardGrave** [comment]
Hi @jbhurwitz,

Did you compile fastText on your machine, or did you use a compiled binary?

**Comment by sanjaySP** [comment]
I got the same error in AWS, linux 6.7 with 4gb ram.
i used compiled binary.
Any way to resolve this?
