### ISSUE TITLE
Tokenization is inconsistent

### ISSUE THREAD

**Issue by tuvistavie** [facebookresearch/fastText#175]
Hi,

I ran into a few issues when using the library.
Words seem to be tokenized only using whitespaces (`\n`, `\r` etc), which means that

> I ate an apple

and 

> I ate an apple.

get tokenized into two difference sentences as the last word get tokenized either into `apple` or `apple.`. As both sentences are semantically exactly the same, I believe they should not get a different vector representation (except for the period).
This gave me very unexpected results for a classifier, and I think would be worth fixing.

`dictionary.cc` could be modified to include symbols such as `.`, `?` or `!` in the condition of `Dictionary::readWord`, but I think having a real tokenizer could probably help.

What do you think?

**Comment by siavash9000** [comment]
This a common problem in tokenization. Unfortunately just adding the period raises problems with abbreviations. The nltk punkt package adresses this issue:

http://www.nltk.org/api/nltk.tokenize.html

There are also re-implementations of this algorithm in other languages:

https://github.com/lfcipriani/punkt-segmenter
https://github.com/ferristseng/rust-punkt

A simple workaround would be to preprocess the text and detect abbreviations and replace them by the full word or add them to the vocabulary.
Fanciest solution would be to integrate the punkt tokenizer directly (by re-implementing or by the usage of one of the mentioned  libs).

**Comment by EdouardGrave** [comment]
Hi @tuvistavie,

You are correct: for best performance, some preprocessing should be applied to the data (both train and test) before using fastText. As you mentioned, a common preprocessing step is tokenization. Other include lowercasing or various text normalization. As there is no "all-purpose" preprocessing (e.g. tokenization is language dependent), we decided to only use very basic tokenization and let the user preprocess the data.

As @siavash9000 mentioned, several tools exist for tokenization, such as the Stanford Tokenizer (https://nlp.stanford.edu/software/tokenizer.html). For English, a very crude preprocessing can be obtained using
```
>> cat data.txt | sed -e "s/\([\.\!?,'/()]\)/ \1 /g" | tr "[:upper:]" "[:lower:]" > data.preprocessed.txt
```

Best
