### ISSUE TITLE
 Exception: fastText: Cannot load asttext_wiki.bin due to C++ extension failed to allocate the memory

### ISSUE THREAD

**Issue by omerarshad** [facebookresearch/fastText#176]
i have 8 gb free ram and when i try to load model of 3 GB, i get this error. Can anyone tell how to load pre trained vector in fasttext?

**Comment by EdouardGrave** [comment]
Hi @omerarshad,

The binary model is probably too large to fit in memory. We will maybe release smaller models in the future. Have you tried using the text model? You can only load the first `k` words of the models, since they are sorted by frequency.

Best

**Comment by tarrekshaban** [comment]
I am having the same issue. I do not think it is memory as my computer has over 256 gb of memory. Not quiet sure what to do to solve the issue.

**Comment by gabrer** [comment]
I have got the same issue only using the Python package "fasttext".
Instead, the C++ function "load_model"  works properly.

**Comment by stiebels** [comment]
Same issue with 32gb memory in Python package 'fasttext'.

**Comment by ArgentumBlack** [comment]
Same issue with the binary model， but the text model worked.

**Comment by kelly-tlz** [comment]
I have the same question, whatever model I load. @gabrer how to tackle this problem with c++

**Comment by Ellibeere** [comment]
I have the same issue with 8gb and trying to use wiki.ady.vec text model.

I also tried only loading the first few hundreds lines, didn't work either.

**Comment by lxw0109** [comment]
Same problem. Anybody help? Thank you ~

**Comment by omerarshad** [comment]
shift to ubuntu. it works there :/

**Comment by lxw0109** [comment]
Thank you @omerarshad , but actually I'm working on Ubuntu 16.04 64bits.
