### ISSUE TITLE
Definition of character n-gram in fasttext

### ISSUE THREAD

**Issue by iarroyof** [facebookresearch/fastText#178]
Hi. I have read the papers and I can't see something where a definition of "character n-gram" is provided. A possible example definition could be: given a word, e.g. "genomics", the corresponding set of 3-grams is given by `G_0={gen, eno, nom, omi, mic, ics}`. Another possible definition could be, for the same example word: `G_1={gen,omi,cs\0}`. Please, can someone clear what exactly "n-gram" is referring to? Given that the score function (the argument of the output layer softmax) takes the sum of the n-gram hidden embeddings, a possible and intuitive choice is `G_1`, but I'm not sure. 

Once defined what an n-gram actually is, the set `G` contains different `N=1,2,..,n,...-grams` at the same time? or a set `G` is generated independently for each `n`? 

Thanks :)

**Comment by EdouardGrave** [comment]
Hi @iarroyof,

the set of character n-grams used by fastText corresponds to `G_0={gen, eno, nom, omi, mic, ics}`.

Yes, the set `G` contains n-grams for various values of `n`, such that `minn <= n <= maxn`.

Best

**Comment by iarroyof** [comment]
Very grateful for your reply @EdouardGrave . Last question... please confirm or correct me. Then the resulting embedding for `2 <= n <= 3`  is given by the sum of the projections of `G={ge, en, no, om, mi, ic, cs, gen, eno, nom, omi, mic, ics}` ?
