### ISSUE TITLE
predict_proba is not working

### ISSUE THREAD

**Issue by enod** [facebookresearch/fastText#179]
Hi,

Thanks for this awesome library. I'm building sentiment analyzer on it. 
model.predict model works but model.predict_proba always gives the same value in both positive and negative text.

**Comment by EdouardGrave** [comment]
Hi @enod,

Are you using the command line binary or the python bindings?

**Comment by enod** [comment]
I'm using python bindings.

**Comment by cpuhrsch** [comment]
Hey @enod, you'll need to follow up with the author of the bindings to resolve this issue, unless you can reproduce an error with the binary itself. I'll close the issue for now, but please feel free to reopen if this is the case.
