### ISSUE TITLE
Question/FeatureRequest: Serving in Java

### ISSUE THREAD

**Issue by anjishnu** [facebookresearch/fastText#184]
Any recommended interfaces for serving fasttext in java?

**Comment by spate141** [comment]
I have not used this, but you can definitely check this: 

> https://github.com/vinhkhuc/JFastText

**Comment by cpuhrsch** [comment]
Hello @anjishnu, we don't officially have support for Java yet. It's not on our near-term roadmap, but  is a feature we have considered. You might be able to access a wider audience on discussion boards such as stackoverflow. I'll close this issue for now, as it is not directed related to the fastText binary itself, but I took note of this feature request.

**Comment by claeyzre** [comment]
Found an incredible one for predicting => https://github.com/linkfluence/fastText4j
