### ISSUE TITLE
Multiple labels in training data

### ISSUE THREAD

**Issue by duyvuleo** [facebookresearch/fastText#185]
Hi,

Is it possible for fastText to run on the training data in which multiple labels for each instance are employed, e.g.,

**__label__A __label__C** particularly in already existing electrical buildings installations , it is a simple matter to integrate the inventive circuit .

Thanks!

**Comment by spate141** [comment]
You can use multiple labels like this:  
`__label__A, __label__C particularly in already existing electrical buildings installations , it is a simple matter to integrate the inventive circuit .`

Related information here : #72

**Comment by duyvuleo** [comment]
@spate141 : Thanks for pointing to the related issue. Still a bit confused. Which one of the followings is correct:

1) __label__**A,** __label__C particularly in already existing electrical buildings installations , it is a simple matter to integrate the inventive circuit .

2) __label__**A ,** __label__C particularly in already existing electrical buildings installations , it is a simple matter to integrate the inventive circuit .

**Comment by spate141** [comment]
It doesn't make any difference! You can use either of any format,
`__label__1,__label__2` or `__label__1 , __label__2` or `__label__1, __label__2`

**Comment by duyvuleo** [comment]
Cool. Thanks!

**Comment by nguyentheanhhnvntd** [comment]
Hello, if I use __label__1,__label__2 and it will consider that just one label, right @spate141 ??
