### ISSUE TITLE
can you provide some the pre-trained classifier.bin or model.bin for AG,sogou or other datasets?

### ISSUE THREAD

**Issue by IvyGongoogle** [facebookresearch/fastText#186]
hello, fasttext is cool. But now I do not have training dataset described in your paper such as AG, sogou or other datasets. can you provide some the pre-trained classifier.bin or model.bin for AG, sogou, DBP or other datasets for `text classification` or `word representation learning` ?
THANK YOU in advance!

**Comment by cpuhrsch** [comment]
Hey @IvyGongoogle,

We recently released a large set of word embeddings on top of Wikipedia for a total of 294 different languages. You [can find them here](https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md). The 'bin+text' links include a model for each of the languages. This should have you covered for unsupervised models.

For supervised models you can run the 'classification-results.sh' script. This will fetch a few datasets and train a model for each. This includes the datasets that you mention (such as ag, sogou or dbp). Let me know if you're in a resource constrained environment where you can't run this, but please do try running it first. fastText tries to also work well in low-resource environments.

Thank you
Christian

**Comment by IvyGongoogle** [comment]
@cpuhrsch  thank you very much! that is cool!

**Comment by cpuhrsch** [comment]
@IvyGongoogle I'm happy to hear, that you like this! Please remember to close out the issue if you consider this resolved for now.

**Comment by IvyGongoogle** [comment]
@cpuhrsch Ok.

**Comment by IvyGongoogle** [comment]
@cpuhrsch sorry to bother you again. where to get the dataset for tag prediction in your paper ?

**Comment by cpuhrsch** [comment]
Hey @IvyGongoogle ,

I think you mean [YFCC100M](http://www.yfcc100m.org/). You can find a download link on Facebook's [fasttext website](https://research.fb.com/projects/fasttext/) under the related section. Let me know if this works for you.

Thank you,
Christian

**Comment by cpuhrsch** [comment]
Hey @IvyGongoogle,

The dataset linked to by the [fasttext website](https://research.fb.com/projects/fasttext/) is in fact already processed into a format that is immediately useable by fasttext. It even includes the train, valid and test split. Once you download it, you should be good to go.

Thank you,
Christian

**Comment by IvyGongoogle** [comment]
@cpuhrsch Ok, thank you, I will try.

**Comment by EdouardGrave** [comment]
Hi @IvyGongoogle,

You can use the command line options `-minCount 100` and `-minCountLabel 100` to remove the words and tags occurring less than 100 times.

Best,
Edouard.

**Comment by IvyGongoogle** [comment]
@EdouardGrave oh, thankyou very much!
