### ISSUE TITLE
question for pre_trained vector

### ISSUE THREAD

**Issue by zhongboyin** [facebookresearch/fastText#187]
What is the each dimension of the 300 dimensions represent? Is it have a specific meaning  for each dimension ?

**Comment by lgalke** [comment]
I suggest this [introductory read](http://sebastianruder.com/word-embeddings-1/).
It is the result of the algorithm learning a good representation (to predict the context).

**Comment by zhongboyin** [comment]
Thank for your answer but I still want to konw what's the each dimension of the 300D represent？

**Comment by bkj** [comment]
Values in a single dimension are not intrinsically interpretable.

**Comment by ardeego** [comment]
@zhongboyin This is an interesting question, not an easy one to answer though. A **very simplistic** answer is, that you have to treat word vectors as random vectors in practice. There is no single vector dimension that represents e.g. “gender”, etc..

More precisely, word vectors are the result of a really simple neural network, that ultimately tries to minimize the inner product of the word vectors that are associated with similar contexts (see [Chris McCormick’s blog](http://mccormickml.com/2016/04/19/word2vec-tutorial-the-skip-gram-model/) for a beginner’s introduction). The learning algorithm does not impose a lot of structure on the word vector dimensions themselves. In general, you can assume that word vectors are [isotropic vectors](https://www.encyclopediaofmath.org/index.php/Isotropic_vector), meaning that these vectors behave much like random vectors, with independent coordinates and no preferred direction (see also [Sanjeev Arora’s post](http://www.offconvex.org/2016/02/14/word-embeddings-2/) blog on the issue. These vectors are just tuned to give you a cosine distance (which is the inner product of the normalized vectors) that approaches one for similar words. Facebook’s fastText takes this a step further by taking into account sub word (N-gram) features, but the underlying ideas are the same.

Does that mean that there is no structure in word vectors whatsoever? No, not quite, and this is where things become interesting… and more complicated. To give you a **very** rough idea of how you can model this: Picture word vectors as the result of a linear combination of a handfull "context vectors” (isotropic unit vectors a.k.a. “discourse vectors”). Think of them as "building blocks" of word vectors each of them representing a narrow contextual topic. You can compute via a technique called “sparse cording”, but that probably goes far beyond your original question. If you want to learn more, you'll find more details on the topic in this [video](https://www.youtube.com/watch?v=KR46z_V0BVw&t=#t=20m53s) and on [Arora’s blog](http://www.offconvex.org/2016/07/10/embeddingspolysemy) and the [paper]( https://arxiv.org/abs/1601.03764) that goes along with it.

Hope this was helpful.
