### ISSUE TITLE
"Dimension of pretrained vectors does not match -dim option" error

### ISSUE THREAD

**Issue by dchaplinsky** [facebookresearch/fastText#190]
I'm trying to train a classifier with this cli params:
`/fasttext supervised -input ../corpora/data4fasttext-uk2en2uk.txt -output ../models/fasttext-uk2en2uk-embed_uber_skipgram_lemmattized  -lr 0.1 -wordNgrams 2 -minCount 1 -bucket 10000000 -epoch 25 -thread 4 -pretrainedVectors ubercorpus.txt.fasttext.lemmatized.300d.bin -dim 300`

I double checked that my pretrained vectors has exactly 300 dimensions (wc -w says 301 because fastText outputs the requested word and 300 floats):
```
$ echo "hello" | ./fasttext print-vectors ubercorpus.txt.fasttext.lemmatized.300d.bin | wc -w
     301
```

Still I'm getting an error.
I'm using current version of fastText from Github.

**Comment by dchaplinsky** [comment]
Ok, it's probably me, who is dumb here, as script expects textual vectors rather than binary model.

On the other hand, documentation has no mention of that.

**Comment by EdouardGrave** [comment]
Hi @dchaplinsky,

As you mentioned, the `-pretrainedVectors` command line option expect a text file and not a binary one (we should mention this in the doc). You can use the `.vec` file instead of the `.bin` which is 
also the output of `./fasttext skipgram`.
