### ISSUE TITLE
Quantize error

### ISSUE THREAD

**Issue by spate141** [facebookresearch/fastText#196]
I already have trained model_1.bin with supervised option, and when I am trying to quantize that model, I am getting following error!

```
/opt/fastText/fasttext quantize -input data.txt -output models/model_1 -verbose 3 -wordNgrams 3 -bucket 1000000 -minn 3 -maxn 6 -lr 0.010 -dim 100 -loss ns -thread 8 -epoch 10 -qnorm -retrain -cutoff 100000
```
```
fasttext: src/vector.cc:71: void fasttext::Vector::addRow(const fasttext::Matrix&, int64_t): Assertion `i < A.m_' failed.
Aborted (core dumped)
```

Edit: If I dont use `-cutoff`  then I can run this without any error!

**Comment by cpuhrsch** [comment]
Hey @spate141,

Thank you for your post! Could you also post the command you used to train the supervised model? This way I can try reproducing the error on my end.

- Christian

**Comment by spate141** [comment]
@cpuhrsch: 

Training command: 
```
/opt/fastText/fasttext supervised -input data.txt -output models/model_1 -verbose 3 -wordNgrams 3 -bucket 1000000 -minn 3 -maxn 6 -lr 0.010 -dim 100 -loss ns -thread 8 -pretrainedVectors model.ngrams.run0.skip.vec -epoch 10
```

**Comment by cpuhrsch** [comment]
Which command did you use to create the pretrained vectors?

**Comment by spate141** [comment]
for vectors:

`/opt/fastText/fasttext skipgram -input data_for_vec.txt -output model.ngrams.run0.skip.vec -verbose 3 -wordNgrams 3 -lr 0.001 -dim 100 -loss ns -thread 8 -epoch 10`

**Comment by cpuhrsch** [comment]
Hey @spate141,

There was a small error in the dictionary, that caused your error. Please try quantizing again and let me know if the issue is resolved for you.

Thank you
Christian

**Comment by spate141** [comment]
Error solved! Thanks for the quick fix.

**Comment by spate141** [comment]
When I am trying to quantize the supervised model, I am getting this error on latest built. 

> Quantize Error: Matrix too small for quantization!

here are the commands used:

Supervised:
`./fasttext supervised -input data.txt -output models/model_1 -verbose 2 -wordNgrams 3 -bucket 1000000 -minn 3 -maxn 6 -lr 0.010 -dim 100 -loss ns -pretrainedVectors vec_1.vec -thread 8 -epoch 30`

Quantize:

`./fasttext quantize -input data.txt -output models/model_1 -verbose 2 -wordNgrams 3 -bucket 1000000 -minn 3 -maxn 6 -lr 0.010 -dim 100 -loss ns -pretrainedVectors vec_1.vec -thread 8 -epoch 10 -retrain -qnorm -dsub 2 -qout`

`Matrix too small for quantization, must have > 256 rows`

I wonder what is the minimum requirement for quantizing output matrix? As If i don't use `-qout` I am not getting the errors!

**Comment by cpuhrsch** [comment]
Hey @spate141,

Presumably there are not more than 256 labels labels, so `-qout` doesn't work (as the output matrix won't meet the requirements). Luckily, given `-dim 100`, your output matrix is already quite small.

Thank you,
Christian

**Comment by spate141** [comment]
Gotcha! Thanks :)

**Comment by bittlingmayer** [comment]
@spate141, does `skipgram` used `-wordNGrams`?

https://github.com/facebookresearch/fastText/blob/6d2c453bf4e1610f056a51d1ead70c9c6e41074c/src/dictionary.cc#L340

**Comment by spate141** [comment]
@bittlingmayer Yes, you can see by `fasttext skipgram` command help, value of default parameters. 
`-wordNgrams: max length of word ngram [1]` is using wordNgrams!

**Comment by bittlingmayer** [comment]
@spate141 Thanks much for the reply

Is there any explanation for that line of code?  One of gensim contributors on the RaRe team pointed it out and wrote that he was under the impression that it is not used in unsupervised mode.

**Comment by microdiploma** [comment]
do you figure out whether it is possible or theoretical correct to quantize  the unsupervised trained model ?

**Comment by chandu1234567** [comment]
HI **@spate141** when i tried to Use fasttext.quantize() , it is throwing me "AttributeError: 'module' object has no attribute 'quantize' "   can u please help ?

**Comment by spate141** [comment]
@chandu1234567 If you are asking about fasttext python wrapper, then NO. quantize() method is not implemented in there. This issue was regarding official fastText C++ library!

**Comment by ankur220693** [comment]
I am using a file 'data.txt' which contains:
ओना,जन सहयोगक जेतेक आशा कएल गेल छल तइ रूपे सहयोग नहि भेटल, माने ई जे परिवारक जनसंख्‍याक हिसावसँ सहयोगक आशा कएल गेल छल से नइ भेटल। 
When i run fastText command:
**./fasttext skipgram -input data.txt -output model**

I am getting the following error.
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Empty vocabulary. Try a smaller -minCount value.
Aborted (core dumped)
