### ISSUE TITLE
when to provide FastText.zip code?

### ISSUE THREAD

**Issue by IvyGongoogle** [facebookresearch/fastText#198]
hello, I am interested in `FastText.zip: Compressing text classification models`, But when can you provide this code?
thank you very much!

**Comment by cpuhrsch** [comment]
Hello @IvyGongoogle,

In fact the repository already contains this code. Check out the 'quantization-example.sh' script and its content. This script creates a quantized model (you can find it in the result folder with file ending '.ftz') and also tests it. To see the savings in disk space compare the file size of the .ftz file with the corresponding .bin file (the script will also print these numbers). Let me know if this works for you!

Thank you,
Christian

**Comment by IvyGongoogle** [comment]
@cpuhrsch my god. it seems to be added into your this repository a day ago. I have tested it. Wonderful!
thank you very much!
