### ISSUE TITLE
can add script to realize the `synonym search` and `sentence similarity`

### ISSUE THREAD

**Issue by IvyGongoogle** [facebookresearch/fastText#199]
hello, I see fastText have the function to compute vector representations of `word` and `sentence or paragraph`, it will be cool if you add simple scripts to realize the `synonym search` and `sentences similarity`.

thank you!

**Comment by cpuhrsch** [comment]
Hey @IvyGongoogle,

It is currently not one of our priorities to officially support this, but it does indeed sound like a great feature to have. I will add it to my list of tasks and we can come back later on to consider this.

Thank you,
Christian

**Comment by IvyGongoogle** [comment]
@cpuhrsch thank for your response. look forward to the implementation.
