### ISSUE TITLE
Question: unit testing framework

### ISSUE THREAD

**Issue by alexbeletsky** [facebookresearch/fastText#20]
I'd like to understand the library a little better and thought to create some tests that can help to mitigate regression issues in the future. 

Last time I deal with Cpp quite some years ago, what is you preferable unit testing framework? I found [Catch](https://github.com/philsquared/Catch) and it looks good. 

What's your thoughts?

**Comment by ahmedghoneim92** [comment]
Catch was the first result I got on Google too. Seems very good. I'd like to help you with that if the moderators think it's a good idea :)

**Comment by cpuhrsch** [comment]
Hello @alexbeletsky, thank you for your interest in our project. We try to keep fastText free of dependencies to make sure it is as easy as possible to use. We would want the tests to also be executable on many other platforms. Ideally these tests would not require a specific dependency. I'll close this issue for now as it is quite old, but please feel free to reopen, if you're still interested.
