### ISSUE TITLE
When I use pretrainedVectors, some of the vector of word becomes all zeros.

### ISSUE THREAD

**Issue by XuelinZeng** [facebookresearch/fastText#201]
I have trained a model before and the .vec file was already generated. Then I ran a command like this ./fasttext skipgram -input new_input_file -output new_output_file -minn 0 -maxn 0 -wordNgrams 0 -dim 50 -thread 50 -pretrainedVectors xxx.vec, those words which appeared in pretrainedVectors, but not appeared in new_input_file, its vector in new_output_file.vec becomes all zeros.
Is there any thing wrong with my operation?

**Comment by spate141** [comment]
I guess you can only use -pretrainedVectors with supervised classification option.

here, 
`-pretrainedVectors  pretrained word vectors for supervised learning []`

**Comment by cpuhrsch** [comment]
Hey @XuelinZeng,

Can you provide me with the full set of commands so I can reproduce this behavior on my end?

Thank you,
Christian

**Comment by cpuhrsch** [comment]
Hey @XuelinZeng, I'm going to close the issue for now. Please feel free to reopen if you haven't been able to resolve it.
