### ISSUE TITLE
A problem in evaluate it by computing the precision and recall for text classification 

### ISSUE THREAD

**Issue by zhongboyin** [facebookresearch/fastText#205]
I was trained my data using the command in readme:
./fasttext supervised -input train.txt -output model

 which my trained data just  as follows:
__label__history	红军 长征 在 中国 革命史 上 的 地位
__label__world	实拍 神秘 之 国 ， 带 你 走进 真实 的 朝鲜
__label__tech	逼格 爆表 ！ 古文 版 2016 网络 热词 ： 燃尽 洪荒 之力...

but while I am trying to evaluate it as the readme said:
./fasttext test model.bin test.txt k
which my test data as follows:
sports	幼儿园 竞跑 比赛 ， 原本 可以 第二名 的 小盆友 跑 到 终点 时 是 被 暂停 了 吗
tech	点评 美团 和 糯米 激战 正酣 ， 而 背后 的 阿里 支付宝 这 几招 或能 秒杀 团购
...

the result returned as follows:
N	0
P@0	nan
R@0	nan
Number of examples: 0
 why  and how to solve?
thanks

**Comment by zhongboyin** [comment]
another result as follows ：
Assertion failed: (k > 0), function predict, file src/model.cc, line 143.
Abort trap: 6
why？

**Comment by zhongboyin** [comment]
the first question  is because the test data hasn't label ,right?
what about the second ?

**Comment by zhongboyin** [comment]
and the second , if there hasn't  the parameter  k , the result will be right...

**Comment by cpuhrsch** [comment]
Hey @zhongboyin,

Thank you for your post. Your test data will also need to follow the same format as your training data. That means you'll need '__label__' as a prefix for your labels. You're likely seeing this error, because this doesn't appear to be the case for your test data. Let me know if this helps!

Thank you,
Christian

**Comment by cpuhrsch** [comment]
Hey @zhongboyin, I'm going to close this issue for now. Please feel free to reopen if it does persist.

**Comment by little-yoki** [comment]
You should replace the letter k by an exact number.
For example:
./fasttext test model.bin test.txt 5

If you do not specify an exact number of k, fasttext will take 1 as default. So when you removed  the letter "k", it should have worked well by default.
