### ISSUE TITLE
Minor issues with the tutorials

### ISSUE THREAD

**Issue by coventry** [facebookresearch/fastText#206]
I ran into a couple of issues working through the tutorials.

- `sed -e "s/([.!?,'/()])/ 1 /g"` doesn't work on ubuntu. 

```bash
cat cooking.stackexchange.txt | sed -e "s/([.!?,'/()])/ 1 /g" | tr "[:upper:]" "[:lower:]" > cooking.preprocessed.txt
bash: !?,'/()])/ 1 /g" | tr "[:upper:]" "[:lower:]" > cooking.preprocessed.txt: event not found
```
- The first `wikifil.pl` I found from google generated garbage. Might want to link a specific version. I wound up using [this](https://gitlab-beta.engr.illinois.edu/upadhya3/event-wikifier/blob/86a4d0d773e412f7fa941d3ef6a8553250c6a5e2/scripts/wikifil.pl).

**Comment by ardeego** [comment]
@coventry The ``wikifil.pl`` is included in the fastText repository: [https://github.com/facebookresearch/fastText/blob/master/wikifil.pl](https://github.com/facebookresearch/fastText/blob/master/wikifil.pl)

If you want a fancier parser checkout  ``wikiextractor`` at [https://github.com/attardi/wikiextractor](https://github.com/attardi/wikiextractor)

**Comment by coventry** [comment]
> The wikifil.pl is included in the fastText repository: 

Huh. Sorry, I must have fat-fingered my `find` command.
