### ISSUE TITLE
Classifying tweet topics

### ISSUE THREAD

**Issue by Mustyy** [facebookresearch/fastText#207]
Is there somewhere I can get data related to tweets with labeling

In the example data is related to cooking so the model I'm training would not be good
I have already trained it on the english wiki data 

Any ideas?

**Comment by cpuhrsch** [comment]
Hey @Mustyy,

I'm not entirely sure how to help you with this. I know that Twitter as an api to download tweets. A Google search probably also yields a few datasets that you could use. One of the first entries I found yielded this post on their discussion board: https://twittercommunity.com/t/how-could-i-get-twitter-data-for-research/10777 . We haven't used Twitter data in our research thus far, so there is no dataset published and linked to fastText that specifically uses tweets.

Thank you,
Christian

**Comment by anthdm** [comment]
Hi @Mustyy,

You can use the Twitter API to pull some tweets in that suit your interest. After that, you can use the text blob library for sentiment analysis, and create a labeled set of tweets, based on their sentiment.

Hope that helps you further.
