### ISSUE TITLE
[unsupervised learning] Export ngram as text file?

### ISSUE THREAD

**Issue by pommedeterresautee** [facebookresearch/fastText#21]
Right now, we are supposed to use fasttext exec to generate vectors for OOV words.
According to the source code, it seems simple to generate them in any prog language if we have access to the n-gram vectors. 

Would it be possible to get a feature to export the content of the bin model (including n-gram) as text file?

**Comment by piotr-bojanowski** [comment]
Hi! Unfortunately, since we use a hashing function for ngrams, we cannot trivially save ngrams and their corresponding vectors.

**Comment by pommedeterresautee** [comment]
I got that, but if we can get the hash, the hashing function documented in some way, and the vector, it would be enough.

**Comment by piotr-bojanowski** [comment]
>  the hashing function documented 
We use our own implementation of the Fowler–Noll–Vo hashing function. See dictionary.cc.
What you propose is equivalent to a re-write of a part of the library in a different programming language. I would rather write a wrapper that calls specific functions of fasttext (see for instance https://github.com/pyk/fastText.py for a Python interface).
Best

**Comment by pommedeterresautee** [comment]
Curiosity: why not using Murmur which is quite standard in similar situation now (spark, vowpal, etc use it)?
