### ISSUE TITLE
Which wikipedia dump is used for the pretrained vectors?

### ISSUE THREAD

**Issue by anton164** [facebookresearch/fastText#211]
I'm working on improving a corpus builder from wikipedia that aims to create a better text corpus from wikipedia dumps. 

I would like to evaluate the quality of our corpus by recreating the pretrained word vectors from this project and evaluating them against eachother. Hence, I was wondering which raw Wikipedia dump you used to create the pretrained word vectors?

**Comment by ardeego** [comment]
@anton164 Any of the recent dumps will do. They are published by Wikipedia monthly-ish. I commented on the issue before (see comment [here](https://github.com/facebookresearch/fastText/issues/161)).

This link will take you to the most recent dump file: [https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2](https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2).

**Comment by cpuhrsch** [comment]
Hello @anton164,

We now have a script called 'get-wikimedia.sh', that you can use to download and process a recent wikipedia dump of any language. This script applies the preprocessing we used to create the published word vectors.

The parameters we used to build the word vectors are the default skip-gram settings, except with a dimensionality of 300 [as indicated on the top of the list of word vectors](https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md) (we now understand that this could be more visible).

Thanks,
Christian
