### ISSUE TITLE
compilation errors with g++-4.6

### ISSUE THREAD

**Issue by pliable-statistics** [facebookresearch/fastText#213]
I'm getting errors when trying to compile fasttext with g++-4.6.4
But it compiles without errors with g++-4.7 or newer.
I believe one should update requirements in documentation:
"((gcc-4.6.3 or newer) or (clang-3.3 or newer))" -> "((gcc-4.7 or newer) or (clang-3.3 or newer))"

```
$ head -n 15 Makefile 
...
CXX = g++-4.6 
CXXFLAGS = -pthread -std=c++0x
OBJS = args.o dictionary.o productquantizer.o matrix.o qmatrix.o vector.o model.o utils.o fasttext.o
INCLUDES = -I.

opt: CXXFLAGS += -O3 -funroll-loops

```

```
$ make clean && make
rm -rf *.o fasttext
g++-4.6  -pthread -std=c++0x -O3 -funroll-loops -c src/args.cc
g++-4.6  -pthread -std=c++0x -O3 -funroll-loops -c src/dictionary.cc
In file included from src/dictionary.cc:10:0:
src/dictionary.h:55:31: sorry, unimplemented: non-static data member initializers
src/dictionary.h:55:31: error: ISO C++ forbids in-class initialization of non-const static member ‘pruneidx_size_’
Makefile:25: recipe for target 'dictionary.o' failed
make: *** [dictionary.o] Error 1
```

**Comment by cpuhrsch** [comment]
Hello @pliable-statistics,

Some recent changes have reduced compatibility older versions of gcc. We try to be compliant with as old versions as possible, however this is becoming increasingly more difficult. It looks like you have access to more recent versions of gcc, so I consider this issue resolved. If this is not true,  please reopen this issue at any time.

Thanks,
Christian

**Comment by pliable-statistics** [comment]
> like you have access to more recent versions of gcc, so I consider this issue resolved.

yes, but documentation still needs to be fixed:
https://github.com/facebookresearch/fastText/blame/master/README.md#L11
