### ISSUE TITLE
How can i get the labels' vector?

### ISSUE THREAD

**Issue by Anikacyp** [facebookresearch/fastText#216]
Does anyone know is there a way to get the labels' vector from the trained model?

**Comment by loretoparisi** [comment]
In my understanding, when doing unsupersived learning (command `fasttext skipgram`), it creates the `.bin` and the `.vec` files:

https://github.com/facebookresearch/fastText/blob/f5f3ecd9b00cc84311a958da2b52e32fba6a491c/tutorials/unsupervised-learning.md

While when doing supervised learning (command `fasttext supervised...`) it only create a `.bin` model file.

**Comment by cpuhrsch** [comment]
For now we don't support the printing of labels given a model, but a slight modification of 'print-word-vectors' should do the trick. I'll add it to the list of upcoming changes.
