### ISSUE TITLE
terminate called after throwing an instance of 'std::length_error' while trying to read in Japanese vectors

### ISSUE THREAD

**Issue by jlowryduda** [facebookresearch/fastText#220]
I've downloaded the Japanese vectors from your [pretrained-vectors page](https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md). However, I can't seem to be able to use them with your command line tool. For example, when I run `echo "要旨" | ./fasttext print-vectors wiki.ja.bin`, I get the following error:

```
terminate called after throwing an instance of 'std::length_error'
   what():  vector::_M_default_append
 Aborted (core dumped)
```

The same error occurs when I try to run `./fasttext print-ngrams wiki.ja/wiki.ja.bin 要旨`

I'm able to use the English vectors just fine.

**Comment by jlowryduda** [comment]
Nevermind, the problem was with my not re-building the code correctly.

**Comment by hellomaxwell** [comment]
I meet the same problem as yours, please tell me detail about it

**Comment by jlowryduda** [comment]
If I remember correctly, I had to just get the newest version of the code and then re-compile it.
