### ISSUE TITLE
Question: can fastText capture the structure of a text (i.e. poem metrics)?

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/fastText#221]
Supposed to have a lyrics poem, like `Elizabeth Barrett Browning`'s famous `How Do I Love Thee`

```
How do I love thee? Let me count the ways.

I love thee to the depth and breadth and height

My soul can reach, when feeling out of sight

For the ends of Being and ideal Grace

I love thee to the level of everyday's

Most quiet need, by sun and candle-light.

I love thee freely, as men strive for Right;

I love thee purely, as they turn from Praise.

I love thee with the passion put to use

In my old griefs, and with my childhood's faith

I love thee with a love I seem to love

With my lost saints, - I love thee with the breath,

Smiles, tears, of all my life! - and, if God choose,

I shall but love thee better after death.
```

If the input dataset has a normalized text (like removing diacritics, none [a-zA-Z] chars, etc.) but keeping `\n` or `\r\n`,  therefore it keep the metrics of the poem, will the network be able to classify it?

At this time my normalization looks like [here](https://github.com/loretoparisi/fasttext.js/blob/master/lib/index.js#L312)

```javascript
/**
 * Normalize test helper
 * @see https://github.com/facebookresearch/fastText/blob/master/classification-example.sh#L15
 * @param text string
 * @return string
 */
FastText.normalize = function(text) {
    text=text.toLowerCase()
    .replace(/^/gm, '__label__')
    .replace(/(?:\\[rn]|[\r\n]+)+/g, " ")
    .replace(/'/g, " ' ")
    .replace(/"/g, '')
    .replace(/\./g, ' \. ')
    .replace(/,/g, ' \, ')
    .replace(/\(/g, ' ( ')
    .replace(/\)/g, ' ) ')
    .replace(/!/g, ' ! ')
    .replace(/\?/g, ' ! ')
    .replace(/;/g, ' ')
    .replace(/:/g, ' ')
    .replace(/\t+/g,'\t').replace(/\t\s/g,' ').replace(/\t/g,' ');
    return text;
```

If not, is this more likely a `LSTM` task for [fairseq](https://github.com/facebookresearch/fairseq)?
My guess is about the text tokenizer that could skip the carriage return anyways...
Thank you.

**Comment by cpuhrsch** [comment]
Hello @loretoparisi,

Do you have labels for your data? I don't see them as part of your example.

Thanks,
Christian

**Comment by loretoparisi** [comment]
@cpuhrsch hello, so I have a dataset of poems, where the label can be the `metrics` involved or the `style` of the writer.

**Comment by cpuhrsch** [comment]
Ok then you can setup a dataset similar to the classification example script (i.e. prefixing each line with __label__<actual label>) and train on it. You can tune and evaluate as is usual with a validation and test set.

Thanks,
Christian

**Comment by cpuhrsch** [comment]
Hello @loretoparisi,

I'm closing the issue now to keep track of answered questions. Please feel free to reopen it at any time, if you think the question hasn't been sufficiently answered.

Thanks,
Christian
