### ISSUE TITLE
Bin file Turkish in old format?

### ISSUE THREAD

**Issue by ErnstTmp** [facebookresearch/fastText#222]
Hello,
in order to read them into fasttext.py , which can currentyy only read the old format, I would need the old version of the pretrained word embeddings in Turkish. Is this file still available?

Thanks and kind regards
Ernst

**Comment by prakhar2b** [comment]
@ErnstTmp [gensim](https://github.com/RaRe-Technologies/gensim) can load both the new and old format of the pretrained (or any) fastText modelled word embeddings. Please look into [this PR](https://github.com/RaRe-Technologies/gensim/pull/1319) (will be merged asap)

The command for loading  the Turkish pretrained vector in gensim is-

```python
import os
from gensim.models.wrappers import FastText
model = FastText.load_fasttext_format(os.path.abspath('wiki.tr'))
```

cc @tmylk @jayantj

**Comment by ErnstTmp** [comment]
@prakhar2b thank you very much for your help, that are good news!
I will use gensim then!
