### ISSUE TITLE
src/dictionary.h:55:31: error: ISO C++ forbids in-class initialization of non-const static member 

### ISSUE THREAD

**Issue by WiFeng** [facebookresearch/fastText#223]
[liuweifeng@vm-10-154-250-5 fastText]$ make
c++ -pthread -std=c++0x -O3 -funroll-loops -c src/dictionary.cc
In file included from src/dictionary.cc:10:0:
src/dictionary.h:55:31: sorry, unimplemented: non-static data member initializers
src/dictionary.h:55:31: error: ISO C++ forbids in-class initialization of non-const static member ‘pruneidx_size_’
make: *** [dictionary.o] Error 1

**Comment by WiFeng** [comment]
[liuweifeng@vm-10-154-250-5 fastText]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/gcc-4.6.3/libexec/gcc/x86_64-redhat-linux/4.6.3/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ./configure --prefix=/usr/local/gcc-4.6.3 --with-mpfr=/usr/local/mpfr-2.4.2/ --with-mpc=/usr/local/mpc-1.0.3/ --with-gmp=/usr/local/gmp-4.3.2/ --with-arch_32=i686 --build=x86_64-redhat-linux --disable-multilib
Thread model: posix
gcc version 4.6.3 (GCC) 
[liuweifeng@vm-10-154-250-5 fastText]$ c++ -v
Using built-in specs.
COLLECT_GCC=c++
COLLECT_LTO_WRAPPER=/usr/local/gcc-4.6.3/libexec/gcc/x86_64-redhat-linux/4.6.3/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ./configure --prefix=/usr/local/gcc-4.6.3 --with-mpfr=/usr/local/mpfr-2.4.2/ --with-mpc=/usr/local/mpc-1.0.3/ --with-gmp=/usr/local/gmp-4.3.2/ --with-arch_32=i686 --build=x86_64-redhat-linux --disable-multilib
Thread model: posix
gcc version 4.6.3 (GCC)

**Comment by pliable-statistics** [comment]
https://github.com/facebookresearch/fastText/issues/213
You are getting errors because fasttext cannot be compiled with gcc 4.6.3.

**Comment by pliable-statistics** [comment]
if for some reason you have to use gcc-4.6.3, then you can checkout this commit:
https://github.com/facebookresearch/fastText/commit/f5f3ecd9b00cc84311a958da2b52e32fba6a491c
code from this commit compiles without errors even with gcc-4.6.3

**Comment by yuquanle** [comment]
hi pliable-statistics:
I have the same error like this. I try the method you provided but failed. My gcc version is gcc-4.8 but the error is still exist.@pliable-statistics

**Comment by pliable-statistics** [comment]
@yuquanle 
can you please provide output of `c++ -v` and `uname -a` commands

**Comment by yuquanle** [comment]
@pliable-statistics  thank you very much ,I have solve it.

**Comment by Chenweihua405** [comment]
@WiFeng  thank you , I have the same problem with you!

**Comment by WiFeng** [comment]
@Chenweihua405  use gcc 4.7 or newer.

**Comment by cpuhrsch** [comment]
Hello all,

We try to support older gcc versions as possible. Indeed recent changes have broken backwards compatibility for old versions of gcc (before 4.7). We're going to try and change this in upcoming updates, however it's going to become increasingly more difficult to support versions this old (gcc 4.6.3 was released March 2012).

Thanks,
Christian
