### ISSUE TITLE
Unsupervised training - new line vs no new line in samples?

### ISSUE THREAD

**Issue by akcom** [facebookresearch/fastText#229]
When looking through the wikipedia example, no new lines are added to separate training sentences.  But in Dictionary::readLine() (called by trainThread()), it appears as if input sentences are chunked by new lines.

Should we be using new lines to separate training sentences?  Is the wikipedia file just an example of a situation where a substantial amount of training data overcomes the noise induced by edge cases where sentence boundaries are crossed for context?

**Comment by cpuhrsch** [comment]
Hello @akcom,

In general I advise to separate sentences or paragraphs with newlines at their boundaries. We might update the wikipedia dataset to reflect this as well in the future, depending on new features we plan to introduce (and for performance reasons).

Thanks,
Christian
