### ISSUE TITLE
Pre-trained models - loading GloVe models

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/fastText#230]
I would like to use pre-trained word embedding `GloVe` models like the Twitter model ( (2B tweets, 27B tokens, 1.2M vocab, uncased, 25d, 50d, 100d, & 200d vectors ) available [here](https://nlp.stanford.edu/projects/glove/)
Do I need a conversion between the `FastText` and the `GloVe` models?

**Comment by gserapio** [comment]
I'd like to know this as well!

**Comment by cpuhrsch** [comment]
Hello @loretoparisi,

You can indeed load these vectors. All you need to add is the number of lines and the dimensionality at the beginning of the GloVe files. You'll see that these then match the .vec format that we use.

Thanks,
Christian

**Comment by loretoparisi** [comment]
@cpuhrsch thank you. What about Google's word2vec model ` GoogleNews-vectors-negative300.bin`? There are some converters from `GloVe`, but any easier way?
