### ISSUE TITLE
Issue with Compilation

### ISSUE THREAD

**Issue by sagnikbanerjee15** [facebookresearch/fastText#231]
Hello I am trying to compile the program but I run into the following issue. Please help.

c++ -pthread -std=c++0x -O3 -funroll-loops -c src/args.cc
c++ -pthread -std=c++0x -O3 -funroll-loops -c src/dictionary.cc
c++ -pthread -std=c++0x -O3 -funroll-loops -c src/matrix.cc
c++ -pthread -std=c++0x -O3 -funroll-loops -c src/qmatrix.cc
c++ -pthread -std=c++0x -O3 -funroll-loops -c src/vector.cc
c++ -pthread -std=c++0x -O3 -funroll-loops -c src/model.cc
c++ -pthread -std=c++0x -O3 -funroll-loops -c src/fasttext.cc
c++ -pthread -std=c++0x -O3 -funroll-loops args.o dictionary.o productquantizer.o matrix.o qmatrix.o vector.o model.o utils.o fasttext.o src/main.cc -o fasttext
productquantizer.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
make: *** [fasttext] Error 1

Thank you

**Comment by onurgu** [comment]
Do you have a line like

`productquantizer.o: src/productquantizer.cc src/productquantizer.h src/utils.h`

in your Makefile?

**Comment by sagnikbanerjee15** [comment]
Yes I do

**Comment by onurgu** [comment]
Then the problem is that the current version of the object file became corrupted somehow.

Just run
`
make clean
`
and then
`
make opt
`

**Comment by sagnikbanerjee15** [comment]
Oh Thank you this time it worked..
ᐧ

Sagnik Banerjee
Graduate Research Assistant
Bioinformatics and Computational Biology
Department of Plant Pathology and Microbiology
Dr. Roger Wise's Lab
Iowa State University

*"The moment I have realized God sitting in the temple of every human body,
the moment I stand in reverence before every human being and see God in him
- that moment I am free from bondage, everything that binds vanishes, and I
am free" - Swami Vivekananda*
