### ISSUE TITLE
Need a sample data.txt file

### ISSUE THREAD

**Issue by SilentFlame** [facebookresearch/fastText#232]
Hello @EdouardGrave @piotr-bojanowski,

I need a sample data.txt file to train my model of `fasttext` in the process to us it for creating and testing vectors for words "out of vocabulary".

Please provide some link to some useful resources.

**Comment by cpuhrsch** [comment]
Hey @SilentFlame, I'm not sure what you mean exactly. What type of model would you like to train using fasttext? There are two example scripts, that train both supervised and unsupervised models (see classification-example.sh and word-vector-example.sh). These will also fetch the required data.

**Comment by SilentFlame** [comment]
I'm to train for a model to give me a vector of some "Out of vocabulary" word.

I guess from your above answer I'll get the needed. Thanks :)

**Comment by cpuhrsch** [comment]
Closing this issue now as it appears the question has been sufficiently answered.
