### ISSUE TITLE
Purpose of -minn  and -maxn for supervised training

### ISSUE THREAD

**Issue by namp** [facebookresearch/fastText#234]
It is pretty clear what the purpose of the parameters minn and maxn is in unsupervised mode (e.g. skipgram) where vectors of sequences between minn and maxn characters are produced. However  I have a difficulty in understanding the purpose of these parameters in supervised mode and especially how they are combined with wordNgrams>1

Judging by their default values in supervised mode which is 0 for both, I suspect they are only there for code compatibility purposes.

Thanks

**Comment by cpuhrsch** [comment]
Hello @namp,

Indeed the supervised training mode is not making used of subwords yet. Therefore these options have no effect.

Thanks,
Christian

**Comment by cpuhrsch** [comment]
Hello @namp,

This feature has been added as part of 431c9e2.

Thanks,
Christian
