### ISSUE TITLE
what is the function of -neg

### ISSUE THREAD

**Issue by zhongboyin** [facebookresearch/fastText#235]
how to use this parameter and what is it's function ?can you take me an example ?

**Comment by cpuhrsch** [comment]
Hello @zhongboyin,

The option -neg allows you to choose the number of negative samples that are sampled at each iteration when using the negative sampling loss. More negative samples will yield a more accurate approximation of the loss at increased computational cost. Please see following paper for details on this procedure.

[Distributed Representations of Words and Phrases and their Compositionality](https://arxiv.org/abs/1310.4546) by Tomas Mikolov, Ilya Sutskever, Kai Chen, Greg Corrado, Jeffrey Dean

Thanks,
Christian
