### ISSUE TITLE
The pre-trained word vectors in bin and text formats are not the same

### ISSUE THREAD

**Issue by sls56** [facebookresearch/fastText#238]
On the "fastText_multilingual" repo, a user reported that the pre-trained word vectors provided here in the bin+text download do not always match those provided in the text download.

https://github.com/Babylonpartners/fastText_multilingual/issues/4

Is there a reason for this? Are they different training runs?

**Comment by EdouardGrave** [comment]
Hi @sls56,

Thanks for reporting this. Indeed, there was a small mixup when we updated the bin+text archives to support the new binary file format. We are fixing this, and will update you once it is done.

Best,
Edouard.

**Comment by EdouardGrave** [comment]
Hi @sls56,

Everything should be fixed now (all models corresponding to the first models we released). Please re-open the task if there are still discrepancies.

Best,
Edouard.
