### ISSUE TITLE
 supervised() got an unexpected keyword argument 'wordNgrams'

### ISSUE THREAD

**Issue by jasminezz** [facebookresearch/fastText#240]
fasttext version:0.8.3
python version:2.7
I using the func  like this:
  ```
 classifier = fasttext.supervised(train_file, output_model, label_prefix="__label__", dim=64, lr=0.5,
                                     bucket=100000, thread=20, loss='hs', wordNgrams = 2)
```
but get the error:
 supervised() got an unexpected keyword argument 'wordNgrams'?
 I check the function info  " -wordNgrams         max length of word ngram [1] ", I really don't know why, need your help?

**Comment by cpuhrsch** [comment]
Hello @jasminezz,

Unfortunately we can't help you with this. You're probably best advised to follow up with the maintainer of the Python package, unless you can reproduce an error with the fasttext binary itself (which is part of this repository).

Thank you,
Christian
