### ISSUE TITLE
Difference between English and Simple English pretrained vectors..

### ISSUE THREAD

**Issue by michellemorales** [facebookresearch/fastText#244]
I was wondering what was the difference between these two models?

**Comment by EdouardGrave** [comment]
Hi @michellemorales,

These two models were trained on the [English Wikipedia](https://en.wikipedia.org/wiki/Main_Page) and [Simple English Wikipedia](https://simple.wikipedia.org/wiki/Main_Page) respectively. You can learn more about the Simple English Wikipedia [here](https://simple.wikipedia.org/wiki/Wikipedia:Simple_English_Wikipedia).

Best,
Edouard.
