### ISSUE TITLE
when does the fasttext can be calculated on windows？

### ISSUE THREAD

**Issue by Chenweihua405** [facebookresearch/fastText#245]

**Comment by cpuhrsch** [comment]
Hello @Chenweihua405,

Have you tried compiling fasttext on Windows and found issues using it?

Thanks,
Christian

**Comment by VaclavObornik** [comment]
Hi, yes, I'm getting two errors:

error C2039: 'iota': is not a member of 'std' 
error C3861: 'iota': identifier not found

But everything looks ok if I add 
#include <numeric>
in files using std::iota

I have found the solution here: http://www.programmingforums.org/thread7858.html

**Comment by cpuhrsch** [comment]
Hello @VaclavObornik,

That's interesting. What compiler / version are you using? Maybe it's related to that more than the OS.

- Christian

**Comment by saroufimc1** [comment]
@VaclavObornik Can you please explain what you mean by 
"I add
#include <numeric>
in files using std::iota" 

In which file do you add this?

**Comment by saroufimc1** [comment]
@VaclavObornik : are you then able to import the package in Python? I am getting 
ImportError: No module named 'fastTextpy
Althought it is there...

**Comment by cpuhrsch** [comment]
Hello @Chenweihua405,

We've recently added numeric to the recent header files, which should enable the compilation on Windows. Please let me know if the issue remains and feel free to reopen this at any point. Thanks to @VaclavObornik for pointing this out.

Thanks,
Christian
