### ISSUE TITLE
Retrieve weights of classifier

### ISSUE THREAD

**Issue by Romainsauvestre** [facebookresearch/fastText#249]
Hi, is it possible to retrieve the weights of the classifier please?

Thank you!
Romain

**Comment by dcsan** [comment]
if you mean the probability, have a look at the `predict-prob` method.

`./fasttext predict-prob \`

**Comment by pierrearb** [comment]
@Romainsauvestre this PR answers your question https://github.com/facebookresearch/fastText/pull/295
Let's hope it'll be merged soon

**Comment by Romainsauvestre** [comment]
Thank you @pierrearb , exactly what I was looking for !
