### ISSUE TITLE
how to print out word vector file in supervised classification

### ISSUE THREAD

**Issue by michaelwiegand82** [facebookresearch/fastText#250]
When I run the supervised classifier within fastText, I only obtain a bin-file.
There is no vector file.
I read in a previous (closed) issue (#96) that this was announced be changed.
Do I make anything wrong or does the current version of fastText still not produce the vector file?

Thank you.

**Comment by loretoparisi** [comment]
@michaelwiegand82 I think at this time, this feature is not still implemented.

**Comment by bittlingmayer** [comment]
In #104 (Dec 2016), @EdouardGrave said a fix was on the way.

**Comment by dcsan** [comment]
if you use a separate .vec file, like the pretrained vectors, I'm not sure why you would need this.
unless it's a very customised dictionary?

I usually train using the prepared vectors with:

    -pretrainedVectors mj/corpus/binary/wiki.zh.vec \

is there something i'm missing?

**Comment by cpuhrsch** [comment]
Hello @michaelwiegand82,

Your requested feature is now the new default. That means, every mode causes a .vec file to be saved.

Thank you,
Christian

**Comment by michaelwiegand82** [comment]
I just tested it and indeed now found the additional .vec file.
Thank you very much for this addition!
