### ISSUE TITLE
Segementation fault when delete[] codes_ in file qmatrix.cc

### ISSUE THREAD

**Issue by hanzeil** [facebookresearch/fastText#251]
When I delete a fasttext object which is used to do supervised learning, segementation fault occurred when delete[] codes_ in file qmatrix.cc, due to the variable codesize_ equals to 0.
Thank you.

**Comment by cpuhrsch** [comment]
Hello @hanzeil,

This is indeed an issue and we're landing a fix soon.

Best,
Christian

**Comment by cpuhrsch** [comment]
Hey @hanzeil,

The fix for this just landed. Feel free to reopen of this continues to be a problem.

Thanks,
Christian
