### ISSUE TITLE
FastText Zip

### ISSUE THREAD

**Issue by ErnstTmp** [facebookresearch/fastText#252]
Hello,
is there a possibility that you can add the possibility to load FTZ - FastText Zip Models into Gensim? I have a problem with big memory footprint in FastText.

Kind regards
Ernst

**Comment by cpuhrsch** [comment]
Hello @ErnstTmp 

Thank you for your post. Unfortunately we can't help you with this. You're probably best advised to follow up with the maintainer of the package, unless you can reproduce an error with the fasttext binary itself (which is part of this repository). Feel free to reopen this issue at any time if this is indeed the case.

Thank you,
Christian
