### ISSUE TITLE
Entire Set of Nearest Neighbors 

### ISSUE THREAD

**Issue by denzilc** [facebookresearch/fastText#253]
Would it be possible to get the entire list of Nearest Neighbors? Currently, just the [top 10 are printed](https://github.com/facebookresearch/fastText/blob/master/tutorials/unsupervised-learning.md#nearest-neighbor-queries). It would be nice to have the full set.

**Comment by cpuhrsch** [comment]
Hello @denzilc,

You can specify the number of nearest neighbors via one of the parameters.

```
./fasttext nn
usage: fasttext nn <model> <k>

  <model>      model filename
  <k>          (optional; 10 by default) predict top k labels
```

To get all nearest neighbors you'll need to set k to be the size of all words. Make sure you start with a smaller number than that to see how this affects performance.

- Christian
