### ISSUE TITLE
DeepText ConvNets support

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/fastText#266]
Will FastText support the `ConvNets` described in the paper  [Character-level Convolutional Networks for Text Classification](https://arxiv.org/abs/1509.01626) in the next releases?

An implementation is available from the authors in lua/torch [here](https://github.com/zhangxiangxiao/Crepe)

**Comment by cpuhrsch** [comment]
Hello @loretoparisi,

This is not on our agenda at this point in time. In fact, fastText compares favorably against CNNs on most tasks as you can read about in the associated [paper](https://arxiv.org/pdf/1607.01759.pdf). Given that the supervised model fastText implements is much simpler, there's currently no need to expand its complexity, especially given the additional (immense) computational cost of a CNN. 

Thanks,
Christian

**Comment by loretoparisi** [comment]
Thank you I understand your point and it's a good consideration in terms of computational costs and performances! Hopefully the Mikolov/LeCun text classification models comparison will not turn into the Torvalds/Tanenbaum monolithic/microkernel holy war of AI :D
