### ISSUE TITLE
reading pre-trained word2vecs from database

### ISSUE THREAD

**Issue by sam-iitj** [facebookresearch/fastText#267]
I have tried training **_Fasttext_** models with pretrained word vectors. Turns out _**fasttext**_ takes a long amount of time just to load the word vectors in memory. So, I was trying to figure out if there is a way we can establish a DB connection and read the required word vectors on the fly. Lemme know if any one else has the similar concerns or is working on a similar issue.

**Comment by cpuhrsch** [comment]
Hello @sam-iitj,

It is difficult for us to extend fastText for particular DB solutions, since we try to keep the codebase minimal. What do you mean by 'on-the-fly'? Do you mean 'on-demand' if a particular vector is needed for training?

Thanks,
Christian

**Comment by sam-iitj** [comment]
Hello Christian, 

Yup I mean, while we are training a model on a particular dataset we don't need all the pretrained word vectors for training. So, I am trying to figure out a way if we can read only the required word vectors "on-demand" and speed up the training. As from my experience, it takes a lot of time to load up the huge pretrained word vectors file(i.e 8mins  wiki.en.vec). So, if could get away with using the just required word vectors we could have a definite speed up in training as well as while doing the predictions. Lemme know incase, if you any other ideas for speed up or if I am missing a point somewhere. 

-Thanks,
Satyam

**Comment by cpuhrsch** [comment]
Hello @sam-iitj,

You could filter the words, if you know them in advance. That is, you could remove words (lines) in the .vec file that you know won't be needed. Otherwise I'm afraid we don't have the option yet to integrate a database (such as MySQL etc.). This is also something we don't plan to add in the foreseeable future as it will increase the size of the code significantly and removes orthogonality. I, personally, don't find 8 minutes to be a very long time, especially for batch jobs. However, this, understandably, could be very different for real-time jobs. What is your usecase, that you need this to be fast? 

Thanks,
Christian

**Comment by sam-iitj** [comment]
Hello @cpuhrsch , 

Actually my use case is more along the lines of learning from small amount of data and also to quickly incorporate feedback. So, the initial experiments i'm running right now is to cross validate across different number of training samples (i.e. evaluating train and test performance). That is why, I need good run-time performance for both evaluation as well as deployment. Thanks for your suggestions on using the subset of the complete pretrained word vectors file. Lemme know incase you have any other pointers on this issue. 

-Thanks, 
Satyam

**Comment by cpuhrsch** [comment]
Hello @sam-iitj,

At this point there isn't much more I can do here. I'd suggest storing and writing the vectors in RAM via for example a RAM disk (e.g. tmpfs). This could significantly increase your throughput, albeit I'd expect the pretrained vectors to already be buffered in RAM by the filesystem (depending on your settings of course). I'm closing this issue for now as feel like we've thoroughly discussed it. Feel free to reopen it at any point. I'll add this to our list of potential future developments, but I can't guarantee any timeline.

Thanks,
Christian
