### ISSUE TITLE
Can anyone tell me the fasttext train param when Pre-trained word vectors are trained and why the word in the text9 are in one row,will it affect the result when words are put in more than one row?

### ISSUE THREAD

**Issue by piyongze** [facebookresearch/fastText#274]

**Comment by cpuhrsch** [comment]
Hello @piyongze,

Thank you for your post. You can find details on how the [pre trained vectors](https://fasttext.cc/docs/en/pretrained-vectors.html) were build within the [corresponding paper](https://arxiv.org/pdf/1607.04606.pdf). To understand how a lack of a newline does not affect training consider the [getLine function](https://github.com/facebookresearch/fastText/blob/master/src/dictionary.cc#L329). As you can see it will break up the text into chunks of up to [MAX_LINE_SIZE](https://github.com/facebookresearch/fastText/blob/master/src/dictionary.h#L38). I'm going to close this issue now, but please encouraged free to reopen it at any time if you don't consider this issue resolved.

Thanks,
Christian
