### ISSUE TITLE
Vectors for n-grams

### ISSUE THREAD

**Issue by NightXBurn** [facebookresearch/fastText#282]
Can we have the vectors of the subwords informations(n-grams), for construc vectors of unseen words ?

**Comment by cpuhrsch** [comment]
Hello @NightXBurn,

Might the 'print-word-vectors' subcommand be what you are looking for?

Thanks,
Christian

**Comment by NightXBurn** [comment]
Hi @cpuhrsch,
I'm using fastText with python i can't find this command. 

Thanks for your reply,

**Comment by pommedeterresautee** [comment]
words and subwords exists as hash in the bin model. You can't easily extract them (there is by definition no mapping hash -> subwords), but you can generate word vectors leveraging them.

**Comment by NightXBurn** [comment]
Thanks @pommedeterresautee,
In the paper, the author used the word embeddings generated by the skip gram model and the subword informations vectors to construct the word vectors. i'm asking for subword informations to construct vectors for unseen words.

**Comment by englhardt** [comment]
If you want to extract the raw n-grams for a list of words, have a look at PR #289.

**Comment by NightXBurn** [comment]
Thank you so much @cpuhrsch and @englhardt for being helpful.
