### ISSUE TITLE
Why does the argument '-ws' influence the result in supervised learning?

### ISSUE THREAD

**Issue by ssqNo1** [facebookresearch/fastText#287]
And why does the argument '-neg' influence the result when not using negative sampling?

**Comment by cpuhrsch** [comment]
Hello @ssqNo1,

Thank you for your post. Have you succeeded in reproducing this issue using one of the test datasets (such as dbpedia)? You can download several using the fetch_test_data.sh script under the tests folder. If so, could you please post a list of commands using either the cli or python bindings so I can reproduce the issue on my end?

Thanks,
Christian

**Comment by cpuhrsch** [comment]
Hello @ssqNo1,

Thank you again for your post. I'm closing this now due to inactivity, but please feel free to reopen this at any point.

Thanks,
Christian

**Comment by selenewang** [comment]
Hi! I am the same problem here! What does ws means with regards to supervised learning (text classifier)? And why does it influence the accuracy?
