### ISSUE TITLE
using `nn` (nearest neighbor) from code

### ISSUE THREAD

**Issue by dcsan** [facebookresearch/fastText#291]
the tutorial shows using the `nn` command interactively from a prompt, but how do I use it and call with normal code and get results back?

```
./fasttext nn                                
usage: fasttext nn <model> <k>

  <model>      model filename
  <k>          (optional; 10 by default) predict top k labels
```

**Comment by dcsan** [comment]
it seems there is a 
```
void FastText::findNN(const Matrix& wordVectors, const Vector& queryVec,
                      int32_t k, const std::set<std::string>& banSet) {
```

https://github.com/facebookresearch/fastText/blob/master/src/fasttext.cc#L450

method, but is there a public way to call that from the command line?

@piotr-bojanowski 

otherwise what other tools are compatible with your `.vec ` format? I thought that `fasttext` is its own format separate from normal word2vec implementations.

**Comment by englhardt** [comment]
You can also call it with pipes since it reads from `std::cin`:
```
echo "the" | ./fasttext nn model.bin
```
Afterwards, you need to parse/clean the output though.

The `.vec` files are in the "standard" plain text word2vec. For example [gensim](https://radimrehurek.com/gensim/) can load it. Note that the `.vec` files only contain the word vectors and no information on the n-gram vectors. Out of vocabulary words can therefore not be handled like when using `.bin` files with _fastText_.

**Comment by dcsan** [comment]
this doesn't seem to work for me. I still get an interactive prompt.

additionally is there a way to use the other functions with pipes? I tried just get the usage prompt:

```sh
echo "生理 生理性 理性 黄疸" | ./fasttext predict-prob mj/data/binary/labels.model.bin  
usage: fasttext predict[-prob] <model> <test-data> [<k>]
```

**Comment by loretoparisi** [comment]
Having the same issue in https://github.com/facebookresearch/fastText/issues/322

**Comment by cpuhrsch** [comment]
Hello @dcsan ,

Thank you for your post. We do have an implementation of 'find_nearest_neighbor' as part of the Python bindings. It is part of the utilities under

```
fastText.util. find_nearest_neighbor
```

I'm closing this issue for now, but please feel free to reopen this at any point if this doesn't resolve your issue. In particular, you might not want to use Python.

Thanks,
Christian

**Comment by dcsan** [comment]
the issue was resolved, I didn't know at the time how to add `-` as a final param to say to accept stdin.

**Comment by nabilmagnus** [comment]
can help with arguments please . i don't know what to put i have my model (.bin) file but , don't have any result ....

**Comment by loretoparisi** [comment]
@nabilmagnus @dcsan I have implemented this in the node.js wrapper if it can help! https://github.com/loretoparisi/fasttext.js/blob/master/examples/nearest.js
