### ISSUE TITLE
Initialize with GloVe and train on the target corpus

### ISSUE THREAD

**Issue by jgc128** [facebookresearch/fastText#296]
Hi,

Could you please explain what is the proper way of using the parameter `-pretrainedVectors` for a initialization of the embeddings before training them on the target corpus?

I would like to initialize the embeddings with GloVe vectors and then tune it on the target corpus. Is using the parameter `-pretrainedVectors` the proper way of doing this? The description of this parameter says `pretrained word vectors for supervised learning []` - aren't word vectors trained in an unsupervised fashion? 

More over, I could not find any documentation how to load a pre-trained binary model and continue the training.

Thanks!

**Comment by EdouardGrave** [comment]
Hi @jgc128,

The `-pretrainedVectors` option was added mostly to initialize the word embeddings of supervised models with vectors which were trained in an unsupervised fashion. Do you want to initialize an unsupervised model (`cbow` or `skipgram`) with pre-trained vectors?

If so, I believe that using the `-pretrainedVectors` option is the proper way of doing this (I have never tried this though). It will initialize the embeddings and then fine-tune these on the target corpus.

By the way, you can also try to use our recently released word vectors, trained on Wikipedia and common crawl, which are available on the fastText website: https://fasttext.cc/docs/en/english-vectors.html.

As of now, it is not possible to load pre-trained binary models.

Please feel free to re-open this task if this does not answer your questions!

Best,
Edouard.

**Comment by jgc128** [comment]
Hi,
  
  
>Do you want to initialize an unsupervised model (cbow or skipgram) with pre-trained vectors?

Yes, that's exactly what I would like to do. 


>By the way, you can also try to use our recently released word vectors, trained on Wikipedia and common crawl

Great! I did not know about this! It's not on this page:
https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md


Thank you for your responses, it's very helpful!
