### ISSUE TITLE
tar file unzip error

### ISSUE THREAD

**Issue by nityendrasingh** [facebookresearch/fastText#30]
Hey guys,

I'm getting following problem while unzipping downloaded file dbpedia_csv.tar.gz in classification-example.sh

[vols]temp $ tar -xzvf dbpedia_csv.tar.gz 

**gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now**

Any comments?

**Comment by pyk** [comment]
Please run `file(1)` to make sure the downloaded file is a valid gzip compressed data. 

For example:

```
% file dbpedia_csv.tar.gz 
dbpedia_csv.tar.gz: gzip compressed data, from Unix, last modified: Thu Sep 10 03:24:27 2015
% tar -xzvf dbpedia_csv.tar.gz 
dbpedia_csv/
dbpedia_csv/classes.txt
dbpedia_csv/test.csv
dbpedia_csv/train.csv
dbpedia_csv/readme.txt
```

**Comment by nityendrasingh** [comment]
Thanks pyk!

The file at original location (https://googledrive.com/host/0Bz8a_Dbh9QhbQ2Vic1kxMmZZQ1k) is an HTML file. It says that document has moved to new location. 

https://8c47f35de2544a202d525720f08188d254682381.googledrive.com/host/0Bz8a_Dbh9QhbQ2Vic1kxMmZZQ1k

Should I go ahead and update the shell script?

**Comment by pyk** [comment]
The current script is fine, `wget(1)` will follow the URL redirection automatically. 

To follow redirects with `curl(1)`, use the `-L` switch
