### ISSUE TITLE
print-word-vectors fail with pretrained model with std::bad_alloc

### ISSUE THREAD

**Issue by msclar** [facebookresearch/fastText#300]
```
cat single_words_eng | ./fasttext print-word-vectors ../../wiki.en.bin >> word_vectors_fasttext_eng
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```
I checked with `free -mh` and I have almost 8GB of free RAM. I also have 14GB of free space on disk. I tried with the Spanish pretrained model (wiki.es.bin) and it worked fine. What could be the issue? Thanks!

**Comment by cpuhrsch** [comment]
Hello @msclar,

Thank you for your post. This error is indeed expected if you run out of memory. Could you try this again with the most recent version of our code?

Thanks,
Christian

**Comment by cpuhrsch** [comment]
Hello @msclar,

Thank you again for your post. I'm closing this now due to inactivity, but please feel encouraged to reopen this at any point if the problem persists.

Thanks,
Christian

**Comment by dvirginz** [comment]
It happens to me as well.
