### ISSUE TITLE
fail to print-sentence-vectors using model.ftz

### ISSUE THREAD

**Issue by youyangluo** [facebookresearch/fastText#306]
the command "print-sentence-vectors" doesn't work for the compressed model, but other functionality, like "test" or "predict" work well.

**Comment by EdouardGrave** [comment]
Hi @youyangluo,

Thank you for your bug report. We will fix this asap!

Best

**Comment by EdouardGrave** [comment]
Hi @youyangluo,

This should be fixed now.

Best,
Edouard.
