### ISSUE TITLE
fasttext-0.8.3: failed to load/compute vectors from model file in Windows (7) OS

### ISSUE THREAD

**Issue by jerrygaoLondon** [facebookresearch/fastText#308]
I have problems to load/compute vector from pre-trained model file(i.e., bin file) correctly on Windows OS. with ```model['king']``` for example, it always return zero vectors and the vocabulary set (```model.words) is always empty.

Using same model file and code, it works well in Linux.

PS: i have no problem to install and train an embedding (e.g., skipgram model) on Windows OS. ```bin``` and ```bin.vec``` can be generated correctly as expected. 

Any idea ?

**Comment by jerrygaoLondon** [comment]
It might be helpful for someone else :

I finally make it work with xiamx's binary builds for 64 bit Windows and gensim fasttext wrapper (https://github.com/xiamx/fastText/releases).

Training: 

```
from gensim.models.wrappers import FastText
model = FastText.train('c:\\Downloads\\fasttext\\fastText.exe', corpus_file='c:\\Data\\all_sentences.txt')
```

Load from pre-trained model:

```
from gensim.models.wrappers import FastText
model2 = FastText.load_fasttext_format('C:\\Data\\all_sentences_skipgram_v100.bin')
...
```
So, i would be good to merge the windows support patch.

Cheers,
Jerry

**Comment by cpuhrsch** [comment]
Hello @jerrygaoLondon,

Thank you for your post. Unfortunately, we can't help you with this. You're probably best advised to follow up with the maintainer of the package, unless you can reproduce an error with the fasttext binary or Python bindings themselves (which are part of this repository). Feel free to reopen this issue at any time if this is indeed the case.

Thank you,
Christian
