### ISSUE TITLE
Abort trap 6: dyld: Symbol not found

### ISSUE THREAD

**Issue by mjahanshahi** [facebookresearch/fastText#311]
Hi there,

I'm having trouble running any of the commands from fastText. An example of error messages that I get when I run the skipgram routine:

dyld: lazy symbol binding failed: Symbol not found: __ZNKSt8__detail20_Prime_rehash_policy11_M_next_bktEm
  Referenced from: /Users/fastText/./fasttext (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libstdc++.6.dylib

dyld: Symbol not found: __ZNKSt8__detail20_Prime_rehash_policy11_M_next_bktEm
  Referenced from: /Users/fastText/./fasttext (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libstdc++.6.dylib

Abort trap: 6

I've tried to find other people with this issue but it seems like it might be a compiler problem?

I wiped and reinstalled all the required packages and could not progress past this Abort trap6.

My packages in the virtual environment for these experiments are:
certifi                   2016.2.28                py36_0  
cloog                     0.18.0                        0  
gcc                       4.8.5                         8  
gmp                       6.1.0                         0  
isl                       0.12.2                        1  
mkl                       2017.0.3                      0  
mpc                       1.0.3                         0  
mpfr                      3.1.5                         0  
numpy                     1.13.1                   py36_0  
openssl                   1.0.2l                        0  
pip                       9.0.1                    py36_1  
python                    3.6.2                         0  
readline                  6.2                           2  
scikit-learn              0.19.0              np113py36_0  
scipy                     0.19.1              np113py36_0  
setuptools                36.4.0                   py36_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py36_0  
xz                        5.2.3                         0  
zlib                      1.2.11                        0  

Thank you!

**Comment by sedaghatfar** [comment]
Hello, @mjahanshahi were you able to get past the Abort trap: 6 error?

**Comment by sedaghatfar** [comment]
Thank you!

**Comment by maya-ami** [comment]
Hi @mjahanshahi . I'm currently stuck with the same problem. Could you please elaborate on where is ''the correct location'' for the gcc compiler exactly?
