### ISSUE TITLE
Old model

### ISSUE THREAD

**Issue by Emixam23** [facebookresearch/fastText#317]
Hi, 

I can't load the wiki.fr.bin with fasttest.py (0.8.3).

It says on the internet that you changed the model structures, so if it's true, can you either provide an update of the library or a link to the previous model to download?

Thank you for any help !

**Comment by ggyyggyyggyy** [comment]
I used python tools of pyfasttext  instead fasttext. 
Here is the github website, https://github.com/vrasneur/pyfasttext.
Just follow its instructions, it is sure to work!

**Comment by cpuhrsch** [comment]
Hello @Emixam23,

We can't help you with

**Comment by cpuhrsch** [comment]
Hello @Emixam23,

Thank you for your post. Unfortunately, we can't help you with this. You're probably best advised to follow up with the maintainer of the package, unless you can reproduce an error with the fasttext binary or Python bindings themselves (which are part of this repository). Feel free to reopen this issue at any time if this is indeed the case.

Thank you,
Christian
