### ISSUE TITLE
Pretrained russian vector has different length size

### ISSUE THREAD

**Issue by bekerov** [facebookresearch/fastText#318]
Downloaded pretrained russian (text file) word vectors [here](https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md)

I use this code for loading vector
```
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    ...
```

On line 535 this file has incorrect vector length (301)

года
['—', '0.023498', '0.12149', '-0.073881', '-0.70431', '0.062581', '0.10652', '-0.048931', '0.052913', '-0.055506', '0.43748', '-0.13062', '0.13011', '0.086788', '0.056069', '-0.37516', '0.5281', '-0.3793', '-0.24476', '0.34291', '0.12777', '-0.13414', '0.36656', '-0.64564', '0.10394', '-0.15074', '-0.50376', '0.34982', '0.25574', '-0.56582', '-0.14833', '0.22864', '0.070571', '0.26372', '-0.26622', '-0.13925', '-0.1547', '-0.013141', '-0.025499', '0.27183', '-0.3524', '0.075246', '-0.0018144', '0.17131', '-0.49992', '-0.27329', '-0.1307', '-0.35632', '-0.07603', '0.069268', '-0.21408', '0.013884', '-0.049', '-0.27466', '0.0014307', '0.12745', '0.20166', '0.089138', '0.10773', '0.010189', '-0.55659', '0.32298', '-0.47556', '-0.02819', '-0.056929', '0.28663', '-0.13338', '-0.6524', '-0.076967', '-0.041963', '0.23764', '0.11345', '0.02561', '0.27409', '-0.18557', '-0.24235', '-0.30306', '-0.11778', '-0.14809', '-0.067891', '-0.046727', '-0.15876', '0.05202', '0.020732', '0.15732', '0.46279', '-0.069872', '0.30629', '-0.083566', '-0.12716', '-0.092243', '-0.28907', '-0.30935', '0.20664', '-0.088152', '-0.2614', '0.29795', '0.22957', '0.061824', '-0.034472', '-0.074454', '-0.14012', '-0.18947', '0.19226', '0.25841', '-0.0046989', '0.12736', '-0.4176', '-0.27888', '0.53506', '0.48525', '0.40703', '0.15184', '0.19828', '-0.019854', '0.028712', '0.4434', '-0.28439', '0.018626', '-0.37084', '-0.51133', '-0.11276', '0.41912', '0.10644', '0.028228', '0.27616', '-0.070307', '0.053628', '-0.11284', '0.57476', '-0.072872', '0.015899', '0.2397', '0.19118', '0.011608', '-0.18272', '0.15634', '0.32522', '-0.35838', '0.15017', '-0.088002', '0.24407', '-0.16371', '-0.25247', '-0.12128', '-0.29032', '0.1078', '-0.19713', '0.40635', '-0.10261', '-0.20836', '0.26735', '-0.16896', '0.48766', '0.31526', '0.039216', '0.08959', '-0.039507', '-0.10699', '0.063793', '0.18984', '0.16589', '-0.32525', '0.1569', '-0.17123', '0.35364', '0.0032255', '0.16629', '-0.33723', '0.18487', '0.44312', '-0.13136', '0.20915', '-0.049084', '0.032726', '-0.036638', '-0.029758', '-0.1146', '0.51406', '-0.062248', '0.10836', '-0.28531', '-0.13348', '0.49333', '0.0014867', '0.21658', '-0.42501', '0.18735', '0.082973', '-0.19928', '-0.70313', '0.0083858', '-0.18469', '-0.13891', '-0.31803', '-0.81605', '-0.36352', '-0.68278', '0.33454', '0.15017', '-0.47288', '-0.016612', '0.22284', '0.58439', '-0.072966', '0.51678', '-0.19386', '0.38218', '-0.044947', '-0.065488', '0.033403', '-0.38704', '-0.39491', '0.26582', '0.22806', '0.12378', '-0.14388', '-0.049995', '-0.12973', '0.42297', '0.21755', '-0.25133', '-0.33954', '-0.019581', '-0.088319', '0.0099454', '-0.10155', '0.070227', '0.40468', '-0.52329', '-0.31331', '-0.33736', '-0.083911', '-0.054979', '0.30949', '-0.70696', '0.27694', '0.2462', '-0.15163', '-0.048189', '-0.0021578', '-0.26087', '0.038161', '-0.035606', '-0.11668', '0.48442', '0.14212', '-0.10291', '0.040834', '-0.13033', '0.26661', '0.27811', '-0.14117', '-0.53489', '-0.46776', '-0.098981', '0.11612', '-0.013137', '-0.24172', '-0.27606', '0.34689', '-0.39896', '-0.11386', '0.1783', '0.072469', '-0.048611', '0.35845', '0.4428', '0.18771', '-0.00821', '-0.11728', '-0.61911', '-0.065139', '0.2132', '-0.51537', '-0.21661', '-0.34931', '0.3598', '-0.14773', '-0.16364', '0.35899', '-0.28951', '0.15088', '-0.21592', '0.7542', '0.34118', '0.44266', '-0.092184', '-0.33517', '0.1225', '-0.062415', '-0.34483', '-0.059714', '0.23337', '0.31456', '0.24347', '0.16425', '0.52507', '-0.28406', '-0.35718', '0.11511']
Traceback (most recent call last):
ValueError: could not convert string to float: '—'

Is it normal?

**Comment by EdouardGrave** [comment]
Hi @bekerov,

This is a tokenization error. The character between "года" and "—" is not recognized is a whitespace by fastText, which thus consider "года —" to be one word.

If you open the file by only splitting using the lines on spaces, you should not get an error anymore:
```
for line in f:
    values = line.split(' ')
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    ...
```

We will fix this in a new version of the word vectors.

Best,
Edouard.
