### ISSUE TITLE
How to load the pretrained Wikipedia .vec or .bin vectors in PyTorch ?

### ISSUE THREAD

**Issue by laubonghaudoi** [facebookresearch/fastText#319]
I have a short text classification model written in PyTorch and I want to load the pretrained wikipedia word vectors from [this page](https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md) into the model. How can I achieve this ? Do I use
```python
self.embed.weight.data.copy_(torch.from_numpy(pretrained_embeddings))
```
or any other possible way ? Are the downloaded .vec or .bin files off-the-shelf to use ? Do I have to do any manual configurations ?

**Comment by Mithrillion** [comment]
The workaround I found is to load the vectors into SpaCy first, then use a function to convert it to numpy arrays:
```
def get_embeddings(vocab):  # load spacy.model.vocab object
    nr_vector = max(lex.rank for lex in vocab) + 1
    vectors = np.zeros((nr_vector + 1, vocab.vectors_length), dtype='float32')
    for lex in vocab:
        if lex.has_vector:
            vectors[lex.rank + 1] = lex.vector / lex.vector_norm
    return vectors
```

**Comment by cpuhrsch** [comment]
Hello @laubonghaudoi,

Looks like this issue might be resolved, so I'm closing it now, but please feel free to reopen it at any point if this is not the case. As an aside, you can also use our new Python bindings to create   embeddings for any word given a .bin file (see installation instructions within the README and examples within the python directory).

Thanks,
Christian

**Comment by rohitsaluja22** [comment]
@cpuhrsch Are there any FastText bindings available for lua/torch? I want to add fasttext model to my network which I have coded in lua. Please help.
