### ISSUE TITLE
German Version contains Errors

### ISSUE THREAD

**Issue by markbosshard** [facebookresearch/fastText#320]
The following lines contain errors in the German .txt version, where the errors are characters next to the words:

53474: schaffen — 
114262:  _% gebäude
114436 _ha gesamtfläche
189333:  •  •  
... 94 additional lines after these

I am giving up at this point and ignoring bad lines. Will this be fixed?

**Comment by cpuhrsch** [comment]
Hello @markbosshard 

Please see the [FAQ](https://fasttext.cc/docs/en/faqs.html#there-are-misspellings-in-the-dictionary-should-we-improve-text-normalization). I'm closing the issue for now, but please feel free to reopen it at any point if you don't consider this resolved.

Thanks,
Christian
