### ISSUE TITLE
Will the pre-trained vector files be updated?

### ISSUE THREAD

**Issue by jkleiser** [facebookresearch/fastText#321]
It would be nice to know if any of the word vector files have been updated lately, e.g. during the last six months. Is it possible to have "last modified" dates in the list of files?

**Comment by EdouardGrave** [comment]
Hi @jkleiser,

We have updated the .bin files to fix a small bug, but the models have not changed (the .vec files have not been updated). We are working on a new version of the pre-trained word vectors. When releasing these, we will make clear that they are different from the initial ones.

Best,
Edouard.
