### ISSUE TITLE
Unspervised NN and ANALOGIES Not Interactive mode

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/fastText#322]
When I pipe a word echoed to the `nn` mode it works properly:
```
$ echo "love" | ./fasttext nn /root/w2v_model.bin 10
Pre-computing word vectors... done.
Query word? lover 0.661769
unfurl 0.634839
loved 0.610024
loveless 0.545917
someday 0.538872
alaina 0.531431
x3 0.531392
runway 0.524286
glove 0.523325
hoe 0.501622
Query word? [l
```

but using the `analogies` mode it seems to stuck to the query and then to loop again indefinitely on it:

```
"berlin germany france" | ./fasttext analogies /root/w2v_model.bin
Query triplet (A - B + C)? trance 0.877698
clearance 0.810188
exuberance 0.78448
seance 0.774825
lance 0.754855
clearances 0.716718
appearances 0.714397
greivance 0.709422
romance 0.70849
chance 0.693051
Query triplet (A - B + C)? trance 0.877698
clearance 0.810188
exuberance 0.78448
seance 0.774825
lance 0.754855
clearances 0.716718
appearances 0.714397
greivance 0.709422
romance 0.70849
chance 0.693051
Query triplet (A - B + C)? trance 0.877698
clearance 0.810188
exuberance 0.78448
seance 0.774825
lance 0.754855
clearances 0.716718
appearances 0.714397
greivance 0.709422
romance 0.70849
....
```

My aim is to use unsupervised `nn` and `analogies` in a not interactive mode.

**Comment by cpuhrsch** [comment]
Hello @loretoparisi  ,

Thank you for your post. We do have an implementation of 'find_nearest_neighbor' as part of the Python bindings. It is part of the utilities under

```
fastText.util. find_nearest_neighbor
```

Further we have an implementation of [compute-accuracy](https://github.com/tmikolov/word2vec/blob/master/compute-accuracy.c) in Python under python/doc/examples/compute_accuracy.py. This includes an example of how to [complete an analogy](https://github.com/facebookresearch/fastText/blob/master/python/doc/examples/compute_accuracy.py#L40).

I'm closing this issue for now, but please feel free to reopen this at any point if this doesn't resolve your issue. In particular, you might not want to use Python.

Thanks,
Christian
