### ISSUE TITLE
Questions fasttext with Spacy

### ISSUE THREAD

**Issue by montibo** [facebookresearch/fastText#328]
Hi, 
I hope this questions is at the right place here. Do you know how to use fasttext vec.bin models in spacy library ? 
We are building a french chatbot and we think fasttext model will be much better than the current default one on spacy. 

Thanks a lot,

Thibault

**Comment by Mithrillion** [comment]
I don't know if there is a better way but you can use 
```
spacy_model.vocab.load_vectors(open("fasttext.vec", "r")
```
to load from the text file. The problem I am running into is that SpaCy uses `str.split` to read each row, and some space characters in the vocabulary of the .vec file can mess it up. Currently I am using the script below to remove the problematic words and return a "clean" version of the .vec file. There could be other space characters that I have not yet encountered, but the script seems to be working well so far.

```
import re

with open("../wordvecs/wiki.en/wiki.en.vec") as f:
    with open("../wordvecs/wiki.en/wiki.en.nospace.vec", "w") as g:
        f.readline()
        line = f.readline()
        while line:
            if not re.search(r'[\u00A0\u1680\u180e\u2000-\u2009\u200a\u200b\u202f\u205f\u3000\u2028\x85]', line):
                g.write(line)
            line = f.readline()
```

**Comment by montibo** [comment]
thank you very much for answer.

**Comment by honnibal** [comment]
@montibo I've opened an issue about this on spaCy's tracker (so I believe this issue can be closed).

In summary: spaCy should implement the character ngram composition as well as just reading in the vector table. It's pretty easy to do that, and it'll help a lot for languages like French.

**Comment by cpuhrsch** [comment]
Hello @montibo,

In general we can't help with issues regarding third-party libraries or bindings. As an aside, we've been actively developing Python bindings for fastText. Give them a try if you want, installation instructions are part of the README. Closing this now as this appears to be resolved. Please feel free to reopen at any point if that is not the case.

Thanks,
Christian
