### ISSUE TITLE
Building word-representations independently from classification model

### ISSUE THREAD

**Issue by merrellb** [facebookresearch/fastText#33]
We often have a large unsupervised corpus available to generate word-representations but only a smaller subset of labeled data for supervised training.  An option to specify these corpora independently or accomplish this in two distinct steps would allow better usage of all available training data.

**Comment by EdouardGrave** [comment]
We are working on adding options to use unlabeled data during supervised training. Stay tuned.

**Comment by EdouardGrave** [comment]
It is now possible to use pre-trained word vectors (trained on a large unsupervised corpus, for example using `./fasttext skipgram`) when learning supervised models, by using the command line option `-pretrainedVectors`. This option is used to specify a text file containing the pre-trained word vectors.
