### ISSUE TITLE
Ubuntu 16.09 - CPU at 800% as supervised (zombie) process hangs

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/fastText#331]
My process `fasttext`was retaining 800% of cpu

```
208 root      20   0 2872576 2.275g   3728 S 800.0  7.2   2676:26 fasttext 
```

Investigating the run command it was

```
root       208  797  7.2 2872576 2399336 ?     Sl   02:41 2723:24 ./fasttext supervised -input /tmp/0d12bc23-5739-414d-b448-4b5ee4becfb2.csv -output /tmp/ft_tone_model -wordNgrams 2 -minCount 1 -minCountLabel 1 -minn 3 -maxn 6 -t 0.0001 -bucket 10000000 -dim 50 -lr 0.1 -ws 15 -loss ns -lrUpdateRate 100 -epoch 20 -thread 8 -verbose 4
```

where my training file was (for some error occurred in the pre-processing before) just 1 line file:

```
# wc -l < /tmp/0d12bc23-5739-414d-b448-4b5ee4becfb2.csv
1
```

that was like this

```
# cat /tmp/0d12bc23-5739-414d-b448-4b5ee4becfb2.csv
__label__anger	i\ ' m jealous ,  i\ ' m overzealous when i\ ' m down i get real down when i\ ' m high i don\ ' t come down i get angry ,  baby ,  believe me i could love you just like that and i can leave you just as fast but you don\ ' t ,  judge me \ ' cause if you did ,  baby ,  i would judge you too no you don\ ' t ,  judge me \ ' cause if you did ,  baby ,  i would judge you too \ ' cause i got issues ,  but you got \ ' em too so give \ ' em all to me and i\ ' ll give mine to you bask in the glory ,  of all our problems \ ' cause we got the kind of love it takes to solve \ ' em yeah ,  i got issues 
```

The process did not returned with `0` or error, but just kept running like a zombie, detached from the parent process.

**NOTE**
I have also found some `<defunct>` processes like

```
root       180  0.0  0.0      0     0 ?        Z    02:30   0:09 [fasttext] <defunct>
root       193  0.0  0.0      0     0 ?        Z    02:34   0:10 [fasttext] <defunct>
```

**Comment by cpuhrsch** [comment]
Hello @loretoparisi,

Thank you for your post. Could you rerun this using the latest version of fastText? Generally we have not observed this behavior when running our integration tests. In order for me to reproduce this on my end I'd also need your data or see it reproduced on one of our test sets.  Ideally within a [docker image](https://hub.docker.com/_/ubuntu/) since I'll otherwise have no access to your exact environment.

Thanks,
Christian

**Comment by loretoparisi** [comment]
@cpuhrsch closing this, since I'm not aware of this issue anymore!
