### ISSUE TITLE
Do I need to keep period in input text

### ISSUE THREAD

**Issue by yuhengd** [facebookresearch/fastText#333]
Do I need to keep the '.' in original text input in order for fasttext to work better? Thanks.

**Comment by EdouardGrave** [comment]
Hi @yuhengd,

Keeping or removing punctuation in the input text should not have a big influence on the performance of the model. What is important is to "separate" the punctuation from the words (i.e. transforming "The cat sat on the mat." to "The cat sat on the mat ."). This pre-processing step is known as tokenization and can be performed using various open source tools, the Stanford Tokenizer (https://nlp.stanford.edu/software/tokenizer.html).

Best,
Edouard.

**Comment by m4r3x** [comment]
Hi, sorry for bringing this topic up, but I noticed that punctual marks actually play a significant role when it comes to language classification. 

I went with a minimum `probability = 0.4`.

Please take a look at this phrase:
`Heizen mit..` -> it gets identified as `"af": 0.4332830011844635`
`Heizen mit.`  -> it gets identified as "unknown".
`Heizen mit`   -> it gets identified as `"de": 0.9987722039222717`

I've noticed that on pretty short sentences it makes sense to drop the punctual marks if you wish to improve the scoring :)
