### ISSUE TITLE
Problem in replicating Fasttext performance

### ISSUE THREAD

**Issue by hungle2018** [facebookresearch/fastText#334]
I trained a supervised Fasttext model and used the learnt model to extract the text embedding of the training and test set. I applied a linear classifier on the learnt embedding of the train set and tested the classifier on the learnt embedding of the test set. My results could not match the results by using FastText directly. Are there other layer than a linear classifier as mentioned in [https://arxiv.org/abs/1607.01759](https://arxiv.org/abs/1607.01759)?

**Comment by hungle2018** [comment]
Updates: I have extracted the char-ngrams and word embeddings from the trained model, and noted that the word embedding vector is the sum of  component char-ngrams and word embeddings. However, the sentence embedding is not the sum or average of component word embeddings Was there other further processing to obtain the sentence embeddings?

**Comment by honnibal** [comment]
Maybe you didn't normalize the vectors? I think this looks like the relevant bit of code:  https://github.com/facebookresearch/fastText/blob/master/src/fasttext.cc#L393

**Comment by cpuhrsch** [comment]
Hello @hungle2018,

Please consider the answer in this issue https://github.com/facebookresearch/fastText/issues/323. I'm closing this issue now, but please feel encouraged to reopen this issue if you don't consider it resolved.

Thanks,
Christian
