### ISSUE TITLE
sub-words embedding save?

### ISSUE THREAD

**Issue by TamouzeAssi** [facebookresearch/fastText#335]
Hello,

Im new in using this project.  Im interesting to get the sub-word embeddings. 

How can I please get them in order to re-use them in an ulterior task?

Thank you

**Comment by englhardt** [comment]
Have a look at #289.

**Comment by EdouardGrave** [comment]
Hi @TamouzeAssi,

As of now, the simplest way to get the subword embeddings is to use the Python bindings.

You can get the id of a subword using the function `get_subword_id` or the list of all the subwords of a given word using the function `get_subwords`. Then, you can use the function `get_input_vector` to get the vector corresponding to a particular id.

Best,
Edouard.

**Comment by Celebio** [comment]
Hi @TamouzeAssi ,
I am closing the issue now. Feel free to re-open it if you have further questions.

Best regards,
Onur
