### ISSUE TITLE
Score of predicted  Label ?? 

### ISSUE THREAD

**Issue by balaram-bhukya** [facebookresearch/fastText#338]
How to find Score for predicted label. ? what is the confidence level ?

**Comment by hammad7** [comment]
Try predict-prob command. It supports top k as well.

**Comment by cpuhrsch** [comment]
Hello @balaram-bhukya,

Thank you for your post. What @hammad7 describes is indeed the solution. I'm closing the issue now, but please feel free to reopen if this is still current.

Thank you,
Christian
