### ISSUE TITLE
Understanding FastText Options

### ISSUE THREAD

**Issue by myoldusername** [facebookresearch/fastText#339]
First of all , i have to say , this FastText lib , is wonderful peace of art , it's save for me a lot of time , now i am working for Gender detection , and it works 70% fine , looking for more accuracy.

And as a Starter with NLU , with the sort of documentation / HowTo , use FastText simple options, i like to ask for a ref. which describe each option in order to understand what i am doing , not follow other command as a blind !
```

  The following arguments are optional:
  -verbose            verbosity level [2]
  The following arguments for the dictionary are optional:
  -minCount           minimal number of word occurences [5]
  -minCountLabel      minimal number of label occurences [0]
  -bucket             number of buckets [2000000]
  -t                  sampling threshold [0.0001]

  The following arguments for training are optional:
  -lr                 learning rate [0.05]
  -lrUpdateRate       change the rate of updates for the learning rate [100] 
  -dim                size of word vectors [100]
  -ws                 size of the context window [5]
  -epoch              number of epochs [5]
  -neg                number of negatives sampled [5]
  -loss               loss function {ns, hs, softmax} [ns]
  -thread             number of threads [12] 
  -pretrainedVectors  pretrained word vectors for supervised learning []
``` 

I am sure rising the value dos not mean , this is better !, like " learning rate" when i make it 1.00 it return bad result compared with 0.025 .

So i need to know what i am doing , and at least understand ! what this value will do.

**Comment by EdouardGrave** [comment]
Hi @myoldusername,

The learning rate control the how "fast" the model is updated during training: this parameter control the size of the update which is applied to the parameters of the models. Changing the learning rate from 0.025 to 1.0 means that the updates which are applied to the model are 40 times larger. You can read our tutorial (https://fasttext.cc/docs/en/supervised-tutorial.html) to learn more about the different command line options, and their influence.

Best,
Edouard.

**Comment by cpuhrsch** [comment]
I'm closing this issue since @EdouardGrave's answer is quite detailed. @myoldusername please feel free to reopen this at any point if you do not consider this resolved.

Thanks,
Christian
