### ISSUE TITLE
Fasttext language identification Normalization method

### ISSUE THREAD

**Issue by myoldusername** [facebookresearch/fastText#340]
Dear FastText Authors.

Thank you for this wonderful add on , [https://fasttext.cc/docs/en/language-identification.html#content](https://fasttext.cc/docs/en/language-identification.html#content)   

Which is a life saver .
I would like to know what is the Normalization method has been used to add training data , in order to Normalize the text before identification .
Is there any class we can use / port e.g to PHP ?
Regards

**Comment by EdouardGrave** [comment]
Hi @myoldusername,

We did not use any normalization method on the training data, so that the language identification model can be directly used on raw data.

Best,
Edouard.
