### ISSUE TITLE
how can i install fastText in python3 ？

### ISSUE THREAD

**Issue by suparek** [facebookresearch/fastText#342]
**when i install fasttext in python3，i will see these error (i use conda)**:

`Collecting fasttext
  Using cached fasttext-0.8.3.tar.gz
Collecting numpy>=1 (from fasttext)
  Downloading numpy-1.13.3-cp34-cp34m-manylinux1_x86_64.whl (16.9MB)
    100% |████████████████████████████████| 16.9MB 73kB/s 
Collecting future (from fasttext)
  Using cached future-0.16.0.tar.gz
Building wheels for collected packages: fasttext, future
  Running setup.py bdist_wheel for fasttext ... error
  Complete output from command /data/yangtao/anaconda3/envs/fasttext/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0esjlrlr/fasttext/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp1ihhi_kipip-wheel- --python-tag cp34:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.4
  creating build/lib.linux-x86_64-3.4/fasttext
  copying fasttext/model.py -> build/lib.linux-x86_64-3.4/fasttext
  copying fasttext/__init__.py -> build/lib.linux-x86_64-3.4/fasttext
  running build_ext
  building 'fasttext.fasttext' extension
  creating build/temp.linux-x86_64-3.4
  creating build/temp.linux-x86_64-3.4/fasttext
  creating build/temp.linux-x86_64-3.4/fasttext/cpp
  creating build/temp.linux-x86_64-3.4/fasttext/cpp/src
  gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./fasttext -I/data/yangtao/anaconda3/envs/fasttext/include/python3.4m -c fasttext/fasttext.cpp -o build/temp.linux-x86_64-3.4/fasttext/fasttext.o -O3 -pthread -funroll-loops -std=c++0x
  gcc: error trying to exec 'cc1plus': execvp: No such file or directory
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for fasttext
  Running setup.py clean for fasttext
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /data/yangtao/.cache/pip/wheels/c2/50/7c/0d83b4baac4f63ff7a765bd16390d2ab43c93587fac9d6017a
Successfully built future
Failed to build fasttext
Installing collected packages: numpy, future, fasttext
  Running setup.py install for fasttext ... error
    Complete output from command /data/yangtao/anaconda3/envs/fasttext/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0esjlrlr/fasttext/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-lp6cw4xb-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.4
    creating build/lib.linux-x86_64-3.4/fasttext
    copying fasttext/model.py -> build/lib.linux-x86_64-3.4/fasttext
    copying fasttext/__init__.py -> build/lib.linux-x86_64-3.4/fasttext
    running build_ext
    building 'fasttext.fasttext' extension
    creating build/temp.linux-x86_64-3.4
    creating build/temp.linux-x86_64-3.4/fasttext
    creating build/temp.linux-x86_64-3.4/fasttext/cpp
    creating build/temp.linux-x86_64-3.4/fasttext/cpp/src
    gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./fasttext -I/data/yangtao/anaconda3/envs/fasttext/include/python3.4m -c fasttext/fasttext.cpp -o build/temp.linux-x86_64-3.4/fasttext/fasttext.o -O3 -pthread -funroll-loops -std=c++0x
    gcc: error trying to exec 'cc1plus': execvp: No such file or directory
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/data/yangtao/anaconda3/envs/fasttext/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0esjlrlr/fasttext/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-lp6cw4xb-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-0esjlrlr/fasttext/`

**my system is ubuntu 16.04 , it can't be installed on python3？**
my environment is:
Cython                    0.27.2                    <pip>
openssl                   1.0.2l                        0    defaults
pip                       9.0.1                    py34_1    defaults
python                    3.4.5                         0    defaults
readline                  6.2                           2    defaults
setuptools                27.2.0                   py34_0    defaults
sqlite                    3.13.0                        0    defaults
tk                        8.5.18                        0    defaults
wheel                     0.29.0                   py34_0    defaults
xz                        5.2.3                         0    defaults
zlib                      1.2.11                        0    defaults

**Comment by cpuhrsch** [comment]
Hello @jasminezz,

Thank you for your post. Unfortunately, we can't help you with this. You're probably best advised to follow up with the maintainer of the package, unless you can reproduce an error with the fasttext binary itself (which is part of this repository). Feel free to reopen this issue at any time if this is indeed the case.

Thank you,
Christian
