### ISSUE TITLE
lightweight pretrained word2Vec

### ISSUE THREAD

**Issue by Herlderlord** [facebookresearch/fastText#345]
Hi, 

I'm looking for a pretrained word2vec the weight of which is close to 300 Mo. 
Do you know if this kind of pretrained model in ENGLISH exists ? (i know it exists in french)

Best regards.

**Comment by cpuhrsch** [comment]
Hello @Herlderlord,

Thank you for your post. I assume you're looking for a list of pretrained English word vectors. You can find those [here](https://fasttext.cc/docs/en/english-vectors.html#content). I'm closing the issue now, but please feel free to reopen at any point, if you do not consider this resolved.

Thanks you
Christian

**Comment by Herlderlord** [comment]
Hello @cpuhrsch,
Thank you for you answer. 
I'm looking for a pretrained model which is more lightweight. The model have to weight 300 Mo or less. Do you have this kind of pretrained model ? 
(600 Mo is too heavy)
