### ISSUE TITLE
python install error

### ISSUE THREAD

**Issue by jwnsu** [facebookresearch/fastText#348]
Run "python setup.py install" as described in python/Readme.MD, got following error:
"Traceback (most recent call last):
  File "setup.py", line 61, in <module>
    extra_compile_args=["-O3"],
  File "/home/tf/local/lib/python2.7/site-packages/setuptools/extension.py", line 39, in __init__
    _Extension.__init__(self, name, sources, *args, **kw)
  File "/usr/lib/python2.7/distutils/extension.py", line 109, in __init__
    "'sources' must be a list of strings"
AssertionError: 'sources' must be a list of strings".

Env: Ubuntu 16.04/python2.7.12.

**Comment by cpuhrsch** [comment]
Hello @jwnsu,

Thank you for your post. I'm able to reproduce this error on my end (using Python2.7). I found the error and will send out a fix soon.

Thanks,
Christian

**Comment by cpuhrsch** [comment]
The fix has been pushed, please try again!

**Comment by Danielberry90** [comment]
Re: [facebookresearch/fastText] python install error (#348)

**Comment by jwnsu** [comment]
Work like a charm, thanks!

**Comment by Danielberry90** [comment]
[facebookresearch/fastText]
