### ISSUE TITLE
ImportError: No module named 'fastTextpy'

### ISSUE THREAD

**Issue by yolossn** [facebookresearch/fastText#352]
**from fastTextpy import train_supervised**
ImportError                               Traceback (most recent call last)
<ipython-input-14-a845bc8cc085> in <module>()
----> 1 from fastTextpy import train_supervised

ImportError: No module named 'fastTextpy'

I think there is a typo in readme file https://github.com/facebookresearch/fastText/tree/master/python
it must be  **from fastText import train_supervised**

**Comment by cpuhrsch** [comment]
Hello @yolossn,

Thank you for your post!

Try 
```
from fastText import train_supervised
```

Presumably fastTextpy is used somewhere within the documentation, which I'll update.

Thanks,
Christian

**Comment by cpuhrsch** [comment]
The fix has been pushed, please try again!

**Comment by yolossn** [comment]
@cpuhrsch  works fine..
