### ISSUE TITLE
quantize only seems to use 1 core?

### ISSUE THREAD

**Issue by dcsan** [facebookresearch/fastText#353]
I'm using quantize with `    -thread 12 ` argument and the process only seems to use one core (ubuntu 16.0.4)

are there any other ways to speed up the process?
I'm guessing `thread ` is an internal C thread, but should that be able to use > 1 core?

```sh
fasttext quantize \
    -output "${MODEL_FILE}" \
    -input "${LABEL_FILE}" \
    -dim 300 \
    -loss softmax \
    -qnorm \
    -thread 12 \
    -epoch 1
```

![image](https://user-images.githubusercontent.com/514002/32453858-0f39a19a-c2e3-11e7-9479-b8c153deebd5.png)

**Comment by EdouardGrave** [comment]
Hi @dcsan,

As of now, the quantization of models is not multi-threaded, and there are no ways to speed up the process.

Best,
Edouard.

**Comment by dcsan** [comment]
thanks for response! closing.

**Comment by rmc135** [comment]
A further 'gotcha' is that autotuned training with the -autotune-modelsize option will invoke quantization, so the entire run will quietly switch to using a single core only. It took me a while to figure this out. Perhaps the documentation could be updated to warn of this.
