### ISSUE TITLE
save in .gz format

### ISSUE THREAD

**Issue by TamouzeAssi** [facebookresearch/fastText#354]
Hello,

How can I save the .bin format in .gz format (.bin.gz). 

Thank you

**Comment by cpuhrsch** [comment]
Hello @TamouzeAssi,

Thank you for your post. This is currently not supported as part of fastText (and less likely to be implemented). Do you have a particular reason for this feature request?

Thanks,
Christian

**Comment by cpuhrsch** [comment]
Hello @TamouzeAssi ,

Thank you again for your post. I'm closing this now due to inactivity, but please feel encouraged to reopen this at any point if the problem persists.

Thanks,
Christian
