### ISSUE TITLE
format

### ISSUE THREAD

**Issue by bondfeld** [facebookresearch/fastText#355]
I'd like to clarify the format of the Russian vectors. What is this extra hyphen after the word? (With the extra hyphen, the length of the vector is 301, not 300.

россии — -0.060794 -0.0058051 -0.27115 -0.51912 -0.18709 -0.30835 -0.28659 0.2042 0.031658 0.09803 0.091226 0.31346 0.25378 ...

**Comment by EdouardGrave** [comment]
Hi @bondfeld,

This is also a tokenization issue (similar to #356). We are working on a new version of the pre-trained word vectors, and these issues should be fixed.

Best,
Edouard.
