### ISSUE TITLE
Incremental Supervised Training

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/fastText#360]
I'm incrementally adding news contents (with no duplicates) to my dataset for supervised classification.
My training task I'm using the following parameters

```javascript
train [ 'supervised',
  '-input',
  '/data/20171113/dataset.csv',
  '-output',
  '/data/20171113/model',
  '-wordNgrams',
  '2',
  '-minCount',
  1,
  '-minCountLabel',
  1,
  '-minn',
  3,
  '-maxn',
  6,
  '-t',
  0.0001,
  '-bucket',
  10000000,
  '-dim',
  '20',
  '-lr',
  '0.5',
  '-ws',
  15,
  '-loss',
  'ns',
  '-lrUpdateRate',
  100,
  '-epoch',
  '20',
  '-thread',
  8,
  '-verbose',
  4 ]
```

This will generate my `20171113/model.bin` and `20171113/model.vec` files.
Now, in the next training, my dataset `20171114/dataset.csv` will be incremented of N lines and I would like to use the pre-trained vector for the current (previously) generated model i.e. the `20171113` model. Does it make sense?

**NOTE**. _This is a mixed language model, so I cannot apply as-it-is a pre trained word vectors for a certain language_.

**Comment by cpuhrsch** [comment]
Hello @loretoparisi,

Thank you for your post. I'm adding a related issue to this post. Please consider commenting on it instead and closing this to deduplicate issues.

https://github.com/facebookresearch/fastText/issues/312

Thanks,
Christian

**Comment by loretoparisi** [comment]
@cpuhrsch it makes sense, closing then.
