### ISSUE TITLE
Training fastText model with Urdu Corpus

### ISSUE THREAD

**Issue by zarmeen92** [facebookresearch/fastText#368]
I tried training fasttext model using wikipedia Urdu dump.
The issue is that I am unable to extract vectors of urdu words

```
from gensim.models.wrappers import FastText
model = FastText.train('C://Users//ZNasim//Desktop//fasttext/fastText','wikipediaDump.txt')
```
Model got trained successfully but when I tried running query

`model.most_similar('پاکستان')`
![image](https://user-images.githubusercontent.com/15036417/33202826-bba1792c-d11f-11e7-8ab0-e1e67afd4bad.png)

**Comment by omerarshad** [comment]
this because of encoding issue, try model.most_similar(u''پاکست")

**Comment by zarmeen92** [comment]
thanks @omerarshad

**Comment by omerarshad** [comment]
Can you please add a reaction to my comment if it worked
