### ISSUE TITLE
-loss hs is broken

### ISSUE THREAD

**Issue by fstark** [facebookresearch/fastText#370]
Please merge https://github.com/facebookresearch/fastText/pull/369 as -lost hs is broken due to commit https://github.com/facebookresearch/fastText/commit/4a8488df2ffd5b71f9d7123661627a1e14b02829 (missing minus sign in sigmoid function)

**Comment by cpuhrsch** [comment]
Hello @fstark,

I just landed the fix. Thanks for the issue and sorry for the long delay.

Thanks,
Christian
