### ISSUE TITLE
Explanation of the hierarchical softmax in documentation

### ISSUE THREAD

**Issue by lord-alfred** [facebookresearch/fastText#372]
Hi!

In the last of documentation page ( https://fasttext.cc/docs/en/supervised-tutorial.html ) there is text: "_[Add a quick explanation of the hierarchical softmax]_".

Maybe someone can tell the same simple language, as in the documentation?

And about options: -bucket, -dim, -loss?

Thanks, 
LAlf.

**Comment by sakares** [comment]
Perhaps, you can take a look at [Hugo Larochelle's explanation on "Natural language processing - hierarchical output layer"](https://youtu.be/B95LTf2rVWM)

**Comment by Celebio** [comment]
Hi @lord-alfred ,
Thank you for reporting.
This is a duplicate of #599 so I will close this one as well.
Best regards,
Onur
