### ISSUE TITLE
Tokenisers for pre-trained word vectors

### ISSUE THREAD

**Issue by MashaNaslidnyk** [facebookresearch/fastText#378]
I couldn’t find information on which tokenisers were used for training the published word vectors. I’d like to align tokenisers when using these word vectors for my models. Thanks!

**Comment by cpuhrsch** [comment]
Hello @MashaNaslidnyk,

Thank you for your post. Please consider the corresponding [paper](https://arxiv.org/pdf/1607.04606.pdf) for details on this. In particular Section 4.4 might contain the details you are looking for. I'm closing this issue now, but please feel encouraged to reopen it at any point if this is not the case.

Thanks,
Christian

**Comment by MashaNaslidnyk** [comment]
Hi Christian,

Thanks for your reply. The paper describes pre-processing for languages all of which use spaces to divide words (as you mentioned, section 4.4); and readWord in Dictionary expects words to be separated by space characters (https://github.com/facebookresearch/fastText/blob/master/src/dictionary.cc#L201). Looks like tokenisation process here is = separating the sentence by space characters.

Where can I find information on how tokenisation was performed for languages that don't use spaces to separate words (Chinese, Japanese, Thai)?

Thanks,
Masha

**Comment by MashaNaslidnyk** [comment]
(can't re-open so opened a new issue: https://github.com/facebookresearch/fastText/issues/400)
