### ISSUE TITLE
wrong count number of sample using api test of classifier.bin

### ISSUE THREAD

**Issue by lampts** [facebookresearch/fastText#38]
I have a sanity test file which contains 7 samples/lines. But the result of calling test api just print out 5 samples. I also used the api predict, classifier gave 7 results instead.

## Calling test api
LAAMPs-MacBook-Pro:fastText laam$ ./fasttext test ./result/score10en.bin data/sanity.test3
P@1: 1
Number of examples: 5

## Calling predict api
LAAMPs-MacBook-Pro:fastText laam$ ./fasttext predict ./result/score10en.bin data/sanity.test3
__label__fin_irrel
__label__fin_rel
__label__fin_rel
__label__fin_irrel
__label__fin_irrel
__label__fin_rel
__label__fin_irrel

**Comment by EdouardGrave** [comment]
Does your test file contains lines without labels?

**Comment by lampts** [comment]
Yes, you're right. My bad, I closed this issue.
