### ISSUE TITLE
Italian wiki source spurious chars † » ® / # _ % …

### ISSUE THREAD

**Issue by costa974** [facebookresearch/fastText#382]
I'm tinkering with your Italian model trained on wikipedia data, but I have noticed that in the vocabulary, spurious chars appear like: † » ®

For example using ./fasttext nn

Query word? parigi
†parigi 0.795679
parigi, 0.791329
parigi» 0.705036
rennesparigi 0.688673
parigi/champs 0.678263
parigina 0.667331
auxelles 0.664558
parigino 0.664094
bruxelles 0.661636
parigine 0.659439

Query word? londra
londra, 0.792716
†londra 0.756167
londinese 0.703161
londra» 0.700708
edimburgo 0.681085
berkhampstead 0.675016
islington 0.670808
london 0.669887
hampstead 0.661759
guildford 0.655972

Query word? microsoft
/microsoft 0.938877
microsoft® 0.92442
#microsoft 0.870421
windows 0.863817
altrosoftware 0.834722
dos/windows 0.808116
windows® 0.797837
windows/ 0.793634
robosoft 0.787299
egosoft 0.787219

Query word? php
org/w/index 0.896139
/w/index 0.889192
org/wikipedia/it/w/index 0.834432
org/w/api 0.81359
title 0.809429
//it 0.806851
org/otrs/index 0.801352
pl/index 0.79661
ru/index 0.792537
nl/index 0.792295

Query word? facebook
facebookiani 0.857182
thefacebook 0.849898
\bfacebook\ 0.829411
twitter 0.826214
//instagram 0.768138
instagram 0.761067
myspace 0.739092
//myspace 0.718257
blog 0.706665
twitta 0.706629

Query word? html
html, 0.882173
html/ 0.844935
html# 0.836859
htmlhttp 0.828444
html% 0.822481
html_ 0.814309
http 0.792755
html#p 0.791654
htmlhttps 0.791174
html/css 0.787908

Query word? tempo
tempo,il 0.588036
lasso 0.580427
tempo, 0.567424
tempo… 0.554029
indeterminato 0.531332
periodo 0.507661
indeterminatamente 0.501737
addietro 0.501606
pochissimo 0.500905
passato 0.499162

Query word? wikipedia
>wikipedia 0.874852
wwikipedia 0.844891
ikipedia 0.837508
#wikipedia 0.830466
kikipedia 0.829286
wiikipedia 0.829003
@wikipedia 0.828749
itwikipedia 0.828706
wikipedia® 0.827517
cancellare/wikipedia 0.820837

Query word? xbox
playstation 0.91499
/xbox 0.824874
gamecube 0.806964
dreamcast 0.784485
nintendo 0.771212
wii 0.76758
xbox_ 0.764796
joystation 0.756016
treamcast 0.747338
/gamecube/xbox 0.745011

**Comment by cpuhrsch** [comment]
Hello @costa974,

Thank you for your post. I think the following issue is about the exact same issue as the one you found.

https://github.com/facebookresearch/fastText/issues/284

I'm closing this one to remove duplicate issues which makes it easier for us to keep track of them. Please feel encouraged to reopen it at any point if this isn't true.

Thank you,
Christian
