### ISSUE TITLE
[supervised][multi label]

### ISSUE THREAD

**Issue by nguyentheanhhnvntd** [facebookresearch/fastText#383]
I'm training a multi label classification.
While testing it precision and recall very low.
And when using predict probability, it return a multi label per k.
Example with k = 2:
[[('label_A,label_B,label_C,label_D', 0.511719), ('label_E,label_F', 0.179688)]]
How can I improve precision and how to make predict return 1 label per predict probality value?
Many thanks!!

**Comment by pommedeterresautee** [comment]
What you are looking for is a way to predict 1 label if there is only one to predict, and for instance 4 labels when is makes sense.
The way fasttext works make it difficult to reach.
Here is a PR https://github.com/facebookresearch/fastText/pull/134/files

This feature has been requested many times :
https://github.com/facebookresearch/fastText/issues/262

**Comment by nguyentheanhhnvntd** [comment]
thanks I'm going to read that. But now, I'm have other question that my data have more data record in file than the Nexamples: while testing that make me confuse.

**Comment by nguyentheanhhnvntd** [comment]
Hello, I want my prediction only returns 1 label per record. And I may get other by 'k'. Can you help it.

**Comment by cpuhrsch** [comment]
Hello @nguyentheanhhnvntd,

Thank you for your post. As far as I can tell the following issue is about the same topic as yours. Please consider commenting on it and closing this issue to deduplicate issues and making it easier for us to keep track.

https://github.com/facebookresearch/fastText/issues/363

Thanks,
Christian

**Comment by nguyentheanhhnvntd** [comment]
ok thanks, I have just found out where I'm wrong.
