### ISSUE TITLE
Fast Linear Model for Knowledge Graph Embeddings

### ISSUE THREAD

**Issue by onclue** [facebookresearch/fastText#387]
Would you mind adding the scripts to reproduce your results in "Fast Linear Model for Knowledge Graph Embeddings" (https://arxiv.org/pdf/1710.10881.pdf) to the examples? Thanks!

**Comment by david30907d** [comment]
I'm reading this paper (<https://arxiv.org/pdf/1710.10881.pdf>) too. It would be great to have the scripts in this repo. Thanks!

**Comment by onclue** [comment]
Is there maybe a better place to ask for this (e.g. facebook group)? Thanks.

**Comment by villmow** [comment]
Yep, would be nice to have a reference implementation.

**Comment by GittiHab** [comment]
Any progress on this?

**Comment by GittiHab** [comment]
Ah, you can find it in the [`scripts`](https://github.com/facebookresearch/fastText/tree/master/scripts/kbcompletion) folder.
