### ISSUE TITLE
There is a parameter name in a header

### ISSUE THREAD

**Issue by pommedeterresautee** [facebookresearch/fastText#388]
Just noticed that :
https://github.com/facebookresearch/fastText/blob/master/src/fasttext.h#L82
Seems it is an error...

**Comment by cpuhrsch** [comment]
Hello @pommedeterresautee,

Thank you for your post! I'll remove that as part of a next commit. Have you experienced any issues because of this?

Thanks,
Christian

**Comment by pommedeterresautee** [comment]
Yep, in my wrapper because I am using macro... https://github.com/pommedeterresautee/fastrtext/
(I try to keep the code in line with yours, not so easy these days... :-) )

**Comment by cpuhrsch** [comment]
Hello @pommedeterresautee,

Do you have a pointer to the definition of that macro? Also, if this is fine with you, you could depend on our [latest release](https://github.com/facebookresearch/fastText/releases) if you prefer stability over new features. Are there particular changes that caused you a lot of grief?

Thanks,
Christian

**Comment by pommedeterresautee** [comment]
I have quite a lot of them: https://github.com/pommedeterresautee/fastrtext/blob/master/src/r_compliance.h , all because of printing messages to cout / cerr

Call to cerr and cout which are badly managed on R, in general we need to call a special R terminal synchronized version of cout (Rcout in Rcpp) but in the case of fasttext cout or cerr are called from any thread and it makes the whole app crash, so I am using a very new lib to cache the messages pushed to cout and cerr and from time to time I print progress). 
In the very last commit, changes in printInfo broke several of my macros (yep!). I just fixed them tonight.
I can t wait the stable versions because issues may accumulate and I prefer to clean them from time to time instead of one time every X months.
I wrote an email to Alexandre L. about these things and others. Are you Alexandre ?

**Comment by cpuhrsch** [comment]
Hello @pommedeterresautee,

Do the last changes in printInfo help with the cerr, cout issues? I'm not Alexandre L. (I assume you mean Alexandre Lebrun). Are you comfortable sharing some of these issues here?

Thanks,
Christian

**Comment by cpuhrsch** [comment]
Hello @pommedeterresautee,

I applied the request change in f138f3a1ac6f553774cefe90a65f793afcf5c5b5. I'll close the issue now, but please feel free to reopen it at any time if this hasn't been resolved.

Thanks,
Christian

**Comment by pommedeterresautee** [comment]
@cpuhrsch I didn't noticed this change. I will remove all the stuff I did because of multi thread printing.
The other thing remaining is the many tasks finishing with a print instead of returning an object (like find nearest vector, and so on). Right now, I have some copy / adaptation of your C++ code. It would improve thing to separate the tasks and you would be able to call them from Python too...
