### ISSUE TITLE
About pre-trained embeddings from cbow model

### ISSUE THREAD

**Issue by ereday** [facebookresearch/fastText#389]
Hi,
If pretrained word vectors differ for cbow and skip-gram models, where can I find the vectors produced by cbow model? In the pre-trained model section, I could only find the skip-gram version. If important, I'd like to get them for Turkish especially.

**Comment by cpuhrsch** [comment]
Helllo @ereday,

Thank you for your post. Why is it important for you to distinguish between cbow and skipgram? What would you like to do with these embeddings?

Thanks,
Christian

**Comment by cpuhrsch** [comment]
Hello @ereday,

Cbow and skipgram are different methods but with the same goal. We chose skipgram in this particular case because it produces better embeddings. I'll close this issue now, but please feel encouraged to reopen it at any time if this doesn't answer your question.

Thanks,
Christian
