### ISSUE TITLE
Pretrained model permission errors

### ISSUE THREAD

**Issue by Ellibeere** [facebookresearch/fastText#390]
Stumbled over some problems with downloading certain pretrained models, e.g. 

https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki.ki.vec

Access denied

Looks like the s3 permissions are not set properly. Could you look into this?

**Comment by cpuhrsch** [comment]
Hello @Ellibeere,

Thank you for your post. I just fixed the permissions and can now download the file again. I'm going to close this issue now, but please encouraged to reopen if it persists. Note that it might take a bit for this to propagate to your end.

Thanks,
Christian
