### ISSUE TITLE
Make utils from C++ code return objects instead of printing to terminal

### ISSUE THREAD

**Issue by pommedeterresautee** [facebookresearch/fastText#391]
I open a new issue related to my last message in https://github.com/facebookresearch/fastText/issues/388

Right now nn search, analogies, etc. are implemented in C++ but print results to terminal and another implementation exists in Python. For the R wrapper I reimplemented parts of the code in C++ and setup a binding with R.

Would be much better if we all use the same source code. I would mean, at C++ level, separate the actual work (finding a similar vector) and the code using this results (print, return an object, etc.).

This is true for analogies, nn, measures of supervised model, etc.

**Comment by loretoparisi** [comment]
This can be applied also to the progress, that as it is (`cout << ''`) must be captured and it is not robust at all:

```
Progress: 100.0% words/sec/thread:  707626 lr:  0.000000 loss:  0.448124 ETA:   0h 0m
```

It would be better to wrap it and structure is some way.

**Comment by Celebio** [comment]
Hi @pommedeterresautee ,
The last commit 256032b87522cdebc4850c99b204b81b3255cb2a probably does what you mentioned.

Regards,
Onur

**Comment by pommedeterresautee** [comment]
tks you are right, this is a very good news!

**Comment by Celebio** [comment]
@pommedeterresautee : glad to hear that!
I am closing the issue. 
Thank you very much for your feedback.
