### ISSUE TITLE
Learn from an array of string and return a model directly

### ISSUE THREAD

**Issue by pommedeterresautee** [facebookresearch/fastText#392]
Right now, from any wrapper, we need to serialize the data to a file, learn the file, fasttext serialize a model, and then we can load the model.

The process is complex and it s quite obvious when you are performing it from a wrapper (in my case the R wrapper). Classical models expect raw data, labels and return a model, without any serialization in between.

Can we have an access at the C++ level to a function taking an array of string as raw data, an array of string as arguments to be parsed (as it is the case today for this parameter), and return a model directly to the user?

It would be quite helpful for small tasks you are doing again and again.

**Comment by cpuhrsch** [comment]
Hello @pommedeterresautee,

Thank you for your post. The Python wrapper [trains a fastText](https://github.com/facebookresearch/fastText/blob/master/python/fastText/pybind/fasttext_pybind.cc#L66) model given a set of arguments (which includes a path to the input file). There should be no need to save it out first. Let me know if this helps.

Thanks,
Christian

**Comment by pommedeterresautee** [comment]
Didn t see it before. Sorry, will try to replicate on R. Closing.

**Comment by saul-b** [comment]
> Hello @pommedeterresautee,
> 
> Thank you for your post. The Python wrapper [trains a fastText](https://github.com/facebookresearch/fastText/blob/master/python/fastText/pybind/fasttext_pybind.cc#L66) model given a set of arguments (which includes a path to the input file). There should be no need to save it out first. Let me know if this helps.
> 
> Thanks,
> Christian

Hello @cpuhrsch 

I have encountered a similar problem and was hoping to look at the link you shared. I see that the page no longer exists. Any chance you can re-share the link? 

Thanks,
Saul
