### ISSUE TITLE
why the precision is nan returned in fasttext(on windows, python 3.6)

### ISSUE THREAD

**Issue by stonenice** [facebookresearch/fastText#395]
I program a fasttext demo according with the examples you provided, but I got nan when running fasttext.test(). So, who can help me to solve it? 

Environments:
1. windows7
2. python 3.6
3. I install the fasttext by executing the command "pip install fasttext"

**Comment by cpuhrsch** [comment]
Hello @stonenice,

Thank you for your post. The pip package [fasttext](https://pypi.python.org/pypi/fasttext) still refers to the third-party bindings [fastText.py](https://github.com/salestock/fastText.py). Unfortunately we can't help you with questions related to this as the code is not part of our repository. If you would like to use our Python bindings please follow the instructions of the README. I'm closing this issue now, but please be encouraged to reopen it if you don't consider this resolved.

Thanks,
Christian

**Comment by stonenice** [comment]
Thank you very much! I will attempt to install fastText by compiling the source.
