### ISSUE TITLE
Markdown in RSS and Atom feeds on website

### ISSUE THREAD

**Issue by EmilStenstrom** [facebookresearch/fastText#399]
Just wanted to leave a quick note thanking your for having a proper feed for your blog. Only improvement I can see is if you could send HTML in the content of the posts instead of Markdown. Would that be possible?

I'm talking about these two URLs:
* https://fasttext.cc/blog/feed.xml
* https://fasttext.cc/blog/atom.xml

**Comment by EmilStenstrom** [comment]
Also, seems like the links are missing a protocol, so feed readers will resolve them as https://fasttext.cc/blog/fasttext.cc/blog/2016/08/18/blog-post.html - which obviously is the wrong link. Adding a simple https:// fixes this.

**Comment by JoelMarcey** [comment]
Thanks @EmilStenstrom for bringing this to our attention. I have created an issue in the Docusaurus repo to look at this.

**Comment by EmilStenstrom** [comment]
@JoelMarcey Thanks! 

Thinking about it, could the second issue be that you just need to add a protocol here: https://github.com/facebookresearch/fastText/blob/master/website/siteConfig.js#L61 ?

**Comment by JoelMarcey** [comment]
@EmilStenstrom Yes, the url on https://github.com/facebookresearch/fastText/blob/master/website/siteConfig.js#L61 should have an `https://` in front of it. Do you want to submit a pull request to fix that?

**Comment by EmilStenstrom** [comment]
Here's the PR: https://github.com/facebookresearch/fastText/pull/412

**Comment by JoelMarcey** [comment]
The markdown in feed issue should be fixed in the latest version of Docusaurus v1.0.6.

I am planning to release v1.0.7 this weekend too, which, of course, will have the fix as well.
