### ISSUE TITLE
Tokenisers for pre-trained word vectors for scriptio continua

### ISSUE THREAD

**Issue by MashaNaslidnyk** [facebookresearch/fastText#400]
Follow-up to https://github.com/facebookresearch/fastText/issues/378 as I can't re-open it.

I couldn’t find information on which tokenisers were used for training the published word vectors. I’d like to align tokenisers when using these word vectors for my models.

The [paper](https://arxiv.org/pdf/1607.04606.pdf) describes pre-processing for languages all of which use spaces to divide words (section 4.4); and [readWord in Dictionary](https://github.com/facebookresearch/fastText/blob/master/src/dictionary.cc#L201) expects words to be separated by space characters. Looks like tokenisation process here is = separating the sentence by space characters.

Where can I find information on how tokenisation was performed for languages that don't use spaces to separate words (Chinese, Japanese, Thai)?

**Comment by matanster** [comment]
You might want to look [here](https://github.com/facebookresearch/fastText/issues/224)

**Comment by MashaNaslidnyk** [comment]
Thanks! That answers it.
