### ISSUE TITLE
Clarifying regarding the pre-processing of the pre-trained (and sentence segmentation)

### ISSUE THREAD

**Issue by matanster** [facebookresearch/fastText#401]
Hi,

I've carefully reviewed [the new article about the pre-trained embeddings](https://arxiv.org/pdf/1712.09405.pdf) having been released a bit earlier on. Thanks a lot for making that publication! 

Am I correct in understanding _that no sentence segmentation has been carried out as pre-processing_, in training the pre-trained models? meaning that the pre-trained embeddings (for English, and other languages) have been trained such that the input corpora were each treated as one big line, or only segmented by Wikipedia article boundaries and such, but not sentence boundaries?

Clearly, the Moses MT tokenizer which _is_ mentioned in the article ([this code I believe, which will fail to tokenize end-of-sentence period symbols, unless fed one sentence at a time](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/tokenizer/tokenizer.perl)) does not perform sentence segmentation. As an aside, I wonder whether it had been used also for the semitic languages' embeddings, v.s. just for English and European script languages.

Last but not least, may I also ask whether in your experiments, you have juxtaposed some of your results with and without segmentation?

Thanks!

**Comment by EdouardGrave** [comment]
Hi @matanster,

You are correct, we did not use sentence segmentation in our preprocessing. In my experience, I did not observe significant differences with or without sentence segmentation. The version of the tokenizer that we used do tokenize end-of-sentence period symbols.

For other languages, please see our latest release for details about which tokenizers were used: https://fasttext.cc/docs/en/crawl-vectors.html (for the Wikipedia-based multilingual vectors, we used a very crude preprocessing, which can be replicated using the following script: https://github.com/facebookresearch/fastText/blob/master/get-wikimedia.sh).

Best,
Edouard

**Comment by matanster** [comment]
Hi @EdouardGrave 

> In my experience, I did not observe significant differences with or without sentence segmentation.

it always strikes me intriguing, that a context including words from the next or previous sentence don't skew the quality of the embedding. I guess somehow it averages out. As to the new embeddings, I've read the whole article describing them, and thanks for sharing all that information.

Matan
