### ISSUE TITLE
Should I add '<' and '>' to get char ngram vectors?

### ISSUE THREAD

**Issue by munichong** [facebookresearch/fastText#407]
According to [Enriching Word Vectors with Subword Information](https://arxiv.org/abs/1607.04606), FastText adds special boundary symbols < and > at the beginning and end of words, allowing to distinguish prefixes and suffixes from other character sequences. 

For example, "where" is represented as <wh, whe, her, ere, re>, and <where>, if n=3. 

What I want to do is to use fastText to get vectors for individual character ngram (not for the entire word). For example, I expect to get 6 vectors for "where", which will be used to do initialization. These vectors will be continued to train afterwards. I download the English fastText from [fasttext.cc](https://fasttext.cc/docs/en/pretrained-vectors.html), which is trained based on wiki.

My questions: Does fastText literaly store '<' and '>' in the vocabulary? Should I pass a char ngram with '<' and/or '>' to get the vector OR without them?

For instance, for 'where':
```
en_model = FastText.load_fasttext_format('../FastText/wiki.en/wiki.en')
# OPTION 1:
word_vector = []
for charngram in ['wh', 'whe', 'her', 'ere', 're', 'where']:
    word_vector.append(en_model[charngram])
# OPTION 2:
word_vector = []
for charngram in ['<wh', 'whe', 'her', 'ere', 're>', '<where>']:
    word_vector.append(en_model[charngram])
```

**Comment by saroufimc1** [comment]
I have the same question. Can someone answer please?

**Comment by EdouardGrave** [comment]
Hi @munichong and @saroufimc1,

It seems that you are using a third party python wrapper for fastText. The answer to this question depends on the corresponding implementation of this wrapper. In particular, I believe that in Gensim, `model[str]` will consider `str` to be a word (and not a character ngram). In some situation, this means that you cannot retrieve vectors corresponding to subwords like that.

Using the python wrapper from our project, you can obtain a list of subwords (and corresponding indices) using the method `get_subwords`. Then, using the indices, the subword vectors can be obtained by calling the method `get_input_vector`.

Best,
Edouard

**Comment by ceefour** [comment]
@EdouardGrave Does this entirely depend on the library, or also the model?

For example, in I can see in pretrained file `wiki-news-300d-1M-subword.vec`: (using text editor)

```
agree 0.0221 0.0560 -0.0241 0.0155 -0.0281 -0.0171 0.0300 ...
```

I don't see `<agree>`, `<agree`, `agree>`, or other character 3-grams, e.g. `<agr` and `ree>` anywhere in the file.

If the model is correct but only the library makes the difference, what I'm confused is how can the library  "synthesize" (?) a summed word vector without any information of individual character n-gram vectors?

For example, how does the library give the resulting word vector for the misspelled `aggreeee`?

**Comment by ceefour** [comment]
Hm I've found [the answer](https://stackoverflow.com/a/47119362/122441):

> The .vec files contain only the aggregated word vectors, in plain-text. The .bin files in addition contain the model parameters, and crucially, the vectors for all the n-grams.

> So if you want to encode words you did not train with using those n-grams (FastText's famous "subword information"), you need to find an API that can handle FastText .bin files (most only support the .vec files, however...).

Curious, was this mentioned in the docs? And also, some pretrained model downloads (like `wiki-news-300d-1M-subword.vec.zip`) only provide the .vec file but not the .bin file, so is it "useless" for this purpose?
