### ISSUE TITLE
Bin model of "Advances in Pre-Training Distributed Word Representations"

### ISSUE THREAD

**Issue by alberduris** [facebookresearch/fastText#415]
I know that this is not exactly and "Issue" and maybe shouldn't be opened here in Github. But still I think that could be interesting for a lot of people and I've posted the same [here ](https://groups.google.com/forum/#!topic/fasttext-library/QGLaGU7hn-U)and received no answers, so:

Hi,

According to this paper [Mikolov, T., Grave, E., Bojanowski, P., Puhrsch, C., & Joulin, A. (2017). Advances in Pre-Training Distributed Word Representations. arXiv preprint arXiv:1712.09405](https://www.google.com/url?q=https%3A%2F%2Farxiv.org%2Fpdf%2F1712.09405.pdf&sa=D&sntz=1&usg=AFQjCNExe_6uHQIED8YdqCXt0hpH4Y_9fA) the main result of their work is the new set of publicly available pre-trained models. 

They state that _"The models trained on the Wikipedia and News corpora, and on the Common Crawl, were published at the fasttext.cc website and are available to the NLP researchers."_

I think they are referring to those available [here under "English word vectors"](https://www.google.com/url?q=https%3A%2F%2Ffasttext.cc%2Fdocs%2Fen%2Fenglish-vectors.html&sa=D&sntz=1&usg=AFQjCNHzfcH3p9B9fCvedrQSMZ7Uyyn1_A) and [here under "Wiki word vectors". 
](https://www.google.com/url?q=https%3A%2F%2Ffasttext.cc%2Fdocs%2Fen%2Fpretrained-vectors.html&sa=D&sntz=1&usg=AFQjCNGxharr2PX3cS6aieOAcobcrV6Blg)
My question is that the ones under "Wiki word vectors" come with the .vec and .bin files but the ones under "English word vectors" come just with the .vec file.

Is it possible to get the .bin file of the pre-trained word vectors that they're talking about in the paper? Or just the .vec file?

Thanks!

Extra:

With word2vec the .bin file could be converted into a .vec file. I think this is because the .bin file in word2vec contains just the same information as the .vec file.

Is it possible to do this conversion with FastText?

I think maybe it's not possible because according to the documentation:
> model.bin is a binary file containing the parameters of the model along with the dictionary and all hyper parameters. The binary file can be used later to compute word vectors or to restart the optimization.

So the .bin file contains more information than the .vec but anyway maybe it's possible. I'd be grateful if you could throw some light on this.

**Comment by MichaMucha** [comment]
+1 to your request
they are definitely very generous to release this in the first place, the .bin model would be much appreciated nonetheless.

I was trying to use the python fasttext package, but it's taking forever to read the .vec file and it consumes huge amounts of memory.
I built this interface that basically transforms the word2vec file into a leveldb store, so at least it's indexed and loads lazily, so you can get going right away, and if you won't use the entire vocabulary of 1M words, you'll never have to read that.
https://github.com/MichaMucha/emstore it's here maybe it can help.

It won't give you OOV word embeddings, like the .bin file would, but at least it can speed things up maybe.

**Comment by EdouardGrave** [comment]
Hi @alberduris and @MichaMucha,

We have recently released the binary model trained on Wikipedia+News with subwords, which is available here: https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki-news-300d-1M-subword.bin.zip. Since the other models don't use subwords, we will not release binary models for these (since binary models would contain the same information).

We will probably release a model with subwords, trained on common crawl data, in the (very) near future.

Best,
Edouard.

**Comment by alberduris** [comment]
Thank you very much @EdouardGrave 

This is really kind of you.

Facebook AI Research is killing it at NLP research!

Best,

Alber.

**Comment by youknowwho96** [comment]
> Hi @alberduris and @MichaMucha,
> 
> We have recently released the binary model trained on Wikipedia+News with subwords, which is available here: https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki-news-300d-1M-subword.bin.zip. Since the other models don't use subwords, we will not release binary models for these (since binary models would contain the same information).
> 
> We will probably release a model with subwords, trained on common crawl data, in the (very) near future.
> 
> Best,
> Edouard.

I am getting AccessDenied error when trying to download
