### ISSUE TITLE
How to turn off the subword learning ?

### ISSUE THREAD

**Issue by yananchen1989** [facebookresearch/fastText#416]
In my training corpus, all the words are numbers which are id in representation of words. So I want to turn off the subword training function. `-minn 2 -maxn 5` means that all subwords whose length between 2 and 5 will be in consideration. How can I set it to ignore all subwords. 
the ids' range is [0, 200000]

**Comment by ogerhsou** [comment]
-maxn 0

**Comment by EdouardGrave** [comment]
Hi @yananchen1989,

As pointed out by @ogerhsou the way to turn off the subword features is to set the `maxn` parameter to `0`.

Best,
Edouard

**Comment by hafiz031** [comment]
@EdouardGrave which value to pass for `minn`?
