### ISSUE TITLE
Harmonizing the libraryness of this repo

### ISSUE THREAD

**Issue by matanster** [facebookresearch/fastText#419]
I hope this is not a white elephant. Shouldn't the project not be called a library? even the non-github home of it calls it a library, while in fact aside some python API it is a command-line tool. This is also at par with how all of the examples and tutorials treat it :-) just saying. There's not a lot of distance to go for making the C++ core a flexible API for use outside the command-line `main` of it. Would a PR be welcome?

**Comment by Celebio** [comment]
Hi @matanster ,
We began our attempts to delimit the library part of the code with 256032b87522cdebc4850c99b204b81b3255cb2a. Now we can see the `FastText` class an api with the command line tool (`main.cc`) and the python bindings (`fasttext_pybind.cc`) as clients of this api.
Does it make more sense in your opinion? Any feedback is welcome.
Best regards,
Onur

**Comment by Celebio** [comment]
Hi @matanster ,
I will close the issue now. Feel free to re-open it if you have any further questions.

Best regards,
Onur
