### ISSUE TITLE
Absolute prediction score instead of the relative softmax score

### ISSUE THREAD

**Issue by yfletberliac** [facebookresearch/fastText#426]
Hi,

I would like to use a threshold to discard the predictions whose confidence is low. Is this possible with the current library to output an absolute confidence score for the predictions, instead of a relative softmax? I haven't found any reference for this in the documentation nor in the issues. Or is it in the pipeline already for the next release? If not, please let me know and I can have a look at this and hopefully open a PR.

BR,
Yannis

**Comment by matanster** [comment]
Are you sure you would not rather simply treat the currently implemented softmax output as the confidences per each of your labels?

**Comment by yfletberliac** [comment]
I found a workaround, thank you.
