### ISSUE TITLE
Local word order in classification

### ISSUE THREAD

**Issue by matanster** [facebookresearch/fastText#427]
Hi,

The **Bag of Tricks for Efficient Text Classification** article mentions the use of a bag of word n-grams, capturing local word order to assist in the classification ("_we use a bag of n-grams as additional features to capture some partial information about the local word order_"). Can you kindly point at where in the source is this integrates in the classification algorithm? I am unable to reconcile that method with what I can detect in the relevant code portions so far.

Thanks in advance!

**Comment by EdouardGrave** [comment]
Hi @matanster,

The word n-grams are added as features by the `addWordNgrams` method of the `Dictionary` class. This function is called at the end of the `getLine` method (https://github.com/facebookresearch/fastText/blob/master/src/dictionary.cc#L376).

Best,
Edouard.

**Comment by matanster** [comment]
Thanks, sorry about that, I eventually found it and completely forgot to remove this comment :-1:

**Comment by matanster** [comment]
Actually, the way that [addWordNgrams](https://github.com/facebookresearch/fastText/blob/master/src/dictionary.cc#L293) works remains a small mystery for me, along with the addressing scheme where tokens have [both ids and hashes](https://github.com/facebookresearch/fastText/blob/master/src/dictionary.cc#L363-L364). Does this function actually record a word n-gram as a feature in the dictionary? would that feature get an embedding vector somewhere in the code, if not already having one a previous run of an unsupervised model?

Can you please comment on that? I have the rest of the source code pretty much mentally mapped out, but the dictionary part still a bit tricky, not because of the feature hashing per-se, but with regard to how word n-grams are treated there.
