### ISSUE TITLE
Training of the model doesn't check if the output model file can be saved

### ISSUE THREAD

**Issue by oshev** [facebookresearch/fastText#432]
Executing something like,
`./fasttext skipgram -input ~/good_user_queries.txt -output ~/models/user_queries`
The tool spends a lot of time building the model and then gives me this:
`libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument: /Users/someuser/models/user_queries.bin cannot be opened for saving!
Abort trap: 6`
The reason is the output path doesn't exist. It would be good to check if the output file can be saved before training the model so the user doesn't waste their time in case of bad input parameters.

**Comment by EdouardGrave** [comment]
Hi @oshev,

Thank you for reporting this issue. We will publish a fix for this soon.

Best,
Edouard

**Comment by oshev** [comment]
Hi Edouard! 

Many thanks for looking into it!

Best,
Oleg
