### ISSUE TITLE
word Embedding ，but words in input file not in  final .vec file

### ISSUE THREAD

**Issue by zhongboyin** [facebookresearch/fastText#433]
Hi, 
      I want to know wether the words in input file ,  it will must in .vec file wile  I training word embedding?

As I counter the problem that some words in input file, but it doesn's in final .vec file.

thanks

**Comment by spate141** [comment]
Set it to "1" when training with skipgram/cbow to cover all words in input data

`-minCount minimal number of word occurences [5]`

**Comment by EdouardGrave** [comment]
Hi @zhongboyin,

As pointed out by @spate141, if you want to get a representation for each word of the input file when using `cbow` or `skipgram`, you need to set the command line argument `-minCount` to `1` (the default is equal to `5`).

Best.
