### ISSUE TITLE
Who is in charge of fasttext on Pypi? 

### ISSUE THREAD

**Issue by polm** [facebookresearch/fastText#436]
Looking at old issues I saw several comments indicating the [fasttext package on pypi](https://pypi.python.org/pypi/fasttext) was not maintained by Facebook Research. However, [a recent commit](https://github.com/pyk/fastText.py/commit/ed4807359d31296f444f895d26200140b8ce10b4#diff-04c6e90faac2675aa89e2176d2eec7d8) to the README of the version used as the base for those versions suggests that has changed, and that the version on pypi is now maintained by Facebook Research. 

If that's true, would it be possible to put a current version of the library on pypi?

If not, would it be possible to put a current version on pypi under another name? Not having a version on pypi makes it hard to build tools on top of it, which is a pity seeing the Python bindings are nicely maintained.

(I became of this situation [trying to install skift](https://github.com/shaypal5/skift/issues/1), which does a good job but shows how pip makes non-pypi dependencies awkward.)

**Comment by shaypal5** [comment]
As the author of [skift](https://github.com/shaypal5/skift), which is a small Python tool build on top of Python `fasttext`, I have to agree. :)

**Comment by pyk** [comment]
> If that's true, would it be possible to put a current version of the library on pypi?

yes, it's true. The owner of https://pypi.python.org/pypi/fasttext is @cpuhrsch from facebook research team.

Disclaimer: I'm the previous owner

**Comment by shaypal5** [comment]
Cool. Do you have any idea if a packaged version of the official Python bindings has been uploaded to PyPI?

**Comment by polm** [comment]
@cpuhrsch Hello there, you seem to be listed as the maintainer of this package on Pypi as well as being a committer to this repo. Would it be possible to get a version of the official bindings on Pypi? It'd be a great help to library authors.

**Comment by lorosanu** [comment]
It seems there is a packaged version of the official Python binding on [TestPyPi](https://testpypi.python.org/pypi/fasttext).  
Latest version 0.8.22 released in January.  
Maybe that can help while waiting for a PyPi release.

**Comment by sidharthms** [comment]
Any updates on this?

**Comment by sidharthms** [comment]
I created my own pypi mirror for fastText (https://pypi.org/project/fasttextmirror based on https://github.com/sidharthms/fastText) as a temporary solution until this is resolved. Please try to update the official pypi package soon if possible.

**Comment by polm** [comment]
Happy anniversary!

I understand this is a low priority task, but it continues to be a source of frustration and it would be much appreciated if it was taken care of. :pray:

**Comment by wrobstory** [comment]
FYI: still having pain about this over here as well. Are you interested in having someone manage this as a contributor?

**Comment by Celebio** [comment]
Hi,
We are working on unifying all these things, as I also [mentioned here](https://github.com/facebookresearch/fastText/issues/784#issuecomment-483972363). I understand this is a source of frustration but please be patient, it is on our list along with some other features.

Best regards,
Onur

**Comment by osma** [comment]
I can see 0.9.1 has been released a few days ago on PyPI: https://pypi.org/project/fasttext/
Thanks a lot!

**Comment by osma** [comment]
Oh, now I found this [blog post](https://fasttext.cc/blog/2019/06/25/blog-post.html) too.

**Comment by polm** [comment]
This is wonderful new - thanks to the FastText team for the release! Looking forward to making simpler use of it in future projects :)
