### ISSUE TITLE
Is there a way to convert `model.bin` to a human readable form?

### ISSUE THREAD

**Issue by pengyu** [facebookresearch/fastText#443]
The `model.bin` generated by `fastText` is binary. Is there a way to convert it into human readable format?

I assume that n-gram vectors are stored in it. Is it?

Thanks.

**Comment by EdouardGrave** [comment]
Hi @pengyu,

It is possible to convert a binary model to text format using the `dump` sub-command:
```
> ./fasttext dump model.bin
```
You can pass an additional argument to this command among `args, dict, input, output` to only dump part of the model. For example,
```
> ./fasttext dump model.bin dict
```
will only print the dictionary of the model.

**Comment by pengyu** [comment]
$ fasttext dump /tmp/model.bin
usage: fasttext dump <model> <option>

  <model>      model filename
  <option>     option from args,dict,input,output
