### ISSUE TITLE
Pre-trained word vectors for Japanese (common crawl + wiki) is incomplete.

### ISSUE THREAD

**Issue by umutto** [facebookresearch/fastText#444]
Text file for Japanese pre-trained word vectors from https://fasttext.cc/docs/en/crawl-vectors.html  only have 81,976 words in it (should be more than 9,073,245 according to the [paper](https://arxiv.org/abs/1802.06893)). 

`cc.ja.300.vec` file is only 180MB large while `cc.ja.300.bin` file is 7GB. In comparison earlier wikipedia word vector file for Japanese is 1,3GB.  I've also downloaded some other language vectors (common crawl + wiki) to compare and they all have large .vec files.

Counting the lines in `cc.ja.300.vec` file only returns 81,976. I've tried to load the model from `.bin` file and print word vectors using command line but I got `Model file has wrong file format!` error, also tried using 3rd party libraries to compare, but I got unicode error.

Thanks for sharing word vectors, earlier wiki vectors was a great baseline for my project and I would like to try out cc vectors!

And one final nitpick, `[https://fasttext.cc/docs/en/crawl-vectors.html].` link is broken on [https://fasttext.cc/docs/en/pretrained-vectors.html](https://fasttext.cc/docs/en/pretrained-vectors.html) there is an extra `]` character at the end.

**Comment by EdouardGrave** [comment]
Hi @umutto,

Thank you for reporting this issue.

The Japanese pre-trained word vectors in text format should be fixed now.

Regarding the `Model file has wrong file format!` error, have you tried using the latest release of fastText (or even the master branch version)? This should fix the error (please re-open the issue if this is not the case).

Best,
Edouard.
