### ISSUE TITLE
How to understand `fasttext dump`?

### ISSUE THREAD

**Issue by pengyu** [facebookresearch/fastText#446]
How to understand the output in `input.txt` and `output.txt`? The header lines are self-explanatory.  But how to know what each rest row correponds to?

```
$ fasttext skipgram -minCount 1 -dim 5 -input /dev/stdin -output /tmp/model <<< 'they have a happy well behaved dog'
$ fasttext dump /tmp/model.bin input > input.txt
$ fasttext dump /tmp/model.bin output > output.txt
$ head -n 3 input.txt output.txt 
==> input.txt <==
2000008 5
-0.165987 0.156645 -0.124124 -0.0407966 0.097405
0.024156 0.123827 0.00468502 0.198034 0.186645

==> output.txt <==
8 5
-0.000225553 -0.00219077 0.00456214 0.00115895 0.00347056
-0.000546314 -0.000476842 0.000296869 7.39911e-05 0.000176826
```

Also, what does `</s>` mean?

```
$ fasttext dump /tmp/model.bin dict > dict.txt
$ cat dict.txt 
8
they 1 word
have 1 word
a 1 word
happy 1 word
well 1 word
behaved 1 word
dog 1 word
</s> 1 word
```

`1 word` appears in each row. Can it be something else? If not, it seems redudent to keep them in `dict.txt`.

**Comment by EdouardGrave** [comment]
Hi @pengyu,

`</s>` is the end of line token.

The second and third row of the dump of the dictionary correspond to the frequency of the token and whether a given token is a word or a label (which is useful for supervised models).

The rows of the dump of `input` and `output` correspond to the parameters of the model. In your example, the first 8 rows of `input` are the vectors associated to the words, while the remaining 2M rows are used to represent subwords. The rows of `output` are the vectors associated to the context. Usually, when learning unsupervised word representations, these are not kept after training.

Please read the paper "Enriching word vectors with subword information" for more information on the model.

Best,
Edouard.
