### ISSUE TITLE
Run on GPU

### ISSUE THREAD

**Issue by kimchicanh** [facebookresearch/fastText#451]
Hi,

I have problem when I train fasttext with YFCC100M data, it run on CPU and slow. Could it run on GPU???

Thanks

**Comment by matanster** [comment]
Currently not (at least no the official implementation here).

**Comment by EdouardGrave** [comment]
Hi @kimchicanh,

Have you tried using the hierarchical softmax (command line option `-loss hs`) to speed up the training process?

**Comment by kimchicanh** [comment]
hi @EdouardGrave ,

Refer to paper: "We can train fastText on more than one billion words in less than ten minutes using a standard multicore CPU, and classify half a million sentences among 312K classes in less than a minute."

I feel confuse when I run 1 day with 0.1%. I run wrong format data or something I that, I do not change any thing on data YFCC100M 

Thanks

**Comment by matanster** [comment]
@kimchicanh Have you tried reproducing it on another machine?

**Comment by EdouardGrave** [comment]
@kimchicanh,

could please post the command line you are using to run fasttext on this dataset?

Thanks!

**Comment by kimchicanh** [comment]
@EdouardGrave 

This is my command:
./fasttext supervised -input data/YFCC100M/train -output model

When it is running:
Read 1569M words
Number of words:  10682472
Number of labels: 5146120
Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 18Progress:   0.0% words/sec/thread:       9 lr:  0.100000 loss: 15.976125 ETA: 18Progress:   0.0% words/sec/thread:       9 lr:  0.100000 loss: 15.976125 ETA: 18Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 15Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 15Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 15Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 15Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 15Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 15Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 15Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 15Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 15Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 15Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 15Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 15Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 15Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 15Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 17Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      10 lr:  0.100000 loss: 15.976125 ETA: 16Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 16.707058 ETA: 16Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 16.707058 ETA: 15Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 16.707058 ETA: 15Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 16.707058 ETA: 15Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 16.707058 ETA: 16Progress:   0.0% words/sec/thread:      11 lr:  0.100000 loss: 16.707058 ETA: 16Progress:   0.0% words/sec/thread:      13 lr:  0.100000 loss: 16.707058 ETA: 13Progress:   0.0% words/sec/thread:      12 lr:  0.100000 loss: 16.707058 ETA: 14Progress:   0.0% words/sec/thread:      12 lr:  0.100000 loss: 16.707058 ETA: 14Progress:   0.0% words/sec/thread:      12 lr:  0.100000 loss: 16.707058 ETA: 14Progress:   0.0% words/sec/thread:      12 lr:  0.100000 loss: 16.707058 ETA: 14Progress:   0.0% words/sec/thread:      12 lr:  0.100000 loss: 16.707058 ETA: 14Progress:   0.0% words/sec/thread:      12 lr:  0.100000 loss: 16.707058 ETA: 14Progress:   0.0% words/sec/thread:      12 lr:  0.100000 loss: 16.707058 ETA: 14Progress:   0.0% words/sec/thread:      12 lr:  0.100000 loss: 16.707058 ETA: 14Progress:   0.0% words/sec/thread:      12 lr:  0.100000 loss: 16.707058 ETA: 14Progress:   0.0% words/sec/thread:      12 lr:  0.100000 loss: 16.707058 ETA: 14Progress:   0.0% words/sec/thread:      12 lr:  0.100000 loss: 16.707058 ETA: 14Progress:   0.0% words/sec/thread:      12 lr:  0.100000 loss: 16.707058 ETA: 14Progress:   0.0% words/sec/thread:      12 lr:  0.100000 loss: 16.707058 ETA: 14Progress:   0.0% words/sec/thread:      12 lr:  0.100000 loss: 16.707058 ETA: 14Progress:   0.0% words/sec/thread:      12 lr:  0.100000 loss: 16.707058 ETA: 14Progress:   0.0% words/sec/thread:      12 lr:  0.100000 loss: 16.707058 ETA: 14Progress:   0.0% words/sec/thread:      13 lr:  0.100000 loss: 16.707058 ETA: 13Progress:   0.0% words/sec/thread:      13 lr:  0.100000 loss: 16.707058 ETA: 13952h 1m

**Comment by Arf4t** [comment]
**Try this
./fasttext supervised -loss hs -input data/YFCC100M/train -output model**

Try using hierarchical softmax as mentioned earlier by @EdouardGrave .
It surely improves training speed compared to softmax (which is the default option).

**Comment by data-musketeer** [comment]
Or maybe try BlazingText on AWS Sagemaker. It is basically fasttext on GPU.
https://aws.amazon.com/blogs/machine-learning/amazon-sagemaker-blazingtext-parallelizing-word2vec-on-multiple-cpus-or-gpus/
https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_amazon_algorithms/blazingtext_word2vec_text8/blazingtext_word2vec_text8.ipynb

**Comment by matanster** [comment]
@data-musketeer would be nice seeing how this can be applied to the classification part, as it only currently relates to the unsupervised learning part.

**Comment by kimchicanh** [comment]
@Arf4t @matanster @matanster @data-musketeer @EdouardGrave 

Thanks all, guys. I have tried with -loss hs and it is very fast

Sorry when I reply late

Thanks

**Comment by dclong** [comment]
@EdouardGrave 

1. Does FastText supports GPU now? 

2. `-loss hs` makes FastText train fast. But how about the quality of the results?

**Comment by julitopower** [comment]
> @data-musketeer would be nice seeing how this can be applied to the classification part, as it only currently relates to the unsupervised learning part.

Classification is supported on single instances with a single GPU: https://docs.aws.amazon.com/sagemaker/latest/dg/blazingtext.html . See [classification example notebook](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_amazon_algorithms/blazingtext_text_classification_dbpedia/blazingtext_text_classification_dbpedia.ipynb) as well.
