### ISSUE TITLE
Question about the supervised models

### ISSUE THREAD

**Issue by ekeuus** [facebookresearch/fastText#453]
I am trying to use the DBPedia supervised model to test the accuracy with some of my data.

I am not getting human-readable labels for reply. The response is usually just __label__#.

For example, I get the following response with probabilities 

"__label__14 0.583301 __label__2 0.244813 __label__1 0.0978539 __label__7 0.059034 __label__8 0.00464641"

When I use the text 

"Independence Day (Georgian: დამოუკიდებლობის დღე, damoukideblobis dghe) is an annual public holiday in Georgia observed on 26 May. It commemorates the 26 May 1918 adoption of the Act of Independence, which established the Democratic Republic of Georgia in the aftermath of the Russian Revolution of 1917. It is the national day of Georgia. Independence Day is associated with military parades, fireworks, concerts, fairs, and political speeches and ceremonies, in addition to various other public and private events celebrating the history and culture of Georgia."

Are the labels supposed to be numeric or am I missing something bigger here?

**Comment by marmikshah** [comment]
Can you show an example of your training sample? The format is __label__<b>label name</b> then your training set. 
If you've built is this way, then you should get readable labels.

**Comment by ekeuus** [comment]
My question was more conceptual as I was wondering if there are any wiki-based or news-based models, which I can use without training and just use for prediction. 

I hoped to use the DBpedia one in this way - just use it as the model for prediction without any training.

**Comment by EdouardGrave** [comment]
Hi @ekeuus,

The datasets used to train these models are available at: http://goo.gl/JyCnZq. In particular, each dataset contains a file `classes.txt` which indicates what each class corresponds to.

Best,
Edouard.
