### ISSUE TITLE
.vec and .bin file disagree when using -pretrainedVectors

### ISSUE THREAD

**Issue by adodge** [facebookresearch/fastText#456]
Hi.

So, my understanding is that the .vec file contains word vectors for the in-vocabulary items in the .bin file.  However, this seems to not be the case when I train a model with -pretrainedVectors

**Without -pretrainedVectors:**

```
$ fasttext skipgram -input ./data -output model0 -epoch 100 -thread 40

$ grep "^test " model0.vec
test 1.1997 -1.8285 -3.239 -3.1334 1.1499 [...]
$ echo "test" | fasttext print-word-vectors model0.bin
test 1.1997 -1.8285 -3.239 -3.1334 1.1499 [...]
```

**With -pretrainedVectors**

(There's also a difference in -dim, but I doubt this is the problem.  Maybe it is though.)

```
$ fasttext skipgram -input ./data -output ./model1 -dim 300 -epoch 100 -thread 40 -pretrainedVectors glove.42B.300d.txt

$ grep "^test " model1.vec
test -0.51886 -2.1325 1.9213 1.0252 -2.2538 [...]
$ echo "test" | fasttext print-word-vectors model1.bin
test -0.05801 0.015905 0.014907 0.004234 -0.016922 [...]
```

I don't know if this is a bug, or I just don't understand what these files are supposed to do.  Thought it was worth noting though.

Thanks!

**Comment by EdouardGrave** [comment]
Hi @adodge,

Thank you for reporting this issue. We will publish a fix for this bug soon.

Best,
Edouard.

**Comment by EdouardGrave** [comment]
Hi @adodge,

This issue should now be fixed.

Best,
Edouard.
