### ISSUE TITLE
How can I get context vectors from a pretrained model ?

### ISSUE THREAD

**Issue by msobroza** [facebookresearch/fastText#460]
Thanks you in advance for the answer

**Comment by EdouardGrave** [comment]
Hi @msobroza,

One way to get context vectors from a pre-trained model is to use the `dump` subcommand:
```
> fasttext dump model.bin output
```
will print the weights of the "context matrix", while
```
> fasttext dump model.bin dict
```
will print the vocabulary of the model.

Please note that for the models trained on common crawl with position weights (https://fasttext.cc/docs/en/crawl-vectors.html), the same vectors were used for context and target.

Best,
Edouard
