### ISSUE TITLE
Problems with pretrainedVectors=

### ISSUE THREAD

**Issue by mathias3** [facebookresearch/fastText#462]
pretrainedVectors seem not to work properly in python wrappers at least. My model.bin is the same , no matter if trained with them or without, no change. FastText does not trow any error

**Comment by pilipolio** [comment]
Unfortunately it doesn't seem to be supported by the Python wrappers based as of the current master branch https://github.com/facebookresearch/fastText/blob/master/python/fastText/FastText.py#L289

**Comment by mathias3** [comment]
My bad, I did not spot that earlier. In my defence , all the docs seem to say " In general it is assumed that the reader already has good knowledge of fastText..." Thanks  @pilipolio !
