### ISSUE TITLE
Assertion failed: (A.m_ == m_), function mul, file src/vector.cc, line 93.

### ISSUE THREAD

**Issue by shashi-netra** [facebookresearch/fastText#463]
I have a fasttext (v0.1.0) model trained on some reddit posts and I am able to run it

this works

```
echo "a brief history of time" | ./fasttext print-sentence-vectors model_reddit.bin
-0.13403 ... -0.0032769
```

this fails!

`./fasttext predict model_reddit.bin test.txt 3`

where test.txt contains the line "a brief history of time", I get this error

```
Assertion failed: (A.m_ == m_), function mul, file src/vector.cc, line 93.
Abort trap: 6
```

what could be wrong?

**Comment by vasiliy-mikhailov** [comment]
same here 
./fasttext predict model.bin test.txt 1
fasttext: src/vector.cc:93: void fasttext::Vector::mul(const fasttext::Matrix&, const fasttext::Vector&): Assertion `A.m_ == m_' failed.
Aborted (core dumped)

**Comment by vasiliy-mikhailov** [comment]
solved: invoking fasttext I specified skipgram instead of supervised worked well
`./fasttext supervised -input mnt_data_clean.csv -output model`
`./fasttext predict model.bin test.txt 1`

**Comment by wingleungchoi** [comment]
Could fasttext use skipgram model for `predict`?

**Comment by Celebio** [comment]
Hi @wingleungchoi ,
No. The prediction is for the supervised model.

Best regards,
Onur
