### ISSUE TITLE
python api to get vector for sub word

### ISSUE THREAD

**Issue by ariwaranosai** [facebookresearch/fastText#468]
It would be nice if we can get sub word vector directly by python api.

**Comment by theo-m** [comment]
You can:
```python
ftmod.get_input_matrix()[ftmod.get_subword_id("help")]
# or, cleaner:
ftmod.get_input_vector(ftmod.get_subword_id("help"))
```

**Comment by EdouardGrave** [comment]
Hi @ariwaranosai,

As noted by @theo-m, you can obtain the id of a given subword using the method `get_subword_id`. You can then use the method `get_input_vector` to obtain the corresponding vector:
```python
vec = model.get_input_vector(model.get_subword_id("help"))
```
You can also get a list of subwords (and corresponding ids) of a given word by using the method `get_subwords`.

Best,
Edouard
