### ISSUE TITLE
fasttext supervised classification return empty array on testing the classifier

### ISSUE THREAD

**Issue by raady07** [facebookresearch/fastText#472]
Windows,
Python 3.4
Pycharm

Issue: same code work in Ubuntu but not in windows. 

I am trying to build a supervised classifier using fast text API. My data is 'output.txt' with 15000 rows, 2 columns (gender and name) and 2 classes m/f.
`__label__F Mary
__label__F Santa
...
__label__M John`

my code is 
`classifier = fasttext.supervised('output.txt','model', label_prefix='__label__',thread=8)

labels = classifier.predict('Maria',k=1)
print(labels)`
the output is
 `[[],[],[],[]]`

The learnt supervised classifier model is saved in model.bin

how to find the problem, because same code is able to work in Ubuntu ( my friends pc) and gives an accuracy of 94 %. Any help appreciated.

**Comment by bedapudi6788** [comment]
It would be better if you include what exactly is the error you are getting.

**Comment by raady07** [comment]
I am not getting any error or output when I use the same chunk of code in windows, I have reinstalled fasttext and dont know why it returns an empty array instead of sending some probability for the word.

**Comment by nlyf** [comment]
+1, have the same problem

**Comment by nomadlx** [comment]
I think you should set `label_prefix="__label__"`

**Comment by Meadow201317** [comment]
Try the `label_prefix="__label__"`, not work

**Comment by a11apurva** [comment]
Do you have the exact same line as below in your friends's code, successfully running on Ubuntu?
`classifier = fasttext.supervised('output.txt','model', label_prefix='label',thread=8)`
and not the following :
`classifier = fasttext.supervised('output.txt','model', label_prefix='__label__',thread=8)`

**Comment by raady07** [comment]
Read in some blogs, unfortunately, I currently don't have the link. Fasttext works in Linux and still updating for Windows.

**Comment by Sunmx** [comment]
I have the same problem, it works for mac, but not work for win10

**Comment by aravindm50** [comment]
Same problem persistent with Debian VM instance in Google Cloud. Any solution?

**Comment by espdev** [comment]
I have the same problem on Windows (py3.6 x64 / fasttext 0.8.3)
```python
classifier = fasttext.supervised('train.txt',
                                 'model',
                                 label_prefix='__label__',
                                 epoch=100,
                                 silent=False)

print(classifier.label_prefix)
print(classifier.labels)

labels = classifier.predict(['Еду в Магадан', 'В Магадан!'])
print(labels)
```
Output:
```
Read 0M words
Number of words:  170
Number of labels: 2
Progress: 100.0%  words/sec/thread: 2133905  lr: 0.000000  loss: 0.202012  eta: 0h0m 
__label__
[]
[[], []]
```
It seems the labels were lost.

**Comment by Priyanka638** [comment]
Hi,
I'm having the same issue as you. I was wondering if you find a solution to this.

**Comment by espdev** [comment]
@Priyanka638

There is no a solution at the moment. This is a bug in fasttext C++ code. The project it seems abandoned and no one will fix it, also no pull requests will be accepted.

The one solution: just use Linux or WSL.
