### ISSUE TITLE
Reference outdated

### ISSUE THREAD

**Issue by buechel** [facebookresearch/fastText#481]
I know this is completely unrelated to programming but you should include a reference to the TACL instead of the arxiv paper. That way your would encourage people to cite the peer-reviewed version of the paper as for example the ACL guidelines demand.

**Comment by EdouardGrave** [comment]
Hi @buechel,

Thank you for reporting this issue. We have updated the README, which now uses the TACL bibtex instead of the arxiv version.

Best,
Edouard.
