### ISSUE TITLE
what is the function that is used for negative sampling?

### ISSUE THREAD

**Issue by infinite-Joy9l** [facebookresearch/fastText#484]
while trying to understand how negative sampling works I was going through [this blog post](http://mccormickml.com/2017/01/11/word2vec-tutorial-part-2-negative-sampling/). In this post the probability of keeing the word is discussed. is the equation that is used in fasttext the same?

**Comment by infinite-Joy9l** [comment]
![image](https://user-images.githubusercontent.com/28727956/38765419-b80acc9a-3fde-11e8-9380-72be9d672e6b.png)

**Comment by EdouardGrave** [comment]
Hi @infinite-Joy,

Yes, fastText uses the same equation as word2vec to define the probability of keeping a word. The quantity `0.001` in that equation can be changed using the command line option `-t` (it is equal to 1e-4 by default in fastText).

Best,
Edouard.

**Comment by BlockheadLS** [comment]
Hi @infinite-Joy9l ,
No, this is the code `pdiscard_[i] = std::sqrt(args_->t / f) + args_->t / f`.

**Comment by shocho3858** [comment]
> Hi @infinite-Joy9l ,
> No, this is the code `pdiscard_[i] = std::sqrt(args_->t / f) + args_->t / f`.

Actually, the equation you mentioned is the same as infinite-Joy9l's.

**Comment by BlockheadLS** [comment]
> > Hi @infinite-Joy9l ,
> > No, this is the code `pdiscard_[i] = std::sqrt(args_->t / f) + args_->t / f`.
> 
> Actually, the equation you mentioned is the same as infinite-Joy9l's.

Yes, you are right.
