### ISSUE TITLE
Python version: setting parameters does not work

### ISSUE THREAD

**Issue by pstroe** [facebookresearch/fastText#486]
Hello,

it seems that using the Python version of fastText, it is not possible to set parameters like word_ngrams, maxn, minn. The only parameter I can set is min_count. I get this error when trying to train a model with the help of a Python script:

`zsh: floating point exception  python lib/fasttext_classifier.py -d  -o  -b 3 -p True -s True`

Any ideas?

Best,

Phillip

**Comment by EdouardGrave** [comment]
Hi @pstroe,

Thank you for reporting this issue.

Could you please provide the python code used to train the model?

Best,
Edouard

**Comment by dsalfran** [comment]
Hi @EdouardGrave 

I found the same error as the original poster. It's very simple to replicate.

```
import fasttext
ft_clf = fasttext.supervised('datasets/sample.txt', 'model', lr=0.25, epoch=100, word_ngrams=2)
```

The `sample.txt` file ([here](https://github.com/facebookresearch/fastText/files/2749877/sample.txt) attached) follows the standard convetion for fasttext.

**Comment by ohlionel** [comment]
I also encountered the same problem.
My computer is a Macbook, and i install fasttext via pip:`pip install fasttext`
Here is my python code:
`import fasttext
classifier = fasttext.supervised('ama_cls.data', 'acc_amazon', word_ngrams=2)`
Here is the error massage:
`Process finished with exit code 136 (interrupted by signal 8: SIGFPE)`
It seems like things go wrong when you add parameter"word_ngrams"

**Comment by Celebio** [comment]
Hi @dsalfran , @ohlionel,
You were using the unofficial module.

We unified the APIs from the official and the unofficial module, as described in [this blog post](https://fasttext.cc/blog/2019/06/25/blog-post.html). 

You can also find a comprehensive overview of the resulting API [here](https://fasttext.cc/docs/en/python-module.html).

Thank you very much for your feedback.

I am closing this issue. Feel free to re-open it if you have a question.

Best regards,
Onur
