### ISSUE TITLE
Different subwords with the same ID

### ISSUE THREAD

**Issue by tdopierre** [facebookresearch/fastText#489]
Hi,

In order to perform a sentence classification task, I wanted to use pre-trained words & subwords embeddings from fastText. However I have a hard time recovering the subwords embeddings, considering some subwords seem to have the same ID (see below).

```
>>> import fastText
>>> model = fastText.FastText.load_model('/tmp/fastText/fr/wiki.fr.bin')
>>> model.get_subword_id('mitswe'), model.get_subword_id('bonj')
(2745775, 2745775)
```

How can two subwords have the same ID ?

Thanks

**Comment by EdouardGrave** [comment]
Hi @tdopierre,

The id of a given subword is obtained by hashing the corresponding subword string. Thus, two different subwords might have the same id in case of a collision, and are then represented by the same vector. The main motivation for using hashing is that we can then easily control the amount of memory used by the model, by choosing the number of bucket.

Best,
Edouard
