### ISSUE TITLE
Fasttext Reverse Model (Vector to Character Model)

### ISSUE THREAD

**Issue by ultragen74** [facebookresearch/fastText#496]
I am using fasttext for information extraction from unstructured data. After extracting Information I want to convert output vector into words or characters. Is there any existing model or function that can solve problem.

**Comment by canggihpw** [comment]
You can use the `nearest neighbor` function to get the nearest word vector. As the exact word, I don't think the current model capable. But it would be a great feature.

**Comment by EdouardGrave** [comment]
Hi @ultragen74,

Unfortunately, at this time, fastText cannot generate a word (or sequence of characters) from a given vector. As suggested by @canggihpw, one potential solution would be to search the nearest neighbors of the given vector (but this would only return "in vocabulary" words).

Best,
Edouard.
