### ISSUE TITLE
Is different between fasttext and fastText in python?

### ISSUE THREAD

**Issue by nomadlx** [facebookresearch/fastText#497]
According to a blog, i have install fasttext in my python, by use `pip install fasttext`. I used it to process my dataset which is a data of classification question. It seem to work very well, the acceptable accuracy is achieved and run fast.
But today, i look at this repository carefully. I found the example in  python's document is used `train_supervised`, but it in my code is `supervised`. Finally, i found these are two different libraries: **fasttext** and **fastText**!
I want to know the source of fasttext library, and whether these two libraries have some potential difference? or it just another wrap of the c code of this repository?

**Comment by EdouardGrave** [comment]
Hi @nomadlx,

The recommended method to install our python bindings for fastText is the following:
```
$ git clone https://github.com/facebookresearch/fastText.git
$ cd fastText
$ pip install .
```
Then, from python, you should use
```python
import fastText
```
You can find examples on how to use the bindings in the folder [python/doc/examples](https://github.com/facebookresearch/fastText/tree/master/python/doc/examples) of our repo.

Best,
Edouard

**Comment by ruckc** [comment]
@EdouardGrave 

Imagine a world where every library recommended this process.  How would you ever keep up?  Pip & wheels exists to solve a problem you seem to be ignoring.  No one can create anything repeatable out of raw git clones that could change day to day.

**Comment by Celebio** [comment]
Hi @ruckc ,
We are addressing this issue, we will unify everything. Thank you for your patience :) 

Regards,
Onur
