### ISSUE TITLE
Bug: ETA time very inaccurate 

### ISSUE THREAD

**Issue by DomHudson** [facebookresearch/fastText#500]
## Summary
I find that the time remaining output is extremely inaccurate. This has been tested on Ubuntu 16 and Ubuntu 18  and both reported approximately 1 hour 20 for a dataset that takes over 7 hours to train with. The ETA always decreases but it takes much longer than 1 minute for the ETA to decrease by 1 minute.

**Comment by EdouardGrave** [comment]
Hi @DomHudson,

This should be fixed now (after merging PR #501).

Best,
Edouard
