### ISSUE TITLE
How to merge multiple pre-trained models or how to get model.bin from model.txt?

### ISSUE THREAD

**Issue by altvali** [facebookresearch/fastText#502]
I'm working on an application where it needs to understand documents written in multiple languages. Is it possible to combine multiple models? Particularly, I want to start with pretrained word vectors for English and add word vectors for another language, overwriting English vectors in case of collisions. Then I want to use `print-word-vectors` on the resulted model.bin. Since model.txt files are human readable, I can take two of them and combine them, but I don't know how to obtain the resulting model.bin.

Can this be done from the command line?

**Comment by swigder** [comment]
To just get binary format, without character-level embeddings, I trained for zero epochs using the -pretrainedVectors flag and use the output.

To regenerate character-level embeddings from trained vectors if you only have txt format, I used this (fairly slow) code - https://github.com/swigder/fastText/commit/7bbb7bf2407ec36586eb5efb03af3ed0e7444150. Not sure how well it would work if you're mixing languages though.

Note that there's a bug in -pretrainedVectors - if any of your "words" are whitespace, and words following it won't be loaded. This applies to at least 2 of the pretrained English models on fasttext.cc.
