### ISSUE TITLE
Python predict raises exception if all results below threshold

### ISSUE THREAD

**Issue by polm** [facebookresearch/fastText#503]
The `predict` code will raise a `ValueError` if all results are below the `threshold`. Example:

    ft = fastText.load_model('model.bin')
    res = ft.predict('blah blah blah', threshold=1.0)

The natural thing seems to be to return an empty tuple.

**Comment by Celebio** [comment]
Hi @polm,
The issue should be fixed by the commit 2936e07.

I am closing the issue. Feel free to re-open it if you still observe the problem.

Thank you for reporting!

Best regards,
Onur
