### ISSUE TITLE
Pretrained Crawl English model not loaded completely with -pretrainedVectors 

### ISSUE THREAD

**Issue by swigder** [facebookresearch/fastText#505]
The crawl-300d-2M.vec model available at https://fasttext.cc/docs/en/english-vectors.html contains a tab for a word, which causes loading with -pretrainedVectors to not load all words.

Offending line (at least, the first one):

`sed -n '44916p' crawl-300d-2M.vec`

See also https://github.com/facebookresearch/fastText/issues/444

**Comment by EdouardGrave** [comment]
Hi @swigder,

Thank you for reporting this issue! This should be fixed now.

Best,
Edouard.
