### ISSUE TITLE
Wiki vectors for Gothic and Old Church Slavonic are unavailable

### ISSUE THREAD

**Issue by danielhers** [facebookresearch/fastText#511]
When trying to access [the](https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki.got.vec) [files](https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki.cu.vec), I get:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>4A77FFE31CFE9DA9</RequestId>
<HostId>
F+Ugp31kfmmxS+1BA7RFyX0ZcpUSSpAFTjKzlQr3d4jxuocVhUkDURJx6K3VGa9rGBbsK8hdAg4=
</HostId>
</Error>
```

**Comment by piotr-bojanowski** [comment]
Hi @danielhers,

This should be solved now. Thanks for bringing that up!

Best,

Piotr
