### ISSUE TITLE
Make regular releases of fastText

### ISSUE THREAD

**Issue by dclong** [facebookresearch/fastText#514]
I looked into a few libraries for fastText, but an essential question come up. I don't know which version of original fastText they correspond to and whether they are compatible with the latest version of fastText. It helps users a lot to make regular releases (and best for other language binds such as Python and Java as well).

**Comment by Celebio** [comment]
Hi @dclong ,
Thank you very much for your suggestion. You are right, we should do more regular releases. We are trying to align our long term roadmap with smaller contributions, which makes it more difficult. But we agree with you, hopefully you will see more releases.

I am closing this issue. Feel free to re-open it if you have a question.

Best regards,
Onur
