### ISSUE TITLE
how can I READ the model.bin in java or python

### ISSUE THREAD

**Issue by flybirp** [facebookresearch/fastText#52]
thanks

**Comment by pyk** [comment]
For python, you can use the `fasttext` module

```shell
pip install fasttext
```

example to load the model:

```
import fasttext

# Load Skipgram or CBOW model
model = fasttext.load_model('model.bin')
# print some word vector
print model['king'] 

# Or load pre-trained classifier
classifier = fasttext.load_model('model.bin', label_prefix='__label__')

# To predict k-best labels from texts
classifier.predict(texts, k=3)
```

Link to the github repo: https://github.com/salestock/fastText.py

**Comment by flybirp** [comment]
thanks very much

**Comment by xiaokai-wang** [comment]
If having a C++ interface?

Thanks.

**Comment by lababidi** [comment]
I wanted to leave a note here that the python library no long works with pre-trained word embeddings trained from Wikipedia:

https://github.com/salestock/fastText.py/issues/115
