### ISSUE TITLE
Does the removal of consecutive whitespaces affect word vectors generated?

### ISSUE THREAD

**Issue by pengyu** [facebookresearch/fastText#520]
I understand that FastText does not require the removal of all punctuation. But it is not clear to me what is the effect of removing consecutive whitespaces. Could somebody explain? Thanks.

https://github.com/facebookresearch/fastText/issues/441

**Comment by galogen777** [comment]
I prefer remove all punctuation and *all* consecutive *whitespaces collapse to one* but on my model it doesn't influense precision.

**Comment by EdouardGrave** [comment]
Hi @pengyu,

Removing consecutive whitespaces (except newlines) do not have an effect on training, as consecutive whitespaces are treated as one whitespace by fastText (i.e. additional whitespaces are ignored).

FastText uses newlines to separate examples, and words are not sampled across lines (please see #518 for a longer answer regarding newlines). In practice, removing or keeping newlines does not have a big impact usually. We thus recommend to keep newlines when training word vectors.

Best,
Edouard.
