### ISSUE TITLE
Meaning of -minCount

### ISSUE THREAD

**Issue by pengyu** [facebookresearch/fastText#521]
The help says the following. But the explanation is too short and it is not clear what it means. Can anybody provide a more detailed explanation in the context of the fastText algorithm? Thanks.

```
-minCount           minimal number of word occurences [1]
```

P.S. It is that fasttext's help for `-minCount` is not clearly written. Apparently, the explanation from the following URL is clearer.

https://www.npmjs.com/package/word2vec

**Comment by a11apurva** [comment]
minCount is used to discard those words which appear less than minCount times in your training corpus.

The intuition behind this is that if your training corpus is large enough and if frequency of a particulat word is very less, it will act as a noise and the model will not converge properly. But, this is xorpus/case dependent and thus it is a hyper-parameter which you can tune to your need.

**Comment by EdouardGrave** [comment]
Hi @pengyu,

As indicated by @a11apurva, the command line option `-minCount` indicates the threshold for discarding rare words: all the words which appear less than the value of `minCount` will be ignored by fastText.

There are multiple reasons for using this: first, on very large corpora, the vocabularies tend to be large, leading to large models. Reducing the size of the vocabulary by augmenting the value of `-minCount` is thus a way to control the memory used by fastText. The second reason is that words that only appear a small number of time will not have a good representation, and might lead to overfitting.

Best,
Edouard.
