### ISSUE TITLE
Which algorithm is being used for the classification task ? 

### ISSUE THREAD

**Issue by a11apurva** [facebookresearch/fastText#523]
I have followed the references provided and the code and understood how the word-embedding are being generated. What I am not able to get is:

1. How is sentence/document vector is created using individual word embedding

2. Which algorithm is being used for the classification task (when using ./fasttext supervised supervised and then ./fasttext supervised predict)

**Comment by EdouardGrave** [comment]
Hi @a11apurva,

1. A sentence/document vector is obtained by averaging the word/ngram embeddings.
2. For the classification task, [multinomial logistic regression](https://en.wikipedia.org/wiki/Multinomial_logistic_regression) is used, where the sentence/document vector corresponds to the features. When applying fastText on problems with a large number of classes, you can use the hierarchical softmax to speed-up the computation (with the command line option `-loss hs`).

Please note that the two weight matrices (corresponding to the word/ngram embeddings and the classifiers) are learned jointly.

Best,
Edouard.

**Comment by sumantk** [comment]
Hi, in which file can I see the implementation of multinomial logistic regression? I only saw a binary logistic function in a file.

**Comment by ceefour** [comment]
Thank you @EdouardGrave , it would be very useful if this info is mentioned in the supervised-tutorial file

**Comment by kargaranamir** [comment]
> 2. For the classification task, [multinomial logistic regression](https://en.wikipedia.org/wiki/Multinomial_logistic_regression) is used, where the sentence/document vector corresponds to the features. When applying fastText on problems with a large number of classes, you can use the hierarchical softmax to speed-up the computation (with the command line option `-loss hs`).

Hi @EdouardGrave, Is the speed-up for inference or training?
