### ISSUE TITLE
Please reconsider restrictions in PATENTS (Additional Grant of Patent Rights Version 2)

### ISSUE THREAD

**Issue by rjgsousa** [facebookresearch/fastText#525]
Dear all,

as you did with [react-native](https://github.com/facebook/react-native/issues/8952), and for the same reasons, can you please reconsider restrictions in PATENTS (Additional Grant of Patent Rights Version 2)?

Thank you.

**Comment by Celebio** [comment]
Hi @rjgsousa ,
We are under MIT license [since v0.2.0](https://github.com/facebookresearch/fastText/releases/tag/v0.2.0).

Thank you very much for your feedback.

I am closing this issue. Feel free to re-open it if you have a question.

Best regards,
Onur
