### ISSUE TITLE
Wrong license in setup.py

### ISSUE THREAD

**Issue by justinormont** [facebookresearch/fastText#526]
The license in setup.py is claimed to be both BSD & MIT in different sections.

In the classifiers section, it says, `License :: OSI Approved :: MIT License'`, and it should instead say, `'License :: OSI Approved :: BSD License'`.

https://github.com/facebookresearch/fastText/blob/3ba1758d1ce4c660b82086067ad876a835af43ae/setup.py#L155
https://github.com/facebookresearch/fastText/blob/3ba1758d1ce4c660b82086067ad876a835af43ae/setup.py#L150

**Comment by EdouardGrave** [comment]
Hi @justinormont,

Thank you for raising this issue. We recently landed a commit that re-license fastText to MIT. We've also fixed these incoherences in `setup.py`.

Best,
Edouard.
