### ISSUE TITLE
when install the fastText got that eror

### ISSUE THREAD

**Issue by xyjsjruiliu** [facebookresearch/fastText#53]
c++ -pthread -std=c++0x -O3 -funroll-loops -c src/dictionary.cc
src/dictionary.cc: In member function ‘void Dictionary::threshold(int64_t)’:
src/dictionary.cc:189: error：expected primary-expression before ‘[’ token
src/dictionary.cc:189: error：expected primary-expression before ‘]’ token
src/dictionary.cc:189: error：expected primary-expression before ‘const’
src/dictionary.cc:189: error：expected primary-expression before ‘const’
src/dictionary.cc:193: error：expected primary-expression before ‘[’ token
src/dictionary.cc:193: error：expected primary-expression before ‘]’ token
src/dictionary.cc:193: error：expected primary-expression before ‘const’

**Comment by EdouardGrave** [comment]
This is probably because you are using a c++ compiler which does not support new wording of lambdas. What compiler are you using?
