### ISSUE TITLE
Does the supervised and word representation task have different valid parameters？

### ISSUE THREAD

**Issue by datazhen** [facebookresearch/fastText#530]
For example, Does `maxn`, `minn` only works  in the word representation task and `wordNgrams` works in in supervised?

Hopefully you can list all the valid parameters for each of tasks. 

thank you again!

**Comment by EdouardGrave** [comment]
Hi @datazhen,

Thank you for raising this issue.

The following parameters are only used by the supervised mode: `minCountLabel`, `wordNgrams`, `label` and `pretrainedVectors`.

The following parameters are only used by the skipgram and cbow modes: `t`, `ws`.

Additionally, the `neg` parameters is only used by the negative sampling loss (`-loss ns`).

We will update the readme to add this information.

Best,
Edouard.

**Comment by karlek** [comment]
The README.md still hasn't been updated, and there's no information about this anywhere except this issue. Furthermore, it would be better if flags were not printed for incompatible modes in the help. Even better is that they should error when used and not be accepted for the incompatible modes silently. I suggest that this issue should be opened again.
