### ISSUE TITLE
Memory Allocation Error While Loading the Model

### ISSUE THREAD

**Issue by sodaliAyran** [facebookresearch/fastText#532]
Hi there, I'm getting an error while I'm trying to load a pre-trained model on a remote server.
import fastText
model = fastText.load_model("wiki.tr.bin")

Model size is nearly 3.5 GB and my server has only has let's say 2 GB of RAM. Is there any way to reduce the model size or any efficient way to load it. I'm willing to sacrifice performance.

Thank you.

**Comment by matanster** [comment]
You can quantize the model. See in the command-line options.

**Comment by sodaliAyran** [comment]
@matanster pardon my noobnes but I've seen those commands but I'm not sure how can I use them on a python application.

**Comment by matanster** [comment]
Well whereas I'm not familiar with the python wrapper, the command line
execution can quantize a model, thus making it drastically smaller with
typically only a small hits on performance (as in accuracy). It is meant
exactly for this scenario.

**Comment by sodaliAyran** [comment]
@matanster  OK, I found out how to do it. Basically first I have to run this command
$ ./fasttext supervised -input  /wiki.tr.vec -output /wiki.tr
then
$ ./fasttext quantize -input /wiki.tr.vec -output /wiki.tr

Then it works. Hopefully it will do what I want. 

Thank you.

**Comment by matanster** [comment]
Yes, you may prepare the model using the command line, then load it in your
python application. Which of these stages is also available in the python
API I wouldn't know.

**Comment by sodaliAyran** [comment]
I prepare the model in fasttext console then load in the python.
So basically: 

$ ./fasttext supervised -input /wiki.tr.vec -output /wiki.tr
then
$ ./fasttext quantize -input /wiki.tr.vec -output /wiki.tr

$ python
import fastText
model = fastText.load_model('wiki.ftz')

Done.
