### ISSUE TITLE
Any open source python implementation of fasttext?

### ISSUE THREAD

**Issue by omerarshad** [facebookresearch/fastText#534]
Thanks for such a great contribution, Is there any python implementation of fasttext? or any plans to do such?

**Comment by giacbrd** [comment]
If you are looking for pure Python code, you can look at https://github.com/giacbrd/ShallowLearn
I have not worked on it for a long time, but I would, in the near future

**Comment by omerarshad** [comment]
Thanks for the references, but there is no open source implementation of fasttext in it.

**Comment by a11apurva** [comment]
Hi,
You you can check this package available at pypi : https://pypi.org/project/fasttext/
The open repo of the same : https://github.com/salestock/fastText.py

**Comment by omerarshad** [comment]
this is wrapper to C code, if I want to add new hidden layer for example, then still I have to add it in c

**Comment by EdouardGrave** [comment]
Hi @omerarshad,

I am not aware of a full python implementation of fastText. Some functionalities of fastText are implemented in `cython` in the [gensim](https://radimrehurek.com/gensim/) library. 

Best,
Edouard.
