### ISSUE TITLE
Bug in wikipedia parser?

### ISSUE THREAD

**Issue by foldl** [facebookresearch/fastText#535]
I have downloaded Chinese word vectors. The first word is \</s\>, an HTMl tag.  I think this indicates that there is bug in wikipedia parser.

https://s3-us-west-1.amazonaws.com/fasttext-vectors/word-vectors-v2/cc.zh.300.vec.gz

https://github.com/facebookresearch/fastText/blob/master/docs/crawl-vectors.md

**Comment by EdouardGrave** [comment]
Hi @foldl,

Thank you for raising this issue.

This is not a bug in the Wikipedia parser: `</s>` is a special token used by fastText to represent the end of line (c.f. [line 23](https://github.com/facebookresearch/fastText/blob/master/src/dictionary.cc#L23) of `dictionary.cc`). You can ignore that line from the model file.

Best,
Edouard.
