### ISSUE TITLE
Arabic Sentiment Analysis

### ISSUE THREAD

**Issue by sheikho1983** [facebookresearch/fastText#537]
How can I use fasttext for Arabic Sentiment Analysis?

**Comment by matanster** [comment]
With fasttext, you'd probably have to annotate hundreds of sentences (the more the better) as "good" and "bad" sentiment, then use fasttext to learn a classification model from your examples. You can also use other tools and resources for what's called sentiment analysis.

**Comment by Celebio** [comment]
Hi @sheikho1983 ,
As @matanster mentioned, you need to train a classifier on your data. You can find more information on how to use the supervised model of fastText [here](https://fasttext.cc/docs/en/supervised-tutorial.html).

I am closing the issue now. Feel free to re-open it if you have further questions.

Best regards,
Onur
