### ISSUE TITLE
Incorrect use of FNV-1a

### ISSUE THREAD

**Issue by danieldk** [facebookresearch/fastText#539]
I am implementing a Rust library that can read and use fastText embeddings (so that I don't have to bind against the C++ library). While writing unit tests, I found that fastText uses the FNV-1a hash incorrectly (I think). FNV hashes per octet of data [1], however, the following line in `Dictionary::hash`:

~~~c++
h = h ^ uint32_t(str[i]);
~~~

sign-extends any byte > 0x7f (thus leading and continuation bytes in UTF-8) in g++/clang++, since `char` is signed in by default in those C++ implementations. Consequently, the 24 most significant bits of the FNV state get flipped. The following should be correct:

~~~C++
h = h ^ uint32_t(uint8_t(str[i]));
~~~

I am not sending a pull request, since it would make all existing models 'incompatible', and it will probably not lead to any measurable differences. But I thought it would be good to mention this in case anyone else runs into this.

[1] http://www.isthe.com/chongo/tech/comp/fnv/index.html#FNV-1a

**Comment by EdouardGrave** [comment]
Hi @danieldk,

Thank you for reporting this issue.

As you said, there is not an easy fix for this problem. One thing that we will fix is to make the hash function independent of compiler specific behavior by using:
```c++
h = h ^ uint32_t(int8_t(str[i]));
```

We will also try to document this issue, so that other re-implementation of fastText do not run into the same problem.

Best,
Edouard.

**Comment by Celebio** [comment]
Hi,
As discussed here, [this commit](https://github.com/facebookresearch/fastText/commit/9c9b9b2eca4fdc0182182cb69234fffbb847d820) implements the cast to `int8_t` in order to keep compatibility.

I am closing this issue now. Thank you @danieldk for pointing this problem!

Best regards,
Onur
