### ISSUE TITLE
fastText in Caffe2 library to run with GPU

### ISSUE THREAD

**Issue by junjieqian** [facebookresearch/fastText#540]
Reading the manuals and found this link, https://github.com/facebookresearch/fastText/blob/master/docs/faqs.md#can-we-run-fasttext-program-on-a-gpu. Would anyone share the link to the implementation?

Thanks

**Comment by EdouardGrave** [comment]
Hi @junjieqian,

Unfortunately, this implementation is not public at this time. Our goal was to indicate that it is possible to implement similar models for GPUs, by using deep learning frameworks such as caffe2 or pytorch. However, please note that one of the goal of fastText is to provide efficient NLP tools for CPU, which do not require GPU to learn models.

Best,
Edouard
