### ISSUE TITLE
Limit word length - Skipgram

### ISSUE THREAD

**Issue by gavincangan** [facebookresearch/fastText#541]
I am using FastText to compute skipgrams on a corpus containing a long sequence of characters with no spaces. After an hour or so, FastText produces a model containing vectors (of length 100) corresponding to "words" of length 50 characters from the corpus.

I tried setting -minn and -maxn parameters, but that does not help (I kind of knew it won't, but tried anyway), and -wordNgrams parameter only applies if there are spaces, I guess (?!). This one is just a long stream of characters representing state, without spaces.

The documentation doesn't seem to have any information on this (or perhaps I'm missing something?). I was wondering if perhaps someone has been through this or something similar, where you had to limit the size of the words corresponding to an output vector?

**Comment by EdouardGrave** [comment]
Hi @gavincangan,

FastText always uses spaces as token delimiters (and thus, will not work for non-tokenized sequences). For example, for languages such as Japanese or Chinese, it is very important to segment the data into words before applying fastText. The `-minn` and `-maxn` parameters are used to indicate the length subword features (which are character ngrams, inside a token).

Best,
Edouard.
