### ISSUE TITLE
Gensim will not return desired summary output

### ISSUE THREAD

**Issue by Jbrown214** [facebookresearch/fastText#544]
I am currently running a program via Python3 through IntelliJ platform that uses Gensim library to summarize legal cases. I know that in order for Gensim to work, it has to meet a minimum length requirement. However, there is one case that has over 8,000 words and when I try to call and set the word_count parameter to 100, I do not see any text. However, when I decide to  call for the ratio parameter and set it arbitrarily to 0.1, I then am I able to see the returned summary output.  

Could anyone suggest what might the issue might be?

**Comment by EdouardGrave** [comment]
Hi @Jbrown214,

This issue seems to be related to the Gensim library and not fastText, and I would suggest to open an issue on the [Gensim Github repository](https://github.com/RaRe-Technologies/gensim).

Best,
Edouard.
