### ISSUE TITLE
Gender detection , Use Full name or First Name only !

### ISSUE THREAD

**Issue by beshoo** [facebookresearch/fastText#546]
Dear Flocks 
Back to https://github.com/facebookresearch/fastText/issues/336

I get a Huge database with multi language dataset of " Full Name " Gender Labiled , so what is the advice.

Extract only firstName from the dataset ?
Or use Full Name ? 
While when we will quarry we may send only (firstName).

Regards

**Comment by Celebio** [comment]
Hi @beshoo ,
I believe you should try both and then test the performance of your model with `test` command on some validation sets.

I am closing this issue. Feel free to re-open it if you have further questions.

Best regards,
Onur
