### ISSUE TITLE
Shouldn't this be 'not in'

### ISSUE THREAD

**Issue by grahamannett** [facebookresearch/fastText#554]
https://github.com/facebookresearch/fastText/blob/4062c21e13eba9f7a5d7c516b045c901ea1510de/python/fastText/util/util.py#L58

Im trying to use the python module and it was giving me the same word.  Looked into it and it seems like this maybe is just returning words in the ban list?

**Comment by abulhawa** [comment]
This is correct, for the intended purpose. However, check #552 for a fix that gives the same results returned by command line ./fasttext nn, skipping the query word

**Comment by grahamannett** [comment]
@abulhawa Ah cool.  I noticed even when I did change stuff around that it wasn't working the same as training the model and calling nn from the cli.  Will check out your PR and see if it works as expected, guess I can close those and comment in your PR if there is an issue.
