### ISSUE TITLE
Word vectors not matching the quality of fasttext classification model

### ISSUE THREAD

**Issue by rbchinnam** [facebookresearch/fastText#556]
I am using fasttext to associate medical text notes for patients with admission decisions (classification). This is similar to sentiment analysis. I am getting decent accuracy. However, I also have structured quantitative data that I would like to leverage for further improving the accuracy of the model. The plan was to extract word vector embedding for each patient's text note (one vector for the entire text note) and combine it with the patient's quantitative data to build another classifier with better performance. 

To my surprise, even without adding the quantitative data, I am not able to use the word vectors supplied by fasttext using the model learnt above to build another classifier that can match the performance of the fasttext classification model.    

I am simply calling the get word vector function using the trained fasttext model and the same text notes used for training the model in the first place. 

Am I doing something wrong? Appreciate any input.  I am using the fastTextR package in R. Thanks.

**Comment by Celebio** [comment]
Hi @rbchinnam ,
We do not support fastTextR package.

I am closing this issue since it is quite old and you probably found a solution to your problem.

If you observe the issue with our package, feel free to re-open it, we would be happy to help you.

Best regards,
Onur
