### ISSUE TITLE
Supervised Text Classification

### ISSUE THREAD

**Issue by aakashb1** [facebookresearch/fastText#557]
How are word embedding learnt in the case of supervised text classification in fastText?  Are char n-grams used in learning word representation of the input file for the supervised classification as well?

**Comment by bedapudi6788** [comment]
Yes, word vectors learning works same in both supervised and unsupervised modes.

**Comment by BlockheadLS** [comment]
Hi @aakashb1 ,
    Word embedding can be learned from supervised and unsupervised models. However, the embedding from supervised model is about the label, and the embedding from unsupervised model is about the context.

**Comment by abeerunscore96** [comment]
@BlockheadLS Could you please expand on what that means? Would a supervised model not learn from context? i.e. would it not be able to judge whether the word "girl" is feminism related in the sentence "Girls have historically been mistreated ... " but not feminism related in "A few girls walked by ..." ?

**Comment by Celebio** [comment]
Hi @abeer-khan ,
You can find a longer version of @BlockheadLS 's great answer in this [comment](https://github.com/facebookresearch/fastText/issues/469#issuecomment-486229924).

I am closing this issue now. Feel free to re-open it if you have further questions about the subject.

Best regards,
Onur

**Comment by Allenlaobai7** [comment]
Hi @Celebio , I have several questions regarding supervised training. 

1. I got this from the original paper('Bag of tricks for efficient text classification'): 
> we use a bag of n-grams as additional features to capture some partial information about the local word order.' 

however the default 'wordNgrams' is equal to 1 in supervised learning. Does it mean that if I go with the default setting of 'wordNgrams =1', 'minn = 0' and 'maxn = 0', the model will only use vectors of the input words(without word n-grams or char n-grams) for training?

2. after i increased minn and maxn from 0 to 4 (with pretrained vectors) , the model's performance drops. Is it better to not use subword information for classification?

3. if I use skipgram to train an embedding on some texts, can i use this embedding as pretrained vectors for classification task involving the same dataset?

Thank you! :)
