### ISSUE TITLE
Multilabel Classification

### ISSUE THREAD

**Issue by davidsbatista** [facebookresearch/fastText#56]
Does fastText supports multilabel classification?

**Comment by EdouardGrave** [comment]
Yes, fastText supports multilabel classification.

**Comment by HimaVarsha94** [comment]
But it doesn't support multilabel testing right? As in it always only returns 1 class during test time?

**Comment by gunny-probably** [comment]
Bump @HimaVarsha94 - during test time, you can specify parameter `k` to indicate the top `k` best labels found. So yes, the package does support multilabel testing. You have to specify the "multi" in "multilabel" testing.
