### ISSUE TITLE
Version is somehow behind the one in PyPi

### ISSUE THREAD

**Issue by yasonk** [facebookresearch/fastText#560]
Not sure how this happened, but the version from PyPi(https://pypi.org/project/fasttext/) is higher than in setup.py here. However, PyPi references this repo in the description. Is there another repo that's more up to date?

**Comment by m09** [comment]
Actually, 8.22 > 8.3 so this version is newer. Nobody pushed this version on PyPi yet though (which is super annoying). Your best bet it probably to use PyPi Test (https://test.pypi.org/project/fasttext/) where the version is up to date or to just bundle the repo and install locally in your application.

**Comment by Celebio** [comment]
Hi @yasonk , @m09,
[Pypi version](https://pypi.org/project/fasttext/) is now in line with [github version](https://github.com/facebookresearch/fastText/tree/master/python), as described in [this blog post](https://fasttext.cc/blog/2019/06/25/blog-post.html). In particular, you can see how we ended up with different versions and version numbers [here](https://fasttext.cc/blog/2019/06/25/blog-post.html#fasttext-vs-fasttext-what-happened).

Now, the python version is also synced with git repository tag, which is now [0.9.1](https://github.com/facebookresearch/fastText/releases/tag/v0.9.1)

Thank you very much for your feedback. I hope everything is clearer now. I am closing this issue. Feel free to re-open it if you have a question.

Best regards,
Onur

**Comment by m09** [comment]
That's great news, thanks!
