### ISSUE TITLE
Why does the example write the data to a file, only to then read it again?

### ISSUE THREAD

**Issue by thomasahle** [facebookresearch/fastText#562]
In the python tests, there is a train/validation example, in which the validation is written to a temporary file, which is then immediately reread - using `mode.get_line`:
https://github.com/facebookresearch/fastText/blob/25d0bb04bf43d8b674fe9ae5722ef65a0856f5d6/python/fastText/tests/test_script.py#L217

Is there any advantage to doing it this way? Or could we have just used the validation data directly from memory?

**Comment by EdouardGrave** [comment]
Hi @thomasahle,

Thank you for your question! I believe that this python script is meant to test wether the python and c++ implementation of `test` produce the same results, hence the writing of the data to a temporary file. To answer your question, the validation data could directly be used from memory. Please note that this script contains test, and are not examples of how to use our python bindings.

Best,
Edouard.
