### ISSUE TITLE
Does the parameters minn and maxn make sense for Chinese?

### ISSUE THREAD

**Issue by little-yoki** [facebookresearch/fastText#565]
As you might know, there is no clear boundaries between words in Chinese, like the sentence 

> "祝您一路顺风！".

Now assume I have already removed the punctuation and separated words in the text by white spaces. Suppose I get 

>  "祝您 一路顺风" 

for the sentence above.
I know that if I set the `minn` and `maxn` parameters to be like 3 and 6, I can utilize the subword information. 

But I am wondering that whether I can utilize subword information in Chinese text classification?  If so, in the example above, what are the character bigrams for word "一路顺风" ? Are them 

> ["一路", "路順", "顺风"] ?

Thank you!

**Comment by EdouardGrave** [comment]
Hi @little-yoki,

Yes, the `minn` and `maxn` parameters can be used for Chinese text classification, as long as your data is encoded in `utf-8`. Indeed, fastText assumes that the data used `utf-8` to split words into character ngrams. For Chinese text classification, I would recommend to use smaller values for `minn` and `maxn`, such as 2 and 3.

Best,
Edouard.
