### ISSUE TITLE
models difference for fasttext.cc and https://github.com/facebookresearch/fastText ??

### ISSUE THREAD

**Issue by Sandy4321** [facebookresearch/fastText#575]
how data for English word2vec models is different for these 2 models download links?

https://fasttext.cc/docs/en/english-vectors.html

https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md

**Comment by EdouardGrave** [comment]
Hi @Sandy4321,

The models from [https://fasttext.cc/docs/en/english-vectors.html](https://fasttext.cc/docs/en/english-vectors.html) were trained on Wikipedia, as well as news data from the [WMT workshop](http://statmt.org/wmt16/translation-task.html) and the (UMBC corpora)[https://ebiquity.umbc.edu/resource/html/id/351/UMBC-webbase-corpus]. Additionally, there is also a mode that was trained on data from the common crawl project. We highly recommend to use these newer models, as they are of much higher quality compared to the ones from the second link (which were trained on Wikipedia only). Please also see the paper (Advances in Pre-Training Distributed Word Representations)[https://arxiv.org/abs/1712.09405] if you want more details about the techniques used to train these models.

Best,
Edouard.

**Comment by Sandy4321** [comment]
Edouard, 
thank you very much for soon answer
your data is a really great job, 
Thank you very much
1
by the way , wich data you used from mentioned above WMT workshop
http://statmt.org/wmt16/translation-task.html
2
What standalone python code we can use to use these pre-trained models for classification
 Idea is not use C++ fasttext code but only to use python packages.
It is especailly important for Winodws users , since C++ fastext code can not be compiled on Windows
Thank you
