### ISSUE TITLE
how may words in data? for example in  'crawl-300d-2M.vec'

### ISSUE THREAD

**Issue by Sandy4321** [facebookresearch/fastText#577]
from fasttext.cc we see that there are should be  n-grams for characters/letters
" vectors of substrings of characters contained in it"
indeed we see it
```
'Trip' in z
True
'ip' in z
True
'Tri' in z
True
'ri' in z
True
'qq' in z
True
'qqq' in z
True
'qqqq' in z
True
'qqqqq' in z
False
```
so there are no  2 million words  in  'crawl-300d-2M.vec'
but actually, we have much fewer words?

it is what written
https://fasttext.cc/docs/en/faqs.html

```
Why does fastText produce vectors even for unknown words?
One of the key features of fastText word representation is its ability to produce vectors for any words, even made-up ones. Indeed, fastText word vectors are built from vectors of substrings of characters contained in it. This allows to build vectors even for misspelled words or concatenation of words.
```

**Comment by Sandy4321** [comment]
here 
len(my_data)
1999995
z = list(my_data.keys())
where my data is from 

```


import io

def load_vectors(fname):
    fin = io.open(fname, 'r', encoding='utf-8', newline='\n', errors='ignore')
    n, d = map(int, fin.readline().split())
    data = {}
    for line in fin:
        tokens = line.rstrip().split(' ')
        data[tokens[0]] = map(float, tokens[1:])
    return data
fname = 'crawl-300d-2M.vec'
my_data = load_vectors(fname)
q=1
```

**Comment by EdouardGrave** [comment]
Hi @Sandy4321,

The data that we used to train this model is from common crawl, and thus, very noisy. For this reason, there are "words" such as `qqq` that are present in our training data, and have a corresponding representation. We did not filter the words in any way, but kept the 2M most frequent "words" from the training data.

Best,
Edouard.
