### ISSUE TITLE
Suppressing character ngrams altogether 

### ISSUE THREAD

**Issue by matanster** [facebookresearch/fastText#578]
Just a quick one ― does fasttext enable suppressing character ngrams altogether, thusly being used only as a concurrent implementation of the original word2vec algorithm? sometimes you just don't want them e.g. when performing some kinds of research. 

Anything like maxn = 0 or the like?

**Comment by EdouardGrave** [comment]
Hi @matanster,

Yes, using `-maxn 0` will disable the character ngrams altogether.

Best,
Edouard.
