### ISSUE TITLE
UnpicklingError: invalid load key, '\xba'.

### ISSUE THREAD

**Issue by tastyminerals** [facebookresearch/fastText#579]
I am using **fastText** to create custom embeddings.
`fasttext skipgram -dim 50 -input data.txt -output orig_fasttext_50`

Afterwards, I attempt to load these pretrained embeddings the following way.

```python
with open("orig_fasttext_50", 'rb') as f:
    return pickle.load(f)
```

However, `pickle.load(f)` throws the following error: `_pickle.UnpicklingError: invalid load key, '\xba'.`

What am I doing wrong?

**Comment by EdouardGrave** [comment]
Hi @tastyminerals,

After training a model with the fastText command line, you can load it in python by using our bindings:
```python
import fastText

model = fastText.load_model("PATH_TO_MODEL")
```
Please see the [example folder](https://github.com/facebookresearch/fastText/tree/master/python/doc/examples) for how to use our bindings.

Best,
Edouard.
