### ISSUE TITLE
A problem about negative sampling

### ISSUE THREAD

**Issue by BlockheadLS** [facebookresearch/fastText#584]
As follows, this code is about how to use negative sampling.
<img width="731" alt="2018-07-24 5 04 37" src="https://user-images.githubusercontent.com/15126142/43128119-b9ac2c54-8f63-11e8-8daf-fc8fd48985f1.png">
<img width="469" alt="2018-07-24 5 04 55" src="https://user-images.githubusercontent.com/15126142/43128131-bec943c0-8f63-11e8-9437-e0018745380e.png">

However, the getNegative seems always return target, is this right?

**Comment by EdouardGrave** [comment]
Hi @BlockheadLS,

Actually, the `getNegative` method never returns `target`: the while loop exits only when `negative` is different from `target`, ensuring the desired property.

Best,
Edouard.

**Comment by BlockheadLS** [comment]
Yes, I am wrong. Thank you!
