### ISSUE TITLE
Why does python wrapper 0.8.22 unsupport pretrainedVectors while 0.8.3 support ?

### ISSUE THREAD

**Issue by sisiruowan** [facebookresearch/fastText#587]
Can I change some codes to support `pretrainedVectors` in Python wrapper 0.8.22 ?

Fasttext 0.8.3 python wrapper (downloaded from pip) supports `pretrained_vectors` to improve the performance of my fasttext classification models. But it takes too much memory. 

The fasttext 0.8.22 (current master branch) supports  `quantize` which can save lots of memory. 
But unfortunately, it does't support `pretrainedVectors`-- https://github.com/facebookresearch/fastText/blob/master/python/fastText/FastText.py#L289, 

**which means I can't use both `quantize` and `pretrainedVectors` in my models!** 

So, I want to know : 
1. Why the current version Python wrapper 0.8.22 doesn't support `pretrainedVectors`?
2. When will it support `pretrainedVectors` ?  
3. How can I change some codes of this repository to support `pretrainedVectors` if it's possible ?

**Comment by EdouardGrave** [comment]
Hi @sisiruowan,

Thank you for raising this issue.

The fastText python wrapper (from master) should now support the `pretrainedVectors` option.

Please re-open the issue if you still have trouble with this.

Best,
Edouard.
