### ISSUE TITLE
Does fasttext have intermediate levels while trying to predict a label?

### ISSUE THREAD

**Issue by sauravm8** [facebookresearch/fastText#595]
For example, lets say the following training data was used
sentence1 - label1
sentence2 - label2
sentence3 - label1
sentence4 - label2
sentence5 - label1
sentence6 - label2

So, when we are trying to predict the label while training, does it form a hierarchical knowledge structure where there are intermediate nodes between the sentence vector and label1 or label2? So sort of hidden features?

**Comment by EdouardGrave** [comment]
Hi @sauravm8,

The fastText supervised model works as follow: each word (and word ngram) is associated to a vector representation (a.k.a. embedding, in dimension 100 by default). A representation for the input text is obtained by averaging the embeddings corresponding to the words and ngrams that appear in the input. Then, a linear classifier is used on this representation to obtain the score corresponding to each label.

Thus, the average of the word/ngram vectors can be seen as a "hidden representation" of the sentence.

Best,
Edouard.
