### ISSUE TITLE
missing words when minCount = 1?

### ISSUE THREAD

**Issue by zjuAJW** [facebookresearch/fastText#602]
When I train fastText unsupervised on some dataset which contains about 80 million different words, the final result only contains 9 million words . I use skipgram and set minCount equal to 1, so I think all words should be included in the result. Am i missing someting here? My dataset is too big?

**Comment by zjuAJW** [comment]
I tried to reduce the size of my corpus and then the number of word in result increase! Why does this happen?

**Comment by EdouardGrave** [comment]
Hi @zjuAJW,

The maximum size of the dictionary is 21M elements. When the dictionary is full, the thresholding method is applied, based on the word frequency (hence, the number of words might be significantly smaller than 21M after thresholding). One way to increase the size of the vocabulary is to change the constant `MAX_VOCAB_SIZE` (c.f [dictionary.h#L37](https://github.com/facebookresearch/fastText/blob/master/src/dictionary.h#L37)). Please note that the dictionary is considered full when the load of the corresponding hash map is equal to 0.7 (hence with `MAX_VOCAB_SIZE` equal to 30M, the maximum number of word in the vocabulary is 0.7 x 30M = 21M).

Best,
Edouard.
