### ISSUE TITLE
Unable to install fasttext (python) on windows.

### ISSUE THREAD

**Issue by ragvri** [facebookresearch/fastText#606]
So I am unable to install fasttext for python on windows.  I followed the methods mentioned [in this issue](https://github.com/salestock/fastText.py/issues/91)

When I enter `python setup.py install`, I get the following error:

`error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2`

I tried using the wheel at [https://www.lfd.uci.edu/~gohlke/pythonlibs/#fasttext](https://www.lfd.uci.edu/~gohlke/pythonlibs/#fasttext). It does install a module, however the name of the module is **fasttext** unlike **fastText** that gets installed on Ubuntu following the method mentioned in `Readme.md`. Also the `fasttext` module that does get installed is unable to load a prebuilt model like `wiki.de.bin`. I get an error saying `Cannot load ../fasttext/wiki.es/wiki.es.bin due to C++ extension failed to allocate the memory` [Relevant issue](https://github.com/salestock/fastText.py/issues/115).

**Comment by ragvri** [comment]
@racha999 That has nothing to do with my issue

**Comment by ragvri** [comment]
New wheels updated at  [lfd.uci.edu/~gohlke/pythonlibs/#fasttext]( lfd.uci.edu/~gohlke/pythonlibs/#fasttext). Use the wheels for windows.

**Comment by 1049451037** [comment]
@ragvri Hi, the URL is not valid now

**Comment by 1049451037** [comment]
https://www.lfd.uci.edu/~gohlke/pythonlibs/#fasttext
