### ISSUE TITLE
How to set evaluate the label against a specific label

### ISSUE THREAD

**Issue by LeoLiu1998** [facebookresearch/fastText#608]
I am working on a binary classification, but I am not sure how to calculate Precision, Recall and F1 score on one class. Can I do that by changing FastText argument?

**Comment by EdouardGrave** [comment]
Hi @LeoLiu1998,

Unfortunately, fastText does not support the computation of Precision, Recall and F1 score for one class yet. For now, I would suggest to use the `predict-prob` command and a third party library to compute the precision, recall and F1.

Best,
Edouard.
