### ISSUE TITLE
How to get the vector for an unknown word phrase using Gensim?

### ISSUE THREAD

**Issue by somnathrakshit** [facebookresearch/fastText#609]
Using the Gensim library in Python, how can I get the vector of an unknown word phrase (words that are absent in dictionary) which may be of multiple words? e.g. "San Francisco"

I am using the pretrained models that have been provided on the fasttext.cc website.

**Comment by a11apurva** [comment]
Hi @somnathrakshit ,
It wont be possible to use Gensim for OOV words, that's one of the disadvantages that fasttext has tried to solve using char level embeddings, so you can use the fasttext for it.

If you want to try the same on your own using python you can refer to [section 3.2 sub-word model](https://arxiv.org/pdf/1607.04606.pdf) and write your own script for it.

**Comment by EdouardGrave** [comment]
Hi @somnathrakshit,

This issue seems to be concerning the Gensim library, and I invite you to open an issue on their github.

Best,
Edouard.
