### ISSUE TITLE
missing words?

### ISSUE THREAD

**Issue by danielhomola** [facebookresearch/fastText#61]
Hi and thanks so much for making this code public!

When I train fastText unsupervised on some chatdata, the textfile with the vectors only contains about half of the words in my corpus.. If I train it with labels then I'll get a vector for all the words in the corpus.. So somehow - it seems - fastText discards half of the words from my corpus in the unsupervised setting.. am I missing something here? sorry if this is  really trivial..

**Comment by EdouardGrave** [comment]
In both setting, words appearing less than `minCount` times in the training file are discarded by fastText. The default value of `minCount` is different for each setting. It is equal to 1 for supervised training and 5 for unsupervised training. This can be changed using the `-minCount` command line option.

**Comment by danielhomola** [comment]
thanks so much for the quick answer! I missed this default sorry...
