### ISSUE TITLE
1 iteration for large data vs 5 iterations for part of data

### ISSUE THREAD

**Issue by angrypark** [facebookresearch/fastText#611]
Hi. I have a large corpora (1B sentences, korean) and trying to train embedding with FastText. Paper(Learning Word Vectors for 157 Languages) suggests more iterations improves performance but it is impossible to train 1B sentences for 5 (or more) times. I want to choose whether to train 1B sentences 1 time or to train 100M sentences for 5 times. Do you have any suggestions?

**Comment by EdouardGrave** [comment]
Hi @angrypark,

In general, the more data, the better. Thus, I would suggest to train for 1 epoch over the full dataset of 1B sentences. May I ask why you cannot do more than 1 epoch?

Best,
Edouard.

**Comment by EdouardGrave** [comment]
Hi Sungnam,

One thing that might be helpful to train faster is to change the number of threads used by fastText: this is done by using the `-thread` command line option. The default is `12`, and I would suggest to try different values, such as `2`, `4` or `8`, which might lead to better results based on your CPU.

Best,
Edouard.
