### ISSUE TITLE
[Request] Can you make a new release?

### ISSUE THREAD

**Issue by vasanthaganeshk** [facebookresearch/fastText#612]
Can you make a new release by creating a tag? There seem to be some API changes from the last release and the master.

**Comment by gwerbin** [comment]
Also the helpful `dump` subcommand was added.

It doesn't have to be a *new* release. But clearly a lot of work has been done over the past year, people should be able to benefit from that.

**Comment by Celebio** [comment]
Hi,
We released the [version 0.2.0](https://github.com/facebookresearch/fastText/releases/tag/v0.2.0) of fastText and will continue to tag when we have a consistent api that we want to freeze before breaking it.
Thank you both for your suggestion.

Regards,
Onur
