### ISSUE TITLE
The same Precision and Recall results

### ISSUE THREAD

**Issue by BBBzou** [facebookresearch/fastText#613]
Hello,
I implemented the fasttext at CentOS for binary classification and the results of precision and recall are the same. However, these two results of other users  also be the same as I searched. I wonder whether it's correct? Could the precision equal to recall at the classification problem? Or I did something wrong with the experiment? 
Hoping for your answer.
Thanks

**Comment by a11apurva** [comment]
The R@1 and P@1 will always be identical as we compute the multi-class precision and recall.
use R@k and P@k where k>1 to see the difference.
Refer #93 for more explanation.

**Comment by EdouardGrave** [comment]
Hi @BBBzou,

As indicated by @a11apurva, the precision and recall computed by fastText correspond to the multi-class problem. In the case of binary classification, where you have a positive and negative classes and only want to compute the precision and recall of the positive class, I would suggest to use the `predict-prob` command and a third party library to compute the precision and recall.

Best,
Edouard.

**Comment by BBBzou** [comment]
@a11apurva @EdouardGrave  Thank you for your answer!
