### ISSUE TITLE
Typo in https://fasttext.cc/docs/en/pretrained-vectors.html

### ISSUE THREAD

**Issue by ToonTalk** [facebookresearch/fastText#615]
Note that the ']' is part of the href below so the link doesn't work

<p>Please note that a newer version of multi-lingual word vectors are available at: [<a href="https://fasttext.cc/docs/en/crawl-vectors.html]">https://fasttext.cc/docs/en/crawl-vectors.html]</a>.</p>

**Comment by EdouardGrave** [comment]
Hi @ToonTalk,

Thank you for reporting this issue. This should be fixed now.

Best,
Edouard.
