### ISSUE TITLE
 conflict with pytorch

### ISSUE THREAD

**Issue by techkang** [facebookresearch/fastText#619]
It seems that fastText is conflict with pytorch.

My code is simply as follow:
`
import fastText
import torch
`
and I get:
`bash: 行 1: 15992 段错误               env "PYTHONUNBUFFERED"="1" "PYTHONPATH"="/root/.pycharm_helpers/pycharm_matplotlib_backend:/root/fastText:/root/fastText/ae:/root/fastText/temp" "PYCHARM_HOSTED"="1" "JETBRAINS_REMOTE_RUN"="1" "PYCHARM_MATPLOTLIB_PORT"="51582" "PYTHONIOENCODING"="UTF-8" /root/anaconda3/bin/python -u /root/fastText/temp.py`

My fastText is latest version and pytorch is alos latest. I install pytorch via pip and command: 'pip install http://download.pytorch.org/whl/cpu/torch-0.4.1-cp36-cp36m-linux_x86_64.whl '. I  use anaconda3, pip 10.0.1 and python 3.6.5.

**Comment by techkang** [comment]
This information may be useful.
[environment]
- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): pip
- Build command you used (if compiling from source): No
- OS: CentOS Linux 7 (Core)
- PyTorch version: 0.4.1
- Python version: 3.6.5
- CUDA/cuDNN version: No
- GPU models and configuration: No
- GCC version (if compiling from source): 4.8.5
- CMake version: 3.6.2
- Versions of any other relevant libraries:
  - fasttext 0.8.22

**Comment by techkang** [comment]
I tried to open a new issue in https://github.com/pytorch/pytorch/issues/new and I faild. Sad.

**Comment by techkang** [comment]
## System info
Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: None

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
CMake version: version 3.6.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy (1.14.3)
[pip] numpydoc (0.8.0)
[pip] torch (0.4.1)
[pip] torchfile (0.1.0)
[pip] torchnet (0.0.4)
[pip] torchvision (0.2.1)
[conda] faiss-cpu                 1.3.0            py36_cuda0.0_1    pytorch
[conda] torch                     0.4.1                     <pip>
[conda] torchfile                 0.1.0                     <pip>
[conda] torchnet                  0.0.4                     <pip>
[conda] torchvision               0.2.1                     <pip>

**Comment by Celebio** [comment]
Hi @techkang ,
Could you please try to install fasttext with `pip install fasttext` and tell if you still observe the issue?

Best regards,
Onur

**Comment by edkek** [comment]
I'm experiencing this same problem with the latest version of fasttext and pytorch **on linux only** This doesn't seem to be a problem on Windows. Haven't tested on osx.

# How to Reproduce in Anaconda 
(anaconda isn't required but easier to reproduce)

```
conda create -n test_fasttext python=3.7
conda activate test_fasttext
conda install pytorch torchvision cudatoolkit=9.0 -c pytorch
pip install fasttext
python -c "import torch; import fasttext;"
```
You should get a segmentation fault. 

# Workaround
The work around described in [this issue](https://github.com/pytorch/pytorch/issues/9129#issuecomment-406063804) fixes this, however this isn't ideal for CI/CD environments, where simply installing from modified whl files isn't really sensible. The issue seems to be the problem described in the [same issue here](https://github.com/pytorch/pytorch/issues/9129#issuecomment-406049383)

> Basically if two libs both using pybind11 are compiled using incompatible compilers, this will happen (see pybind/pybind11#1262). By "incompatible" I mean e.g., gcc and clang, gcc < 4.9.2 and gcc >= 4.9.2. To avoid such issue as much as possible, we compile our release binaries with gcc 4.9.2. So if you are compiling fasttext with a gcc < 4.9.2 it will segfault. Can you look into the gcc version used?

What version of gcc is being used when deploying to PyPi? This seems like the most likely source of the problem.

**Comment by edkek** [comment]
@Celebio Any update on this issue?

**Comment by Raghava14** [comment]
Hi even I am facing the same issue any update ? Was anyone able to solve it ?
