### ISSUE TITLE
Precision and recall metrics

### ISSUE THREAD

**Issue by lcorbel** [facebookresearch/fastText#62]
Hi,

I've heard that it was now possible to get precision and recall values for the labels of our classifier, but I just can't find the option (maybe I'm dumb). Can you run me trough that process ?

Thanks

**Comment by EdouardGrave** [comment]
As of now, it is only possible to compute the overall precision and recall at k. We will probably add an option to compute these metrics for each label soon. In the meantime, you can use the `predict` functionality and compute these metrics with a third party library.

**Comment by lcorbel** [comment]
I see, yes it would be a valuable functionality in my opinion. Thanks for the quick answer, keep up the nice work :)
