### ISSUE TITLE
 can't download Korean bin version

### ISSUE THREAD

**Issue by sjl0110** [facebookresearch/fastText#620]
I am keep trying but it doesn't work. 

AccessDeniedAccess 
DeniedF70B4891B17F067090j4X/MZnmbTG3OT5kEg/nf6fHC2UIqCQaxkMANbj3gVyqO3zXf6hSxpEnFGuikoBno2yI0rFsQ=

This is the message I got.
Can anyone help me?

**Comment by martin0258** [comment]
Also cannot download Chinese bin from https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki.zh.zip

I'm guessing it's the same problem so leaving a comment here instead of opening a new issue.

Error message below
```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>32157D89915A6E13</RequestId>
<HostId>
uXmeGcKfqAbK1uCzfPBBsp27Wxsj810CL41RdjSXfq/gTXkRn6DQKMy1uJtEjfyMGzkacsGTO0c=
</HostId>
</Error>
( function(){ window.SIG_EXT = {}; } )()
```

**Comment by dcsan** [comment]
yep, I was about to notify the same.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>93AD9744BF00D428</RequestId><HostId>LKwAJU2TFPh7jRvMre7FE56J+XRwm2lBOjPp2Y1dGT1Y3liotPaPYdp1KZy/X4u9Sbdh1C+55oA=</HostId></Error>%
```

**Comment by piotr-bojanowski** [comment]
Hi all,

This was due to read permission being set wrong in AWS. It should be solved by now.

Thanks a lot for pointing that out!

Best,

Piotr

**Comment by dcsan** [comment]
working now, thanks for fixing!

**Comment by sjl0110** [comment]
Thanks, Korean works as well!
