### ISSUE TITLE
pretrained vector files not available on AWS

### ISSUE THREAD

**Issue by dcsan** [facebookresearch/fastText#627]
Perhaps you have a build process, but the files here have been inaccessible for the last few days

https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki.zh.zip

```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>451BAA8490BE509E</RequestId>
<HostId>
ehXVKjnlrCNNSmcC0e4EuC1KlZGm4MhBj8ncgkqyBKBEyBBc2kZO94BGrXRQF/fR3VsvJpI4TBw=
</HostId>
</Error>
```

**Comment by juice500ml** [comment]
Same problem for Korean also.
Pretrained wikipedia bin+text
https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki.ko.zip

**Comment by piotr-bojanowski** [comment]
Hi,

This was already mentioned in #620 and should be fine now.
Thanks a lot for pointing this out!

Best,

Piotr
