### ISSUE TITLE
what dimensions are the Supervised models vectors?

### ISSUE THREAD

**Issue by dcsan** [facebookresearch/fastText#628]
I'm trying to use the files here
https://fasttext.cc/docs/en/supervised-models.html

eg the sogounews.bin archive.

I get the error below.

```
./bin/fastText/fasttext supervised -input ./data/ignored/training/label-data.txt \
 -output ./data/ignored/training/labels-model \
  -pretrainedVectors ./data/ignored/common/sogou_news.bin \ 
 -wordNgrams 2 -minn 2 -wordNgrams 5 -neg 10 -loss hs -verbose 0 -thread 4 \
 -dim 10

Dimension of pretrained vectors does not match -dim option
```

the last param is the important one. checking their classifier file

https://github.com/facebookresearch/fastText/blob/master/classification-results.sh#L91

it looks like they were trained with `-dim 10` 
(this seems very low dimensionality...)

any case I tried `-dim 10`  but get that error still.

So I'm wondering what else I could try (gave it a shot at various other dims but still no luck)

```
  ./fasttext supervised -input "${DATADIR}/${DATASET[i]}.train" \
    -output "${RESULTDIR}/${DATASET[i]}" -dim 10 -lr "${LR[i]}" -wordNgrams 2 \
    -minCount 1 -bucket 10000000 -epoch 5 -thread 4 > /dev/null
  ./fasttext test "${RESULTDIR}/${DATASET[i]}.bin" \
    "${DATADIR}/${DATASET[i]}.test"
```

**Comment by dcsan** [comment]
when I use the same model file to `print-sentence-vectors` I do indeed get 10 vectors as a result:

```
bin/fastText/fasttext print-sentence-vectors ./data/ignored/common/sogou_news.bin < data/test.txt

2.5963 -0.57814 -0.68345 1.0774 -1.409 -0.086598 -1.661 -0.27923 0.061441 -0.32467
```

so I'm wondering what else might not match?

**Comment by dcsan** [comment]
am i correct in thinking that those supervised models can be used like word vectors as the `pretrainedVectors` param?

**Comment by a11apurva** [comment]
Hi @dcsan , can you try this?
Open the .bin file using gensim's wordvec utilities and save it as a text file. Then you can see the content and try to figure out whats wrong.

**Comment by EdouardGrave** [comment]
Hi @dcsan,

The problem comes from the fact that it is not possible to use models in binary format with the `pretrainedVectors` command line option. This option can only be used with models in text format. One potential solution is to dump the binary model in text format, for example by using the python script [bin_to_vec.py](https://github.com/facebookresearch/fastText/blob/master/python/doc/examples/bin_to_vec.py).

Best,
Edouard.
