### ISSUE TITLE
Skipgram or CBOW?

### ISSUE THREAD

**Issue by wadhwasahil** [facebookresearch/fastText#632]
Can anybody tell whether these  models https://fasttext.cc/docs/en/english-vectors.html are based on skip-gram or CBOW methology?

**Comment by EdouardGrave** [comment]
Hi @wadhwasahil,

These models are based on the CBOW methodology, with position weights. Please see section 2.2 of https://arxiv.org/abs/1712.09405 or section 3 (CBOW) of https://arxiv.org/abs/1802.06893 for more details of CBOW with position weights.

Best,
Edouard.

**Comment by wadhwasahil** [comment]
Do you intend to open source the code for generating such models?
