### ISSUE TITLE
Problem when building fasttext on linux mint 19

### ISSUE THREAD

**Issue by EstevaoCostaG3** [facebookresearch/fastText#636]
I'm getting the following problem when I try to use the "make" command on fastText directory that I just downloaded. Help me please.

c++ -pthread -std=c++0x -march=native -O3 -funroll-loops -c src/args.cc
make: c++: Command not found
Makefile:22: recipe for target 'args.o' failed
make: *** [args.o] Error 127

**Comment by EstevaoCostaG3** [comment]
I've tried it and got the following error: 
g++ -pthread -std=c++0x -march=native -O3 -funroll-loops -c src/args.cc
make: g++: Command not found
Makefile:22: recipe for target 'args.o' failed
make: *** [args.o] Error 127

**Comment by bataB95** [comment]
I had the same problem, if anyone has discovered the solution ?

**Comment by willianpaixao** [comment]
You need to install C++ compiler before compiling _fasttext_. Try:

`sudo apt-get update && sudo apt-get install g++` then run `make` again.

**Comment by ishaanasur** [comment]
> You need to install C++ compiler before compiling _fasttext_. Try:
> 
> `sudo apt-get update && sudo apt-get install g++` then run `make` again.

This worked for me, Thanks :)

**Comment by willianpaixao** [comment]
Hi @EstevaoCostaG3 if that works for you, could you please close the issue?

**Comment by EstevaoCostaG3** [comment]
@willianpaixao , actually I haven't been able to solve this issue, since I didn't needed to use FastText anymore
