### ISSUE TITLE
"Encountered NaN" code improvement ??

### ISSUE THREAD

**Issue by yunhenk** [facebookresearch/fastText#638]
I encounted  this problem: **"terminate called after throwing an instance of 'std::runtime_error' what(): Encountered NaN."** There seems have been issues alike: #465, #385. After searching the code, it seems the problem comes from these code segments:

matrix.cc

```cpp
real Matrix::dotRow(const Vector& vec, int64_t i) const {
  assert(i >= 0);
  assert(i < m_);
  assert(vec.size() == n_);
  real d = 0.0;
  for (int64_t j = 0; j < n_; j++) {
    d += at(i, j) * vec[j];
  }
  if (std::isnan(d)) {
    throw std::runtime_error("Encountered NaN.");
  }
  return d;
}
```

```cpp
real Matrix::l2NormRow(int64_t i) const {
  auto norm = 0.0;
  for (auto j = 0; j < n_; j++) {
    norm += at(i, j) * at(i, j);
  }
  if (std::isnan(norm)) {
    throw std::runtime_error("Encountered NaN.");
  }
  return std::sqrt(norm);
}
```
I wonder if these code segments can be improved.Thanks.

**Comment by EdouardGrave** [comment]
Hi @yunhenk,

Thank you for raising this issue!

Most of the time, NaNs appear when the learning rate is to high, and the training diverges. In that case, the solution is to reduce the learning rate. We'll improve the error messages, and try to improve the handling of instability during training.

Best,
Edouard.

**Comment by hafiz031** [comment]
@EdouardGrave still gives the same error without any handling :( ...also there are other cases I have found where this problem can happen: https://github.com/facebookresearch/fastText/issues/385#issuecomment-985032155

This is making `FastText` unreliable to be used in production environment where we cannot explicitly check and modify codebase from backend every time.
