### ISSUE TITLE
Unpickling

### ISSUE THREAD

**Issue by Nikita-Rao24** [facebookresearch/fastText#640]
Hi,
I have downloaded your pre trained word embedding model for french as I am doing sentiment analysis for french data
But when I am trying to load that model in my code , I am getting unpickling error:could not find MARK

Can you help solve this issue.
Thank you

**Comment by EdouardGrave** [comment]
Hi @Nikita-Rao24,

You cannot use pickle to load the model in python. When using the model in binary format, you can load the model using our python bindings with:
```python
from fastText import load_model
fasttext_model = load_model(args.model)
```
Please see the [python folder](https://github.com/facebookresearch/fastText/tree/master/python) for more information about our bindings.


You can also use the pre-trained models in text format, and load these in python using:
```python
import io

def load_vectors(fname):
    fin = io.open(fname, 'r', encoding='utf-8', newline='\n', errors='ignore')
    n, d = map(int, fin.readline().split())
    data = {}
    for line in fin:
        tokens = line.rstrip().split(' ')
        data[tokens[0]] = [float(x) for x in tokens[1:]]
    return data
```

Best,
Edouard.
