### ISSUE TITLE
How the bucket size affects the model size?

### ISSUE THREAD

**Issue by creat89** [facebookresearch/fastText#641]
Hello,

I'd like to know how the size of the bucket affects the model size. I've seen that the larger the bucket, the larger the model. But, how or why is this happening? If I remember well, the bucket is used to increase the size of the matrix that it is used for the dictionary, but apart from what are the other effects on the dictionary.

Regards,
Creat89

**Comment by EdouardGrave** [comment]
Hi @creat89,

The size of the model will increase linearly with the number of buckets. The size of the input matrix is `DIM x (VS + BS)`, where `VS` is the size of the vocabulary and `BS` is the number of buckets. The number of buckets does not have other influence on the model size.

The buckets are used for hashed features (such as character ngrams or word ngrams), which are used in addition to word features. In the input matrix, each word is represented by a vector, and the additional ngram features are represented by a fixed number of vectors (which corresponds to the number of buckets).

Best,
Edouard.
