### ISSUE TITLE
-pretrainedVectors is not supported with Python API?

### ISSUE THREAD

**Issue by ZichaoHuang** [facebookresearch/fastText#642]
According to [https://github.com/facebookresearch/fastText/blob/master/python/fastText/FastText.py#L255](https://github.com/facebookresearch/fastText/blob/master/python/fastText/FastText.py#L255), `-pretrainedVectors` is not supported for text classification.

How can I load pretrained word embeddings for text classification with fastText Python API?

**Comment by EdouardGrave** [comment]
Hi @ZichaoHuang,

This was fixed recently (see the merged PR #529), and we just forget to remove this comment. You can use the `pretrainedVectors` option from the python bindings.

Best,
Edouard.
