### ISSUE TITLE
Window size

### ISSUE THREAD

**Issue by BehroozMansouri91** [facebookresearch/fastText#643]
Is there a way to define a bigger window size for some special words? Can we change window size dynamically?

**Comment by Celebio** [comment]
Hi @BehroozMansouri91 ,
Unfortunately there is not a way to specify window size for some special words from the API.

However it is fairly easy to modify the code to do that. You can modify [here](https://github.com/facebookresearch/fastText/blob/master/src/fasttext.cc#L344) (cbow) or [here](https://github.com/facebookresearch/fastText/blob/master/src/fasttext.cc#L362) (skipgram) to set the variable `boundary` for a specific word (you will need the `wordId` of your word, you can use `dict_->getId` / `dict_->getWord` to do the conversion).

Hope it helps.

Best regards,
Onur

**Comment by 1049451037** [comment]
Hi, I have another question about window size. What will happen if window size is bigger than the document length? Will that document still make sense?

**Comment by Celebio** [comment]
Hi @1049451037 ,
In fasttext, each line is considered as an independent document. This means that two words appearing on different lines will never be considered as appearing in the same context. So if some of your lines are shorter than the context window size, the context window will just be truncated.

Regards,
Onur

**Comment by lengockyquang** [comment]
hi @Celebio , in list of options, the default context window is 5, so does it mean with current word at position t, we will get context of current word by t-5 and t+5 ?
