### ISSUE TITLE
Duplicate words in Japanese embedding cc.ja.300.vec

### ISSUE THREAD

**Issue by bvhinkle** [facebookresearch/fastText#648]
There are many duplicate words in the pretrained embedding file for Japanese cc.ja.300.vec downloadable from https://fasttext.cc/docs/en/crawl-vectors.html. For example, | appears with 23 distinct vectors.
There may be bugs in either how dictionaries are stored or in how they are written to ".vec" files.

**Comment by EdouardGrave** [comment]
Hi @bvhinkle,

Thank you for raising this issue!

We will upload a new version of the models in text format with this issue fixed.

Best,
Edouard

**Comment by piotr-bojanowski** [comment]
Hi @bvhinkle ,

The updated models have been uploaded.

Best,

Piotr
