### ISSUE TITLE
BSD+Patents License

### ISSUE THREAD

**Issue by jkmarz** [facebookresearch/fastText#650]
fastText is currently licensed as BSD + Patents clause.

Last year there was a huge discussion in the OSS community regarding this license, with some organizations going so far as to ban the use of any projects under this license. Ultimately Facebook decided to change the license on a number of its projects (the most notable being React) to solve this issue. Please see the following for reference:
https://meshedinsights.com/2017/07/16/apache-bans-facebooks-license-combo

https://medium.com/@raulk/if-youre-a-startup-you-should-not-use-react-reflecting-on-the-bsd-patents-license-b049d4a67dd2

https://code.fb.com/web/relicensing-react-jest-flow-and-immutable-js

Is there any plan to follow suit and change the license of fastText to something else?

**Comment by EdouardGrave** [comment]
Hi @jkmarz,

Thank you for raising this issue. We recently landed a commit to re-license fastText to the MIT license.

Best,
Edouard.

**Comment by jkmarz** [comment]
That’s terrific to hear!
