### ISSUE TITLE
Is it possible to obtain the IN- OUT embeddings using this API? 

### ISSUE THREAD

**Issue by PSanni** [facebookresearch/fastText#654]
Hi, I can obtain IN and OUT(syn0 & syn1) embeddings using gensim. 
https://radimrehurek.com/gensim/models/fasttext.html#gensim.models.fasttext.FastText.syn1

is it possible to obtain the same using this Python wrapper? 

Thanks.

**Comment by EdouardGrave** [comment]
Hi @PSanni,

Thank you for raising this issue!

Yes, it is possible to obtain the input and output parameters with our Python wrapper. To do this, please use the methods `get_input_matrix` and `get_output_matrix` (see [FastText.py#L150](https://github.com/facebookresearch/fastText/blob/master/python/fastText/FastText.py#L150)).

Best,
Edouard.

**Comment by PSanni** [comment]
Thanks, @EdouardGrave

But in this case, it just returns the full output matrix. There is no inbuilt function to get a single word vector from the output matrix.  Do you know how this can be done?
