### ISSUE TITLE
Adding the bin file to wiki-news-300d-1M-subword.vec.zip

### ISSUE THREAD

**Issue by KurtJanssensCRW** [facebookresearch/fastText#656]
In wiki-news-300d-1M-subword.vec.zip there is no bin file.
This means that we cannot use the subword information.
Would it be possible to add this?
Many thanks!

**Comment by EdouardGrave** [comment]
Hi @KurtJanssensCRW,

The binary model is available at the following URL: https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki-news-300d-1M-subword.bin.zip.

Best,
Edouard.

**Comment by nzw0301** [comment]
The link, https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki-news-300d-1M-subword.bin.zip, is unavailable now. The current link is https://dl.fbaipublicfiles.com/fasttext/vectors-english/wiki-news-300d-1M-subword.bin.zip.

**Comment by aliakhtar** [comment]
Any reason why the .bin file can't be included in the official .zip file? Its sketchy to download it from a random URL - although thanks for sharing it as a workaround
