### ISSUE TITLE
Compile error with commit fabb04e

### ISSUE THREAD

**Issue by zooplankton** [facebookresearch/fastText#66]
Using gcc 4.9.2

PS 09/01/2016 15:30:03> mingw32-make.exe fasttext
...
c++ -pthread -std=c++0x args.o dictionary.o matrix.o vector.o model.o utils.o src/fasttext.cc -o fasttext
In file included from src/fasttext.cc:10:0:
src/fasttext.h:32:5: error: 'clock_t' does not name a type
     clock_t start;
     ^
src/fasttext.cc: In member function 'void FastText::printInfo(real, real)':
src/fasttext.cc:96:27: error: 'start' was not declared in this scope
   real t = real(clock() - start) / CLOCKS_PER_SEC;
                           ^
src/fasttext.cc: In member function 'void FastText::train(std::shared_ptr<Args>)':
src/fasttext.cc:273:3: error: 'start' was not declared in this scope
   start = clock();
   ^
Makefile:40: recipe for target 'fasttext' failed
mingw32-make: *** [fasttext] Error 1

Problem solved by including time.h before fasttext.h in fasttext.cc or just move the include to fasttext.h

**Comment by EdouardGrave** [comment]
This should be fixed now.
