### ISSUE TITLE
How to build fastText in windows10

### ISSUE THREAD

**Issue by momo1986** [facebookresearch/fastText#666]
I try to compile and install it in win10.
However，during the compilation, errorC2039, errorC3861 and errorC2512 reported. 
The log is in Chinese.
![image](https://user-images.githubusercontent.com/34225874/47138947-40244100-d2ed-11e8-9634-f9002844f44b.png)
It makes me agony, how to resolve the problem?

**Comment by mbednarski** [comment]
Try to add

#include <string>

in productquantizer.cc

**Comment by mohammedayub44** [comment]
@momo1986  I'm trying to replicate it on windows too. If you could please send the summary steps you used for this. It would really save me a lot of time.

Thanks !
Mohammed Ayub

**Comment by Celebio** [comment]
Hi @momo1986 , @mbednarski 
We fixed the missing include issue in 58fe650b1da62f2a9cd96db0b2b69f3eeda66966.

Thank you for your help.
Best regards,
Onur
