### ISSUE TITLE
If I want to improve the training speed, what I should do in hardware?

### ISSUE THREAD

**Issue by 0x0004** [facebookresearch/fastText#668]
I know that using the '-hs' parameter can speed up the training.

If I want to improve the training speed, what I should do in hardware?

Such as  increasing the number of cpu cores, increasing the cpu main frequency, or increasing the memory bandwidth?

I hope to learn some specific details.

Thank you :)

**Comment by 0x0004** [comment]
@Celebio

**Comment by 0x0004** [comment]
@EdouardGrave

**Comment by EdouardGrave** [comment]
Hi @0x0004,

I guess the easiest way to improve the training speed is to augment the number of threads that are used by fastText. Thus, the more CPU cores, the better (the number of threads should be set to the number of "hardware threads" of your CPU. This is done with the `-thread` command line option). In the near future, we might also explore the use of SSE/AVX instructions to speed up matrix/vector operations (e.g. see PR #653).

Best,
Edouard.
