### ISSUE TITLE
fasttext python install is broken

### ISSUE THREAD

**Issue by bananemure** [facebookresearch/fastText#670]
Installing collected packages: fasttext
  Found existing installation: fasttext 0.8.22
    Uninstalling fasttext-0.8.22:
      Successfully uninstalled fasttext-0.8.22
  Running setup.py install for fasttext ... error
    Complete output from command /home/stephane.mbatchou/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-ao4zu5lm/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-0i7hapan/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/fastText
    copying python/fastText/FastText.py -> build/lib.linux-x86_64-3.6/fastText
    copying python/fastText/__init__.py -> build/lib.linux-x86_64-3.6/fastText
    creating build/lib.linux-x86_64-3.6/fastText/util
    copying python/fastText/util/util.py -> build/lib.linux-x86_64-3.6/fastText/util
    copying python/fastText/util/__init__.py -> build/lib.linux-x86_64-3.6/fastText/util
    creating build/lib.linux-x86_64-3.6/fastText/tests
    copying python/fastText/tests/test_configurations.py -> build/lib.linux-x86_64-3.6/fastText/tests
    copying python/fastText/tests/__init__.py -> build/lib.linux-x86_64-3.6/fastText/tests
    copying python/fastText/tests/test_script.py -> build/lib.linux-x86_64-3.6/fastText/tests
    running build_ext
    creating tmp
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/stephane.mbatchou/anaconda3/include/python3.6m -c /tmp/tmptqz75932.cpp -o tmp/tmptqz75932.o -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/stephane.mbatchou/anaconda3/include/python3.6m -c /tmp/tmpteix6vg9.cpp -o tmp/tmpteix6vg9.o -fvisibility=hidden
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    building 'fasttext_pybind' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/python
    creating build/temp.linux-x86_64-3.6/python/fastText
    creating build/temp.linux-x86_64-3.6/python/fastText/pybind
    creating build/temp.linux-x86_64-3.6/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/stephane.mbatchou/anaconda3/include/python3.6m -I/home/stephane.mbatchou/.local/include/python3.6m -Isrc -I/home/stephane.mbatchou/anaconda3/include/python3.6m -c python/fastText/pybind/fasttext_pybind.cc -o build/temp.linux-x86_64-3.6/python/fastText/pybind/fasttext_pybind.o -DVERSION_INFO="0.8.22" -std=c++14 -fvisibility=hidden
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    python/fastText/pybind/fasttext_pybind.cc: In lambda function:
    python/fastText/pybind/fasttext_pybind.cc:206:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 for (int32_t i = 0; i < vocab_freq.size(); i++) {
                                     ~~^~~~~~~~~~~~~~~~~~~
    python/fastText/pybind/fasttext_pybind.cc: In lambda function:
    python/fastText/pybind/fasttext_pybind.cc:220:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 for (int32_t i = 0; i < labels_freq.size(); i++) {
                                     ~~^~~~~~~~~~~~~~~~~~~~
    python/fastText/pybind/fasttext_pybind.cc: In lambda function:
    python/fastText/pybind/fasttext_pybind.cc:262:54: error: no matching function for call to ‘fasttext::FastText::predict(std::stringstream&, int32_t&, std::vector<std::pair<float, std::__cxx11::basic_string<char> > >&, fasttext::real&)’
                 m.predict(ioss, k, predictions, threshold);
                                                          ^
    In file included from python/fastText/pybind/fasttext_pybind.cc:11:0:
    src/fasttext.h:62:8: note: candidate: void fasttext::FastText::predict(int32_t, const std::vector<int>&, std::vector<std::pair<float, int> >&, fasttext::real) const
       void predict(
            ^~~~~~~
    src/fasttext.h:62:8: note:   no known conversion for argument 1 from ‘std::stringstream {aka std::__cxx11::basic_stringstream<char>}’ to ‘int32_t {aka int}’
    src/fasttext.h:108:8: note: candidate: void fasttext::FastText::predict(std::istream&, int32_t, bool, fasttext::real)
       void predict(std::istream&, int32_t, bool, real = 0.0);
            ^~~~~~~
    src/fasttext.h:108:8: note:   no known conversion for argument 3 from ‘std::vector<std::pair<float, std::__cxx11::basic_string<char> > >’ to ‘bool’
    python/fastText/pybind/fasttext_pybind.cc: In lambda function:
    python/fastText/pybind/fasttext_pybind.cc:284:56: error: no matching function for call to ‘fasttext::FastText::predict(std::stringstream&, int32_t&, std::vector<std::pair<float, std::__cxx11::basic_string<char> > >&, fasttext::real&)’
                   m.predict(ioss, k, predictions, threshold);
                                                            ^
    In file included from python/fastText/pybind/fasttext_pybind.cc:11:0:
    src/fasttext.h:62:8: note: candidate: void fasttext::FastText::predict(int32_t, const std::vector<int>&, std::vector<std::pair<float, int> >&, fasttext::real) const
       void predict(
            ^~~~~~~
    src/fasttext.h:62:8: note:   no known conversion for argument 1 from ‘std::stringstream {aka std::__cxx11::basic_stringstream<char>}’ to ‘int32_t {aka int}’
    src/fasttext.h:108:8: note: candidate: void fasttext::FastText::predict(std::istream&, int32_t, bool, fasttext::real)
       void predict(std::istream&, int32_t, bool, real = 0.0);
            ^~~~~~~
    src/fasttext.h:108:8: note:   no known conversion for argument 3 from ‘std::vector<std::pair<float, std::__cxx11::basic_string<char> > >’ to ‘bool’
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
  Rolling back uninstall of fasttext

**Comment by tombosc** [comment]
I get the same error.

**Comment by infotun2** [comment]
I have also the same problem :(

**Comment by jarvis-wu** [comment]
same problem

**Comment by wxjia** [comment]
same problem, too.

**Comment by elvirast** [comment]
the same problem  :(
after installing with cmake  I can't import the load_model function:

from fastText import load_model
ImportError: cannot import name 'load_model' from 'fastText' (unknown location)

**Comment by Celebio** [comment]
Hi @bananemure,
Thank you for reporting the issue! We will push a fix as soon as possible.
Regards.

**Comment by Celebio** [comment]
Could you please check 25c3994e17314f816b38ed86cda48526fadb3d94 ?

**Comment by infotun2** [comment]
> 
> 
> Could you please check [25c3994](https://github.com/facebookresearch/fastText/commit/25c3994e17314f816b38ed86cda48526fadb3d94) ?

Working fine ! thank you...

**Comment by jodotlearn** [comment]
not work for me...

error messages 
=========================================
Processing /root/fastText
Requirement already satisfied: pybind11>=2.2 in /usr/local/lib/python3.6/site-packages (from fasttext==0.8.22) (2.2.4)
Requirement already satisfied: setuptools>=0.7.0 in /usr/local/lib/python3.6/site-packages (from fasttext==0.8.22) (40.5.0)
Requirement already satisfied: numpy in /usr/local/lib64/python3.6/site-packages (from fasttext==0.8.22) (1.15.3)
Building wheels for collected packages: fasttext
  Running setup.py bdist_wheel for fasttext ... error
  Complete output from command /usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-zciqpnty/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-3igoboi8 --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  running build_ext
  gcc -pthread -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++1y -fPIC -I/usr/include/python3.6m -c /tmp/tmp7gn6x1yo.cpp -o tmp/tmp7gn6x1yo.o -std=c++14
  gcc: error: unrecognized command line option '-std=c++14'
  gcc -pthread -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++1y -fPIC -I/usr/include/python3.6m -c /tmp/tmpbnqitsoo.cpp -o tmp/tmpbnqitsoo.o -std=c++11
  gcc -pthread -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++1y -fPIC -I/usr/include/python3.6m -c /tmp/tmphu7d4yw9.cpp -o tmp/tmphu7d4yw9.o -fvisibility=hidden
  building 'fasttext_pybind' extension
  gcc -pthread -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++1y -fPIC -I/usr/local/include/python3.6m -I/root/.local/include/python3.6m -Isrc -I/usr/include/python3.6m -c python/fastText/pybind/fasttext_pybind.cc -o build/temp.linux-x86_64-3.6/python/fastText/pybind/fasttext_pybind.o -DVERSION_INFO="0.8.22" -std=c++11 -fvisibility=hidden
  python/fastText/pybind/fasttext_pybind.cc: In lambda function:
  python/fastText/pybind/fasttext_pybind.cc:206:53: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
               for (int32_t i = 0; i < vocab_freq.size(); i++) {
                                                       ^
  python/fastText/pybind/fasttext_pybind.cc: In lambda function:
  python/fastText/pybind/fasttext_pybind.cc:220:54: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
               for (int32_t i = 0; i < labels_freq.size(); i++) {
                                                        ^
  python/fastText/pybind/fasttext_pybind.cc: In lambda function:
  python/fastText/pybind/fasttext_pybind.cc:271:34: error: parameter declared 'auto'
                   [&d](const auto& prediction) {
                                    ^
  python/fastText/pybind/fasttext_pybind.cc: In lambda function:
  python/fastText/pybind/fasttext_pybind.cc:273:32: error: 'prediction' was not declared in this scope
                         std::exp(prediction.first),
                                  ^
  In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                   from /usr/include/c++/4.8.2/valarray:38,
                   from /usr/local/include/python3.6m/pybind11/stl.h:19,
                   from python/fastText/pybind/fasttext_pybind.cc:14:
  /usr/include/c++/4.8.2/bits/stl_algo.h: In instantiation of '_OIter std::transform(_IIter, _IIter, _OIter, _UnaryOperation) [with _IIter = __gnu_cxx::__normal_iterator<std::pair<float, int>*, std::vector<std::pair<float, int> > >; _OIter = std::back_insert_iterator<std::vector<std::pair<float, std::basic_string<char> > > >; _UnaryOperation = pybind11_init_fasttext_pybind(pybind11::module&)::__lambda81::__lambda82]':
  python/fastText/pybind/fasttext_pybind.cc:275:18:   required from here
  /usr/include/c++/4.8.2/bits/stl_algo.h:4926:33: error: no match for call to '(pybind11_init_fasttext_pybind(pybind11::module&)::__lambda81::__lambda82) (std::pair<float, int>&)'
    *__result = __unary_op(*__first);
                                   ^
  python/fastText/pybind/fasttext_pybind.cc:271:20: note: candidate is:
                   [&d](const auto& prediction) {
                      ^
  python/fastText/pybind/fasttext_pybind.cc:271:44: note: pybind11_init_fasttext_pybind(pybind11::module&)::__lambda81::__lambda82
                   [&d](const auto& prediction) {
                                              ^
  python/fastText/pybind/fasttext_pybind.cc:271:44: note:   candidate expects 0 arguments, 1 provided
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for fasttext
  Running setup.py clean for fasttext
Failed to build fasttext
Installing collected packages: fasttext
  Running setup.py install for fasttext ... error
    Complete output from command /usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-zciqpnty/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-jpgcisbi/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/fastText
    copying python/fastText/FastText.py -> build/lib.linux-x86_64-3.6/fastText
    copying python/fastText/__init__.py -> build/lib.linux-x86_64-3.6/fastText
    creating build/lib.linux-x86_64-3.6/fastText/util
    copying python/fastText/util/util.py -> build/lib.linux-x86_64-3.6/fastText/util
    copying python/fastText/util/__init__.py -> build/lib.linux-x86_64-3.6/fastText/util
    creating build/lib.linux-x86_64-3.6/fastText/tests
    copying python/fastText/tests/test_script.py -> build/lib.linux-x86_64-3.6/fastText/tests
    copying python/fastText/tests/__init__.py -> build/lib.linux-x86_64-3.6/fastText/tests
    copying python/fastText/tests/test_configurations.py -> build/lib.linux-x86_64-3.6/fastText/tests
    running build_ext
    gcc -pthread -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++1y -fPIC -I/usr/include/python3.6m -c /tmp/tmpyjeew3by.cpp -o tmp/tmpyjeew3by.o -std=c++14
    gcc: error: unrecognized command line option '-std=c++14'
    gcc -pthread -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++1y -fPIC -I/usr/include/python3.6m -c /tmp/tmphgr9o0tf.cpp -o tmp/tmphgr9o0tf.o -std=c++11
    gcc -pthread -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++1y -fPIC -I/usr/include/python3.6m -c /tmp/tmpadvk1djo.cpp -o tmp/tmpadvk1djo.o -fvisibility=hidden
    building 'fasttext_pybind' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/python
    creating build/temp.linux-x86_64-3.6/python/fastText
    creating build/temp.linux-x86_64-3.6/python/fastText/pybind
    creating build/temp.linux-x86_64-3.6/src
    gcc -pthread -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -std=c++1y -fPIC -I/usr/local/include/python3.6m -I/root/.local/include/python3.6m -Isrc -I/usr/include/python3.6m -c python/fastText/pybind/fasttext_pybind.cc -o build/temp.linux-x86_64-3.6/python/fastText/pybind/fasttext_pybind.o -DVERSION_INFO="0.8.22" -std=c++11 -fvisibility=hidden
    python/fastText/pybind/fasttext_pybind.cc: In lambda function:
    python/fastText/pybind/fasttext_pybind.cc:206:53: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 for (int32_t i = 0; i < vocab_freq.size(); i++) {
                                                         ^
    python/fastText/pybind/fasttext_pybind.cc: In lambda function:
    python/fastText/pybind/fasttext_pybind.cc:220:54: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 for (int32_t i = 0; i < labels_freq.size(); i++) {
                                                          ^
    python/fastText/pybind/fasttext_pybind.cc: In lambda function:
    python/fastText/pybind/fasttext_pybind.cc:271:34: error: parameter declared 'auto'
                     [&d](const auto& prediction) {
                                      ^
    python/fastText/pybind/fasttext_pybind.cc: In lambda function:
    python/fastText/pybind/fasttext_pybind.cc:273:32: error: 'prediction' was not declared in this scope
                           std::exp(prediction.first),
                                    ^
    In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                     from /usr/include/c++/4.8.2/valarray:38,
                     from /usr/local/include/python3.6m/pybind11/stl.h:19,
                     from python/fastText/pybind/fasttext_pybind.cc:14:
    /usr/include/c++/4.8.2/bits/stl_algo.h: In instantiation of '_OIter std::transform(_IIter, _IIter, _OIter, _UnaryOperation) [with _IIter = __gnu_cxx::__normal_iterator<std::pair<float, int>*, std::vector<std::pair<float, int> > >; _OIter = std::back_insert_iterator<std::vector<std::pair<float, std::basic_string<char> > > >; _UnaryOperation = pybind11_init_fasttext_pybind(pybind11::module&)::__lambda81::__lambda82]':
    python/fastText/pybind/fasttext_pybind.cc:275:18:   required from here
    /usr/include/c++/4.8.2/bits/stl_algo.h:4926:33: error: no match for call to '(pybind11_init_fasttext_pybind(pybind11::module&)::__lambda81::__lambda82) (std::pair<float, int>&)'
      *__result = __unary_op(*__first);
                                     ^
    python/fastText/pybind/fasttext_pybind.cc:271:20: note: candidate is:
                     [&d](const auto& prediction) {
                        ^
    python/fastText/pybind/fasttext_pybind.cc:271:44: note: pybind11_init_fasttext_pybind(pybind11::module&)::__lambda81::__lambda82
                     [&d](const auto& prediction) {
                                                ^
    python/fastText/pybind/fasttext_pybind.cc:271:44: note:   candidate expects 0 arguments, 1 provided
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-zciqpnty/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-jpgcisbi/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-zciqpnty/
