### ISSUE TITLE
Batch prediction is SLOW - it could have been vectorized at pybind c++ instead of python

### ISSUE THREAD

**Issue by bananemure** [facebookresearch/fastText#673]
https://github.com/facebookresearch/fastText/blob/25c3994e17314f816b38ed86cda48526fadb3d94/python/fastText/FastText.py#L137

1-Now python is using a FOR LOOP of predict_one to run batch prediction and is SLOW due to python for-loop. Can it be optimized directly inside c++ binding?

2- Also batch " \n check " can be optimized  with pandas series as a vectorized check.

**Comment by 0x0004** [comment]
if type(text) == list:  
    The predict_one is slow than multilinePredict too.

**Comment by 0x0004** [comment]
@Celebio

**Comment by Celebio** [comment]
Hi @bananemure , @0x0004 ,
I agree. I will consider putting back the "vectorized" version in C++. I would like to check some little things just before.

Regards,
Onur

**Comment by Celebio** [comment]
Hi @bananemure @0x0004 ,
Thank you for reporting the problem.
41a0f39dc7f51d1f61baae0266c12f43050835c4 should fix the issue.

Best regards,
Onur
