### ISSUE TITLE
Add build badges to the README.md

### ISSUE THREAD

**Issue by willianpaixao** [facebookresearch/fastText#674]
A very common practice in Github repositories is to add some self-generated images called badges, that makes easy for users to see the current state of development of the project, like build status, coverage, tests and etc.

Since the README.md already specifies that the project uses CircleCI, would be quick to add those badges. Follow a reference.

https://circleci.com/docs/2.0/status-badges/

Kind regards,
Willian Paixao

**Comment by Celebio** [comment]
Hi @willianpaixao ,
Thank you for suggesting this. We will consider it.

Regards,
Onur

**Comment by Celebio** [comment]
Hi @willianpaixao ,
The commit 4aee63d adds the badge.
Thank you for your suggestion.

Regards,
Onur
