### ISSUE TITLE
Creating Conda environment w/ fastText on Windows Failed

### ISSUE THREAD

**Issue by gdonoso94** [facebookresearch/fastText#675]
Hello,

I've been trying to build fastText within a Conda environment in Windows 10 and it is not working because it's missing the libraries:

#include \<string\>
#include \<cstring\>

Would it be possible to have them included in a, hopefully not far from now, commit? I'm building a pipeline and I cannot access the code manually during the process.

**Comment by Celebio** [comment]
Hi @gdonoso94 ,
Thank you for reporting the issue.
Could you please send the output of the failing commands?

Regards,
Onur
