### ISSUE TITLE
multithread and huffman tree

### ISSUE THREAD

**Issue by coderApes** [facebookresearch/fastText#680]
when train in a multithread way ,  dose every thread maintain their own huffman tree ?  if do, why ? Looking forward to your reply

**Comment by EdouardGrave** [comment]
Hi @coderApes,

Thank you for asking the question!

Yes, you are correct, each thread maintain their own Huffman tree. There is no particular reason for that, besides the fact that there is own model per thread, and the Huffman tree construction happens in the model class. We will refactor part of the code in the near future, and are likely to fix such issues in the process.

Best,
Edouard
