### ISSUE TITLE
fixing embedding for training classifier

### ISSUE THREAD

**Issue by wangsiheaaaa** [facebookresearch/fastText#681]
I have a set of embeddings from different method and want to do some ablation study using fasttext's rapid classification training. One thing I want to do is fixing the embedding and just updating the softmax classifier for comparing the embeddings. The 'lr' parameter seems to work on both. Does fasttext have an option that supports this? If not I think I need to check the source code.

**Comment by EdouardGrave** [comment]
Hi @wangsiheaaaa,

Thank you for asking this question!

As of now, fastText does not have a command line option to support this. However, there is a very simple modification of the code that will allow this. Just comment out the three lines 259-261 in the method `update` of the class `Model`:
```c++
  for (auto it = input.cbegin(); it != input.cend(); ++it) {
    wi_->addRow(grad_, *it, 1.0);
  }
```
These three lines perform the update of the word embeddings.

Best,
Edouard.
