### ISSUE TITLE
fasttext embedding all vectors in .vec file are -nan

### ISSUE THREAD

**Issue by Aohailin** [facebookresearch/fastText#687]
Command:
./fastText-0.1.0/fasttext skipgram -input train -output fasttext -minCount 17 -wordNgrams 1 -minn 2 -maxn 4 -t 0.00001 -lr 0.1 -dim 200 -ws 3 -epoch 30 -loss hs -thread 8 -bucket 5000000

Here is the problem,
When i train fasttext embedding model using a large corpus which is 130G, problem is all vec item in .vec file is nan, when load the model by pyfasttext, get all -nan vectors by calling get_numpy_vector() api and get all 0 vectors by calling get_numpy_sentence_vector()

Besides, i change MAX_VOCAB_SIZE to 100m for larger vocab and recompile source file #602

PS: when i train fasttext embedding model by the head 10w lines of train file, the moel generated is ok

**Comment by EdouardGrave** [comment]
Hi @Aohailin,

Thank you for reporting this issue!

The learning rate you are using (`0.1`) is probably to high, leading to divergence during training and NaNs in the learned model. I suggest reducing the learning rate to the default of `0.05` or even lower, to `0.025`. This should fix the problem. Please re-open the issue if not.

Best,
Edouard.
