### ISSUE TITLE
Set training parameters with python library

### ISSUE THREAD

**Issue by AnastasiaMalysheva** [facebookresearch/fastText#691]
Hello. I'm trying to train fasttext model using python library like this:

model = fasttext.skipgram('train_fasttext_corpus_space.txt', 'model')

But it seems like I can't set parameters like min_count, lr and others with this interface. Do they have different parameters names? I couldn't find any documentation about it.

**Comment by Celebio** [comment]
Hi @AnastasiaMalysheva ,
It looks like you are using the [pypi](https://pypi.org/project/fasttext/) version of the library.
The interface seems to allow you to specify those parameters : https://github.com/pyk/fastText.py/blob/master/fasttext/fasttext.pyx#L232

Can you try something like this?
`model = fasttext.skipgram('train_fasttext_corpus_space.txt', 'model', min_count=5, lr=0.5)` ?

Please note that the actual pypi interface will be soon deprecated and replaced by the official [python bindings](https://github.com/facebookresearch/fastText/tree/master/python). We will try to keep compatibility as much as we can but if you have the possibility to use the github version now that would be great.

Best regards,
Onur

**Comment by wwfwwf** [comment]
Thanks anyway ! I solved the problem by referring to the website:https://github.com/pyk/fastText.py/blob/master/fasttext/fasttext.pyx#L232
and the loss should be set to 'hs' , not hs. dizzy，dizzy， dizzy！
Best regards,
wwf

**Comment by wwfwwf** [comment]
example:设置min_count=5

**Comment by Celebio** [comment]
Hi @AnastasiaMalysheva , @wwfwwf ,
[Pypi version](https://pypi.org/project/fasttext/) is now in line with [github version](https://github.com/facebookresearch/fastText/tree/master/python), as described in [this blog post](https://fasttext.cc/blog/2019/06/25/blog-post.html).

The parameter names are [compatible](https://fasttext.cc/blog/2019/06/25/blog-post.html#parameters) with the unofficial version which used snake case.

I am closing this issue. Feel free to re-open it if you have a question.

Best regards,
Onur

**Comment by Zachary4biz** [comment]
Hi @Celebio  ,
**how can i set MAX_LINE_SIZE in pypi version?**
I get some long text to classify, 2048 should be enough. 
AND, just to be sure, 2048 means 2048 tokens not the str-length, right?

**Comment by Celebio** [comment]
Hi @Zachary4biz ,
In order to change `MAX_LINE_SIZE`, you have to compile again after changing the value in the [source code](https://github.com/facebookresearch/fastText/blob/master/src/dictionary.h#L37).

And you are right, this is the [number of tokens](https://github.com/facebookresearch/fastText/blob/master/src/dictionary.cc#L371).

Best regards,
Onur
