### ISSUE TITLE
Weird results with quantization

### ISSUE THREAD

**Issue by rjsbhatia** [facebookresearch/fastText#692]
I am seeing some strange results after quantizing a model. I am not sure whats causing this or if this is the expected behavior. 

I want to be able to find similar words using the word vector model provided. I am quantizing the model to reduce the size of the bin file. 

Using the model bin file for english from https://fasttext.cc/docs/en/crawl-vectors.html

If i do 

./fasttext nn en2/cc.en.300.bin 
Query word? dog
dogs 0.846346
puppy 0.787301
pup 0.769224
canine 0.743528
pet 0.733371
doggie 0.73265
dog-- 0.724239
beagle 0.723118
dachshund 0.722993
cat 0.707861

This seems to work as expected. 

i quantized the model by running these commands

./fasttext supervised -input en/cc.en.300.vec -output en/cc.en.300
./fasttext quantize -input en/cc.en.300.vec -output en/cc.en.300

Doing the same thing with the bin file generated by supervised i do not get the same results

 ./fasttext nn en/cc.en.300.bin 
Query word? dog
Favoring 0.457077
cirrus 0.44418
slow-roast 0.43489
osteotome 0.429941
12,560 0.428151
Zoilos 0.425369
568-B 0.425115
mario 0.424975
APGI 0.421373
10,172 0.420792

Using the quantized model produces this
./fasttext nn en/cc.en.300.ftz 
Query word? dog
Favoring 0.455203
cirrus 0.440182
slow-roast 0.439381
osteotome 0.437597
568-B 0.425945
Zoilos 0.423766
Open. 0.421278
APGI 0.420266
Gher 0.419723
18.07 0.41881

Shouldn't the quantize model be able to produce same results as the original bin file?

**Comment by Celebio** [comment]
Hi @rjsbhatia ,
Thank you for your message.

For the moment, we can't quantize word-vector models, only classification models.

Please also note that `.vec` files are output files, not input files. 

Regards,
Onur
