### ISSUE TITLE
multithreading Dictionary::readFromFile

### ISSUE THREAD

**Issue by emesday** [facebookresearch/fastText#695]
Even if `-thread` is greater than 1, we can not get the benefits when creating a dictionary. How about improving this part?

**Comment by mskimm** [comment]
The above approach does not look good, but I will share it.

This is done by
 - each thread has own Dictionary instance
 - each thread reads its part of the input file.
 - reduce the map results

This implementation is `about 2 times faster with -thread 20` but `about 1.5 times slower with -thread 2` on yfcc100m.

This seems very sensitivity the cardinality of words.

**Comment by emesday** [comment]
stale
