### ISSUE TITLE
extract character embeddings

### ISSUE THREAD

**Issue by fermat97** [facebookresearch/fastText#696]
Hi, is that possible to train a model for character embeddings with fasttext, I mean a model for embedding 'a', 'b',....

**Comment by EdouardGrave** [comment]
Hi @fermat97,

Thank you for your question!

Using the `skipgram` model, it is possible to learn embeddings for character n-grams. The length of the n-grams can be set using the `-minn` and `-maxn` command line options. You can then obtain the corresponding embeddings using the python bindings, and in particular, the methods `get_subword_id` and `get_input_vector`. For example, to get the vector corresponding to the n-gram `an`, use
```python
model.get_input_vector(model.get_subword_id("an"))
```

Best,
Edouard.
