### ISSUE TITLE
Output vectors already pre-computed by using subword information?

### ISSUE THREAD

**Issue by mana-ysh** [facebookresearch/fastText#698]
Hi, I have some questions about the generated vector file `model.vec` after running word vector training scripts.

In the original paper[1], they calculate each word representation via summation of inner subword representations.
e.g) In the case n=3 and the vector of word "where", we calculate its vector as the summation of the representations of "<wh", "whe", "her", "ere", "re>" and  the word itself "\<where\>", I think.

How this tool generates the vector of the entry "where" in `model.vec` ?
I mean the output vector in `model.vec` is already summed over inner subword representations? or just output of the representation of "\<where\>" itself?

I'm confused with these calculations because there seems to be no entry word which contains the special suffix/prefix characters ("<" and ">").

Thank you in advance.

[1]  P. Bojanowski*, E. Grave*, A. Joulin, T. Mikolov, Enriching Word Vectors with Subword Information.

**Comment by Celebio** [comment]
Hi @mana-ysh ,
The `.vec` file contains the representation of words seen in the train file. Those representations include subword information. For more insight you can have a look at the function [`FastText::saveVectors`](https://github.com/facebookresearch/fastText/blob/master/src/fasttext.cc#L88), (and specially the call to the [`FastText::getWordVector`](https://github.com/facebookresearch/fastText/blob/master/src/fasttext.cc#L66) which gathers subword information).

Best regards,
Onur

**Comment by mana-ysh** [comment]
Hi @Celebio,
Thank you for quick response and clarifying.
I can understand its behavior clearly!
