### ISSUE TITLE
why signed no module named 'fastText'?

### ISSUE THREAD

**Issue by FankLi** [facebookresearch/fastText#706]
I use python，when:
from fastText import train_unsupervised

I have impotred Cpython and fasttext.

**Comment by Celebio** [comment]
Hi @jzlixiao ,
Are you using the [github](https://github.com/facebookresearch/fastText/tree/master/python) version or the [pypi](https://pypi.org/project/fasttext/) version?

The github version should allow you to use `from fastText import train_unsupervised`.

Regards,
Onur

**Comment by jzlixiao** [comment]
hi，@Celeio
How to use?clone code or pip install ***?

**Comment by jzlixiao** [comment]
> Hi @jzlixiao ,
> Are you using the [github](https://github.com/facebookresearch/fastText/tree/master/python) version or the [pypi](https://pypi.org/project/fasttext/) version?
> 
> The github version should allow you to use `from fastText import train_unsupervised`.
> 
> Regards,
> Onur

Hi,I use pip install fasttext to get this.

**Comment by jzlixiao** [comment]
@Celebio @EdouardGrave Hi,I use pip install fasttext to get this，but error.why not ?
thank you for repy

**Comment by Celebio** [comment]
Hi @jzlixiao ,
Can you try this?

Uninstall any fastText version you have : 
```
pip uninstall -y fastText
pip uninstall -y fasttext
```
Then build python bindings from a fresh copy of fastText : 
```
git clone git@github.com:facebookresearch/fastText.git
cd fastText
pip install .
```

**Comment by jzlixiao** [comment]
Hi, @Celebio 
`pip install fasttext `
this function is well.But I still have doubts.I used this method which was ok three months ago,but not now.
Thanks!

**Comment by Celebio** [comment]
Hi @FankLi ,
[Pypi version](https://pypi.org/project/fasttext/) is now in line with [github version](https://github.com/facebookresearch/fastText/tree/master/python), as described in [this blog post](https://fasttext.cc/blog/2019/06/25/blog-post.html).

I hope it makes everything clear.

Thank you very much for your feedback.
Best regards,
Onur
