### ISSUE TITLE
Push to PyPi?

### ISSUE THREAD

**Issue by whiletruelearn** [facebookresearch/fastText#708]
It will be great if we can have the official version of the python binding pushed to PyPi. This will make the install process smooth and for everyone to use the official python binding instead of using projects such as [Pyfasttext](https://github.com/vrasneur/pyfasttext) and [Fasttext.py](https://github.com/salestock/fastText.py)

**Comment by vaughnkoch** [comment]
Also, I noticed that the latest git tag is v0.2.0, but the python setup.py code shows it as '0.8.22'.

**Comment by Celebio** [comment]
Hi @whiletruelearn , @vaughnkoch ,
[Pypi version](https://pypi.org/project/fasttext/) is now in line with [github version](https://github.com/facebookresearch/fastText/tree/master/python), as described in [this blog post](https://fasttext.cc/blog/2019/06/25/blog-post.html).

The python version is also synced with git repository tag, which is now [0.9.1](https://github.com/facebookresearch/fastText/releases/tag/v0.9.1)

Thank you very much for your feedback!

Best regards,
Onur
