### ISSUE TITLE
Empty vocabulary. Try a smaller -minCount value.

### ISSUE THREAD

**Issue by mikessoldier** [facebookresearch/fastText#71]
Hello!
I'm having a bit of trouble, because, i get this error each time i try to exec this:
`./fasttext supervised -input / -output data/train.txt -lr 0.025 -dim 100 -ws 5 -epoch 1 -neg 5 -loss ns -bucket 2000000 -minn 3 -maxn 6 -thread 4 -t 1e-4 -lrUpdateRate 100`
I have formated my data, almost exactly as you have in the **classification_example.sh**
`1	wallet	Give more sales to old clients`
If this is my fault, please, let me know where is my mistake

**Comment by EdouardGrave** [comment]
From the example you provided, it seems that you are mixing the -input and -output arguments and the useful options for the supervised and unsupervised settings. If you are trying to do classification, you should try:
`./fasttext supervised -input INPUT_FILE -output model -lr 0.5 -dim 10 -wordNgrams 2`
where `INPUT_FILE` is the training data (each label should start by the prefix `__label__`). fastText will write the model in the binary file `model.bin`

**Comment by mikessoldier** [comment]
Ok! thank you so much for your response! I'll try that.

**Comment by mikessoldier** [comment]
As I thought, I got it right, but I skipped the `__label__` part, and it didn't recognize any of them.
Thank you for your support!
