### ISSUE TITLE
predict probability greater than 1.0  on python interface

### ISSUE THREAD

**Issue by SeanLee97** [facebookresearch/fastText#718]
```python
from fastText import load_model

clf = load_model("model.bin")
labels, scores = clf.predict(datas)
```

Probability should not greater than 1.0, but I found some values in `scores` greater than 1.0 , for example 1.00000536, 1.00000978 ... 

In my chinese dataset number of labels is two, it is a binary-classification problem.

**Comment by EdouardGrave** [comment]
Hi @SeanLee97,

This is due to small numerical approximation errors. You can consider this probabilities to be equal to `1.0`.

Best,
Edouard.
