### ISSUE TITLE
Why is label size clipped to 32 characters?

### ISSUE THREAD

**Issue by bhoomit** [facebookresearch/fastText#720]
https://github.com/facebookresearch/fastText/blob/3c4a3ea5f59480377ad82ad39e7b8b4c10d29280/python/fastText/FastText.py#L134

```
if type(text) == list:
       text = [check(entry) for entry in text]
       predictions = self.f.multilinePredict(text, k, threshold)
       dt = np.dtype([('probability', 'float64'), ('label', '<U32')])
       result_as_pair = np.array(predictions, dtype=dt)
```

This is causing issue when label string length is > 32 characters

**Comment by EdouardGrave** [comment]
Hi @bhoomit,

Thank you for reporting this issue! We will fix it shortly.

Best,
Edouard.

**Comment by bhoomit** [comment]
Should I SEND a PR?

**Comment by EdouardGrave** [comment]
Sure. Does your fix work for any label length?

**Comment by bhoomit** [comment]
@edenbaus I tried this `('label', 'object')`. It works but not sure about the downside.

Else we can set really high value like 150. Unlikely to be larger than that. We have some 50 classes and the max length is about 80 characters.

**Comment by Celebio** [comment]
Hi,
I tested `object` dtype : 
- It keeps the entire label string
- `%timeit` in IPython measure shows no performance drop
- as we are converting the result with `tolist()`, we are keeping the backward type compatibility (we never returned `numpy.unicode_` but `unicode`)

So it looks like using `object` is the way to fix the issue. I will take care of that.

Thanks again for reporting the issue!

Best regards,
Onur

**Comment by bhoomit** [comment]
Glad that I could help :)
