### ISSUE TITLE
multiple label prefix in one line

### ISSUE THREAD

**Issue by congchan** [facebookresearch/fastText#728]
Hi, I would like to use single one data file for different label categories prediction tasks.

Say I make my data into this format :
__labelA__xxx __labelB__yyy sentence

If I wanna predict labelA task, simply pass train_supervised (Label ="LabelA"), will fasttext treat labelB as part of the sentence?

**Comment by karlek** [comment]
Yes, it would. Use separate files instead.

**Comment by EdouardGrave** [comment]
Hi @congchan,

Thank you for your question!

As indicated by @karlek, fastText will treat `labelB` as words. Thus, you should use separate files.

Best,
Edouard
