### ISSUE TITLE
How to correctly handle frequent words with no information for information retrieval?

### ISSUE THREAD

**Issue by ctrado18** [facebookresearch/fastText#729]
I use my own trained word vectors for information retrieval by avergaing all vectors for each sentence. Afterwards I calculate the cosine similiarity to find the associated text. Now it seems that it focues on irrelevant words like the word _costs_ in `How much costs a sunglass?`. The word costs appears very often than the word sunglasses. Now, it could be the case that the algorithm producing the vectros focuses too much on those words and giving  bad vectors, or, the way of avergaing is not adequate as the word costs is not within the right information text, such that information texts are preferred if they also contain the word costs. As such I need to dosome weighted averaging discounting more frequent words?

Or could it be better if I discount morefrequent words during training with `-t`?

**Comment by EdouardGrave** [comment]
Hi @ctrado18,

Thank you for your question!

I would suggest to do the following: (1) normalize the word vectors before averaging, (2) use a weighing scheme for the averaging, such as tf/idf, to reduce the influence of frequent words.

Discounting more frequent words during training with the option `-t` probably won't have much effect on the quality of retrieval.

Best,
Edouard.
