### ISSUE TITLE
Assertion failed on ./fasttext predict

### ISSUE THREAD

**Issue by spate141** [facebookresearch/fastText#73]
predict command failed!

> ./fasttext predict model.bin test.txt 
> 
> ```
> Assertion failed: (counts.size() == osz_), function setTargetCounts, file src/model.cc, line 188.
> Abort trap: 6
> ```

model train command was:

> ./fasttext supervised -input train.txt -output model -wordNgrams 4 -bucket 1000000 -thread 16
> 
> ```
> Read 4223M words
> Number of words:  16577869
> Number of labels: 25
> Progress: 100.0%  words/sec/thread: 375706  lr: 0.000000  loss: 0.169518  eta: 0h0m 
> ```

**Comment by EdouardGrave** [comment]
Are you using the latest version of fastText? Can you reproduce this on a smaller dataset? What compiler / os are you using?

Could you please print the size of `counts` and `osz_`, by replacing the assert with 
`std::cout << counts.size() << " " << osz_ << std::endl;`

**Comment by spate141** [comment]
> Latest version of fastText: Yes
> OS: MacOS X, 10.11.6
> compiler: gcc 7
> replacing assert with **std::cout << counts.size() << " " << osz_ << std::endl;**
 ```
25 0
Assertion failed: (A.n_ == vec.m_), function mul, file src/vector.cc, line 60.
Abort trap: 6
```

**Comment by EdouardGrave** [comment]
It seems that the output matrix is not loaded properly. What is the size of the `model.bin` file?

**Comment by spate141** [comment]
7.8 GB

**Comment by EdouardGrave** [comment]
In order to better understand what is happening, could please replace
`  input_->load(ifs);
  output_->load(ifs);`
in the function `FastText::loadModel` (lines 83 and 84 of `fasttext.cc`) by
`  input_->load(ifs);
  std::cout << input_->m_ << " " << input_->n_ << std::endl;
  std::cout << "ifs.good() " << ifs.good() << std::endl;
  std::cout << "ifs.eof()  " << ifs.eof() << std::endl;
  std::cout << "ifs.fail() " << ifs.fail() << std::endl;
  std::cout << "ifs.bad()  " << ifs.bad() << std::endl;
  output_->load(ifs);
  std::cout << output_->m_ << " " << output_->n_ << std::endl;
  std::cout << "ifs.good() " << ifs.good() << std::endl;
  std::cout << "ifs.eof()  " << ifs.eof() << std::endl;
  std::cout << "ifs.fail() " << ifs.fail() << std::endl;
  std::cout << "ifs.bad()  " << ifs.bad() << std::endl;`
Then, re-compile and re-run
`./fasttext predict model.bin test.txt`

Have you tried to fit smaller models on the same data (for example using a larger `-minCount` such as 50)? If yes, did you have similar issues?

Did you change the version of fastText between training and testing?

Would it be possible for you to share the trained model with us?

Thanks for your help!

**Comment by spate141** [comment]
Error: 
`Assertion failed: (A.n_ == vec.m_), function mul, file src/vector.cc, line 60.
Abort trap: 6`

```
15415554 100
ifs.good() 0
ifs.eof()  0
ifs.fail() 1
ifs.bad()  1
0 0
ifs.good() 0
ifs.eof()  0
ifs.fail() 1
ifs.bad()  1
199 0
```

Have you tried to fit smaller models on the same data (for example using a larger -minCount such as 50)? If yes, did you have similar issues?
- Yes, small model works perfectly.

Did you change the version of fastText between training and testing?
- No.

Would it be possible for you to share the trained model with us?
- Sorry, the model data is proprietary and I don't have the appropriate permission to share it.

Thanks.

**Comment by xiamx** [comment]
I also encountered this issue recently, my model is only 2GB. It was because I was running out of diskspace and `fasttext supervised` couldn't output the model entirely, and fails silently (still exited with code 0)

**Comment by spate141** [comment]
@xiamx I have the required disk space and memory to load the model (75GB disk space, and 30GB RAM)

**Comment by neosyon** [comment]
I also had the same issue when loading the binary English and German pretrained models provided in this repository. I'm using the last version of fasttext.

**Comment by lhoang29** [comment]
Same here, failed for both predict and test mode: fasttext: src/model.cc:203: void fasttext::Model::setTargetCounts(const std::vector<long int>&): Assertion `counts.size() == osz_' failed.
Aborted (core dumped)

**Comment by spate141** [comment]
Issue was solved with code update!

**Comment by sharathkumaraDS** [comment]
Spate141... 
I'm getting same issue..  What code updates you made.   I mean which file modified?
Please reply.. 

Sharath

**Comment by spate141** [comment]
@sharathkumaraDS That issue was solved with fastText library code update. Using the latest code resolved the issue.

**Comment by data-steve** [comment]
Im getting same error off a fresh github install this morning

Though for me, the error occurs when I'm using a modified version of the bash script in classification_result.sh to loop over data sets:

```
for i in {0..1}
do
  echo "Working on dataset ${DATASET[i]}"
  ./fasttext supervised -input "${DATADIR}/${DATASET[i]}.train" \
    -output "${RESULTDIR}/${DATASET[i]}" -lr "${LR[i]}" -wordNgrams 2 \
    -minCount 1 -bucket 10000000 -epoch 25 -thread 12  > /dev/null
  ./fasttext test "${RESULTDIR}/${DATASET[i]}.bin" \
    "${DATADIR}/${DATASET[i]}.test"
done
```
It'll run `test` on the first in the loop just fine and output the precision and recall. But on the next one and all there after, I get the following error when it comes to the `test` step, despite the `supervised` step still working:
```
fasttext: src/model.cc:226: void fasttext::Model::setTargetCounts(const std::vector<long int>&): Assertion `counts.size() == osz_' failed.
Aborted
```

Any suggestions?

**Comment by data-steve** [comment]
I think what happened for me is that I ran out of free space on my aws instance

**Comment by spate141** [comment]
@data-steve Thats the only reason I can think of, else the latest commit code solves such issues

**Comment by ofilip** [comment]
I hit the same issue on the latest fasttext. Problem happens when compression-related args are used: -cutoff 30000 -retrain -qnorm -qout -dsub 8. Without them, training works well.

**Comment by xentnex** [comment]
Faced the same problem with the latest code from github repos.

Model size is 50MB.

$ ./fasttext.exe nn kategori.sg.model.bin
assertion "counts.size() == osz_" failed: file "src/model.cc", line 226, function: void fasttext::Model::setTargetCounts(const std::vector<long int>&)
Aborted (core dumped)


Cygwin, Windows 10 pro, COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/lto-wrapper.exe
Hedef: x86_64-pc-cygwin
/cygdrive/i/szsz/tmpp/gcc/gcc-5.4.0-1.x86_64/src/gcc-5.4.0/configure --srcdir=/cygdrive/i/szsz/tmpp/gcc/gcc-5.4.0-1.x86_64/src/gcc-5.4.0 --prefix=/usr --exec-prefix=/usr --localstatedir=/var --sysconfdir=/etc --docdir=/usr/share/doc/gcc --htmldir=/usr/share/doc/gcc/html -C --build=x86_64-pc-cygwin --host=x86_64-pc-cygwin --target=x86_64-pc-cygwin --without-libiconv-prefix --without-libintl-prefix --libexecdir=/usr/lib --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --enable-bootstrap --enable-__cxa_atexit --with-dwarf2 --with-tune=generic --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-graphite --enable-threads=posix --enable-libatomic --enable-libcilkrts --enable-libgomp --enable-libitm --enable-libquadmath --enable-libquadmath-support --enable-libssp --enable-libada --enable-libgcj-sublibs --disable-java-awt --disable-symvers --with-ecj-jar=/usr/share/java/ecj.jar --with-gnu-ld --with-gnu-as --with-cloog-include=/usr/include/cloog-isl --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible
seçenekleriyle yapılandırıldı.
Evre modeli: posix
gcc version 5.4.0 (GCC)

**Comment by creat89** [comment]
Hello,

I tried yesterday the last version of fastText on a Windows computer using Cygwin (don't ask me why I'm forced to use a Windows computer XD), and I had the same problem as @xentnex.

The only difference is the gcc version which is the 6.4 and I'm using Windows 7 instead of Windows 10.

**Comment by n1rv4n4** [comment]
**Command:** 
`./fasttext predict-prob wiki.tr.bin test.txt`

**Output:** 
```
fasttext: src/vector.cc:93: void fasttext::Vector::mul(const fasttext::Matrix&, const fasttext::Vector&): Assertion `A.m_ == m_' failed.
Aborted (core dumped)
```

Is this issue resolved? I compiled the newest version, but it still gives this error.

**Comment by Jordy-VL** [comment]
> **Command:**
> 
> `./fasttext predict-prob wiki.tr.bin test.txt`
> 
> **Output:**
> 
> ```
> fasttext: src/vector.cc:93: void fasttext::Vector::mul(const fasttext::Matrix&, const fasttext::Vector&): Assertion `A.m_ == m_' failed.
> Aborted (core dumped)
> ```
> Is this issue resolved? I compiled the newest version, but it still gives this error.

I am still having the same issue. Any issue which follows up on this?

**Comment by mattiewasiak** [comment]
I got rid of the `counts.size() == osz_`line in model.cc and was able to get it to run for anyone still having this issue.

**Comment by Stolaine** [comment]
@mattiewasiak I am havind the issue `counts.size() == osz_` in `model.cc:315`

**Comment by mattiewasiak** [comment]
@Stolaine did you try commenting out the line?
