### ISSUE TITLE
ModuleNotFoundError: No module named 'pybind11'

### ISSUE THREAD

**Issue by alexpnt** [facebookresearch/fastText#730]
I am trying to install fastText from my setup.py installation script. However, it always gives this error:

`ModuleNotFoundError: No module named 'pybind11'`, even after I specify that I want pybind11 installed.

However, if I install pybind11 using pip, before running the setup.py, it works. 

fastText should be able to find pybind11.

**Comment by AIGeneratedUsername** [comment]
@alexpnt I've installed `pip install pybind11` and `brew install pybind11` and I still have the error. How did you solve this?
