### ISSUE TITLE
In supervised mode can subwords and wordNgrams be used together?

### ISSUE THREAD

**Issue by karlek** [facebookresearch/fastText#731]
When training a model in supervised mode, is it possible to use `-wordNgrams` and subwords (`-minn` and `-maxn`) together? 

In other words, will this command both train a model with ngrams of size 2, and have subword tokens of length 3? Or will it only use one of the methods?
`$ ./fasttext supervised -input training.txt -ouput model -wordNgrams 2 -minn 3 -maxn 3`

**Comment by EdouardGrave** [comment]
Hi @karlek,

Thank you for your question!

Yes, it is possible to use both the subwords and wordNgrams together. Please note that in this case, the subwords and wordNgrams are hashed to the same buckets. It is thus a good idea to use a large value for the option `-bucket` (such as the default, which is equal to `2000000`), to avoid collisions.

Best,
Edouard

**Comment by karlek** [comment]
Thanks @EdouardGrave!
