### ISSUE TITLE
void Model::initSigmoid()

### ISSUE THREAD

**Issue by yishen-zhao** [facebookresearch/fastText#737]
In this function,what's meaning "real x = real(i * 2 * MAX_SIGMOID) / SIGMOID_TABLE_SIZE - MAX_SIGMOID;"

**Comment by Celebio** [comment]
Hi @yishen-zhao ,
This function builds a precomputed sigmoid table. Instead of calling `1.0 / (1.0 + std::exp(-x)`, we pre-populate an array with values in it, and as value we choose the range [-8;8] (`[-MAX_SIGMOID;MAX_SIGMOID]`).

Regards,
Onur
