### ISSUE TITLE
Greek

### ISSUE THREAD

**Issue by gcelano** [facebookresearch/fastText#740]
The Greek model here https://fasttext.cc/docs/en/crawl-vectors.html is about Modern (or Ancient) Greek?

**Comment by EdouardGrave** [comment]
Hi @gcelano,

The [Crawl model](https://fasttext.cc/docs/en/crawl-vectors.html) was trained on Greek data from the web as well as the Greek Wikipedia. Thus, this data (mostly) corresponds to Modern Greek. We currently don't have a model for Ancient Greek.

Best,
Edouard
