### ISSUE TITLE
How does fasttext scale with number of threads?

### ISSUE THREAD

**Issue by Lizhen0909** [facebookresearch/fastText#743]
Did anyone test on it? I tested on 20 and 40 thread, did not find significant difference.

**Comment by EdouardGrave** [comment]
Hi @Lizhen0909,

This mostly depends on the number of cores that your CPU has. Using a number of threads larger than the number of CPU cores usually don't lead to increase performance. Thus, you should set the number of threads to be equal to the number of CPU cores to get the best performance.

Best,
Edouard.
