### ISSUE TITLE
UnicodeEncodeError when using latest FastText from master in Py 2.7

### ISSUE THREAD

**Issue by MikolajSedek** [facebookresearch/fastText#746]
When I train fasttext with train_unsupervised on utf-8 encoded csv file and try to use .get_words(include_freq=True) method I get trackeback:

> > ---------------------------------------------------------------------------
> UnicodeEncodeError                        Traceback (most recent call last)
> <ipython-input-16-9dcae77fab4a> in <module>()
> ----> 1 words, freqs = ft_model.get_words(include_freq=True, on_unicode_error='replace')
> 
> /Users/mikolaj.sedek/miniconda2/envs/py2ml/lib/python2.7/site-packages/fastText/FastText.pyc in get_words(self, include_freq, on_unicode_error)
>     168         the function get_subwords.
>     169         """
> --> 170         pair = self.f.getVocab(on_unicode_error)
>     171         if include_freq:
>     172             return (pair[0], np.array(pair[1]))
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 5: ordinal not in range(128)

However, this does not happen when I check out to latest tag:
`cd fastText; git checkout 0.2.0; pip install -U .`
I suspect that this commit: https://github.com/facebookresearch/fastText/commit/e13484bcb261cda51d33c4940ab5e might be the source of error. Using on_unicode_error='replace' does not help, the error still occurs :(. 

My sys.version:

> 2.7.15 |Anaconda 4.4.0 (x86_64)| (default, Nov 13 2018, 17:07:45) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

Below full notebook code to reproduce error:

```
import pandas as pd
!git clone https://github.com/facebookresearch/fastText.git
!cd fastText; pip install -U .
!pip install Faker
from faker import Faker
fake = Faker('pl_PL')

def create_data(lines=100, words_in_sent=5):
    data = []
    for line in range(lines):
        data.append([fake.city() for i in range(words_in_sent)])
    return pd.DataFrame(data)
    
create_data().to_csv("test.csv", sep=" ", header=False, encoding="utf-8")

import fastText    
ft_model = fastText.train_unsupervised("test.csv")
words, freqs = ft_model.get_words(include_freq=True, on_unicode_error='replace')
```

**Comment by Celebio** [comment]
Hi @MikolajSedek, 
Thank you for reporting the issue!

It should be fixed by 71c0ee5a8b91df21585aec8cb18991d696414fd5. Feel free to re-open the issue if it is not the case.

Best regards,
Onur
