### ISSUE TITLE
How to train a high precision fastText model?

### ISSUE THREAD

**Issue by negacy** [facebookresearch/fastText#750]
I am interested in training a high precision (relatively low recall) fasttext model for text classification. Are there helpful tips that are suggested? 

Thanks in advance.

**Comment by EdouardGrave** [comment]
Hi @negacy,

One thing that is useful to tradeoff precision for recall is to only predict labels which have a score above a certain threshold. This can be achieved with fastText in the following way:
```
> ./fasttext predict <model.bin> <valid.txt> <K> <T>
```
where `K` is the maximum number of labels that will be predicted and `T` is the threshold. For example, you can predict only labels that are above the `0.5` threshold with the command
```
> ./fasttext predict <model.bin> <valid.txt> 1 0.5
```
This also works with the `test` subcommand.

Best,
Edouard.
