### ISSUE TITLE
release of pretrained context (not word) vectors

### ISSUE THREAD

**Issue by dkajtoch** [facebookresearch/fastText#758]
As far as I know fasttext, similarly as word2vec, uses a pair of vectors for each word (or character n-gram). One is called word vector, and is what people use all the time, but there is also context vector which is not released into public. Is there are a chance to release both pretrained representations? Secondly, If I want to use a variant to transfer learning to train vector representation on some specific texts do I need both representations?

**Comment by EdouardGrave** [comment]
Hi @dkajtoch,

For the Wikipedia models, you can obtain the "context" vectors of each words by using the binary model format. You can either use the `dump` subcommand of the command line tools, or the python bindings to access this information. For the more recent Crawl models, we did not use context vectors: we shared the parameters of the "word" and "context" vectors. This was made possible by the use of position weights during training of these models.

In general, I believe that you don't need both representations to perform transfer learning.

Best,
Edouard
