### ISSUE TITLE
Windows 7 MinGW-W64 build produces a corrupted model file

### ISSUE THREAD

**Issue by S-Eugene** [facebookresearch/fastText#76]
fastText built on Windows 7 with MinGW-W64 gcc version 4.9.2 (x86_64-posix-seh-rev1) creates a model file that is not loaded correctly in `test` or `predict` modes.
Can be fixed by explicitly specifying `std::ifstream ifs(filename, std::ifstream::binary);`  in  `FastText::loadModel` and `std::ofstream ofs(args_->output + ".bin", std::ofstream::binary);` in `FastText::saveModel` in fasttext.cc

**Comment by EdouardGrave** [comment]
Thanks for your report. This is now fixed.
