### ISSUE TITLE
The embedding is either sum or average value of n-gram embeddings ?

### ISSUE THREAD

**Issue by Zhiyu-Chen** [facebookresearch/fastText#762]
In the original paper "Enriching Word Vectors with Subword Information", it seems that the word vector is the sum of the n-gram embeddings. But in the OOV experiment, why it uses the average instead of sum?

When trying this package, it seems using the average for both OOV words and words in the vocabulary.

the following codes will print "True". 

word = 'abcdefg'
word_embedding = model.get_word_vector(word)
subs, subinds = model.get_subwords(word)
sub_embedings = model.get_input_matrix()[subinds]
sub_embedding = sub_embedings.sum(axis=0)
np.allclose(word_embedding,sub_embedding/len(subs))

**Comment by EdouardGrave** [comment]
Hi @Zhiyu-Chen,

You are correct, fastText uses the average to compute the word vector from subword vectors. Please note that for most usages, word vectors should be normalized, and thus using the sum or average does not make a difference.

Best,
Edouard.

**Comment by EdouardGrave** [comment]
Hi @cloudyyyyy,

The embedding of the special sequence `<where>` is used both for training and test time. We *always* include the embedding corresponding to full words (here, corresponding to `<where>`) in the average to obtain the final word vector.

Best,
Edouard.
