### ISSUE TITLE
Question : Can I load a zip model ?

### ISSUE THREAD

**Issue by userFT** [facebookresearch/fastText#768]
Using the Python wrapper, I'd like to zip a current model (let's say wiki.simple.bin) and load this model using the load_model() function. However, it looks like i'm not able to do so.
Did I do something wrong or what am I trying to do is not possible ?

Thanks for your help!

**Comment by EdouardGrave** [comment]
Hi @userFT,

As of now, it is unfortunately not possible to load a compressed model (with `zip`) using the `load_model()` function.

Best,
Edouard

**Comment by Celebio** [comment]
Hi @userFT ,
The best way to compress a model for fastText is to use [quantization](https://fasttext.cc/docs/en/cheatsheet.html#quantization).

You can also use python's [zipfile module](https://docs.python.org/3/library/zipfile.html#module-zipfile) to reduce the file size. It can help if you need to send the file over the network, but you will have to decompress it before using it with fastText so it won't help on the memory footprint.

I am closing the issue now. We will keep this suggestion in mind.

Best regards,
Onur
