### ISSUE TITLE
Can't import fastText and can import fasttext but I need fastText

### ISSUE THREAD

**Issue by Vonisoa** [facebookresearch/fastText#770]
I want to try a script on linux using python 3.6. I installed fastText with pip and when i import fastText, I got import error . But when I import fasttext, there is no error.
The trouble is my code is based on fastText and I don't know how to use fasttext with it:
```
from fastText import FastText
input='A little test'
model = FastText.load_model('lid.176.bin')
ang=model.predict(input, k=1)
```
Can anyone help please

**Comment by ruckc** [comment]
@Vonisoa fastText is not directly pip installable from pypi.  You "must" clone from git and build it that way.  

_side note: i find this requirement absurd, and i'm just a user of fastText_

**Comment by Vonisoa** [comment]
Yes, you're right! there is no way to install fastText from pypi.
