### ISSUE TITLE
Need Sigmoid activation to get independent probability of predictions?

### ISSUE THREAD

**Issue by giriannamalai** [facebookresearch/fastText#774]
I'm using BlazingText which is based on FastText. But, now want to get independent result of prediction without summing upto 1 ?
I have checked other issues. There is one. Please add this to feature request

**Comment by EdouardGrave** [comment]
Hi @giriannamalai,

Please note that when using fastText, you can use the one-vs-all loss (with command line argument `-loss ova`), which will give the desired behavior. For issues related to BlazingText, please directly use their github repo, as we are not the developers of BlazingText.

Best,
Edouard.

**Comment by giriannamalai** [comment]
ova ? Did not find this in the information
 page?
