### ISSUE TITLE
-bash : fastText: command not found

### ISSUE THREAD

**Issue by cpoptic** [facebookresearch/fastText#784]
Standard installation, nothing out of the ordinary, using `pip install fastTest`

when trying to run a supervised model using `fastText supervised -input training.txt -output my_output_model`,

it breaks and gives a `bash: fastText: command not found` error.

No clue why.  I'm using a virtual environment.
Running the python interpreter and running `import fastText` works with no problem.
But trying to execute that command to train the model from the command prompt breaks it.

Could there be an environment variable I need to set?
I tried setting `export MACOSX_DEPLOYMENT_TARGET=10.9`, as per another Issue comment, but no avail.  I'm on a Mac btw.

```
$ pip list | grep fast
fasttext                          0.8.22     
```        
I suspect this is related to my PATH variable

**Comment by Celebio** [comment]
Hi @cpoptic ,
When you install fasttext's python bindings via `pip`, it will install [the pypi version](https://pypi.org/project/fasttext/) which is not the same thing as [the github version](https://github.com/facebookresearch/fastText/tree/master/python). (Also note that `pip` manages packages in a case insensitive manner).

In any case, installing the python binding will not install the binary `fastText`, which is the C++ version.

So you have 3 options :
1) Clone https://github.com/facebookresearch/fastText and run `make`, to get the `fastText` binary.
2) Clone https://github.com/facebookresearch/fastText and run `python setup.py install`, to get the `fastText` module for python
3) run `pip install fasttext` to get the `fasttext` module for python.

You have more information about the first two options in the [README](https://github.com/facebookresearch/fastText#getting-the-source-code)

At the moment `fasttext` module and `fastText` module are incompatible. We are working on unifying these things. Thank you for reporting your experience.

Best regards,
Onur

**Comment by cpoptic** [comment]
Yes I've used option 2, running `python setup.py install` after cloning the repo.  It installs successfully.
I can even check by running the python interpreter and `import fastText` (note the uppercase T).

But when running `fastText supervised -input training.txt -output my_output_model` from the command line, I get `bash: fastText: command not found` error.

**Comment by cpoptic** [comment]
Could we please get this straightened out?  There is significant confusion regarding fasttext vs fastText.   https://github.com/facebookresearch/fastText/issues/485
Not sure what the rationale was behind maintaining two libraries with one letter capitalized and the other lowercase.  I think most would agree that decision is an invitation to headaches.

**Comment by Celebio** [comment]
Hi @cpoptic ,
I agree it's confusing. As mentioned we are working on unifying all those things.

Your feedback is very valuable. Thank you again for sharing it. I will close this issue, feel free to re-open it if you have further questions.

Best regards,
Onur

**Comment by TheurgicDuke771** [comment]
> Hi @cpoptic ,
> I agree it's confusing. As mentioned we are working on unifying all those things.
> 
> Your feedback is very valuable. Thank you again for sharing it. I will close this issue, feel free to re-open it if you have further questions.
> 
> Best regards,
> Onur

Is the unification completed?
