### ISSUE TITLE
Re-enforced learning with FastText 

### ISSUE THREAD

**Issue by CharlesCCC** [facebookresearch/fastText#785]
Is the FastText able to support re-enforced learning ? If not, has anyone tried implemented ?

**Comment by Celebio** [comment]
Hi @CharlesCCC,
What do you mean by "re-enforced learning" ?

Onur

**Comment by CharlesCCC** [comment]
@Celebio It another type of ML.

Assume I build a simple fruit classifier to tell "apple" and "orange"   if the classification is correct identify the image, it will be rewarded, if not, it will get penalized. 

So, this way, we can "re-enforce" the learning by having some kind of reward-penalty mechanism (which I believe a lots of Autonomous Driving car are using). to improve the model over-time. 

More detail [here](https://en.wikipedia.org/wiki/Reinforcement_learning)

**Comment by Celebio** [comment]
Hi @CharlesCCC ,
There is no reinforcement learning capability built-in in fastText. You can use what fastText produces (word vectors) to train a RL model.

Please note that reinforcement learning models are used when there is a sequence of actions to be done, where as in the model of fastText we are taking a decision per sample (which is penalised by the chosen loss if the prediction is incorrect).

You can have more information on the model in [this section of the readme](https://github.com/facebookresearch/fastText#references), and ask questions to the community if something is not clear.

Best regards,
Onur
