### ISSUE TITLE
Invalid Japanese Binary Data?

### ISSUE THREAD

**Issue by polm** [facebookresearch/fastText#789]
I tried downloading the Japanese binary embeddings from [here](https://fasttext.cc/docs/en/crawl-vectors.html), but when I try to unzip them I get a CRC error (whether using gunzip or 7zip). I believe the download is complete; I was unable to resume it with wget, which just said the download was already finished.

The md5sum of the file is `504d32156f8762fac46d9224c56cdbb7`, and it's 4.2GB, which is the size wget reports when it starts downloading. Is there something wrong with my download, or is this a problem with the file on the server?

I see there have been other issues with this file like #444 and #648 but I think they're all marked resolved at the moment.

**Comment by huynhldvn** [comment]
I got the same problem when downloading Vietnamese bin data. Tried to use wget and everything worked well. Please try to use wget as well.

**Comment by polm** [comment]
I was already using wget.

**Comment by polm** [comment]
At some point the file appears to have been fixed. Now after downloading the md5sum is `90c72bb4bcfc2c032ecee41976b967e3` and it unzips correctly.
