### ISSUE TITLE
Cosine distance is unnormalized in find_nearest_neighbor (Python)

### ISSUE THREAD

**Issue by VictorXunS** [facebookresearch/fastText#791]
Some people have mentioned it before me, but I haven't found a specific issue for this.

Cosine distance is wrongly computed in Python version of getNN:

Should be:

`np.matmul(vectors, query, out=cossims) / np.linalg.norm(vectors, axis=1)`

instead of:

`np.matmul(vectors, query, out=cossims)`

Alternatively, the commentary has to be updated to indicate that input vectors should be normalized.

**Comment by Celebio** [comment]
Hi @VictorXunS ,
For nearest neighbours, please use the one that is directly exposed in the FastText model now: https://github.com/facebookresearch/fastText/blob/9479e4ecd565aa8f1e0da52303c876b5fb6fa0d1/python/fasttext_module/fasttext/FastText.py#L87

I am closing the issue. Feel free to re-open if the solution is not satisfying.

Best regards,
Onur
