### ISSUE TITLE
Multi-label classification problem

### ISSUE THREAD

**Issue by rxy1212** [facebookresearch/fastText#797]
In this doc [https://fasttext.cc/docs/en/supervised-tutorial.html](doc), I notice that fastText support multi-label classification task by just add an argument "-loss one-vs-all". I want to know what's the magic here and how "-loss one-vs-all" works.
Thanks.

<img width="830" alt="sample" src="https://user-images.githubusercontent.com/14829556/57604116-f1ded400-7595-11e9-952e-8969f2c2d9a5.png">

**Comment by Celebio** [comment]
Hi @rxy1212 ,
You are right, we should probably add more technical information on this subject in our docs.

The loss "one-vs-all" trains an independent classifier for each label.  For each label, it computes a probability value by taking the sigmoid function without taking into account any other information related to other labels, and then it applies cross entropy loss to it (called `binaryLogistic` in the source code).

I am closing the issue now. Feel free to re-open it if you need any further information.

Best regards,
Onur
