### ISSUE TITLE
Memory leak in Python module

### ISSUE THREAD

**Issue by NProkoptsev** [facebookresearch/fastText#802]
There is memory leak in python if I use the following code
```
ft_model = FastText.load_model('model.bin')
for _ in range(10000000):
    s = ft_model.get_subwords('FastText')[0]
```

**Comment by Celebio** [comment]
Hi @NProkoptsev ,
Can you specify a little bit more ? How do you see the memory leak? Which version of python are you using, 2 or 3 ?

Regards,
Onur

**Comment by NProkoptsev** [comment]
Hi, I'm using python3.
In my code I frequently access ft_model.get_subwords, and it seems after calling this method, memory doesn't release. If you run the snippet above, you will notice that you will run out of RAM soon enough.

**Comment by Celebio** [comment]
Hi @NProkoptsev ,
Thank you for reporting the issue. It should be fixed by [this PR](https://github.com/facebookresearch/fastText/pull/844) by @lukeandshuo.

I am closing the issue now. Feel free to re-open it if you observe the problem again.

Best regards,
Onur
