### ISSUE TITLE
fasttext cbow no working?

### ISSUE THREAD

**Issue by eduamf** [facebookresearch/fastText#808]
Is cbow option working? What is wrong?

```
>$ ./fasttext cbow -input /opt/data/Mix/Brasil_Celex2013-2017_Leis.pt \
     -output /opt/Brasil_Celex2013-2017_Leis -minCount 7 -dim 256 
     -loss softmax -thread 30

Read 166M words
```
More than two hours later

```
Number of words:  295330
Number of labels: 0
Progress:   0.2% words/sec/thread:       4 lr:  0.049878 loss: 14.322811 ETA: 1917h40m
```
I think the problem is the softmax option.

**Comment by Celebio** [comment]
Hi @eduamf ,
Softmax is slower than, say, negative sampling, but in your case 4 words per second per thread is really slow.

If you try to read the input file with another program, is it slow as well? Can you also try to set thread to 1?

Regards,
Onur

**Comment by Celebio** [comment]
Hi @eduamf ,
I will close the issue. If you still observe the issue related to fastText, feel free to re-open it.

Best regards,
Onur
