### ISSUE TITLE
eta time for supervised training

### ISSUE THREAD

**Issue by spate141** [facebookresearch/fastText#81]
When I started training a supervised model:
`Progress: 2.7%  words/sec/thread: 6565  lr: 0.097276  loss: 0.616644  eta: 18h4m   4m`

and after `58 hours`, this is what I am seeing:
`Progress: 86.2%  words/sec/thread: 5512  lr: 0.013768  loss: 0.175465  eta: 3h6m    4m`

Am I missing anything here? I thought, training would be complete in 18h!

**Comment by EdouardGrave** [comment]
Did you run other jobs on the same machine?

**Comment by spate141** [comment]
No, just the fastText
[16 core CPU, 30GB RAM]

**Comment by EdouardGrave** [comment]
How many threads did you use? The ETA might be inaccurate when the number of threads is greater than the number of CPU cores.

**Comment by spate141** [comment]
Ooops.. I used 32 threads. I think that might be the issue. Thanks.
