### ISSUE TITLE
Print-vectors only printed out the word vectors, not the sentence/paragraph vectors

### ISSUE THREAD

**Issue by longma307** [facebookresearch/fastText#82]

**Comment by EdouardGrave** [comment]
Could you please give more details? FastText prints out sentence vectors only for models trained using the `supervised` mode.

**Comment by longma307** [comment]
@EdouardGrave I used the pre-trained supervised model to generate the sentence vectors, but I only got the word vectors instead of the sentence vectors. Each word with its corresponding vectors per line, could you give me an example of the text.txt format? My "text.txt" file was one document per line without labels, was that correct? Thanks.

**Comment by EdouardGrave** [comment]
To obtain sentence vectors from a supervised model trained with labeled data, you can use the `print-vectors` command:
```
$ ./fasttext print-vectors model.bin < text.txt
```
where `text.txt` contains one sentence per line. This functionality was added recently, so you might need to pull the latest version to be able to use it.

**Comment by longma307** [comment]
Hello Edouard,

Thank you for your response. I tried to use the print-vectors two weeks ago, I may need to pull the latest version to check it again.

First, I trained the labeled data under the supervised training and obtained a model.
Second, I used this model to generate the sentence vectors. The “text.txt data” I have been tried has following format:
I am a student, I am student
I am in us, I am in us

But I only get the word vectors instead of getting the sentence vectors. Can you verify if this format is correct?

Thanks.

Long

**Comment by EdouardGrave** [comment]
Yes, the file format seems correct. The functionality was added approximately two weeks ago, so you should probably try the latest version. 

Best.

**Comment by longma307** [comment]
Thanks, I am going to try it.
