### ISSUE TITLE
Word set empty after train model.

### ISSUE THREAD

**Issue by litozz** [facebookresearch/fastText#824]
I have a `.txt` file with text that I can read as a String. Then, I try to train a model (cbow or skipgram, behavior is the same) like that:

    import fasttext
    model = fasttext.cbow('./myfile.txt', 'modelcbow')

If I try to get `model.words`, it returns `set()`, i.e. There's no words in the model. With the same input in fasttext console command it builds the model properly.

What can be done to fix it? Thanks!

**Comment by Celebio** [comment]
Hi @litozz ,
I suggest you to install the latest python bindings as explained [here](https://fasttext.cc/docs/en/python-module.html).
As mentioned in [this blog post](https://fasttext.cc/blog/2019/06/25/blog-post.html), the `cbow` function is from the unofficial api and is not supported. Instead you should call
```
import fasttext
model = fasttext.train_unsupervised('./myfile.txt')
```
and then
```
model.words
```

I will close the issue. If you still face any problem, feel free to re-open it.

Best regards,
Onur
