### ISSUE TITLE
Make fastText fast again

### ISSUE THREAD

**Issue by gartentrio** [facebookresearch/fastText#826]
Since commit [Base class for matrices (c35edc3)](https://github.com/facebookresearch/fastText/commit/c35edc3a26b4f0d2b67a18f2f8eb21209a7420a5) fastText is ~6 times slower, so sad!

Before commit "c35edc3a26b4f0d2b67a18f2f8eb21209a7420a5":
```
fasttext cbow -input sents.txt -output model -loss ns -thread 1

Read 2M words
Number of words:  42519
Number of labels: 359
Progress:   5.6% words/sec/thread:   97079 lr:  0.047185 loss:  3.006866 ETA:   0h 1m
```

After commit "c35edc3a26b4f0d2b67a18f2f8eb21209a7420a5":
```
fasttext cbow -input sents.txt -output model -loss ns -thread 1

Read 2M words
Number of words:  42519
Number of labels: 359
Progress:   5.7% words/sec/thread:   17374 lr:  0.047160 loss:  3.002542 ETA:   0h 9m
```

**Comment by Celebio** [comment]
Hi @gartentrio ,
Thank you for reporting the issue. We will have a look.

Onur

**Comment by Celebio** [comment]
Hi @gartentrio ,
Can you please check again at head?

Regards,
Onur

**Comment by Celebio** [comment]
Hi @gartentrio ,
The issue should be fixed at head revision.

I am closing the issue. Feel free to re-open if you observe the issue again.
Thank you again for reporting.

Best regards,
Onur

**Comment by gartentrio** [comment]
Commit "624b7097abc8c209903d4ad8b8c12841d88bd38a" did the trick, thank you!

```
Read 2M words
Number of words:  42519
Number of labels: 359
Progress:   5.1% words/sec/thread:   98846 lr:  0.047430 loss:  3.046528 ETA:   0h 1m
```
