### ISSUE TITLE
Upper Bound for Vocabulary Size?

### ISSUE THREAD

**Issue by budhiraja** [facebookresearch/fastText#83]
Hi,
Is there an upper bound for vocabulary size? I have a dataset that has 3 Million tokens but the word vectors are coming only for  90791.
Thanks!

**Comment by EdouardGrave** [comment]
When training unsupervised models (with the commands `skipgram` or `cbow`), words appearing less than 5 times are removed from the vocabulary. This default setting can be changed with the `-minCount` option.
