### ISSUE TITLE
(Re-opening) Ova loss doesn't do multi-label classification in python package

### ISSUE THREAD

**Issue by hminooei** [facebookresearch/fastText#830]
Based on the [documentation](https://fasttext.cc/docs/en/supervised-tutorial.html#multi-label-classification), I'm expecting loss='ova' to result in multi-label classification. But in practice (I'm using python fasttext #version 0.8.22), only loss='ns' results in multi-label classification. 

@Celebio suggested using k=-1 should resolve it but actually with k=-1 essentially I get the same results as k=2 (I only have two classes). However, the probabilities add up to 1 for all samples I tried predicting for (I was expecting the probabilities don't add up to 1 at least for some samples) whereas if I set the loss to 'ns' the probabilities don't add to 1 (they are either <1 or >1) which is expected.

Have you guys tested 'ova' loss in the python package? I think this is a bug.

**Comment by giriannamalai** [comment]
Hi,
The bug is there and notified by @Celebio 
You can follow it here.
https://github.com/facebookresearch/fastText/issues/829

**Comment by Celebio** [comment]
As discussed in https://github.com/facebookresearch/fastText/issues/829. I am closing this issue as well. Feel free to re-open if something is not clear.

Best regards,
Onur
