### ISSUE TITLE
Python: predict raises ValueError when doing multiple text when different number of values are above threshold

### ISSUE THREAD

**Issue by mvsjober** [facebookresearch/fastText#846]
When we are giving `predict()` a list of texts to predict for, each text might produce a different number of results above the given threshold. This raises a ValueError when predict tries to form an `ndarray` out of all the prediction results.

A minimal example to reproduce the error:

```python
import fasttext

text = [
    "Hello hello hello",
    "Foo bar baz",
    "Given a string, get a list of labels and a list of corresponding probabilities."
]

# wget https://dl.fbaipublicfiles.com/fasttext/supervised-models/dbpedia.ftz
model = fasttext.load_model('dbpedia.ftz')
r = model.predict(text, k=100, threshold=0.2)
```

Result:
```
Traceback (most recent call last):
  File "./test_fasttext.py", line 16, in <module>
    r = model.predict(text, k=100, threshold=0.2)
  File "/home/msjoberg/sw/opt/miniconda3/envs/fasttext/lib/python3.7/site-packages/fasttext/FastText.py", line 151, in predict
    result_as_pair = np.array(predictions, dtype=dt)
ValueError: setting an array element with a sequence.
```

**Comment by osma** [comment]
Seems very similar to the case that PR #876 tries to fix

**Comment by Celebio** [comment]
Hi @osma,
I believe those are different issues. We will publish a fix soon for both.

Best regards,
Onur

**Comment by osma** [comment]
Thanks for the clarification and update @Celebio. Looking forward to the fix, since this currently keeps us from upgrading.

**Comment by Celebio** [comment]
Hi @mvsjober , @osma ,
Both issues should be fixed by commits https://github.com/facebookresearch/fastText/commit/7fb0dd3ed5a667279e198fa70025ddb704076bed and https://github.com/facebookresearch/fastText/commit/2936e07ac240de663d7175e5a814df5d6879a1e0.

I am closing the issue. Feel free to re-open it if you observe the same problem.
Best regards,
Onur

**Comment by osma** [comment]
Thanks @Celebio !

**Comment by mvsjober** [comment]
OK, I can confirm at least that my test case works now with the fixed version. Thanks!
