### ISSUE TITLE
Is it normal to have </s> token in embedding vec file

### ISSUE THREAD

**Issue by lengockyquang** [facebookresearch/fastText#848]
Hi, i'm using fastText to create word representation with script below:

> ./fasttext cbow -input ../train.en -output ../output/train -dim 512 -minCount 0 -epoch 50

When i opened train.vec file, I saw < /s >  token with its vector. So is it normal to have it in vec file ? Did i miss something ?

**Comment by Celebio** [comment]
Hi @lengockyquang .
Thank you for your question. It is expected. You can refer to [Edouard](@EdouardGrave)'s answer [here](https://github.com/facebookresearch/fastText/issues/177#issuecomment-294624818) for more insight.

I close this issue now, feel free to re-open it if you have further questions.

Best regards,
Onur
