### ISSUE TITLE
Fasttext supervised classifier predicts always the same probability

### ISSUE THREAD

**Issue by KonstantinaLazaridou** [facebookresearch/fastText#853]
Hi, I am classifying a set of news articles with the fasttext classifier (binary classification). The output of the model is always zero, and the probabilities are almost identical. I am also classifying the same data with other Keras models and I have satisfying results.

This is the code:
```import fasttext
fasttext_clf = fasttext.train_supervised(training_file, lr=0.05, verbose=True);
with open(test_file, "r") as inputf:
   for line in inputf.readlines():
      test_doc = line.split("__label__")[0];  # my per line format is "text __label__$label$"
      clf_result = fasttext_clf.predict(test_doc);  # I checked that the text in test_doc is OK
```

The "clf_result" values look like:
```(('__label__0',), array([ 0.50013661]))
(('__label__0',), array([ 0.50012213]))
(('__label__0',), array([ 0.5001812]))
(('__label__0',), array([ 0.50016522]))
........
(('__label__0',), array([ 0.50017184]))
(('__label__0',), array([ 0.50013584]))
(('__label__0',), array([ 0.5001781]))
```

The classifier's output is:
```
Read 0M words
Number of words:  80869
Number of labels: 2
Progress: 100.0% words/sec/thread: 2209148 lr:  0.000000 loss:  0.694915 ETA:   0h 0m

```
Any idea why?

Thank you very much in advance

**Comment by giriannamalai** [comment]
Add more epochs. Default epochs are 5.
Add at least 100 or 1000 epoch to find the better results.

**Comment by KonstantinaLazaridou** [comment]
Thanks, the results are fine now with 100 and with 500 epochs.

**Comment by alext234** [comment]
Hi, it happens to me too with low epoch and after increasing it i have better prob values. 
Just curious How does epoch help in this case ? What is epoch for actually?

**Comment by ninesky110** [comment]
I have 23 labels and 800,000 smaples and I set the epoch 3000, but I still have same preidiction result. I dont know what's wrong with the model, help me
