### ISSUE TITLE
fasttext install error

### ISSUE THREAD

**Issue by zxyscz** [facebookresearch/fastText#854]
Requirement already satisfied: pybind11>=2.2 in /usr/lib/python3.6/site-packages (from fasttext==0.9.1) (2.3.0)
Requirement already satisfied: setuptools>=0.7.0 in /usr/lib/python3.6/site-packages (from fasttext==0.9.1) (41.0.1)
Requirement already satisfied: numpy in /usr/lib64/python3.6/site-packages (from fasttext==0.9.1) (1.16.4)
Building wheels for collected packages: fasttext
  Building wheel for fasttext (setup.py) ... error
  ERROR: Complete output from command /usr/bin/python3.6 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-syzzxumz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ao4g1_bx --python-tag cp36:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/fasttext
  copying python/fasttext_module/fasttext/__init__.py -> build/lib.linux-x86_64-3.6/fasttext
  copying python/fasttext_module/fasttext/FastText.py -> build/lib.linux-x86_64-3.6/fasttext
  creating build/lib.linux-x86_64-3.6/fasttext/util
  copying python/fasttext_module/fasttext/util/util.py -> build/lib.linux-x86_64-3.6/fasttext/util
  copying python/fasttext_module/fasttext/util/__init__.py -> build/lib.linux-x86_64-3.6/fasttext/util
  creating build/lib.linux-x86_64-3.6/fasttext/tests
  copying python/fasttext_module/fasttext/tests/test_script.py -> build/lib.linux-x86_64-3.6/fasttext/tests
  copying python/fasttext_module/fasttext/tests/__init__.py -> build/lib.linux-x86_64-3.6/fasttext/tests
  copying python/fasttext_module/fasttext/tests/test_configurations.py -> build/lib.linux-x86_64-3.6/fasttext/tests
  running build_ext
  creating tmp
  gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c /tmp/tmpydpatrsc.cpp -o tmp/tmpydpatrsc.o -std=c++14
  gcc: error: unrecognized command line option ‘-std=c++14’
  gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c /tmp/tmpcz3uyzci.cpp -o tmp/tmpcz3uyzci.o -std=c++11
  gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c /tmp/tmpasajmvqa.cpp -o tmp/tmpasajmvqa.o -fvisibility=hidden
  building 'fasttext_pybind' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/python
  creating build/temp.linux-x86_64-3.6/python/fasttext_module
  creating build/temp.linux-x86_64-3.6/python/fasttext_module/fasttext
  creating build/temp.linux-x86_64-3.6/python/fasttext_module/fasttext/pybind
  creating build/temp.linux-x86_64-3.6/src
  gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -I/root/.local/include/python3.6m -Isrc -I/usr/include/python3.6m -c python/fasttext_module/fasttext/pybind/fasttext_pybind.cc -o build/temp.linux-x86_64-3.6/python/fasttext_module/fasttext/pybind/fasttext_pybind.o -DVERSION_INFO="0.9.1" -std=c++11 -fvisibility=hidden
  In file included from /usr/include/python3.6m/pybind11/pytypes.h:12:0,
                   from /usr/include/python3.6m/pybind11/cast.h:13,
                   from /usr/include/python3.6m/pybind11/attr.h:13,
                   from /usr/include/python3.6m/pybind11/pybind11.h:49,
                   from python/fasttext_module/fasttext/pybind/fasttext_pybind.cc:12:
  /usr/include/python3.6m/pybind11/detail/common.h:112:20: fatal error: Python.h: No such file or directory
   #include <Python.h>
                      ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1

**Comment by zxyscz** [comment]
i install fasttext in linux，but i got a error，how can i to solve it？

**Comment by Celebio** [comment]
Hi @zxyscz ,
Could you try [this](https://stackoverflow.com/a/21530768/411264) and check again?

Best regards,
Onur

**Comment by zxyscz** [comment]
> Hi @zxyscz ,
> Could you try [this](https://stackoverflow.com/a/21530768/411264) and check again?
> 
> Best regards,
> Onur

@Celebio thanks for your help, i use this method to solve my problem

**Comment by Celebio** [comment]
Hi @zxyscz ,
As far as I understand you don't observe the problem anymore.

I am closing this issue now, feel free to re-open it if you have further questions.

Best regards,
Onur

**Comment by aniketcha98** [comment]
Hi

Getting the same error and although I have tried the above solution but the error is same 

How I can solve this?

Thanks
