### ISSUE TITLE
incorrect result of fasttext model

### ISSUE THREAD

**Issue by bellaDS** [facebookresearch/fastText#857]
I created a fasttext model to do comments sentiments analysis , I used a train_File with 51% positive comments, 47% negative and 2% neutral. When I want to test with some given sentences always results are divided between: 0.49 .. positive, 0.47 .. negative, 0.02 neutral, even if I type a single negative word. I have the following code :

import fasttext

model = fasttext.train_supervised(TRAIN_FILE, lr=0.1, dim=20, epoch=20, word_ngrams=1 , loss='softmax')

model.save_model(MODEL_FILE)
model = fasttext.load_model(MODEL_FILE)

pred = model.predict(['bad'], k =3)
print(pred)

I get always a result around 0,4.. positif , 0,4... negatif , 0.0.. neutral :

([['__label__négatif', '__label__positif', '__label__neutre']], array([[0.49168783, 0.47954634, 0.02879585]]))

Can someone tell me where the mistake lies

**Comment by Celebio** [comment]
hi @bellaDS ,
Do you have a validation file? Can you run `model.test` on it?

Best regards,
Onur

**Comment by bellaDS** [comment]
here is the whole code to better understand : 

train_df, test_df = df.randomSplit([0.8, 0.2], 42)
import fasttext
import sys
TRAIN_FILE = 'data/train.txt'

TEST_FILE = 'data/test.txt'
MODEL_FILE = 'data/model.bin'

with open(TRAIN_FILE, 'w', encoding='UTF-8') as fp:
    for i, row in enumerate(train_df.toLocalIterator()):
        fp.write('__label__%s %s\n' % (row['label'], row['text']))
        if i % 1000 == 0:
            print(i)
   
with open(TEST_FILE, 'w', encoding='UTF-8') as fp:
    for i, row in enumerate(test_df.toLocalIterator()):
        fp.write('__label__%s %s\n' % (row['label'], row['text']))
        if i % 1000 == 0:
            print(i)
model = fasttext.train_supervised(TRAIN_FILE, lr=0.1, dim=100, epoch=5, word_ngrams=1  , loss='softmax')

model.save_model(MODEL_FILE)
model = fasttext.load_model(MODEL_FILE)
pred = model.predict(['hypocrite'], k =2)

**Comment by bellaDS** [comment]
hi @Celebio 

Yes I have a validation file.
I solved this problem by up sampling the train file and changing the lr value from 0.01 to 0.1

Thank you for your reply.
