### ISSUE TITLE
Error in predict method for model trained with "hs" loss

### ISSUE THREAD

**Issue by celis** [facebookresearch/fastText#863]
I train a supervised model with "loss": "hs", and call the predict method with a list of strings as the argument, this crashes when k (the number of predictions requested) is large.  When I train the model with softmax, this doesnt occur.  When I pass a single string instead of a list of strings to the predict method of the model trained with "hs" loss, this error doesnt occur either. 

System: python 3.7.2, OS.  Have reproduced the error in fasttext-0.8.22 and in  fasttext-0.9.1 versions.   

The error logs i get when calling model.predict(["string1", "string2"], 10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/my_venv/lib/python3.7/site-packages/fasttext/FastText.py", line 151, in predict
    result_as_pair = np.array(predictions, dtype=dt)
ValueError: setting an array element with a sequence.

**Comment by Celebio** [comment]
Hi @celis,
The commit 7fb0dd3ed5a667279e198fa70025ddb704076bed should fix this issue.

I will close this issue, feel free to re-open it if the fix doesn't work.

Best regards,
Onur
