### ISSUE TITLE
train_supervised with pretrainedVectors of 5GB size - 5 times slower than without pretrained?

### ISSUE THREAD

**Issue by ziqizhang** [facebookresearch/fastText#867]
First apologies if I should not post this question as 'issue', in which case please kindly point me to any mailinglist/forums that I can ask this.

I am doing supervised classification on a small-ish dataset of about 8000 sentences, using pretrainedvectors and also without. The code are as follows:

```
'model = fasttext.train_supervised(input=fasttext_train,
                                          minn=4, maxn=10, wordNgrams=3,
                                          neg=10, loss='ns', epoch=3000,
                                          thread=30,
                                          dim=300,
                                          pretrainedVectors=embedding_file)'
#embedding_file points to a pretrained .vec file that is 5GB in size

model = fasttext.train_supervised(input=fasttext_train,
                                              minn=4, maxn=10, wordNgrams=3,
                                              neg=10, loss='ns', epoch=3000,
                                              thread=30,
                                              dim=300)
```
The first line took almost 3 hours while the second took only 40 minutes. I wonder what makes such a big difference?

Could it be:

1. It takes very long time to load very large .vec files? When I use Gensim to load the same .vec file, it took nearly an hour just to load it before it does anything else. I wonder if the same thing is happening here. 
2. It takes a lot of time to perform vector lookups in the pretrained embedding? 
3. anything else?

Can anybody advise on this, or suggest other ways to 'speed things up'? I understand that fasttext can only use the .vec format of pretrained embeddings...

Many thanks

**Comment by LowinLi** [comment]
i also have this confuse
