### ISSUE TITLE
Multi-threading on multiple epochs

### ISSUE THREAD

**Issue by raduk** [facebookresearch/fastText#87]
The line 253 in fastext.cc receives one line from the stream at a time:

`localTokenCount += dict_->getLine(ifs, line, labels, model.rng);`

The different parts of the `ifs` are correctly distributed among the threads in the beginning (line 238 in `trainThread`). For one epoch I think it is OK, but when we do multiple epochs, the stream is being set to the beginning in line 258 of dictionary.cc when it reaches the end. If my reasoning is correct, this will lead to all the threads reading the same data (beginning of the file) in second epoch, instead of each thread reading a different part of the file.

**Comment by EdouardGrave** [comment]
The different threads are all looping over the input file, starting from different positions. So at any given time, each thread is reading a different part of the input file.

**Comment by raduk** [comment]
They are, for the first epoch, until the eof is reached in the dictionary. Then the dictionary will seek the stream at the beginning in getLine, not at the position the thread is supposed to read from. How can it set it at the correct position ? Unless I am missing something...
