### ISSUE TITLE
Wrong Label tagging when train data has repeated words.

### ISSUE THREAD

**Issue by giriannamalai** [facebookresearch/fastText#871]
I have 100 labels with around 10k records. 
Example data, Not the actual one.
Text - Label
The day is good - Wish
Have a good nice day - Wish

This case, I trained a model with WordNgram 3 and loss function OVA. 

If "**good**" keyword comes under any non-relevant text. The model is wrongly tagging it with the label "Wish" . 
Ex., I went for walk a its good.
If I remove "**good**" from the above text, I got lesser probability around 1%  which is correct. 
When "**good**" is not removed, it predicted as 100% and tagged with Wish label.

How do I prevent this kind of issues?
Is there any way i can reduce the weight of certain words?

**Comment by Rajput245** [comment]
@giriannamalai did you find any solution for this problem?

**Comment by giriannamalai** [comment]
@Rajput245 No fix in fastText. This is the way how BOW works. 
You have to change your algorithm and increase train set. Then, go to deep learning models. Its the only fix.
