### ISSUE TITLE
Is the fix to memory leak making it to a release?

### ISSUE THREAD

**Issue by davidefiocco** [facebookresearch/fastText#875]
As https://github.com/facebookresearch/fastText/pull/844 seems to solve a fairly serious bug, I was wondering if the fix will make it soon to a version release on pip. Thanks!

**Comment by thomasthiebaud** [comment]
It seems that your workaround works https://github.com/facebookresearch/fastText/pull/844#issuecomment-584704451. But the bug seems serious enough to release a new version with a fix!

**Comment by Celebio** [comment]
Hi @thomasthiebaud ,
Yes it is coming soon. Thank you for your feedback and your patience.

Best regards,
Onur

**Comment by thomasthiebaud** [comment]
Amazing ;) Thanks for the quick answer

**Comment by grzegorz-bednarczyk** [comment]
Any updates on the release?

**Comment by davidefiocco** [comment]
Looks fixed as of 

https://github.com/facebookresearch/fastText/releases/tag/v0.9.2

So I am tentatively closing this.

**Comment by thomasthiebaud** [comment]
AMAZING ;)
