### ISSUE TITLE
Improving load_vectors function

### ISSUE THREAD

**Issue by CristhianBoujon** [facebookresearch/fastText#882]
I have changed a bit the `load_vectors` function and it allows me reduce the RAM usage in approximately 75%. I would like to propose add this function instead of the original.
Below you can see a benchmark using [memory_profiler](https://pypi.org/project/memory-profiler/)

```
$ python -m memory_profiler vectors.py
Filename: vectors.py

Line #    Mem usage    Increment   Line Contents
================================================
     3   38.508 MiB   38.508 MiB   @profile
     4                             def load_vectors(fname):
     5   38.508 MiB    0.000 MiB       fin = io.open(fname, 'r', encoding='utf-8', newline='\n', errors='ignore')
     6   38.508 MiB    0.000 MiB       n, d = map(int, fin.readline().split())
     7   38.508 MiB    0.000 MiB       data = {}
     8 38164.562 MiB    0.262 MiB       for line in fin:
     9 38164.562 MiB   11.781 MiB           tokens = line.rstrip().split(' ')
    10 38164.562 MiB   48.215 MiB           data[tokens[0]] = map(float, tokens[1:])
    11 38164.562 MiB    0.000 MiB       return data

_________________________________________________________________________________________________________________

$ python -m memory_profiler np_vectors.py
Filename: np_vectors.py

Line #    Mem usage    Increment   Line Contents
================================================
     4   66.789 MiB   66.789 MiB   @profile
     5                             def load_vectors(fname):
     6   66.789 MiB    0.000 MiB       fin = io.open(fname, 'r', encoding='utf-8', newline='\n', errors='ignore')
     7   66.789 MiB    0.000 MiB       n, d = map(int, fin.readline().split())
     8   66.789 MiB    0.000 MiB       data = {}
     9 5401.383 MiB    0.258 MiB       for line in fin:
    10 5401.383 MiB    0.262 MiB           tokens = line.rstrip().split(' ')
    11 5401.383 MiB   48.008 MiB           data[tokens[0]] = np.array(list(map(float, tokens[1:])))
    12 5401.383 MiB    0.000 MiB       return data 
```

As you can see, the original function use 38164.562 MiB vs 5401.383 MiB of the modified function.
I also add the scripts

**vectors.py** (Original function)
```
import io

@profile
def load_vectors(fname):
    fin = io.open(fname, 'r', encoding='utf-8', newline='\n', errors='ignore')
    n, d = map(int, fin.readline().split())
    data = {}
    for line in fin:
        tokens = line.rstrip().split(' ')
        data[tokens[0]] = map(float, tokens[1:])
    return data

if __name__ == '__main__':
    load_vectors('cc.es.300.vec')
```

**np_vectors.py** (Modified function)
```
import io
import numpy as np

@profile
def load_vectors(fname):
    fin = io.open(fname, 'r', encoding='utf-8', newline='\n', errors='ignore')
    n, d = map(int, fin.readline().split())
    data = {}
    for line in fin:
        tokens = line.rstrip().split(' ')
        data[tokens[0]] = np.array(list(map(float, tokens[1:])))
    return data

if __name__ == '__main__':
    load_vectors('cc.es.300.vec')
```

**Comment by Celebio** [comment]
Hi @CristhianBoujon ,
Thank you! it sounds good. Did you check that it works correctly both on Python2 and Python3?
If so, can you make a pull request?

Best regards,
Onur

**Comment by CristhianBoujon** [comment]
@Celebio I just tried on Python3. I will try to test it on Python2

**Comment by mrshu** [comment]
@Celebio @CristhianBoujon I've tried it on Python2 and it seems to work correctly as well (although it is quite a bit slower than Python3).

Just a quick note: the codebase already contains a `load_vectors` function that takes a very similar approach in the `alignment` project/directory: https://github.com/facebookresearch/fastText/blob/master/alignment/utils.py#L13

**Comment by CristhianBoujon** [comment]
@mrshu that's great! Thank you! I'll create a PR

**Comment by CristhianBoujon** [comment]
@Celebio @mrshu you can see the [Pull Request ](https://github.com/facebookresearch/fastText/pull/920)

**Comment by aassumpcao** [comment]
I know this issue has been closed, but can I also ask for the changes to be added to the example in https://fasttext.cc/docs/en/crawl-vectors.html? The text file load example is out of date compared to https://github.com/facebookresearch/fastText/blob/master/alignment/utils.py#L13 and would also be significantly improved with this pull request. Thanks!

**Comment by CristhianBoujon** [comment]
@aassumpcao thank you for your comment. I added the same change to `crawl-vectors.md`

**Comment by CristhianBoujon** [comment]
> @Celebio @mrshu you can see the [Pull Request ](https://github.com/facebookresearch/fastText/pull/920)

@Celebio Can you check the pull request?
