### ISSUE TITLE
Hyperparameter autotuning for Python in Docs

### ISSUE THREAD

**Issue by fclesio** [facebookresearch/fastText#886]
First at all thanks for delivering a very good piece of software. 

We had yesterday the [release of the hyperparameter autotuning for command line](https://ai.facebook.com/blog/fasttext-blog-post-open-source-in-brief/) but checking the [tutorials](https://fasttext.cc/docs/en/supervised-tutorial.html) and the official Python wrapper we do not have any example of the Autotune implemented even with the [implementation in the main code](https://github.com/facebookresearch/fastText/blob/master/python/fasttext_module/fasttext/FastText.py). Can you guys describe how we can use it?

Thanks in advance. 

```
    arg_names = ['input', 'lr', 'dim', 'ws', 'epoch', 'minCount',
        'minCountLabel', 'minn', 'maxn', 'neg', 'wordNgrams', 'loss', 'bucket',
        'thread', 'lrUpdateRate', 't', 'label', 'verbose', 'pretrainedVectors',
        'seed', 'autotuneValidationFile', 'autotuneMetric',
        'autotunePredictions', 'autotuneDuration', 'autotuneModelSize']
```

**Comment by Celebio** [comment]
Hi @fclesio ,
Thank you for your feedback!

The implementation of the autotune is on the C++ side, python only manages its arguments. The portion of the code you quote is indeed the place it is defined.

If you look at the [documentation of the autotune](https://fasttext.cc/docs/en/autotune.html) feature specifically, you can use these examples like this:

command line:
```
>> ./fasttext supervised -input cooking.train -output model_cooking -autotune-validation cooking.valid
```
in python:
```
import fasttext
model = fasttext.train_supervised(input='cooking.train', autotuneValidationFile='cooking.valid')
```
then test it with `model.test('cooking.valid')`

Other examples become:
```
model = fasttext.train_supervised(input='cooking.train', autotuneValidationFile='cooking.valid', autotuneDuration=600)
model = fasttext.train_supervised(input='cooking.train', autotuneValidationFile='cooking.valid', autotuneModelSize="2M")
```

Regards,
Onur

**Comment by fclesio** [comment]
Thanks for your answer @Celebio can I work on a PR to include that in the Python docs or there's someone working on that? (I already checked the backlog and there's no PRs for that)

**Comment by Celebio** [comment]
thank you @fclesio ,
we are working on that. However once published, please feel free to complete or add suggestions.
Thanks again!

**Comment by fclesio** [comment]
You're welcome, and once again thanks for the very good software @Celebio .

**Comment by Celebio** [comment]
Hi @fclesio ,
The documentation contains also [python examples](https://fasttext.cc/docs/en/autotune.html) now. Thank you again for your feedback!

Best regards,
Onur

**Comment by fclesio** [comment]
Thanks!
