### ISSUE TITLE
Print out the best parameters from autotune

### ISSUE THREAD

**Issue by AhmedIdr** [facebookresearch/fastText#887]
Hey, thank you for the new autotune feature. I was just wondering if there is a way to print out the best parameters (maybe I missed that in the docs) or to print out the whole process to track the fine-tuning that is being done. 
Thanks in advance.

**Comment by Celebio** [comment]
Hi @AhmedIdr ,
Thank you for your feedback. We will complete the docs.

You can display the parameters autotune is exploring with `-verbose 3`.

However, for the moment there is not a straightforward way to display the best parameters found during autotuning. A workaround for the moment could be to use `dump` command (`./fasttext dump model_cooking.bin args`) once the training has finished.

Regards,
Onur

**Comment by AhmedIdr** [comment]
Hey @Celebio,
Thank you for your quick answer. 

Regards, 
Ahmed

**Comment by arimbr** [comment]
I found a way to get the model parameters with the Python bindings by inspecting the model object with `model.f.getArgs()`.

I use the following code in this [repository](https://github.com/arimbr/valohai-fasttext-example/blob/master/models/classification/commands.py) to retrain the model on all the data.

```
train_parameters = {
    'lr': 0.1,
    'dim': 100,
    'ws': 5,
    'epoch': 5,
    'minCount': 1,
    'minCountLabel': 0,
    'minn': 0,
    'maxn': 0,
    'neg': 5,
    'wordNgrams': 1,
    'bucket': 2000000,
    'thread': multiprocessing.cpu_count() - 1,
    'lrUpdateRate': 100,
    't': 1e-4,
    'label': LABEL_SEPARATOR,
    'verbose': 2,
    'pretrainedVectors': '',
    'seed': 0,
}

def get_model_parameters(model):
    args_getter = model.f.getArgs()

    parameters = {}
    for param in train_parameters:
        attr = getattr(args_getter, param)
        if param == 'loss':
            attr = attr.name
        parameters[param] = attr

    return parameters
```

**Comment by nvs-abhilash** [comment]
Just to update for those using Python. You can use `fasttext_model_object.f.getArgs()`. This returns a Python object. And all the hyperparameters are attributes of this object. Below is a short example:

```python
ft_model = fasttext.train_supervised('train.csv')

args_obj = ft_model.f.getArgs()
for hparam in dir(args_obj):
    if not hparam.startswith('__'):
        print(f"{hparam} -> {getattr(args_obj, hparam)}")
```

**Comment by hafiz031** [comment]
@Celebio would you share the way to dump this in a text file.
