### ISSUE TITLE
training data in classification-example.sh has expired 

### ISSUE THREAD

**Issue by cloudtrends** [facebookresearch/fastText#89]
hi all,

When I run command 

    wget -c "https://googledrive.com/host/0Bz8a_Dbh9QhbQ2Vic1kxMmZZQ1k"

HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://8c47f35de2544a202d525720f08188d254682381.googledrive.com/host/0Bz8a_Dbh9QhbQ2Vic1kxMmZZQ1k [following]

HTTP request sent, awaiting response... 502 Bad Gateway
2016-09-23 02:06:36 ERROR 502: Bad Gateway.

Can anyone provide another way to download of example data ?

thanks .

**Comment by inkrement** [comment]
Seems like google stopped to provide drive files via http-download.

**Comment by pyk** [comment]
Hmm i thought it was a temporary error #91

**Comment by inkrement** [comment]
ok, thx. But I found another mirror (https://github.com/le-scientifique/torchDatasets).

**Comment by cloudtrends** [comment]
thanks all.

close this issue.
