### ISSUE TITLE
Available metrics for Autotune

### ISSUE THREAD

**Issue by fclesio** [facebookresearch/fastText#892]
Hello all!

[I took a look in the code for Autotune (https://github.com/facebookresearch/fastText/blob/master/src/autotune.cc) and I just want to know if there's only `f1score` and `labelf1score`?

Thanks in advance.

**Comment by herosunly** [comment]
I also hope add more metrics,such as precision, recall

**Comment by Celebio** [comment]
Hi @fclesio ,
You are right those are the only ones for the moment.

@herosunly , thank you for your feedback. We will try to add more metrics.

I tag the issue "feature request" and will close it now. Feel free to re-open it if you have further questions.

Best regards,
Onur
