### ISSUE TITLE
Calculating the probability

### ISSUE THREAD

**Issue by Chinguun8** [facebookresearch/fastText#897]
How do I see the probability of not finding the correct sentence? For example, Dataset with 2 labels "./fasttext predict-prob" showing "label_1 0.65". Is the probability of label_2 is 0.35? or Do I need to calculate separately?

**Comment by Celebio** [comment]
Hi @Chinguun8 ,
If you used the `softmax` loss (which is the default), the probabilities will sum to 1.

If you use the loss "one-vs-all" as described [here](https://fasttext.cc/docs/en/supervised-tutorial.html#multi-label-classification), the prediction of each label will be independent from the others, so each label's probability in the prediction will still be in the range [0, 1] but won't sum to 1.

Best regards,
Onur

**Comment by Celebio** [comment]
Hi @Chinguun8 ,
I will close the issue now. Feel free to re-open it if you have further questions.

Best regards,
Onur
