### ISSUE TITLE
Make include guards unique

### ISSUE THREAD

**Issue by elfring** [facebookresearch/fastText#9]
I find that include guards like "[`ARGS_H`](https://github.com/facebookresearch/fastText/blob/bef5f3c73d9652a30e82d4b58113dd59b63ce351/src/args.h#L10)" and "[`MODEL_H`](https://github.com/facebookresearch/fastText/blob/bef5f3c73d9652a30e82d4b58113dd59b63ce351/src/model.h#L10)" are too short for the safe reuse of your header files (when they belong to an application programming interface).

**Comment by piotr-bojanowski** [comment]
Hi,
I prefixed all include guards with `FASTTEXT_`.
Commit dc2e6a0dd9c4632c85fa4b2d36d7748169d7272f
Thanks!

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/facebookresearch/fastText/commit/dc2e6a0dd9c4632c85fa4b2d36d7748169d7272f "Addition of a prefix to include guards").
