### ISSUE TITLE
TypeError: unexpected keyword argument 'autotuneValidationFile'

### ISSUE THREAD

**Issue by Cumberbatch08** [facebookresearch/fastText#903]
I update the fasttext, and the version is 0.9.1
but when I use the autotune, I get the error.
who can help me?
many thanks.

**Comment by Celebio** [comment]
Hi @Cumberbatch08 ,
As @CristhianBoujon mentioned, it is not included in the last release.

I am closing this issue now, feel free to reopen it if you have any question.

Best regards,
Onur

**Comment by Cumberbatch08** [comment]
> Hi @Celebio, @CristhianBoujon, @Cumberbatch08.
> which release contains this feature?
> thanks!

hi, @BlazJurisic , look at this:
`$ git clone https://github.com/facebookresearch/fastText.git
$ cd fastText
$ pip install .
`
