### ISSUE TITLE
No method for nearest neighbour

### ISSUE THREAD

**Issue by KalanaGeesara** [facebookresearch/fastText#905]
After installing fasttext binding using pip install fasttext it does not have the get_nearest_neighbor method.

AttributeError: '_FastText' object has no attribute 'get_nearest_neighbors'

**Comment by Hellisotherpeople** [comment]
I had this same issue and do not know why this happens.

**Comment by KalanaGeesara** [comment]
I solved the issue by cloning the GitHub repo and installing it instead of using the command pip install fasttext.

**Comment by Celebio** [comment]
Hi @KalanaGeesara ,
Indeed, this function in the python side is not included in any pypi release. However, the next release will contain it.
I am closing this issue. Feel free to re-open it if you have further concerns.

Thank you.
Onur

**Comment by DrDreave** [comment]
@Celebio Are there already schedules for the next release?

**Comment by sonfiree** [comment]
> I solved the issue by cloning the GitHub repo and installing it instead of using the command pip install fasttext.

It didn’t help me

**Comment by Celebio** [comment]
Hi @DrDreave ,
Yes, we will make a release soon that includes all the differences between pypi and github. Stay tuned!

Onur

**Comment by DrDreave** [comment]
Hi @Celebio,
are there any news on this?

**Comment by DrDreave** [comment]
@Celebio I'm sorry to annoy you, but could you please give us an update about the release schedule.

Thanks!
