### ISSUE TITLE
Cannot download dbpedia_csv data

### ISSUE THREAD

**Issue by pyk** [facebookresearch/fastText#91]
Cannot download `dbpedia_csv.tar.gz` via  [classification-example.sh](https://github.com/facebookresearch/fastText/blob/master/classification-example.sh) due to 502 Error in https://googledrive.com/host/0Bz8a_Dbh9QhbQ2Vic1kxMmZZQ1k

**Comment by pyk** [comment]
oh, it seems temporary error

**Comment by tobiasoberrauch** [comment]
Now its a 404 error :)
