### ISSUE TITLE
[Idea] C API

### ISSUE THREAD

**Issue by ankane** [facebookresearch/fastText#911]
Hi, thanks for this project! What are your thoughts about a C API to make it easier to integrate fastText with other programming languages?

Here's how a few other Python/C++ libraries do it:
- XGBoost: https://github.com/dmlc/xgboost/blob/master/include/xgboost/c_api.h
- LightGBM: https://github.com/Microsoft/LightGBM/blob/master/include/LightGBM/c_api.h
- TensorFlow: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h

**Comment by Celebio** [comment]
Hi @ankane ,
Thank you very much for the idea. It looks pretty cool. It is not really on the near future roadmap. However we would like to know if there is a specific language that you will like to use fastText in.

Regards,
Onur

**Comment by ankane** [comment]
Hey Onur, thanks for the response. I'm hoping to use fastText in Ruby (and recently ported the 3 libraries mentioned above). The ideal situation would be to use a C API + FFI (so it works in JRuby), but it should also be possible to create a native extension with code similar to `fasttext_pybind.cc` without it.

**Comment by ankane** [comment]
fwiw, I put together this prototype and have it working in Ruby with FFI: https://gist.github.com/ankane/82e2bbd1afd47dfc6107e50ba56d6773

It can load a model and get its dimensions. It's based on the LightGBM C API. Every call returns an `int` with 0 on success or -1 on failure, and `FT_GetLastError` returns the error message.

**Comment by ankane** [comment]
I added more to the C API prototype in the gist above, but also discovered Ruby has a library similar to pybind11 called [Rice](https://github.com/jasonroelofs/rice), so decided to use that instead (#937). Will go ahead and close this out.
