### ISSUE TITLE
Is the F1 in multilabel text classification Micro-F1-measure or Macro-F1-measure?

### ISSUE THREAD

**Issue by OpenWaygate** [facebookresearch/fastText#914]
The default metric of autotune is F1, when it comes to mutilabels text classification, is it Micro-F1-measure or Macro-F1-measure? 
![image](https://user-images.githubusercontent.com/27287694/65745298-d4b63680-e12d-11e9-8503-d4ce56a7f2de.png)

**Comment by Celebio** [comment]
Hi @OpenWaygate ,
This is the Micro-F1-Measure.

Best regards,
Onur

**Comment by OpenWaygate** [comment]
Get it, thank you.
