### ISSUE TITLE
'test' doesn't correctly evaluate multi-label results

### ISSUE THREAD

**Issue by bcampbell** [facebookresearch/fastText#92]
I've got a set of news articles I'm trying to classify according to topic (eg "education","economy","crime" etc...).
I've got some sets of manually tagged data which I'm using to build a model.bin (using the 'supervised' option). Some articles cover multiple topics, and thus have multiple labels. Some articles don't cover any of the topics we're interested in, and have no labels at all.
However, the 'test' option assumes that every article should have exactly 'k' labels, regardless of how improbable those labels are scored.
So the resultant precision/recall scores can be waaaaaay out - even when testing against the same dataset used to train the model in the first place!

The only solution I've come up with is to add a probability threshold option to the 'test' operation - any labels with a probability below the threshold would be discarded. Of course then there's the problem of tuning that threshold to an appropriate level... but hey. I doubt there's a 'correct' level, so it's probably a case of leaving it up to the user to tune.

I'm happy to have a go at implementing this - it looks straightforward enough. But is it actually a sane and reasonable approach?

**Comment by cpuhrsch** [comment]
I'm closing this since it hasn't been updated in a long time. Please feel free to reopen this issue if it is still current.
