### ISSUE TITLE
Suggestion: Being able to provide set of relevant labels to predict()

### ISSUE THREAD

**Issue by emilmuller** [facebookresearch/fastText#933]
I think it could be useful being able to provide a set of relevant labels to predict(). One could do it by getting the prediction values for all the labels, but maybe that is not very efficient?

Im using lid.176.bin to predict languages. More specifically, I need to determine if some text is Norwegian or English. Quite often, the texts are quite short. For short texts, the model has problems distinguishing between Norwegian, Danish and Swedish (understandably so). However, I know for a fact that a text is either in English or in Norwegian, and it becomes problematic when Swedish or Danish is suggested. Curiously, Norwegian is often in top 3 (if it is in Norwegian), but is given a really low probability compared to Danish and Swedish (for short texts only).

If I could request the probabilities for only English and Norwegian, that would be great! :)

**Comment by Celebio** [comment]
Hi @emilmuller ,
In your case you can simply ignore all other probabilities.
You should ask to return all labels' probabilities. You will need to take only the probabilities you get for English and Norwegian. Then you simply take the one with the biggest probability.

Regards,
Onur

**Comment by Celebio** [comment]
Hi @emilmuller ,
I hope this answered your question, I will close the issue now. Feel free to re-open it if you have further questions.

Best regards,
Onur

**Comment by khituras** [comment]
I have the same question: First computing all propabilities when you only need two of them seems very inefficient. @Celebio Is it inefficient? In my case, I have 100,000 labels but will mostly have to decide between two or three of them. To compute the probabilities of all labels each time seems a bit over the top.
