### ISSUE TITLE
use autotuneValidationFile always report an error “Validation file cannot be opened”

### ISSUE THREAD

**Issue by caoxueqian19901214** [facebookresearch/fastText#948]
python3 test_fasttext.py
Traceback (most recent call last):
  File "test_fasttext.py", line 12, in <module>
    classifier = fasttext.train_supervised( input = '../data/modelData/train', autotuneValidationFile='../data/modelData/train.valid')
  File "/usr/local/lib/python3.7/site-packages/fasttext/FastText.py", line 455, in train_supervised
    fasttext.train(ft.f, a)
ValueError: Validation file cannot be opened!

I was very confused by the mistake，I am sure I followed the tutorial on the official website exactly. Why did I report this error? I can't find a solution from the source code. Does anyone know how to solve this problem?

**Comment by skabbit** [comment]
I had the same error on command line run.
How did you resolve it?
