### ISSUE TITLE
Fasttext should accept inputs in form of pandas series 

### ISSUE THREAD

**Issue by adiv5** [facebookresearch/fastText#952]
I would want to know if fasttext can give me embedding vectors for every note in a pandas series. Also if the model is trained on all the input notes in series, would i get global representation for all notes or not.

I feel it is unnecessary to make txt files of all the notes in my dataframe and pass them one by one.

if that is already possible please guide me through the same.

Something of the form :

class 1   "This is my text 1"
class 3  "This is another text"

to be converted to :
 
class 1  [0.001021e-4   .....]
class 3  [0.000341e-5   .....]

**Comment by kaushikacharya** [comment]
@adiv5 
 I assume you are talking about creating **queries.txt** for each element of your pandas series:
https://fasttext.cc/docs/en/cheatsheet.html#obtaining-word-vectors
`$ ./fasttext print-word-vectors model.bin < queries.txt`

This calls https://github.com/facebookresearch/fastText/blob/master/src/main.cc#L252
`void printWordVectors(const std::vector<std::string> args) {
`

Based on the expected output you have mentioned you probably want to call
https://github.com/facebookresearch/fastText/blob/master/src/main.cc#L268
`void printSentenceVectors(const std::vector<std::string> args) {`

If you are using python, then in either case, you don't need to write your text into a text file.
For each element of the series, you can call the following function:
https://github.com/facebookresearch/fastText/blob/master/python/fasttext_module/fasttext/FastText.py#L123
`def get_sentence_vector(self, text):`

For python related documentation, you can follow https://github.com/facebookresearch/fastText/tree/master/python
