### ISSUE TITLE
How to access word vectors after supervised learning

### ISSUE THREAD

**Issue by appbern** [facebookresearch/fastText#96]
I've already read that the model.vec file isn't generated anymore in the supervised learning mode. But is there any other possibility to access the trained word vectors after supervised learning?

Thanks in advance!

**Comment by spate141** [comment]
https://github.com/facebookresearch/fastText#text-classification
If you want to compute vector representations of sentences or paragraphs, please use:

`$ ./fasttext print-vectors model.bin < text.txt`

This assumes that the text.txt file contains the paragraphs that you want to get vectors for. The program will output one vector representation per line in the file.

**Comment by EdouardGrave** [comment]
Hi @appbern,

We will change fastText so that it generates the model.vec file again in the supervised mode, probably next week. Stay tuned!

**Comment by rhezabudiono** [comment]
@EdouardGrave Does fastText generate the model.vec file now? I can't get it to output .vec, and I want to output a .vec file so that it plays nicely with genesis. Thanks for your help!
