### ISSUE TITLE
some command line attribute not work in python code

### ISSUE THREAD

**Issue by kazemsamiei** [facebookresearch/fastText#972]
We have some attribute in fasttext that work on command line such as:
./fasttext nn result/fil9.bin
and have command in python:
 model.get_nearest_neighbors('   ')
But commad just work in command line and not work in python code:
AttributeError: '_FastText' object has no attribute 'get_nearest_neighbors'

**Comment by Celebio** [comment]
Hi @kazemsamiei ,
It is in the [latest version](https://github.com/facebookresearch/fastText/blob/master/python/fasttext_module/fasttext/FastText.py#L89) in our repo.
You need to pull the latest commit from our github repo and install python bindings with it.

Best regards,
Onur

**Comment by Celebio** [comment]
Hi @kazemsamiei ,
I hope this answered your question, I will close the issue now. Feel free to re-open it if you have further questions.

Best regards,
Onur

**Comment by kaushikacharya** [comment]
@Celebio 
I have added get_nearest_neighbors in the documentation.
Here's the pull request: https://github.com/facebookresearch/fastText/pull/1068
