### ISSUE TITLE
error handling for the empty predictioins

### ISSUE THREAD

**Issue by leo-gan** [facebookresearch/fastText#975]
fasttext 0.9.1
Windows, python

when I do:
`model.predict(text, k=3, threshold=0.8)`
it should return empty tuple [not found predictions] but instead, I'm getting an Exception, which is not what expected:
```
..\fasttext\FastText.py in predict(self, text, k, threshold, on_unicode_error)
    155             text = check(text)
    156             predictions = self.f.predict(text, k, threshold, on_unicode_error)
--> 157             probs, labels = zip(*predictions)
    158 
    159             return labels, np.array(probs, copy=False)

ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by Celebio** [comment]
Hi @leo-gan ,
Thank you for reporting this issue.

It is already [fixed in our repo](https://github.com/facebookresearch/fastText/blob/master/python/fasttext_module/fasttext/FastText.py#L163) and will be included in the next release.
Best regards,
Onur
