### ISSUE TITLE
get python package version by fasttext.__version__

### ISSUE THREAD

**Issue by KanchiShimono** [facebookresearch/fastText#977]
Many python packages have version info as package top level variable.
So I want to get fastText version like this:

```py
import fasttext

fasttext.__version__
```

It is useful to log the model parameters.
If you agreed to this feature, I will send PR.

**Comment by Celebio** [comment]
Hi @KanchiShimono ,
Yes it makes sense. Please proceed with a PR.

I will close the issue. Feel free to re-open it if you have further questions/suggestions.

Thank you!
Onur

**Comment by KanchiShimono** [comment]
@Celebio 
Thank you for your response.
I will send a PR later.

Best regards.
Kanchi
