### ISSUE TITLE
how to use in multi-label classification?

### ISSUE THREAD

**Issue by Brook-Lan** [facebookresearch/fastText#981]

**Comment by Celebio** [comment]
Hi @Brook-Lan ,
You can have a look [here](https://fasttext.cc/docs/en/supervised-tutorial.html#multi-label-classification).

Hope it helps,
Best regards,
Onur

**Comment by Celebio** [comment]
Hi @Brook-Lan ,
I hope this answered your question, I will now close the issue. Feel free to re-open it if you have further questions.

Best regards,
Onur
