### ISSUE TITLE
New PyPI release?

### ISSUE THREAD

**Issue by osma** [facebookresearch/fastText#985]
Hi,

I'd appreciate if you could make a PyPI release. The current version available on PyPI (0.9.1) still suffers from issue #846 so we can't use it. Instead we are using the even older, unofficial `fasttextmirror` version. (ref: https://github.com/NatLibFi/Annif/issues/290)

Thanks in advance,
Osma

**Comment by Celebio** [comment]
Hi @osma,
Thank you for your feedback. You are right, and we will make a new release soon.

Feel free to re-open this issue if you have further questions.
Best regards,
Onur

**Comment by osma** [comment]
Sorry for bothering, but I'm still waiting for the PyPI release.

**Comment by isolet** [comment]
Any news?
