### ISSUE TITLE
unsupervised and supervised training?

### ISSUE THREAD

**Issue by rnyak** [facebookresearch/fastText#989]
Hello,

I do use supervised training as instructed with my training, validation and test sets. It works well. But, what's the default "word representation" mode when doing supervised training? cbow or skipgram if I do not set any?  And how the words were learned? From Wikipedia's articles?

this is an example code from my supervised training command:

```
./fasttext supervised -input train.txt -output model -wordNgrams 2 -lr 5 -epoch 10
```

Another question is if I want to use my own corpus to learn the word representations, how I should prepare my corpus dataset? Then, how can I use the saved "model.bin" to do supervised training on a training set? I could not find an example for that in the docs. 

Thanks.

**Comment by Celebio** [comment]
Hi @rnyak ,
You can have a look on our [unsupervised train](https://fasttext.cc/docs/en/unsupervised-tutorial.html) tutorial. 

I will close this issue now. If you still have questions regarding this, feel free to re-open the issue and ask here.

Best regards,
Onur
