### ISSUE TITLE
multi label text classification EROR std::runtime_error

### ISSUE THREAD

**Issue by zhangyuanscall** [facebookresearch/fastText#990]
3000+ labels, use fasttext to  multi label text classification
ERROR INFO: 
"""
Read 0M words
Number of words:  30540
Number of labels: 2241
terminate called after throwing an instance of 'std::runtime_error'
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
"""
is memory out?

**Comment by Celebio** [comment]
Hi @zhangyuanscall ,
Could you please share the exact command line you are running?

Regards,
Onur

**Comment by zhangyuanscall** [comment]
> Hi @zhangyuanscall ,
> Could you please share the exact command line you are running?
> 
> Regards,
> Onur
Caused by gradient explosion problem.
I solve this problem by reducing learning rate.
